### ISSUE TITLE
CPP

### ISSUE THREAD

**Issue by WeiqunZhang** [AMReX-Codes/amrex#10]
Here is a list of identifiers used in `#if`, `#elif`, `#ifdef`, or `#ifndef` (excluding include guards in headers) in AMReX sources.   Many of them start with `AMREX_` or `BL_`.  I am proposing we should make every one of them (except `NDEBUG`) to start with `BL_`, or `AMREX_`, or another somewhat unique names.   

Note that `NDEBUG` is a special case.  It's a documented macro in glibc to turn off assertion.  https://www.gnu.org/software/libc/manual/html_node/Consistency-Checking.html 

-   AMREX_GIT_VERSION
-   BL_AIX
-   BL_AMRPROF
-   BL_ASSERT
-   BL_BACKTRACING
-   BL_CCSE_MPP
-   BL_COALESCE_FABS
-   BL_COMM_PROFILING
-   BL_CRAY
-   BL_FIXHEADERDENORMS
-   BL_FIX_GATHERV_ERROR
-   BL_FORT_USE_LOWERCASE
-   BL_FORT_USE_UNDERSCORE
-   BL_FORT_USE_UPPERCASE
-   BL_HOPPER
-   BL_LANG_FORT
-   BL_LAZY
-   BL_MEM_PROFILING
-   BL_NO_FORT
-   BL_PROFILE
-   BL_PROFILING
-   BL_PROFILING_SPECIAL
-   BL_SETBUF_SIGNED_CHAR
-   BL_SIM_HOPPER
-   BL_SIM_HOPPER_MAKE_TCFAB
-   BL_SINGLE_PRECISION_PARTICLES
-   BL_SPACEDIM
-   BL_T3E
-   BL_TESTING
-   BL_TINY_PROFILING
-   BL_TRACE_PROFILING
-   BL_USE_ARRAYVIEW
-   BL_USE_ASSERTION
-   BL_USE_DOUBLE
-   BL_USE_FLOAT
-   BL_USE_FORTRAN_MPI
-   BL_USE_FORT_STAR_PRECISION
-   BL_USE_F_BASELIB
-   BL_USE_F_INTERFACES
-   BL_USE_MPI
-   BL_USE_MPI3
-   BL_USE_NEWPLOTPER
-   BL_USE_OMP
-   BL_USE_TEAM
-   BL_USE_UPCXX
-   CRSEGRNDOMP
-   DEBUG
-   DEBUG_AFAP
-   DIMENSION_AGNOSTIC
-   FORTRAN_BOXLIB
-   HAS_XGRAPH
-   JEFF_TEST
-   MG_USE_FBOXLIB
-   NDEBUG
-   PARTICLES
-   SPACEDIM
-   TESTING_POLYNOMINTERPCOEFFS
-   UPCXX_DEBUG
-   USE_PARTICLES
-   USE_REORG_VERSION
-   USE_SLABSTAT
-   USE_STATIONDATA

**Comment by drummerdoc** [comment]
Sounds good.  Might be time to retire BL_T3E

**Comment by asalmgren** [comment]
How about getting rid of the SIM_HOPPER ones too?

**Comment by WeiqunZhang** [comment]
I am going to ask Vince about SIM_HOPPER.

**Comment by vebeckner** [comment]
hi weiqun,

yes, we can delete this.  it was for distribution mapping tests on hopper.

v.

**Comment by maxpkatz** [comment]
I prefer AMREX_ or AMR_ over BL_.

**Comment by zingale** [comment]
what about `JEFF_TEST` -- if that is still needed, can we atleast make it more meaningful?

**Comment by WeiqunZhang** [comment]
OK. I am going to use `AMREX_`, which is liked by John.  In the end I will provide a script all replacing these names.

**Comment by WeiqunZhang** [comment]
The JEFF_TEST was added by Chuck 13 years ago.  So I guess I can just remove it.

**Comment by WeiqunZhang** [comment]
Fixed in xSDK mode.
