### ISSUE TITLE
Installed AMReX is missing include file AMReX_MultiFabUtil_C.H

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#1018]
I installed AMReX 20.06 (via Spack). The installed header file `AMREX_MultiFabUtil.H` includes the file `AMReX_MultiFabUtil_C.H`, which is not installed. The build fails.

I configured AMReX with `-DUSE_XSDK_DEFAULTS=ON -DDIM:STRING=3 -DBUILD_SHARED_LIBS:BOOL=OFF -DENABLE_MPI:BOOL=ON -DENABLE_OMP:BOOL=ON -DXSDK_PRECISION:STRING=DOUBLE -DENABLE_EB:BOOL=OFF -DXSDK_ENABLE_Fortran:BOOL=OFF -DENABLE_LINEAR_SOLVERS:BOOL=ON -DENABLE_AMRDATA:BOOL=OFF -DENABLE_PARTICLES:BOOL=ON -DENABLE_SUNDIALS:BOOL=OFF`.

**Comment by WeiqunZhang** [comment]
Some files have been misplaced in `ENABLE_FORTRAN` section.

**Comment by WeiqunZhang** [comment]
We will fix it.  But for now, could you turn on Fortran?

**Comment by eschnett** [comment]
Thanks for the pointer.
