### ISSUE TITLE
Moving Embedded Boundary

### ISSUE THREAD

**Issue by ghost** [AMReX-Codes/amrex#1022]
Hi all,

I noticed there is no official support for moving embedded boundary on the wiki page. Was this ever attempted ? If not would you consider coding it doable in a short time span?

I would imagine that advecting the level-set function, cut the cells and interpolating the cells values for the freshly cleared cells (classical cut-cell fashion) would work.

Thank you for your help.

**Comment by WeiqunZhang** [comment]
One of our users has successfully done moving EB with the current capability.  When one builds EB using `amrex::EB2::Build(...)`, an `IndexSpace` object is pushed to a stack.  One is allowed to build multiple `IndexSpace` objects and remove existing ones.  The stack can be manged with functions in `class IndexSpace`.  A lot of EB related functions (e.g., `makeEBFabFactory`) can take an `IndexSpace` argument.  If not, they use the `IndexSpace` at the top of the stack.

`EB2::Build` has an optional argument `bool build_coarse_level_by_corasening=true`.  If you have a hyperbolic system and the EB surface does not intersect AMR level boundaries, you can set it to `false` to improve the robustness of geometry generation.

**Comment by ghost** [comment]
Thank you
