### ISSUE TITLE
CoordSys::CellCenter() has zero offsets

### ISSUE THREAD

**Issue by sslattery** [AMReX-Codes/amrex#105]
I have a failing unit test when accessing the cell center function from a `CoordSys` (actually a `Geometry`) object. The following function in `AMReX_CoordSys.cpp` computes the center:
```
void
CoordSys::CellCenter (const IntVect& point,
                      Real*          loc) const
{
    BL_ASSERT(ok);
    BL_ASSERT(loc != 0);
    for (int k = 0; k < BL_SPACEDIM; k++)
    {
        loc[k] = offset[k] + dx[k]*(0.5+ (Real)point[k]);
    }
}
```

However, the offset is zero and therefore the returned cell centers are wrong. I am calling the following geometry constructor as follows:
```
    // Create the global cell-based index domain.
    amrex::IntVect domain_lo( AMREX_D_DECL(0,0,0) );
    amrex::IntVect domain_hi( num_cells );
    amrex::Box index_domain( domain_lo, domain_hi );

    // Create the global geometry.
    d_geometry.define(
        index_domain, &physical_domain, amrex::CoordSys::cartesian );
```
where `physical_domain` contains the proper offsets of the physical box.

Looking at the geometry constructor int `AMReX_Geometry.cpp` and the subsequent call to `define` it seems that the offsets are never set with the base class:
```
Geometry::Geometry (const Box&     dom,
                    const RealBox* rb,
                    int            coord,
                    int*           is_per)
{
    define(dom,rb,coord,is_per);
}

void
Geometry::define (const Box&     dom,
                  const RealBox* rb,
                  int            coord,
                  int*           is_per)
{
    if (c_sys == undef)
        Setup(rb,coord,is_per);

    domain = dom;
    ok     = true;

    for (int k = 0; k < BL_SPACEDIM; k++)
    {
        dx[k] = prob_domain.length(k)/(Real(domain.length(k)));
	inv_dx[k] = 1.0/dx[k];
    }
    if (Geometry::spherical_origin_fix == 1)
    {
	if (c_sys == SPHERICAL && prob_domain.lo(0) == 0 && BL_SPACEDIM > 1)
        {
            prob_domain.setLo(0,2*dx[0]);

            for (int k = 0; k < BL_SPACEDIM; k++)
            {
                dx[k] = prob_domain.length(k)/(Real(domain.length(k)));
		inv_dx[k] = 1.0/dx[k];
            }
	}
    } 
}
```

Should these offsets be set using the `RealBox` defining the physical domain in the `define` function? Or does the user need to explicitly set the offsets?

**Comment by sslattery** [comment]
For reference if I explicitly call:
```
    // Create the global geometry.
    d_geometry.define(
        index_domain, &physical_domain, amrex::CoordSys::cartesian );
    d_geometry.SetOffset( physical_domain.lo() );
```
Then the centers are correct.

**Comment by atmyers** [comment]
I agree it would be better if, whenever the `RealBox` was set, it also set the `offset` to be consistent with it. @WeiqunZhang do you have any objection to me making that change?

**Comment by WeiqunZhang** [comment]
Haven't got time thinking about this yet.

**Comment by WeiqunZhang** [comment]
Yes, I agree we should set `offset` when `prob_domain` is set.

**Comment by atmyers** [comment]
This should be fixed now in development. Thanks for reporting!
