### ISSUE TITLE
Not all processors used even when there are enough boxes

### ISSUE THREAD

**Issue by tpg2114** [AMReX-Codes/amrex#1092]
I recently ran into an issue when trying to restart a simulation with more processors than it was originally using. The process to restart looks identical to the documentation -- read the box arrays, then for each level, create a distribution map. The documentation says that the library keeps track of how much work has already been assigned to a processor and takes that into account when assigning more work. 

However, when I try to start with more processors than I had before, many processors end up with no work assigned. As an example, I have a simulation with 5 levels and box arrays with size `{720, 1290, 3210, 3100, 4900}`. It runs if I use < 4900 processors and a roundrobin mapping, but does not run if I use more. (The code crashes if not all processors are assigned work, for various reasons that will be hard to fix.)

The verbose mapping output seems to indicate that it resets the work assigned to each processor with each level, so the library is not aware of work assigned from previous levels. This means it only lets me fill up processors up to the maximum number of boxes on any given level, rather than up to a number of processors equal to the total number of boxes (which is what I had expected/assumed from the documentation). 

Is there a way to force the library to create a new box array with enough boxes to fill the number of processors when the code is starting from a checkpoint file? It seems to do this when starting from scratch (so long as it doesn't violate the max grid size and blocking factor), but I don't see how to trigger a regeneration and re-distribution when I already have a set of box arrays. My simulation code is in Fortran, but I've already wrapped several other C++ routines I needed, so I'm not adverse to doing that if needed.

**Comment by tpg2114** [comment]
Was able to answer my own question... the key word I suppose was when I said it "looks identical" -- it wasn't identical, however. 

I was doing something along the lines of:

    read all box arrays
    loop over levels
        set box array
        build distromap
        set distromap

    do something else

    loop over levels
         build multifab using boxarray and distromap

And therein is the problem... I had assumed the load balancing would be based on "lightweight" information gathered from the box arrays since it was able to load balance new box arrays that had not yet been used to make multifabs. I thought once a box array and distromap have been set, then it would know how much each processor was doing. However, digging through the code revealed it looks for the size of the allocated multifabs instead. 

So, splitting apart the loop to build distromaps and the loop to build multifabs was my downfall here. Sorry for opening a ticket that turned out to be my own error!

It might be worth expanding the documentation on the checkpoint file section to explain a bit better what the code is doing there. And/Or perhaps in the load balancing section to indicate that the load balancing is done based on already-allocated multifabs.

**Comment by WeiqunZhang** [comment]
Thanks for the suggestion.  We will update the documentation to make it clear.
