### ISSUE TITLE
nvcc and mpicxx

### ISSUE THREAD

**Issue by WeiqunZhang** [AMReX-Codes/amrex#1093]
I don't see a way to fix this WarpX issue without major changes to the make system. https://github.com/ECP-WarpX/WarpX/issues/1144  The issue is nvcc does not recognize the `-pipe` flags passed by mpicxx to gcc. 

Currently we are setting environment variables such as `OMPI_CXX` and `MPICH_CXX` so that the `mpicxx` will use nvcc as underlying compilers.  For OpenMPI family, we further set `OMPI_CXXFLAGS` to substitute `-pthread` by `-Xcompiler -pthread` for nvcc.  However, we do not have a way to do that for MPICH and MVAPICH.  Looking through mvapich's mpicxx bash script, it seems that the compiler flags cannot be altered through an environment variable.

Maybe we need to use our own nvcc wrapper so that the flags passed from mpicxx can be sanitized for nvcc.

P.S.  CMake does not work either for WarpX.

**Comment by maximumcats** [comment]
While writing a wrapper for nvcc [is a possible path](https://github.com/kokkos/kokkos/blob/master/bin/nvcc_wrapper), it's not one I recommend we take. An option to nvcc was added to [forward unrecognized compiler options to the host compiler](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-guiding-compiler-driver-forward-host-compiler) (and [host linker](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-guiding-compiler-driver-forward-host-linker)) precisely for this reason, and we should use those for the recent versions of the CUDA toolkit that support them (10.2+). (CMake also has implemented these in recent versions, I think 3.17+).

**Comment by WeiqunZhang** [comment]
We should definitely add those new nvcc flags for >= 10.2.  Unfortunately most people are still using < 10.2.

**Comment by WeiqunZhang** [comment]
So maybe we should do both.

**Comment by maximumcats** [comment]
It doesn't seem worth it to go through the effort if 10.2 works for people and that will eventually become the default in the near future. (The WarpX issue indicates that this is not an urgent problem.) 10.2 is already the default on Cori GPU. 11.0 will be supported on Summit within a few months, and you can already use 10.2 there now (it's not exposed in the default environment, but I encourage people to try it out and see if it works for them -- I can tell them how offline).

**Comment by maximumcats** [comment]
Anyway let's first verify if the 10.2+ resolution works.

**Comment by WeiqunZhang** [comment]
I will try it on corigpu.

**Comment by maximumcats** [comment]
We could also try the strategy of making mpicxx the host compiler for nvcc. That doesn't always work either, but having it as an option probably doesn't hurt.
