### ISSUE TITLE
nGhost for MultiFab%copy doesn't accept vector

### ISSUE THREAD

**Issue by dunhamsj** [AMReX-Codes/amrex#1096]
Hello,

I'm using the Fortran interfaces, and I want to use the copy functionality of MultiFabs, but it only accepts scalars. I have different numbers of ghost cells in the different spatial dimensions, and was wondering if nGhost can be extended to include 3D arrays?

Thanks,
Sam

**Comment by WeiqunZhang** [comment]
Yes, we will add it.
