### ISSUE TITLE
amrex_fillpatch with two levels will segfault when scomp doesn't start at first index

### ISSUE THREAD

**Issue by tpg2114** [AMReX-Codes/amrex#1113]
While trying to split apart a call to the Fortran `amrex_fillpatch` so I can use different interpolation methods for different variables in the Multifab, I ran into a segfault when the `scomp` argument does not start at the first index. I tracked the problem down to the `for` loop that builds the BC's in `AMReX_fillpatch_fi.cpp` on [line 69](https://github.com/AMReX-Codes/amrex/blob/development/Src/F_Interfaces/AmrCore/AMReX_fillpatch_fi.cpp#L69):

    for (int i = 0; i < ncomp; ++i) {
	    bcs.emplace_back(lo_bc[i], hi_bc[i]);
    }

The `lo_bc` and `hi_bc` arrays have null pointers in the 0 to `scomp` positions (done in `AMReX_fillpatch_mod.F90`) and so the loop starting at 0 triggers a segfault when it tries to build a `BCRec` with the null pointers. 

Replacing the loop with:

    for (int i = scomp; i < scomp+ncomp; ++i) {
	    bcs.emplace_back(lo_bc[i], hi_bc[i]);
    }

seems to have fixed the issue for me.

**Comment by tpg2114** [comment]
It looks like the same problem occurs in `amrex_fillcoarsepatch` and the loop on [line 97](https://github.com/AMReX-Codes/amrex/blob/development/Src/F_Interfaces/AmrCore/AMReX_fillpatch_fi.cpp#L97) also needs updated for `scomp` not at the start.

**Comment by WeiqunZhang** [comment]
Thanks for reporting this!

**Comment by tpg2114** [comment]
No problem! I'm working out what I need to do to submit pull requests directly (whether or not I need approval for public release from a government lab) -- hopefully in the future I can contribute more easily if I find other issues.
