### ISSUE TITLE
AMReX CMake: Bad AMReX_Config.H with AppleClang 

### ISSUE THREAD

**Issue by sayerhs** [AMReX-Codes/amrex#1124]
Executing `make install` with a CMake configured project using AppleClang ends up with a malformed `AMReX_Config.H` header file. 

When building against MacOS default LLVM/Clang, CMake sets `CMAKE_CXX_COMPILER_ID = AppleClang` this is not checked in the install helpers https://github.com/AMReX-Codes/amrex/blob/fd4e0d1078a489fe9f07f0d4aa9de77f1680ed2c/Tools/CMake/AMReXInstallHelpers.cmake#L26-L36 and  `COMPILER_ID_MACRO` variable ends up empty, and the `AMReX_Config.H` file that is generated ends up with this 

```C++
#ifdef __cplusplus
#ifndef
static_assert(false,"libamrex was built with AppleClang");
#endif
#ifdef _OPENMP
static_assert(false,"libamrex was built without OpenMP");
#endif
#endif
```

and ends up with a compile time error when this file is included in another project

```
In file included from /exawind/install/clang/amrex/include/AMReX.H:4:
/exawind/install/clang/amrex/include/AMReX_Config.H:46:9: error: macro name missing
#ifndef
        ^
```

cc: @ax3l @mic84

**Comment by ax3l** [comment]
Thank you for the detailed report!

**Comment by ax3l** [comment]
@WeiqunZhang what do we roll with in `GNUmake`, I would just go with `__llvm__`. Most of the time this works.

**Comment by sayerhs** [comment]
@ax3l I can confirm that `__llvm__` works with AppleClang

**Comment by WeiqunZhang** [comment]
Yes, I agree with using `__llvm__`.
