### ISSUE TITLE
Suggested code cleaning to avoid GPU-related porting mistakes

### ISSUE THREAD

**Issue by drummerdoc** [AMReX-Codes/amrex#1136]
In all AMReX applications ported to GPU, there are countless repetitions or slight variations of the following code.
```
#ifdef _OPENMP
#pragma omp parallel if (Gpu::notInLaunchRegion())
#endif
   {
      for (MFIter mfi(mf, TilingIfNotGPU()); mfi.isValid(); ++mfi) {
        ...
      }
    }
```
This seems unnecessarily verbose and error-prone, and if we decide to change this strategy in the future to support HIP or DPC++ shortcomings, or other architectures, this will require a pile of manual search and replace edits that will also be error-prone. 

It would be nicer (and easier to incorporate future mods) if we could write something like this instead:
```
#AMREX_OMP_PARALLEL_START
  for (MFIter mfi(mf); mfi.isValid(); ++mfi) {
    ...
  }
#AMREX_OMP_PARALLEL_END
```
Seems like this is just a couple (more) macros and a default argument to the MFIter constructor.  Is there a compelling reason NOT to do this?

**Comment by maximumcats** [comment]
I don't think this requires any changes to AMReX to implement at the application code level. The application can define their own macro if they want to, and by default we now have a tile size that effectively always disables tiling for the GPU build (#953).

**Comment by drummerdoc** [comment]
The comment/suggestion was intended to apply more broadly than just one application.  It was intended as a suggestion to improve the AMReX API in general.

**Comment by maximumcats** [comment]
It doesn't hurt to add another macro if it's useful (which is the only change needed here). I'd prefer if it was named clearly to indicate that it is intended to disable the parallel region for GPU builds (since there are applications where one might want to use OpenMP even when building to target GPUs).

**Comment by drummerdoc** [comment]
There's a balance.  I originally thought of something more verbose, but decided that the use case you mention is at this point rare enough that it is a special case rather than the norm. I believe the same logic was followed to decide to implement #953

**Comment by WeiqunZhang** [comment]
Not all applications use `#omp paralllel if (Gpu::notInLuanchRegion())`.  WarpX simply disables OpenMP in makefile if it is built for GPU.

If we have to have `AMREX_OMP_PARALLEL_END`, I would argue that's certainly more error prone.  Fortunately we don't.  So what we are really looking at is
```
#ifdef _OPENMP
#pragma omp parallel if (Gpu::notInLaunchRegion())
#endif
```
or
```
#pragma omp parallel if (Gpu::notInLaunchRegion())  // if you don't mind warnings on unknown pragmas
```
vs.
```
AMREX_OMP_PARALLEL
```

Another thing is it's not always simple `omp parallel`.  If it has some additional `private`, `reduction`, etc., it may be hard to do with a macro.

**Comment by drummerdoc** [comment]
The WarpX example then would be a no-op.  The reduction requirement is a special case that is extremely rare in almost every app that I have looked at.  Also, we could avoid the END component by using a () syntax like many other AMReX macros.

All that said, there seems to be a desire to keep the repetitive/verbose syntax in order to keep the operations explicit in this particular case. Thank you for the comments.
