### ISSUE TITLE
Non-standard Fortran in AMReX_INTERP_3D.F

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#115]
Code in `AMReX_INTERP_3D.F` uses a `dfloat` intrinsic function.  This is not a standard Fortran intrinsic, but apparently a commonly supported extension.  However the NAG compiler does not recognize it.  There are several ways to fix the problem.  I'd be happy to submit a PR, but want to know your preference:
1. Rely on automatic Fortran type conversion/promotion, making replacements such as `dfloat(lratiox)` with `lratio`.  In all the uses here, automatic conversion does the right thing.
2. Replace `dfloat` with the standard intrinsic `dble`.  However `dble` is deprecated (but unlikely to disappear).
3. Replacements `dfloat(lratiox)` --> `real(lratiox,kind(1.0d0))`

**Comment by zingale** [comment]
I think we also need to allow for it to be single or double precision, depending on how it was compiled.

**Comment by nncarlson** [comment]
Option 1 should do exactly that.  `dfloat` converts to double precision regardless of the how it is compiled (the `REAL_T` macro is what you refer to here?), but then it doesn't make a difference here because the automatic conversion kicks in to convert to single on assignment if that's how the code was compiled.

**Comment by WeiqunZhang** [comment]
I have no preference.

**Comment by maxpkatz** [comment]
I prefer option 1 for simplicity.

**Comment by nncarlson** [comment]
Okay, I've gone with option 1.  See PR #117

**Comment by WeiqunZhang** [comment]
The pull request has been merged.
