### ISSUE TITLE
amrex_geometry_initialzied should be set to false upon finalization (and spell checked)

### ISSUE THREAD

**Issue by mattbement** [AMReX-Codes/amrex#1160]
In Src/F_Interfaces/Base/AMReX_geometry_mod.F90, amrex_geometry_initialzied should probably be set to .false. in amrex_geometry_destroy.  Failure to do so can cause problo and probhi to be erroneous.  Also, should probably fix spelling to amrex_geometry_initialized.

**Comment by WeiqunZhang** [comment]
Could you tell us more about your use case? Are you building multiple geometry objects with different problo and probhi?

Thanks for pointing out the typo.  I used auto-completion in emacs.  So if a typo is made in the place, it sometimes propagates all the way through. :)

**Comment by mattbement** [comment]
I'm working with Neil Carlson and Zach Jibben on TruchasPBF.  In a nutshell, our parallel-in-time approach requires us to repeatedly set up and tear down AMReX meshes, potentially with different physical domains. We never have more than one geometry object in existence at a time, but we need to make sure each one gets initialized cleanly.

**Comment by nncarlson** [comment]
@WeiqunZhang, to expand on Matt's description, we execute sequences of amrex "sessions" bracketed by `amrex_initialize` and `amrex_finalize` pairs (there is only one `mpi_init` and `mpi_finalize` on the outside).  The `amrex_geometry_module` has initialized `save`'ed module variables.  These effectively need to be reset when `amrex_finalize` is called.  Here is my patch that appears to work for us: 
[reset-geometry.txt](https://github.com/AMReX-Codes/amrex/files/4956850/reset-geometry.txt)

PS: I didn't correct the spelling error :-)

**Comment by WeiqunZhang** [comment]
@nncarlson The fix looks good to me.  Do you want to submit a PR or want me to do it?  Please feel free to fix the typo.

**Comment by nncarlson** [comment]
I'll do a PR that includes the typo fix.
