### ISSUE TITLE
How to impose normal EB condition with nodal projection?

### ISSUE THREAD

**Issue by darylbond** [AMReX-Codes/amrex#1167]
I have cell centred data defining electric and magnetic fields and I am using the nodal projection method as outlined in the [docs](https://amrex-codes.github.io/amrex/docs_html/LinearSolvers.html#nodal-projection) to approximate the divergence condition div(E)=rho_c and div(B)=0. I am now implementing EB boundary conditions and the magnetic field boundary for a perfect conductor is satisfied by this approach (field parallel to the wall), however, I would like to also implement the electric field condition which is normal to the wall. I have been looking through  `MLNodeLaplacian::compRHS()` and associated functions in an attempt to decipher where the parallel condition is enforced, but have not had much success. I am wondering if someone could point me in the right direction or perhaps outline an alternative approach?

**Comment by WeiqunZhang** [comment]
I think EB boundary being a perfect conductor for the E field means the potential (i.e., the scalar field we solve in projection) is a constant (say zero) on EB boundary, whereas we have Neumann boundary on EB for the B field and velocity.  In the later case, a node of a cut cell is part of the linear system's unknowns, even if it is inside EB.  But for the E field case with homogeneous Dirichlet boundary on EB, those covered nodes are not part of the system's unknowns.  The nodal linear solver has been recently extended to support the overset method.  It seems to me it can be used for your case.  You might want to look at `amrex/Tests/LinearSolvers/NodalOverset`.  I think all you need to do is (1) provide a nodal Dirichlet mask that is zero for uncovered nodes and one for covered nodes, (2) set `phi` and `rhs` to zero on covered nodes right before you call `solve`.  I don't think you need to do anything special in `compRHS`.

**Comment by darylbond** [comment]
Yes, the final corrected potential across the entire surface should be constant, but I believe the condition at the surface is inhomogeneous Neumann. That is, we have `E = -grad(phi)` and with the condition that the electric field is normal to the interface, we have `n.E = -n.grad(phi) = -dphi/dn`, where `n` is the surface normal. Is it possible to define an inhomogeneous Neumman condition with EB? Looking through the docs it doesn't appear to be one of the options.

**Comment by WeiqunZhang** [comment]
I am confused.  It seems to me that specifying both Dirichlet and Neumann would overspecify the problem mathematically.  Physically, it seems to me that you are saying the surface charge is known before the solve and it's fixed during the solve even though it's the surface charge on a perfect conductor.

**Comment by WeiqunZhang** [comment]
Here is my understanding of your problem.  We can decompose any `E` field into two parts `E = grad p + curl A`.  You want to get rid of the curl part.  Taking div on both sides gives us `div E = div grad p`  You solve the problem to obtain `p`.  Then you simply compute `grad p` and that's your `E`.  Note that this is different from projection for B and velocity, for which we do `B - grad p` to get the curl part.  I think my original suggestion of using Dirichlet boundary should work.  I admit I could be entirely wrong.

**Comment by darylbond** [comment]
I am still trying to figure it out myself, so the confusion is mutual. I'll do some more thinking on the matter, many thanks for your suggestions.
