### ISSUE TITLE
Communicate AMReX modifications that change downstream solutions/behaviors 

### ISSUE THREAD

**Issue by drummerdoc** [AMReX-Codes/amrex#1195]
Recently, minor changes were made to the way the tensor solver interprets EB geometry at outflow boundaries.  While they are almost surely "the right thing to do", they change computed solutions, and will impact downstream codes in ways that the mod developers can't possibly anticipate.  This will affect regression tests, and solutions in general, and could cause a lot of confusion.  They also suggest/reinforce a design philosophy for AMReX algorithms that should be communicated in some way other than buried in a PR that is merged and forgotten.

As another example, I recently added a new approach to tagging cells for refinement in PR #1166 that I think makes a huge change in how all applications can manage problem-specific tagging at runtime.  I tried to summarize my addition and its use in the PR, but it's not clear that this is the most effective way to announce additional or modified functionality.  Perhaps the release notes highlight these things at a very high level.  The documentation is not really set up to alert users to new or changed features and why they were necessary, only to explain what's currently in place.

I wonder if the collective AMReX user base has suggestions for a better approach to documenting the evolving library and its use, to call out new features or changed functionality, to provide example usage code and/or explanations that drove the decisions that were made. Examples might be added tutorials/regression tests, but also some sort of wiki or living document somewhere?

**Comment by zingale** [comment]
I think the release notes are the best place.

Of course, you could have AMReX Twitter...

**Comment by drummerdoc** [comment]
One problem with release notes is that they put all the work on Weiqun, not only to describe what was done, but why.  Moreover, if the mod does make the highlight reel, it's tersely summarized at best.  In the case of the solver outflow BC's above, a couple sentences describing the fix, maybe a picture and some indication of what was observed and how this fixes things, would be useful.  Currently, I know of no place for such a thing, and it simply doesn't happen.  A similar discussion just happened between me and Michele Rosso about the origin and meaning of "fpu" in the low Mach/incompressible codes.  Another example is the discussion regarding options in the regression suite to reuse builds....or? I've also recounted the argument for switching to forked AMReX development (and why old hashes don't work) to 4-5 people separately now.  So, this kind of thing comes up more and more.

Without capturing the discussions, code is merged and life moves on.  As the user base of AMReX grows, the lines of communications are becoming less and less direct to most of us.  I thought something like this would be useful, but it does place more burden on those that contribute to AMReX.  The reason to post it here is that maybe someone else has had positive experiences with other modes to communicate this information that they'd like to share.

**Comment by zingale** [comment]
we try to require each PR that is a major change to update our release notes (CHANGES.md) as part of the PR with a link to the PR number.  That way the author of the change describes the impact and the link to the PR can be used to see additional details including any figures put in the PR discussion.  I think that works well for us, but you have be require the update to the release notes before accepting the PR (we have a PR template with checkboxes that we sometimes remember to use)

**Comment by zingale** [comment]
also, regarding fpu, I think we documented that in the appendix of this paper: https://iopscience.iop.org/article/10.1088/0004-637X/807/1/60/pdf

if I recall, it stood for face predict upwind

**Comment by drummerdoc** [comment]
Nope :). I wrote the first version of that in IAMR and when I named it, it was for "fill patched Umac".

**Comment by asalmgren** [comment]
One thing we could do -- while incomplete it would still be helpful -- is to identify in every PR whether it is expected that anybody's solutions (aka regression tests) will differ as a result of this change.   I don't know if there's a slick git way to do that, or just "require" that the person writing the commit make a statement about the expectation of whether it will change the answer.

**Comment by zingale** [comment]
you can do that with a PR template as well.  We have those checkboxes for Castro:

https://github.com/AMReX-Astro/Castro/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by drummerdoc** [comment]
I like the template!  Is there a way to round up the text of a month's worth of PR's into a summary document with an RSS feed or some other notification type thing?

**Comment by zingale** [comment]
I'm sure there's a github action for that.

**Comment by drummerdoc** [comment]
There is, it turns out.  ...looking into the config settings/functionality.
