### ISSUE TITLE
HDF5 I/O - format details and possible typo in node vs cell data

### ISSUE THREAD

**Issue by thomasgillis** [AMReX-Codes/amrex#1212]
Dear AMReX community,

I am trying to replicate your data format for my own home-made I/O.
While going through the code, and especially [this file](https://github.com/AMReX-Codes/amrex/blob/1a4780d8ef5fb2fa7948ab926c942ea551690e60/Src/Base/AMReX_PlotFileUtil.cpp), I think that I found a small typo (see hereunder).

In any case, do you have a some extensive documentation on the file format that you use? As I try to write compatible files, I would be interested in some more details.

---------------------------------------------------------
Here is the small typo that I think does not match the hdf5 format (from my understanding of the hdf5 format, actually I couldn't test it).
At [line 943](https://github.com/AMReX-Codes/amrex/blob/1a4780d8ef5fb2fa7948ab926c942ea551690e60/Src/Base/AMReX_PlotFileUtil.cpp#L943), you have
```c++
            int vbCount(0);
            Vector<int> vbox(sortedGrids.size() * 2 * AMREX_SPACEDIM);
            Vector<int> centering(sortedGrids.size() * AMREX_SPACEDIM);
            count[0] = sortedGrids.size();
            for(int b(0); b < sortedGrids.size(); ++b) {
                for(int i(0); i < AMREX_SPACEDIM; ++i) {
                    vbox[(vbCount * 2 * AMREX_SPACEDIM) + i] = sortedGrids[b].smallEnd(i);
                    vbox[(vbCount * 2 * AMREX_SPACEDIM) + i + AMREX_SPACEDIM] = sortedGrids[b].bigEnd(i);
                    centering[vbCount + i] = sortedGrids[b].ixType().test(i) ? 1 : 0;
                }
                ++vbCount;
            }
```

And I guess that this line is wrong,
```c++
centering[vbCount + i] = sortedGrids[b].ixType().test(i) ? 1 : 0;
```
and should be
```c++
centering[vbCount * AMREX_SPACEDIM + i] = sortedGrids[b].ixType().test(i) ? 1 : 0;
```

**Comment by atmyers** [comment]
It looks like you're correct to me - @houjun could you please confirm that this indeed a bug?

Re: a detailed description of the output format, that is something that we should have but currently don't. Let's leave this issue open as a reminder so that we get to this the next time we have a documentation push.

**Comment by houjun** [comment]
Yes, I think it is a bug, will create a pull request to fix this

**Comment by thomasgillis** [comment]
@atmyers could you let it open so that I can get a description of the data format you use?
Thx for your time!
