### ISSUE TITLE
divide by zero in EB generation

### ISSUE THREAD

**Issue by darylbond** [AMReX-Codes/amrex#1272]
The function `set_eb_data()` fails with an arithmetic error given a simple signed distance field (SDF). The SDF is given by the quadratic spline approximation of a circle with four points and is shown below along with with the zero contour

![sdf](https://user-images.githubusercontent.com/726462/90408101-b9a83880-e0ea-11ea-987e-08a65ab3508d.png)

The offending code appears to be https://github.com/AMReX-Codes/amrex/blob/b4128deaff6e9ec9a91b605271f1aa972a1d3809/Src/EB/AMReX_EB2_2D_C.cpp#L67 or https://github.com/AMReX-Codes/amrex/blob/b4128deaff6e9ec9a91b605271f1aa972a1d3809/Src/EB/AMReX_EB2_2D_C.cpp#L74

where `vfrac(i,j,0) = 0.5*(axm+axp)` or `vfrac(i,j,0) = 0.5*(aym+ayp)` are approximately zero. In order to bypass the issue I have inserted a check for these conditions and set values according to the covered condition from `build_cells()`

e.g.

```
if (axm+axp < small) {
  vfrac(i,j,0) = 0.0;
  vcent(i,j,0,0) = 0.0;
  vcent(i,j,0,1) = 0.0;
  barea(i,j,0) = 0.0;
  bcent(i,j,0,0) = -1.0;
  bcent(i,j,0,1) = -1.0;
  bnorm(i,j,0,0) = 0.0;
  bnorm(i,j,0,1) = 0.0;
  return;
}
```

and likewise for `aym+ayp < small`. Note that this failure is occurring when `axm=8e-12, axp=aym=ayp=0`. This hack appears to be working but I am wondering if this is just a corner case that hasn't been hit previously, or is there more at play here?

**Comment by WeiqunZhang** [comment]
This looks like a corner case that we have not seen before.  I am wondering how this happened, `axm=8.e-12, axp=aym=ayp=0`?  I guess it's possible if a cut on ym or yp face is so small that aym or ayp becomes 0.  Could you please share your EB setup so that we can make EB generation more robust?

**Comment by OscarAntepara** [comment]
Maybe this could be related but I am getting this error `0::Assertion ncuts <= 2' failed, file "../../../Src/EB/AMReX_EB2_3D_C.cpp", line 494, Msg: "amrex::EB2::build_faces: more than 2 cuts not supported" !!!`
with this configuration

       `Geometry geom;
        {   
            RealBox rb({-0.64,-0.32,-0.32}, {0.64,0.32,0.32}); // physical domain
            Array<int,AMREX_SPACEDIM> is_periodic{false, false, false};
            Geometry::Setup(&rb, 0, is_periodic.data());
            Box domain(IntVect(0), IntVect(255,127,127));
            geom.define(domain);
        }
            Real rotation = (45./180.) * M_PI;

            Array<Real,3> origin = {0.0, 0.0, 0.0};
            EB2::CylinderIF my_cyl(0.1, -1, 2, origin, true);
            auto my_cyl_rotated = EB2::rotate(my_cyl, rotation, 1);

            auto gshop_cyl = EB2::makeShop(my_cyl_rotated);
            EB2::Build(gshop_cyl, geom, 0, 0);
        `

**Comment by darylbond** [comment]
@WeiqunZhang I would gladly share the EB setup but it is implemented through a highly customized lua initialisation routine, rather than the IF classes available in AMReX, so that could be a little tricky. Unfortunately, our project isn't open source (yet), so I can't just give you a link. I had a crack at implementing the same geometry using the SplineIF class but something is going on there too, using the following points should give a reasonable approximation of a circle, as shown in the schematic, but instead gives the following 

```
{{0,1},{0.5,1},{1,0.5},{1,0},{1,-0.5},{0.5,-1},{0,-1},{-0.5,-1},{-1,-0.5},{-1,0},{-1,0.5},{-0.5,1},{0,1},}
```

![circle](https://user-images.githubusercontent.com/726462/90459398-94481880-e144-11ea-812a-9ae281408aba.png)
![bezier](https://user-images.githubusercontent.com/726462/90459494-d5d8c380-e144-11ea-8449-6a5497f51ce5.png)


I also encountered a possible bug when compiling in 2D where 

https://github.com/AMReX-Codes/amrex/blob/3235db6b295923ed454cc1bbdfe6ce3b6964e93c/Src/EB/AMReX_EB2_IF_Spline.H#L41

should probably be something like `amrex::RealVect x(AMREX_D_DECL(p[0], p[1], p[2]));`

**Comment by WeiqunZhang** [comment]
Yes, that's a bug.

Not sure what's going on with the circle.  @rgrout

**Comment by asalmgren** [comment]
@OscarAntepara -- does it fail in 2D as well (at 45 degrees) or only in 3D?

**Comment by OscarAntepara** [comment]
only in 3D, as far as I have tested it

**Comment by WeiqunZhang** [comment]
I am able to reproduce the divide-by-zero error.  There is a PR to fix this.  Note that if it is not crashed by `amrex.fpe_trap_zero=1`, the old code actually produces correct results because those cells with `vcent=inf` will be set to covered later.
