### ISSUE TITLE
regtest.py: option to disable `git pull`

### ISSUE THREAD

**Issue by RemiLehe** [AMReX-Codes/amrex#130]
When using the script `regtest.py`, it is possible to specify a commit or branch for which the tests should be run (in the corresponding test input file, through the `branch = ` line). 

When doing so, the python script performs `git checkout <specified commit>` and then `git pull`. However, when a commit hash is provided (as opposed to a branch name) in the test input file, the `git pull` fails (because the code is in a "detached HEAD" state after `git checkout`). 

Is there an option to disable `git pull`? I think that the option `--no_update` disables both `git checkout <specified commit>` and `git pull`, which is not quite what I am looking for.

**Comment by WeiqunZhang** [comment]
I think `[--amrex_git_hash hash] [--source_git_hash hash] [--extra_src_git_hash hash]` does what you want.

**Comment by WeiqunZhang** [comment]
In the warpx case, `extra_src_git_hash` is for picsar.

**Comment by zingale** [comment]
I ran into this recently too, so if there is a nicer way to handle this, I'm open to changing it.

**Comment by RemiLehe** [comment]
Thanks for the information. @WeiqunZhang 's solution should work for my use case.

**Comment by WeiqunZhang** [comment]
`--no_update All` is very useful when combined with `git bisect`.
