### ISSUE TITLE
Documentation rendering problems

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#1304]
Hello, I noticed in the documentation, for example https://amrex-codes.github.io/amrex/docs_html/External_Profiling_Tools.html#nsight-systems, the `.rst` files have lines that are invisible in the rendered documentation.

**Comment by atmyers** [comment]
Thank you for pointing this out, I believe this will fix the error: https://github.com/AMReX-Codes/amrex/pull/1306

**Comment by kngott** [comment]
Oh: Andrew beat me to it!

I've added some additional changes to the highlighting to improve readability. Apparently, highlights inside sphinx's numbered lists don't work. This removes those as well to make the section on targeting regions for Nsight Systems analyses readable.

Thanks for pointing out the issue, Jon!

**Comment by jrood-nrel** [comment]
Looks fixed, thanks!
