### ISSUE TITLE
Tag Array Assignment in version 20.07

### ISSUE THREAD

**Issue by aerojpapp** [AMReX-Codes/amrex#1308]
Hello All,

I've recently upgraded from version 19.10 to 20.07 and noticed a peculiarity with the tag array assignment.  To be able to use AMReX with my software, the unrefined level 0 grid is specified by my own partitioning program.  In other words, in my overloaded make new level from scratch routine, instead of using the topology AMReX determines, I reset the box array and distro-map to my own values for level is 0 (calling amrex_set_boxarray(0,ba) and amrex_set_distromap(0,dm)).  In version 19.10, my tag box array would match the set box array and distro-map.  With version 20.07, the tag box array seems to be assigned to the original box array and distro-map values.  From what I gather, it seems that the tag box array is allocated and assigned after my overloaded make new level from scratch routine in version 19.10 but before in 20.07, hence the inconsistency?  Is this true, and if so, where/how can I fix?  I'm using the FORTRAN interfaces.

Thanks,

John

**Comment by WeiqunZhang** [comment]
Could you post some code snippets so that we could better understand your issue?

**Comment by aerojpapp** [comment]
Everything is pretty well embedded but I'll give you my "process"...

- Registering overloaded functions:

            !!
            !!  Register overloaded functions
            call amrex_init_virtual_functions(AMREXCoreFuns_MakeNewLevelFromScratch, &
                                              AMREXCoreFuns_MakeNewLevelFromCoarse,  &
                                              AMREXCoreFuns_RemakeLevel,             &
                                              AMREXCoreFuns_ClearLevel,              &
                                              AMREXCoreFuns_ErrorEstimate)

- Overloaded AMREXCoreFuns_ErrorEstimate

          !!
          !!  Tag cells for refinement.  TagBoxArray tags is built on level lev grids.
          !!
          subroutine AMREXCoreFuns_ErrorEstimate(lev,cp,time,settag,cleartag) bind(c)
            use iso_c_binding
            use AMREXFunsMod
            use CraftAMREXMod
            use amrex_amr_module
                                use CommDataMod

            implicit none

            integer, intent(in),value:: lev
            type(c_ptr),intent(in),value:: cp
            real(amrex_real),intent(in),value:: time
            character(kind=c_char),intent(in),value:: settag, cleartag

            type(amrex_tagboxarray):: amrTBoxArray
            type(amrex_mfiter):: mfi
            type(amrex_box):: bx
            real(amrex_real),contiguous,pointer,dimension(:,:,:,:):: vararrGradRMS
            character(kind=c_char),contiguous,pointer,dimension(:,:,:,:):: tagarr
                !!
                !!  Define refinement threshold here for now but will be input parameter in future
                real(amrex_real),dimension(1:5):: amrrRefThresh
                amrrRefThresh(1)= 1.0
                amrrRefThresh(2)= 1.0
                amrrRefThresh(3)= 1.0
                amrrRefThresh(4)= 1.0
                amrrRefThresh(5)= 1.0
            !!
            !!  Assignment of incoming C pointer to AMReX TagBoxArray type
            amrTBoxArray= cp
            !!
            !!  Loop through blocks and tag cells for refinement
            call amrex_mfiter_build(mfi,amrMFabQ(lev),tiling=.false.)
            do while(mfi%next())
               bx= mfi%tilebox()
               tagarr=> amrTBoxArray%dataptr(mfi)
               vararrGradRMS=> amrMFabGradRMS(lev)%dataptr(mfi)
               call AMREXFuns_TagRefine(lev,time,amrrRefThresh(lev+1),settag,cleartag                                   &
                                                ,bx%lo,bx%hi,lbound(vararrGradRMS),ubound(vararrGradRMS),vararrGradRMS  &
                                                            ,lbound(tagarr),ubound(tagarr),tagarr)
            end do
            call amrex_mfiter_destroy(mfi)

            return
          end subroutine AMREXCoreFuns_ErrorEstimate

- Tag Refine subroutine

          !!
          !!  Subroutine defines the refinement necessary based on refinement threshold using default methods
          !!
          subroutine AMREXFuns_TagRefine(iLvl,amrrTime,amrrRefThresh,cSetTag,cClearTag,iBoxLo,iBoxHi      &
                                                    ,iVarLoGradRMS,iVarHiGradRMS,amrrVarGradRMS,iTagLo,iTagHi,cTag)
            use craft_flags

            implicit none

            integer,dimension(1:4),intent(in):: iVarLoGradRMS,iVarHiGradRMS
            integer,dimension(1:4),intent(in):: iTagLo,iTagHi
            integer,dimension(1:3),intent(in):: iBoxLo,iBoxHi
            character(kind=c_char),intent(in):: cSetTag,cClearTag
            integer,intent(in):: iLvl
            real(amrex_real),intent(in)::  amrrVarGradRMS(iVarLoGradRMS(1):iVarHiGradRMS(1),iVarLoGradRMS(2):iVarHiGradRMS(2),iVarLoGradRMS(3):iVarHiGradRMS(3),iVarLoGradRMS(4):iVarHiGradRMS(4))
            real(amrex_real),intent(in)::  amrrTime,amrrRefThresh
            character(kind=c_char),intent(inout):: cTag(iTagLo(1):iTagHi(1),iTagLo(2):iTagHi(2),iTagLo(3):iTagHi(3))

            integer,dimension(1:3):: iDomainLo,iDomainHi
            integer:: i,j,k,iCnt,iDir,iIdx,iNG
            real:: rFact
            !!
            !!  Scaling factor for gradients
            rFact= 0.75
            !!
            !!  Determine entire cell domain size for current level
            iDomainLo(1:3)= amrex_geom(iLvl)%domain%lo(1:3)
            iDomainHi(1:3)= amrex_geom(iLvl)%domain%hi(1:3)

            write(8,'(a,i3)') "AMReX:  Tagging Default at Level: ",iLvl
#if 1
              write(8,*) "Domain   : ",iDomainLo(1:3)
              write(8,*) "           ",iDomainHi(1:3)

              write(8,*) "Var      : ",iVarLoGradRMS(1:3)
              write(8,*) "           ",iVarHiGradRMS(1:3)

              write(8,*) "Box      : ",iBoxLo(1:3)
              write(8,*) "           ",iBoxHi(1:3)

              write(8,*) "Tag      : ",iTagLo(1:3)
              write(8,*) "           ",iTagHi(1:3)
#endif
              ....bunch of code working with tag array....
            return
          end subroutine AMREXFuns_TagRefine

- My level 0 partition table.  First column is process index, 2nd - 8th columns are imin, imax, jmin, jmax, kmin, kmax grid points

   0    1      1   33    1   33    1    2 amr
   1    1     33   65    1   33    1    2 amr
   2    1     65   97    1   33    1    2 amr
   3    1     97  129    1   33    1    2 amr
   4    1      1   33   33   65    1    2 amr
   5    1     33   65   33   65    1    2 amr
   6    1     65   97   33   65    1    2 amr
   7    1     97  129   33   65    1    2 amr

- Results of AMREX_TagRefine() subroutine for version 19.10 process 0:

AMReX:  Performing post level make/remake for level  0 box     1
AMReX:  End make new level at level  0
AMReX:  Tagging Default at Level:   0
 Domain   :            0           0           1
                     127          63           1
 Var      :           -2          -2           1
                      33          33           1
 Box      :            0           0           1
                      31          31           1
 Tag      :           -2          -2           1
                      33          33           1

- Results of AMREX_TagRefine() subroutine for version 19.10 process 1:

AMReX:  Performing post level make/remake for level  0 box     1
AMReX:  End make new level at level  0
AMReX:  Tagging Default at Level:   0
 Domain   :            0           0           1
                     127          63           1
 Var      :           30          -2           1
                      65          33           1
 Box      :           32           0           1
                      63          31           1
 Tag      :           30          -2           1
                      65          33           1

- Results of AMREX_TagRefine() subroutine for version 20.07 process 0:

MReX:  Performing post level make/remake for level  0 box     1
AMReX:  End make new level at level  0
AMReX:  Tagging Default at Level:   0
 Domain   :            0           0           1
                     127          63           1
 Var      :           -2          -2           1
                      33          33           1
 Box      :            0           0           1
                      31          31           1
 Tag      :           -2          -2           1
                      33          33           1

- Results of AMREX_TagRefine() subroutine for version 20.07 process 1.  Box indices are correctly mapped but the tag array seems to be mapped to process 4 indices.

AMReX:  Performing post level make/remake for level  0 box     1
AMReX:  End make new level at level  0         
AMReX:  Tagging Default at Level:   0          
 Domain   :            0           0           1
                     127          63           1
 Var      :           30          -2           1
                      65          33           1
 Box      :           32           0           1
                      63          31           1
 Tag      :           62          -2           1
                      97          33           1 

Basically, the assignment for the tag array is directly associated with the process ID as described in the partition table for version 19.10 but for version 20.07, the indices associated with tag array are staggered.  It 'seems' that my level 0 assigned box array and distribution map are not being associated with the tag array correctly.

process 0 box indices -> process 0 tag array indices (OK)
process 1 box indices -> process 2 tag array indices
process 2 box indices -> process 4 tag array indices
process 3 box indices -> process 6 tag array indices
process 4 box indices -> process 1 tag array indices
process 5 box indices -> process 3 tag array indices
process 6 box indices -> process 5 tag array indices
process 7 box indices -> process 7 tag array (OK)

I "think" what is happening is that the tag array is allocated based on the default box array and/or distribution mapping before I reset it under the call to the overloaded AMREXCoreFuns_MakeNewLevelFromScratch() subroutine.

Hope this helps...

John

**Comment by WeiqunZhang** [comment]
In your overload of MakeNewLevelFromScratch, you can call `amrex_set_distromap`, but `amrex_set_boxarray` won't have any effects.  It is supposed to be done in a virtual function that is currently not exposed in Fortran.  However, we probably could modify the code to make `amrex_set_boxarray` called inside `MakeNewLevelFromScratch` work on the coarsest level.  Let me see what we can do.

**Comment by aerojpapp** [comment]
Doh!  Let me check something.  I may have already added some type of interface.  There are a few that I required and added to 18.10 and 19.10 and thought added to 20.07 but may have missed something.  I can give you a complete list and then you can decide if it is worth adding.

John

**Comment by WeiqunZhang** [comment]
Could you test #1310?

**Comment by WeiqunZhang** [comment]
If you have modifications that you would like to contribute, please feel free to submit PRs.  We will review them and then decide.

**Comment by aerojpapp** [comment]
Yes, looking at my 19.10 version, I changed AMReX_AmrMesh.cpp to set both box array and distribution map if the incoming time was greater or equal to zero for this exact function.  I forgot to change the function for 20.07.  I've implemented your fix and will get back to you if it works.

**Comment by aerojpapp** [comment]
That worked.  Thanks.

John
