### ISSUE TITLE
extend_domain_face not working (2D)

### ISSUE THREAD

**Issue by darylbond** [AMReX-Codes/amrex#1313]
I am encountering issues on refined grids where ghost cells are not being flagged as covered with `extend_domain_face=true`. To test this I have defined a domain according to 

```
geometry.prob_lo     =  -10 -15 
geometry.prob_hi     =  20   15 
amr.n_cell           =  64 64
amr.max_level       = 3    
amr.ref_ratio       = 2 2 2 2 2 
amr.blocking_factor = 8
amr.max_grid_size   = 32
eb2.small_volfrac = 1e-6
eb2.extend_domain_face = 0
```

with geometry according to `EB2::BoxIF box({19,-10}, {21,10}, false);` i.e. a simple box that overlaps the domain boundary with the box defining the covered area. The error can then be observed in the below image where the volume fraction is shown on the left and a density field on the right. These FABs are at level 0 with ngrow = 4. From the density field we can see that the ghost cells on the right of the domain are being filled in correctly (zeros where it is supposed to be covered), whereas the volume fraction is only zero where the box is defined inside the domain and unity everywhere outside the domain.

![extend_domain_face_true](https://user-images.githubusercontent.com/726462/91301389-2eb0f780-e7e8-11ea-8607-ba77a4c76e5f.png)

From my understanding of the `extend_domain_face=true` option, the edge values should be extrapolated out to give a volume fraction plot that looks more like the density field plot. This test works with `extend_domain_face=false` as the box is defined outside the domain.

**Comment by WeiqunZhang** [comment]
I cannot reproduce what you see.  Could you provide a reproducer?

**Comment by darylbond** [comment]
I am putting together something now, but I have found that it appears the issue manifests when using `EB2::Build()` with `ngrow>4`.

**Comment by darylbond** [comment]
I have put together a stripped-down version of the EB CNS Pulse example:

[CNS_test.zip](https://github.com/AMReX-Codes/amrex/files/5148358/CNS_test.zip)

This includes some python plotting using the [matplotlibcpp](https://github.com/lava/matplotlib-cpp) library and so some python variables need to be configured in the makefile, or just disable it. Unfortunately, it also segfaults on exit and I haven't been able to track down the memory allocation so my apologies for that, but it should display the fault I am experiencing.

From some experimentation, it appears that it works with `EB2::Build()` with `ngrow == 4` and `m_eb_volume_grow_cells <= 4` as defined by `AmrLevel::SetEBMaxGrowCells`.

What are the implications of `m_eb_basic_grow_cells`, `m_eb_volume_grow_cells` and `m_eb_full_grow_cells` as I am currently unsure as to their correct value given my stencil requirements?

**Comment by WeiqunZhang** [comment]
I think #1321 should fix the issue.
