### ISSUE TITLE
enable the tutorial in cmake

### ISSUE THREAD

**Issue by wangzhezhe** [AMReX-Codes/amrex#1318]
Hello, 

there is a simple question, how to build the examples in the tutorial? I have set `ENABLE_TUTORIALS   ON`, but it looks that the executable is not built successfully:

```
build_amrex$ ls Tutorials/Basic/HeatEquation_EX1_C
CMakeFiles  Makefile  cmake_install.cmake  inputs
```

and there is only one target:

```
build_amrex$ make -j
[100%] Built target amrex
```

Thanks a lot for the help!

**Comment by mic84** [comment]
Hello
 
the tutorials targets are not included in the default target, therefore you need to explicitly do ```make <tutorial-name>``` to build a specific tutorial or ```make tutorials``` to build all of them. If you do ```make help```, you will see a list of available targets. 
I apologize for the the documentation not being clear on this. Please let us know if this works.

**Comment by wangzhezhe** [comment]
Thanks a lot for your help! @mic84
