### ISSUE TITLE
compilation error with gfortran 10.2.0 (and OpenMPI 4.0.4)

### ISSUE THREAD

**Issue by p-costa** [AMReX-Codes/amrex#1382]
Hello everyone,

I get the following error when compiling `amrex` with make and gfortran 10.2.0 (and OpenMPI 4.0.4):

```
/home/pedro/Work/codes/amrex/Src/F_Interfaces/Base/AMReX_parallel_mod.F90:294:23:

  294 |        call MPI_Reduce(tmp, r, 1, amrex_mpi_real, MPI_MIN, rank, m_comm, ierr)
      |                       1
......
  310 |        call MPI_Reduce(tmp, r, n, amrex_mpi_real, MPI_MIN, rank, m_comm, ierr)
      |                       2
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
```

Which seems related to the following line:

```fortran
 module amrex_fi_mpi
   implicit none
   include 'mpif.h'
 end module amrex_fi_mpi
```

To get it to work, I changed the line as shown below, and now the code compiles successfully:
```fortran
 module amrex_fi_mpi
   use mpi
   implicit none
 end module amrex_fi_mpi
```

Not sure if others also experienced this... Looking into the code, it seems like a bug in gfortran, but perhaps still worth reporting the issue here.

**Comment by WeiqunZhang** [comment]
Thanks for reporting this.  It used to the case that `include 'mpif.h'` was more portable than `use mpi`.  That's probably no longer true.  We will do some testing to see if we can switch.
