### ISSUE TITLE
Question regarding CMake variables

### ISSUE THREAD

**Issue by sayerhs** [AMReX-Codes/amrex#1426]
I noticed a few inconsistencies regarding CMake variables that I wanted to clarify. 

- The [CMake configuration options](https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html#customization-options) says `ENABLE_SENSEI_IN_SITU`, while the [visualization page](https://amrex-codes.github.io/amrex/docs_html/Visualization.html#compiling-with-cmake) says `ENABLE_SENSEI`, but the actual source code uses `ENABLE_SENSEI_INSITU`

https://github.com/AMReX-Codes/amrex/blob/c75c4a65ec50580504f87e6ea7cbd4d314644a17/Src/CMakeLists.txt#L139-L141

- There is also a variable `ENABLE_PROPARSER` that I don't see used elsewhere, was this intended to be `ENABLE_PROFPARSER` or are `PROFPARSER` and `PROPARSER` two separate configuration options?

https://github.com/AMReX-Codes/amrex/blob/c75c4a65ec50580504f87e6ea7cbd4d314644a17/Src/Extern/amrdata/CMakeLists.txt#L15-L17

@mic84 @ax3l

**Comment by mic84** [comment]
@sayerhs thank you for reporting this. PR #1428 will fix this issue.
