### ISSUE TITLE
Particle changes

### ISSUE THREAD

**Issue by timrlaw** [AMReX-Codes/amrex#1438]
Hi @atmyers 

It looks like 20.10 has brought a few changes to the way particles work. From what I can tell looking at PRs, the id and cpu fields have been "resized" to 40 and 24 bits respectively.

We have a code that does a fair bit of particle manipulation from Fortran, and in particular it quite often checks whether the particle id is positive, as a quick proxy for whether the particle is still valid (and sets the id to a negative number as a quick way to invalidate particles). I wanted to check whether this kind of thing is still expected to work under the new model?

I see the Fortran particle container in F_Interfaces now has a couple of wrapper methods that call into C++ to extract the id and cpu fields from the 64 bit blob. I could mimic this on our side, but I'm worried it will be a bit slow. An alternative would be to do the bitmasking from Fortran, but then I would need to hardcode the constants 24 and 40 somewhere. Are these expected to be stable going forwards? I would like to make sure we are using the API "properly" to avoid future breaking changes!

Any advice would be much appreciated.

Thanks,
Tim

PS. A heads up, looks like the documentation hasn't been changed to reflect these updates.

**Comment by atmyers** [comment]
Hi Tim,

Thank you for raising this issue, and apologies for the breaking changes. Checking / setting the particle ids as you are doing should definitely work going forward. I think the ideal way to do this from the Fortran side would be to go through the wrapper functions. Would it be possible to try it that way and see if it's fast enough for your purposes? If it's too slow, perhaps we could expose the constants to applications in way that is accessible to Fortran applications. I don't anticipate needing to change those numbers again (the new values should be enough for any realistic run in the near / not so near future), but it would probably be best to have those constants set in AMReX only. 

Thanks,
Andrew

**Comment by timrlaw** [comment]
Hi Andrew,

Thanks for the quick response and for clarifying. No worries on the breaking changes, I totally understand the reason for the change, and we are very grateful for AMReX existing in the first place!

I'll go the wrapper route for now then. If we do see performance issues related to the mask operations no being inlined then I suppose another option is to port our particle code to C++! (which we should really probably do anyway...)

Thanks,
Tim
