### ISSUE TITLE
Linear Solvers: Poisson problems with piecewise constant coefficients and interface jumps

### ISSUE THREAD

**Issue by gdeskos** [AMReX-Codes/amrex#1447]
Dear all,

I am an amex user/developer working within the ([AMR-Wind project ](https://github.com/Exawind/amr-wind)). For the last six monthsI have been developing the multiphase capabilities of AMR-WIND in order to enable water waves and free-surface turbulence simulations. One of the main problems I am facing at the moment is dealing with linear solvers, particularly in the vicinity of the two-fluid interface. Such problems occur both during a MAC projection and a Nodal projection (poisson solve). MLMG really struggles with solving these problems particularly when the density ratio between the two fluids is rho1/rho2>100. 

A possible solution would be to use AMG (using for example Hypre) but this is probably going to really slow down the simulations. I was therefore wondering if there is an easy hack within the native linear solvers. The problem really boils down to \beta (the non-constant coefficient - [see here](https://amrex-codes.github.io/amrex/docs_html/LinearSolvers.html#nodal-projection)) being a piecewise constant coefficient (1/\rho1 in fluid 1 and 1/\rho2 in fluid 2) and the source term containing a jump at the interface. 

Please let me know if someone has already worked on this, or/and have already found a solution. If not I think would be a very useful addition to the existing suite of linear solvers.

Best wishes,
Georgios (Yorgos) Deskos
Postdoctoral Research
National Renewable Energy Laboratory

**Comment by sayerhs** [comment]
@gdeskos Recently there were a few updates to AMReX hypre interface (see #1437 and #1439) that allow you to use hypre solvers and preconditioners from AMReX applications. If you have compiled [AMR-Wind](https://github.com/exawind/amr-wind) with HYPRE support `-DAMR_WIND_ENABLE_HYPRE=ON`, then you can try out the different hypre options. See the [example input file](https://github.com/sayerhs/exawind-sim/blob/master/examples/nalu-amr/sphere-amr.inp#L59-L97), also see exawind/amr-wind#221. It would be a good idea to check if even hypre can solve this issue or not (even if it is slow) or if some thinking of the algorithm.

**Comment by asalmgren** [comment]
@gdeskos --I believe this issue can be closed -- can you confirm?

**Comment by gdeskos** [comment]
yep, we can close this issue !
