### ISSUE TITLE
Build Question - Lib folders

### ISSUE THREAD

**Issue by pedro-ricardo** [AMReX-Codes/amrex#1463]
Hello there, I'm trying to build AMReX with the following libraries and versions:
```
1) gcc/9.1.1
4) cmake/3.16.7
2) mpich/3.3.1
3) petsc/3.11.3
5) hdf5/1.10.5
```
I'm on tag `20.10`, created a `build` folder and using the following options with cmake:
```
-DCMAKE_INSTALL_PREFIX=/opt/apps/amrex/20.10-mpich-3.3.1-petsc-3.11.3-hdf5-1.10.5
-DDIM=3 
-DENABLE_FORTRAN=yes 
-DENABLE_FORTRAN_INTERFACES=yes 
-DENABLE_MPI=yes 
-DENABLE_HYPRE=yes 
-DENABLE_HDF5=yes 
-DENABLE_PETSC=yes
```

How can I set the paths for those libraries I want to use? I coudn't find in the docs flags to set the path of the libraries ...
None of my libs are instaled in the system path, allways in `/opt/apps`.

**Comment by WeiqunZhang** [comment]
I am not a cmake user.  But I think you can use `-DCMAKE_LIBRARY_PATH=/path/to/hypre/lib:/path/to/petsc/lib -DCMAKE_INCLUDE_PATH=/path/to/hypre/include:/path/to/petsc/include`.  Replace `/path/to/hypre` and `/path/to/petsc` with your paths.

@mic84 @ax3l and @sayerhs will correct me if I am wrong.

**Comment by mic84** [comment]
AMReX uses the CMake command [find_package](https://cmake.org/cmake/help/latest/command/find_package.html#id1) to locate external libraries. The CMake  search procedure for external libraries is detailed [here](https://cmake.org/cmake/help/latest/command/find_package.html#id5). 
Long story short: provide either an environmental variable ```PackageName_ROOT``` pointing to the top level installation directory of ```PackageName```, or pass that information via a cmake option, i.e. ```cmake -DPackageName_ROOT=/path/to/top/level/installation/dir```.  Let us know if it works for you.

**Comment by pedro-ricardo** [comment]
Ok thank for the responses...

The `-DMPI_ROOT=\path\to\mpi` and `-DHYPRE_ROOT=\path\to\hypre` worked like a charm.. but i'm having issues with HDF5 lib.
The flag `-DMPI_HDF5=` works but I got strange errors. 

First I poited it to a parallel instalation of HDF5 in my PC, and got:
```
CMake Error at /opt/apps/cmake/3.16.7-gcc-9.3.1/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find HDF5: Found unsuitable version "", but required is at least
  "1.10.4" (found
  HDF5_hdf5_cpp_LIBRARY-NOTFOUND;/opt/apps/hdf5/1.10.5-gcc-9.1.1-mpich-3.3.1/lib/libhdf5.so)
```
So I thought maybe I forgot to turn-on the Cxx support in HDF5

I've now installed the HDF5 lib with `--enable-cxx` and pointed the path to it in cmake .. now i got the following:
```
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /opt/apps/hdf5/1.10.5-gcc-9.1.1/lib64/libhdf5_cpp.so;/opt/apps/hdf5/1.10.5-gcc-9.1.1/lib64/libhdf5.so;/opt/apps/szip/2.1.1-gcc-9.1.1/lib/libsz.so;/opt/apps/zlib/1.2.11-gcc-9.1.1/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found suitable version "1.10.5", minimum required is "1.10.4") found components: CXX 
CMake Error at Tools/CMake/AMReXThirdPartyLibraries.cmake:8 (message):
  
  HDF5 library does not support parallel I/O
Call Stack (most recent call first):
  Src/CMakeLists.txt:19 (include)
```
And that is the lack of a parallel hdf5 instalation.

But I was very surprised when tryed to compile HDF5 with `--enable-cxx` and `--enable-parallel` and got the following from HDF5:
```
configure: error: --enable-cxx and --enable-parallel flags are incompatible.
```

So ... how does AMReX use this? If it needs to be with `cxx` and it needs to be parallel ... but this build is unsuported by HDF5 lib

**Comment by pedro-ricardo** [comment]
I'm used to HDF5 files and AMR type of meshes and I'm only adding this in the instalation because I thought HDF5 would be faster to write outpus than the standard ... but I can just overlook this if you say that it does not make any difference to the standard output you already have

**Comment by sayerhs** [comment]
@pedro-ricardo I have HDF5 1.10.4 and I am able to use `--enable-cxx` and `--enable-parallel` together in the configure line. Can you post your full configure command for hdf5? I pass `CXX=$(which mpic++) CC=$(which mpicc)` as configure arguments, that is the difference may be?

**Comment by pedro-ricardo** [comment]
Yes sure.. I add those compiler flags as well
I'll just add new lines to make it easyer to read
```
CC=/opt/apps/mpich/3.3.1-gcc-9.1.1/bin/mpicc
FC=/opt/apps/mpich/3.3.1-gcc-9.1.1/bin/mpifort
CXX=/opt/apps/mpich/3.3.1-gcc-9.1.1/bin/mpicxx
./configure 
--prefix=/opt/apps/hdf5/1.10.5-gcc-9.1.1-mpich-3.3.1
--enable-parallel
--enable-fortran
--enable-cxx
--with-szlib=/opt/apps/szip/2.1.1-gcc-9.1.1/
--with-zlib=/opt/apps/zlib/1.2.11-gcc-9.1.1/include,/opt/apps/zlib/1.2.11-gcc-9.1.1/lib
```
The error pointed by configure is...
```
configure: error: --enable-cxx and --enable-parallel flags are incompatible.
```

I found from the HDF5 forums [here](https://forum.hdfgroup.org/t/c-versus-parallel/3577), the following
> Hi,
>
>This is because the library-wide lock that we use to enforce thread-safety is not elevated to the language wrappers (or the high-level library, either). We've never closely investigated if there would be problems if a context switch were to occur in the middle of the C++/Fortran/high-level calls, so thread-safety is currently labeled "unsupported" in the wrappers.
>
>You can build with thread-safety and C++ enabled using the --enable-unsupported configure option, but with a potential increase in risk.
>
>It's been a long-term goal of ours to move the lock into the higher-level wrappers, but there's no immediate plans to do this. A sponsor with funding for such a feature would obviously change the situation
>
>Cheers,
>
>Dana Robinson
>Software Engineer
>The HDF Group

So it is possible to compile it. By adding `--enable-unsupported` ... I just thought that this didn't seem like a good idea.
But if you're using it fine than i guess I'll do it

**Comment by pedro-ricardo** [comment]
Ok so now, with HDF5 intalled with `--enable-unsupported`
I can build AMReX with `MPI`, `HYPRE` and `HDF5` without error. 

Moving on to the last one ... PETSc

A flag like `-DPETSC_ROOT=` doesn't seem to work like the others and it can't find PETSc
```
-- kae
-- base PETSC_INCLUDE_DIRS_BASE-NOTFOUND
-- arch PETSC_INCLUDE_DIRS_ARCH-NOTFOUND
-- joe PETSC_INCLUDE_DIRS_BASE-NOTFOUND;PETSC_INCLUDE_DIRS_ARCH-NOTFOUND
CMake Error at /opt/apps/cmake/3.16.7-gcc-9.3.1/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PETSc (missing: PETSC_LIBRARIES PETSC_INCLUDE_DIRS)
  (Required is at least version "2.13")
```
But `-DPETSC_DIR=` does work
The flags are now:
```
-DCMAKE_INSTALL_PREFIX=/opt/apps/amrex/20.10-mpich-3.3.1-petsc-3.11.3
-DDIM=3
-DENABLE_FORTRAN=yes
-DENABLE_FORTRAN_INTERFACES=yes
-DENABLE_MPI=yes -DMPI_ROOT=/opt/apps/mpich/3.3.1-gcc-9.1.1
-DENABLE_HYPRE=yes -DHYPRE_ROOT=/opt/apps/petsc/3.11.3-gcc-9.1.1-mpich-3.3.1
-DENABLE_HDF5=yes -DHDF5_ROOT=/opt/apps/hdf5/1.10.5-gcc-9.1.1-mpich-3.3.1
-DENABLE_PETSC=yes -DPETSC_DIR=/opt/apps/petsc/3.11.3-gcc-9.1.1-mpich-3.3.1
```
But I'm stuck again ... The error is:
```
-- Found PETSc: /opt/apps/petsc/3.11.3-gcc-9.1.1-mpich-3.3.1/lib/libpetsc.so (found suitable version "3.11.3", minimum required is "2.13") 
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Failed to compile
CMake Error at Tools/CMake/AMReX_Defines.cmake:96 (message):
  Failed to find the Fortan C Interface -- check the CMakeError.log
Call Stack (most recent call first):
  Tools/CMake/AMReX_Config.cmake:41 (set_amrex_defines)
  Src/CMakeLists.txt:62 (configure_amrex)
```
But the funny thing is, if i remove the last line (that enables PETSc) in the command above, it passes this part just fine and ends configuration successfuly like:
```
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
```

**Comment by pedro-ricardo** [comment]
I oppened the **CMakeError.log** to check it .. it it has this funny message:
```
[  2%] Building Fortran object CMakeFiles/myfort.dir/my_module.f90.o
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: error: /opt/apps/petsc/3.11.3-gcc-9.1.1-mpich-3.3.1/include: read: Is a directory
collect2: error: ld returned 1 exit status
/bin/sh: /opt/apps/petsc/3.11.3-gcc-9.1.1-mpich-3.3.1/include: Is a directory
```
Now what is the PETSc include dir doing here is a good question :joy: :joy: :joy:

I'm also sorry for annoying you guys this much

**Comment by mic84** [comment]
Thank you for reporting this. This is the first time I see this error. I'll look into it.

**Comment by mic84** [comment]
@pedro-ricardo I think I have a fix: can you try PR #1464 and let me know if it works? Thanks

**Comment by pedro-ricardo** [comment]
@mic84 the PR #1464 Fixes it.

## In summary the answer is

To compile AMReX with `MPICH`, `HDF5`, `Hypre` and `PETSc` libraries installed in non standard folders, the following flags in **cmake** build can be used:
```
-DENABLE_MPI=yes -DMPI_ROOT=/path/to/mpich
-DENABLE_HYPRE=yes -DHYPRE_ROOT=/path/to/hypre
-DENABLE_HDF5=yes -DHDF5_ROOT=/path/to/hdf5
-DENABLE_PETSC=yes -DPETSC_DIR=/path/to/petsc
```
The only trick in those libraries is that `HDF5` must be installed with the flags `--enable-cxx`, `--enable-parallel` and `--enable-unsupported`, otherwise AMReX can not use it.


Thanks very much for the support. :+1:

**Comment by ax3l** [comment]
Just as a note, the variable [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/envvar/CMAKE_PREFIX_PATH.html) can also be used as a universal hint with a list of installation root paths:

For example:
```bash
export CMAKE_PREFIX_PATH=$HOME/software/hdf5-1.12.0:$HOME/software/boost-1.74.0:$CMAKE_PREFIX_PATH
```
