### ISSUE TITLE
virtual ~FabFactory

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/amrex#1478]
Seen with `dpcpp` and `hipcc` (SP compile) and `-Wdelete-non-abstract-non-virtual-dtor`:
```
delete called on non-final 'amrex::FabFactory<SigmaBox>' that has virtual functions but non-virtual destructor
```

**Comment by WeiqunZhang** [comment]
This is fixed in https://github.com/ECP-WarpX/WarpX/pull/1466.
