### ISSUE TITLE
tutorial plotfiles are not readable by postprocessing tools, yt, others

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#15]
The plotfiles produced by `Tutorials/Basic/HeatEquation_EX1_C/` are not readable by the usual Fortran post processing tools or yt.  Also apparently does not work with VisIt (haven't tried this personally).

yt complains in a regex part looking for the endian string.

**Comment by atmyers** [comment]
I think the reason is that the plot files are written with ghost cells, and yt (and maybe some of the other postprocessing tools) don't handle this.

**Comment by WeiqunZhang** [comment]
I just tested with Visit 2.12.2.  It works for me.

**Comment by zingale** [comment]
ah... interesting, okay.  Does visit know how to deal with ghost cells?  Is there a way to turn off the ghost cells here?

**Comment by WeiqunZhang** [comment]
Not sure about Visit.  We can certainly turn off ghost cells in AMReX_PlotFileUtil.cpp.  I am going to do that now.

**Comment by atmyers** [comment]
I've run into this regex string issue before and "solved" it by copying into temporary multifabs with no ghost cells when writing plot files. yt could also be made to detect whether ghost cells are present in AMReX plot files and account for them in the IO routines - I did this for Chombo data a while back. I'll file an issue in yt.

**Comment by WeiqunZhang** [comment]
Can you guys test the latest commit with yt?  Mike, are you supposed to be in NYC today?

**Comment by atmyers** [comment]
The latest commit works for me.

**Comment by zingale** [comment]
It works now.

(turns out there's internet in NYC :)

**Comment by WeiqunZhang** [comment]
I thought you were having fun.

**Comment by drummerdoc** [comment]
You've known Mike long enough now to know that this is his fun.

**Comment by IanHawke** [comment]
Can confirm that Visit 2.12.2 works for me on Mac too, now (didn't earlier); will check with Alice tomorrow (she has it failing with 2.10 on Ubuntu). Also yt loads correctly with the latest commit.

**Comment by zingale** [comment]
This seems to be fixed now.
