### ISSUE TITLE
Multifab question

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#157]
Is it necessarily true that the boxes in a multifab *all* have the same nodal type?  The particular construction sequence I've encountered so far suggest this is the case.  If so, is there a way to get the nodal type without iterating through the boxes?  I'm using the Fortran interface if that matters.

**Comment by WeiqunZhang** [comment]
Yes, all boxes in a multifab have the same nodal type.   In C++, `MultiFab`, via inheritance, has a memeber function `IndexType ixType() const` that can be used to get the type.  We don't have that in Fortran.  We can add one.  I am going to call it `nodal_type` and return `logical, dimension(3)`.

**Comment by WeiqunZhang** [comment]
In the latest development branch, `amrex_multifab`, `amrex_imultifab` and `amrex_boxarray` have a `nodal_type` function.

**Comment by nncarlson** [comment]
Thanks @WeiqunZhang for the clarification and the new function -- it will simplify things for me.

**Comment by nncarlson** [comment]
This seems to be working fine for me, so I'll close the issue.  Thanks again!
