### ISSUE TITLE
Fortran pre-processor errors in AMReX_filcc_mod.F90

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#159]
A recent commit (c7969cda) added includes of C header files to `AMReX_filcc_mod.F90` without apparently being aware that the preprocessor language understood by standard Fortran is a subset of that understood by C/C++.  In particular, the included files use the concatenation operator `##` which is not standard in Fortran.  Some compilers recognize it as an extension, but not the NAG compiler.  So this breaks things for NAG.

**Comment by maxpkatz** [comment]
I'm confused why this is a new issue. Those same includes are in the other FILCC files. Is there some code that uses AMReX_filcc_mod.F90 but not AMReX_FILCC_*D.F90?

**Comment by nncarlson** [comment]
It seems to be the constant macros (`eighth`, etc.) that are goofed up.  Those don't seem to be used in the AMReX_FILC_*D.F90 files you mention.  Actually, this snippet is in those files but not in AMReX_filcc_mod.F90
```
#undef  BL_LANG_CC
#ifndef BL_LANG_FORT
#define BL_LANG_FORT
#endif
```
Perhaps that is significant.

**Comment by maxpkatz** [comment]
Can you try compiling with those lines at the top of AMReX_filcc_mod.F90? I don't have the NAG compiler so I can't test it.

**Comment by nncarlson** [comment]
Just tried, but no luck.  Though I really do think BL_LANG_FORT needs to be set before including AMReX_REAL.H  (it may have been anyway).  I'm confused about this bit from that file:
```
#if __STDC__==1 || defined(__INTEL_COMPILER)
#        define BL_REAL(a) a##D0
#        define BL_REAL_E(a,b) a##D##b
#else
#        define BL_REAL(a) a/**/D0
#        define BL_REAL_E(a,b) a/**/D/**/b
#endif
```
I don't recognize what `/**/` is supposed to do.  It appears it is being translated to `@` in the processed file.  I'll investigate further.

**Comment by maxpkatz** [comment]
It could be that the issue is that the NAG compiler does understand the concatenation operator as ## but because of that conditional logic, we're telling it to use a different concatenation operator. That's why the || defined(__INTEL_COMPILER) is there, because I realized that Intel uses ## too. So a possible "fix" is to add || (NAG_COMPILER) or something to that effect, if this is the case.

**Comment by WeiqunZhang** [comment]
The make system passes `-DBL_LANG_FORT` when compiling F90 files.

My suggestion is add those constants into `AMReX_fort_mod.F90` and not using `AMReX_CONSTANTS.H` in `AMReX_filcc_mod.F90`.

**Comment by WeiqunZhang** [comment]
Or let's have `amrex_constants_module`.

**Comment by maxpkatz** [comment]
I think in this case we can probably just use the existing bl_constants_module. The reason that wasn't done before was presumably because they were originally .F files and didn't support module includes.

**Comment by WeiqunZhang** [comment]
`bl_constants_module` is in F_BaseLib, which hopefully will be gone eventually.

**Comment by WeiqunZhang** [comment]
We certainly don't want `Base` depends on `F_BaseLib`.

**Comment by maxpkatz** [comment]
So what, we should duplicate it in Base?

**Comment by maxpkatz** [comment]
I'm not opposed to that if there's no better way, just trying to figure out the best path here.

**Comment by WeiqunZhang** [comment]
Since F_BaseLib does depend on Base, we have move the content form bl_constants_module into amrex_constans_module, and have bl_constants_module simply use amrex_constants_module.

**Comment by maxpkatz** [comment]
OK by me.

**Comment by nncarlson** [comment]
It looks like you two may have settled on an approach.  To answer @maxpkatz earlier question, no, NAG does not support `##`.  Note that there is a legitimate way of defining the concatenation operator in terms of more basic preprocessor functionality, if you wanted to continue to use the existing include file approach.  I'd need to go dig that up (can't remember off the top of my head).

**Comment by nncarlson** [comment]
Here's a working alternative for the include file snippet I quoted earlier
```
#if __STDC__==1 || defined(__INTEL_COMPILER)
#        define BL_REAL(a) a##D0
#        define BL_REAL_E(a,b) a##D##b
#else
#        define IDENTITY(a) a
#        define BL_REAL(a) IDENTITY(a)IDENTITY(D0)
#        define BL_REAL_E(a,b) IDENTITY(a)IDENTITY(D)IDENTITY(b)
#endif
```
Of course that's not quite right (e.g., need to ensure IDENTITY is only defined once) but you get the idea.
I've used this header iin the past:
```
#ifdef PP_HAS_CONCATENATE
#define CONCATENATE(a,b) a ## b
#else
#define IDENTITY(x) x
#define CONCATENATE(a,b) IDENTITY(a)IDENTITY(b)
#endif
```
This requires setting PP_HAS_CONCATENATE appropriately for the compiler, and then using the CONCATENATE macro everywhere, so it's kind of obnoxious.

**Comment by WeiqunZhang** [comment]
Could you try the latest development branch?

**Comment by nncarlson** [comment]
There was one more place where the new amrex_constants_module needed to be used instead of the header file (found by a NAG failure).  Just submitted a pull request with the changes.

**Comment by nncarlson** [comment]
Thanks for addressing this pre-processor issue @WeiqunZhang, @maxpkatz.  Things compile fine now.  If there was some test suite I could run, I'd like to.  It works for my work-in-progress, but it may not even exercise this change.

There is one more issue with AMReX_filcc_mod.F90 but I'll open a separate issue for it.
