### ISSUE TITLE
Simple mesh build example

### ISSUE THREAD

**Issue by pedro-ricardo** [AMReX-Codes/amrex#1595]
Hello,
I'm using Fortran and trying to build a 2 level static mesh.
I'm setting the `initial_grid_file` parameter on input along other things.
I thought that both `init` subroutines were the only thing I needed to see the mesh in the `amrex_geom` variable. 

```f90
    call amrex_init()
    call amrex_amrcore_init()

    ! Print AMReX public variables
    write(*,*)amrex_max_level
    write(*,*)amrex_ref_ratio
    do i=0,amrex_max_level
        write(*,*)'Level: ',i
        write(*,*)amrex_geom(i)%dx
        write(*,*)amrex_geom(i)%domain%hi
        write(*,*)amrex_geom(i)%domain%lo
    end do
```
But all I see are 2 levels that fully cover the domain size.

The function that reads the `initial_grid_file` is not being called and I know that because I tried to force some errors like:
* Setting more levels in grid file than in input
* Setting a path to a file that does not exist

**So, to read that grid file in input .... what am I missing?**

**Comment by WeiqunZhang** [comment]
The domain in Geometry is the full domain (including regions not covered by any fine levels).  So the messages are correct.

The `initial_grid_file` parameter is only supported in `Amr/AmrLevel` classes in C++.  However, you should be able to get the grids you want with tagging.

**Comment by pedro-ricardo** [comment]
Thank you, I thought that I didn't had to define all those virtual functions to use a static mesh.

But after defining them ... the `amrex_init_from_scratch` subroutine will build the mesh respecting `initial_grid_file`?

**Comment by WeiqunZhang** [comment]
Unfortunately no.   But in the error estimate procedure (e.g., `my_error_estimate` in `Tutorials/FortranInterface/Advection_F/Source/my_amr_mod.F90`, you can read a file and then use the information to tag cells for refinement.

**Comment by pedro-ricardo** [comment]
I see, I'll do that way. Thanks!

But that seems a bypass to the input `initial_grid_file`, right?  This kind of initialization is not included when using the Fortran interfaces?

**Comment by WeiqunZhang** [comment]
That's right.  `initial_grid_file` is only available in `Amr/AmrLevel`, not in `AmrCore`.  The fortran interface is based on the latter.

**Comment by pedro-ricardo** [comment]
Thanks.

**Comment by pedro-ricardo** [comment]
Hello there @WeiqunZhang,
It's on the same subject so i'm not opening a new issue...

When tagging do I have to worry about keeping the grids nested? Or this is secured internally?

And about the tagging usage, correct me if I'm wrong:
* I'm assuming that `settag` will mark a `(i,j,k)` cell in level `L` that I want to become `L+1` cells after regrid
and that `cleartag` is the initial state of the `tagboxarray` variable... To use in case I marked something wrong
* Also a set of cells in level `L` will "disappear" when the corresponding cell in `L-1` is not tagged with `settag`.

**Comment by WeiqunZhang** [comment]
> When tagging do I have to worry about keeping the grids nested? Or this is secured internally?

No, that will be enforced internally.  However, by default there is one error buffer cell.  That is tagging a cell for refinement will effectively mark its neighbor cells to be refined too.   There is also the blocking factor parameter.  These may result in a refined region larger than the tagged the region.

>     * I'm assuming that `settag` will mark a `(i,j,k)` cell in level `L` that I want to become `L+1` cells after regrid
>       and that `cleartag` is the initial state of the `tagboxarray` variable... To use in case I marked something wrong

Yes.

>     * Also a set of cells in level `L` will "disappear" when the corresponding cell in `L-1` is not tagged with `settag`.

Yes, one probably should think that way, even though it's not exactly like that.  (Tagging on level `L` takes places before level `L-1`.  If some cells on `L` have been tagged for refinement to level `L+1`, those cells will not disappear.)

**Comment by pedro-ricardo** [comment]
It's me again... prolonging this issue with another doubt

I got the idea of opening the mesh structure and going through the patches (boxes) in each level, it's very similar to our older code.
```f90
! Open the iterator
call amrex_mfiter_build(mfi, phi(lev), tiling=.true.)
! Iterate over patches (boxes) in level
do while(mfi%next())
    ! Get this box info
    bx = mfi%tilebox()
    ! Set pointer to it's data
    p => phi(lev)%dataPtr(mfi)
    ! Get variable limits
    lo = lbound(p)
    hi = ubound(p)

    ! Pass to a function and use it (...) 
end do
```
My doubt is this: You need to set a variable in `amrex_mfiter_build` so this indexes are valid for data that has the same location as `phi` (cell centered for example). So how can I use the same `mfi` loop to iterate over cell centered and face centered variables?

I've found this in an example, but I don't understand the `resize` and `grow` steps:
```f90
! Open the iterator
call amrex_mfiter_build(mfi, phi_new(lev), tiling=.true.)
! Iterate over patches (boxes) in level
do while(mfi%next())
    ! Get centered box info
    bx = mfi%tilebox()
    ! Loop in directions
    do idim = 1, 3
        ! Copy centered box
        tbx = bx
        ! Transform index in faced for idim direction
        call tbx%nodalize(idim)

        ! From now on ...
        ! I don't get the resizes and grow ??
        call flux(idim)%resize(tbx,ncomp)
        call tbx%grow(1)
        call uface(idim)%resize(tbx,1)
    end do

    ! Pass to a function and use it (...) 
end do
```

**Comment by pedro-ricardo** [comment]
Can I have a hand on understanding the previous question?

**Comment by WeiqunZhang** [comment]
Yes, it's safe to use `mfi` built with `phi` on another multifab if the two have the same distribution map and boxarray (other than index type difference).

`resize` resizes a fab to the given box and the number of components.

`grow` grows a box.

**Comment by pedro-ricardo** [comment]
Ok, thanks .. just to confirm then:

The `grow` is to extend the `mfi%tilebox()` limits? Like to insert in it a ghost layer?
Or it is a must do thing when opening the `mfi` with a centered variable and accessing a faced one.

In this situation I've presented I think the `resize` is a **must do** step after `tbx%nodalize(idim) `, since the box is different for a faced variable. Right?

Once opened, the same `i` index for a center and a face variable will be physically representing different locations, but how are they positioned?

**Like these:**
```
Face Index
i      i+1     i+2     i+3
|-------|-------|-------|
|   o   |   o   |   o   |
|-------|-------|-------|
    i      i+1     i+2
Center Index
```
**Or these:**
```
Face Index
i-1      i      i+1     i+2
 |-------|-------|-------|
 |   o   |   o   |   o   |
 |-------|-------|-------|
     i      i+1     i+2
Center Index
```

**Comment by WeiqunZhang** [comment]
I refer you to https://amrex-codes.github.io/amrex/docs_html/Basics.html#box
```
That is if we consider a cell based index represent i, the nodal index with the same integer value represents i−1/2.
```

https://amrex-codes.github.io/amrex/docs_html/Basics.html#mfiter-and-tiling is also recommended.  Although the examples are in C++, the concept is the same.

**Comment by pedro-ricardo** [comment]
I have a doubt about the Ghost calculation in AMReX when between levels.
Suppose I have a `multifab` that has all levels in the same timestamp and I just want to rebuild the ghosts between levels of this variable.

It is possible to call something like the `amrex_fillpatch` on the variable it self? because it seems in the examples that `amrex_fillpatch` is used to return a hole new variable.

Will calling it like this work?
```f90
call amrex_fillpatch(phi, time, phi(lev-1), time, phi(lev-1), &
                     amrex_geom(lev-1), fill_physbc   , &
                          time, phi(lev  ), time, phi(lev  ), &
                     amrex_geom(lev  ), fill_physbc   , &
                     time, 1, 1, 1,  amrex_ref_ratio(lev-1), &
                     amrex_interp_cell_cons, lo_bc, hi_bc)
```

**Comment by WeiqunZhang** [comment]
Yes, it's safe for the destination to be the same multifab as the source.

**Comment by pedro-ricardo** [comment]
The documentation mention the well known 3 types of ghosts of an AMR grid.
- Internal boundary
- Domain boundary
- Coarse/Fine boundary

So far I've founded: `amrex_multifab_fill_boundary` to fill only the **internal** and `amrex_fillpatch` that fill **all three types**. 
Is there a Fortran subroutine to fill only the Domain Boundary?

**Comment by WeiqunZhang** [comment]
No, there is no such a function unless it's a constant value.  But one can write a `mfiter` loop.  Then with the domain box in geometry and the box of a fab, one should have enough information to determine if a cell is outside the domain.

However, if one needs to fill a constant value for the domain boundary, there is a C++ function for it.
```
void FabArray::setDomainBndry (value_type val, int strt_comp, int ncomp, const Geometry& geom);
```
If that makes things easier, one could add a Fortran wrapper for it.
