### ISSUE TITLE
Error in AMReX_filcc_mod.F90 when compiled in 2D

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#162]
The new version of `AMReX_filcc_mod.F90` has some issues when it is compiled in 2D (amrex_spacedim = 2).  Here's a snippet with an error that the NAG compiler detects (it is really good at this)
```
  subroutine filccn(lo, hi, q, q_lo, q_hi, ncomp, domlo, domhi, dx, xlo, bc)
   [...]
    integer,          intent(in   ) :: q_lo(3), q_hi(3)
    integer,          intent(in   ) :: domlo(amrex_spacedim), domhi(amrex_spacedim)
   [...]
    ks = max(q_lo(3), domlo(3))
    ke = min(q_hi(3), domhi(3))
   [...]
    klo = domlo(3)
    khi = domhi(3)
```
The domlo(3), domhi(3) references are out-of-bounds.

I don't know enough about the code to propose a fix.  If the actual arguments for the domlo/hi dummy arguments are actually length 3, then the dummy arguments could be declared that way.  Otherwise at runtime those references are illegal, though probably harmless (presumably ks, ke, klo, khi aren't actually used).  Here's a patch that avoids executing the illegal references and which also passes muster with the NAG compiler
```patch
@@ -123,15 +123,19 @@ contains
     ie = min(q_hi(1), domhi(1))
     js = max(q_lo(2), domlo(2))
     je = min(q_hi(2), domhi(2))
-    ks = max(q_lo(3), domlo(3))
-    ke = min(q_hi(3), domhi(3))
+    if (amrex_spacedim == 3) then
+       ks = max(q_lo(3), domlo(amrex_spacedim))
+       ke = min(q_hi(3), domhi(amrex_spacedim))
+    end if
 
     ilo = domlo(1)
     ihi = domhi(1)
     jlo = domlo(2)
     jhi = domhi(2)
-    klo = domlo(3)
-    khi = domhi(3)
+    if (amrex_spacedim == 3) then
+       klo = domlo(amrex_spacedim)
+       khi = domhi(amrex_spacedim)
+    end if
 
     do n = 1, ncomp
 
```
Note that there is a a further issue if AMReX is built in 1D, though that seems to be broken at the moment (C++ error elsewhere).
@maxpkatz

**Comment by maxpkatz** [comment]
One of our test suites picked this up and I have already fixed it this morning in the development branch.

45c301572c9ca14da448f38167be1f4fbb2fb519

Thanks for the report!

**Comment by nncarlson** [comment]
Ah, great I must have just missed the update by a few minutes.
