### ISSUE TITLE
Tutorials don't build with MSVC + CUDA

### ISSUE THREAD

**Issue by robertmaynard** [AMReX-Codes/amrex#1639]
The AMReX transformation of C++ CMake properties to CUDA properties causes them all to become `PRIVATE` properties. Therefore the `/experimental:preprocessor` or `/Zc:preprocessor` flags aren't properly propagated to consumers.

Any preferences on how best to resolve this @ax3l?

**Comment by ax3l** [comment]
I think that's now fixed and #1585 adds CI for it.

Xref: #1773 #1593 #1009
