### ISSUE TITLE
GFortran and derived type finalization: working for anyone?

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#166]
I'm running into a segfault when running an executable built with gfortran (gcc 6.4.1).  According to amrex's own traceback file, it is occurring in amrex_imultifab_destroy and it is being called automatically through finalization of some object.  (A higher-level object is being passed to an INTENT(OUT) dummy argument, which triggers finalization of the object.)  The code is working fine when built with Intel 17.

I'm pretty sure this is an issue with gfortran.  To this day gfortran has long-standing serious defects in its implementation of derived type finalization; see the meta bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=37336.  How are other gfortran users dealing with this problem?  By making explicit calls to the "destroy" subroutines to head-off automatic finalization from needing to do anything?

**Comment by WeiqunZhang** [comment]
Yes, this is a known gcc bug.  In `amrex/Tutorials/Amr/Advection_F/Source/amr_data_mod.F90`, we explicitly call destroy.  That seems to work.

**Comment by nncarlson** [comment]
I decided to chase down the specific error.  If anyone is curious, here's an example independent of amrex that segfaults.
```fortran
module mod

  type foo
    integer, pointer :: f(:) => null()
  contains
    final :: foo_destroy
  end type
  
  type bar
    type(foo) :: b(2)
  end type

contains

  elemental subroutine foo_destroy(this)
    type(foo), intent(inout) :: this
    if (associated(this%f)) deallocate(this%f)
  end subroutine

end module

program main

  use mod
  type(bar) :: x
  call sub(x)
  
contains

  subroutine sub(x)
    type(bar), intent(out) :: x
  end subroutine

end program
```
I ought to report it, I guess, but it's probably a duplicate, and most of my reports have gone ignored anyway.
