### ISSUE TITLE
Fortran 'amrex_string' type missing free method

### ISSUE THREAD

**Issue by pedro-ricardo** [AMReX-Codes/amrex#1666]
Thank you for the awesome support so far in helping me port our AMR code to AMReX.

When using the `type(amrex_string)` there is a subroutine to initialize it `call amrex_string_build(varname, "phi")` but no method to free it nor a `final` procedure in the type definition.

This generates a memory leak since the type has an `allocatable` variable. Since it's very simple currently I'm deallocating it manually `deallocate(varname%data)` but it should be a method for it.

**Comment by WeiqunZhang** [comment]
I think Fortran `allocatable` will be automatically deallocated when it is out of scope.

**Comment by WeiqunZhang** [comment]
If not, it's a compiler bug.

**Comment by pedro-ricardo** [comment]
I'm getting this info from `valgrind` and using `gcc-9`, but it might be a false positive then.
```log
4 bytes in 1 blocks are still reachable in loss record 1 of 3
==27065==    at 0x4839753: malloc (vg_replace_malloc.c:309)
==27065==    by 0x4A74878: __amrex_string_module_MOD_amrex_string_build (libamrex.so)
==27065==    by 0x40362C: MAIN__ (main.f08:41)
==27065==    by 0x4034AC: main (main.f08:2)
```
It disappears when I do it manually `deallocate(varname%data)`. 

Thanks
