### ISSUE TITLE
mkconfig.py creates a bad AMReX_Config.H when the user has defined CPPFLAGS to include -I flags

### ISSUE THREAD

**Issue by JBlaschke** [AMReX-Codes/amrex#1682]
I have `CPPFLAGS` set to include `-I/usr/local/...` which trips up the compiler when using GNU make:
```
tmp_build_dir/s/3d.gnu.MPI.EXE/AMReX_Config.H:3:9: error: macro name must be an identifier
#ifndef -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include
```
which is due to a bad `AMReX_Config.H`:
```
#ifndef AMREX_HAVE_NO_CONFIG_H
#define AMREX_HAVE_NO_CONFIG_H
#ifndef -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include
#define -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include -I/usr/local/opt/binutils/include -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include 1
#endif
```
After consulting Michele, I found that `mkconfig.py` does not expect `-I` flags in the `--defines`:
```
$(srcTempDir)/AMReX_Config.H:
        @echo Generating AMReX_Config.H ...
        @if [ ! -d $(srcTempDir) ]; then mkdir -p $(srcTempDir); fi
        @ $(MKCONFIG) --defines="$(CPPFLAGS)" --undefines="" \
                      --comp="$(lowercase_comp)" \
                      --allow-different-compiler="$(ALLOW_DIFFERENT_COMP)" \
                      > $@
```
I suggest sanitizing the input to `--defines` when the user specifies include directories (or better still, non `-D` flags) in `CPPFLAGS`

@WeiqunZhang tag?

@mic84 wants me to make sure that I mention that CMake doesn't run into this problem (my guess would be that CMake sanitizes that inputs into `mkconfig.py` byt GNU Make does not).

**Comment by WeiqunZhang** [comment]
I think the issue is `CPPFLGAS` is usually supposed to be for C preprocessor flags, not C++ flags. 

https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

**Comment by WeiqunZhang** [comment]
If you want to add extra `-I` flags, you can use `INCLUDE_LOCATONS += /usr/local/... /usr/local/...`.

**Comment by WeiqunZhang** [comment]
As for CMake, sure it does not cause a problem in AMReX_Config.H, but your flags will magically disappear and will probably cause problems later.  Otherwise why do you have to pass those flags in the first place?

**Comment by JBlaschke** [comment]
Hi @WeiqunZhang , this is part of my computer's environment config. I add include locations into CPPFLAGS as that is the recommended way to pass includes to python's setuptools

**Comment by JBlaschke** [comment]
I think CMake is able to parse the CPPFLAGS for includes.

**Comment by mic84** [comment]
@JBlaschke can you confirm that your flags did not magically disappear and you don't experience any issue later on? Else I will have to look into it. Thanks.

**Comment by JBlaschke** [comment]
@mic84 when using cmake I can confirm that nothing disappears or stops working (magically or otherwise). I also don't experience any other issues down the road.

**Comment by WeiqunZhang** [comment]
I was doing this, and don't see `xxxxxx` in the flags printed by cmake.  So What did I do wrong?

```
$ CPPFLAGS=-Ixxxxxxxxxxxxx cmake ..
-- CMake version: 3.16.5
-- AMReX installation directory: /home/wqzhang/mygitrepo/amrex/installdir
-- Build type set by user to 'Release'.
-- Building AMReX with AMReX_SPACEDIM = 3
-- Configuring AMReX with the following options enabled: 
--    AMReX_PRECISION = DOUBLE
--    AMReX_MPI
--    AMReX_LINEAR_SOLVERS
-- AMReX configuration summary: 
--    Build type               = Release
--    Install directory        = /home/wqzhang/mygitrepo/amrex/installdir
--    C++ compiler             = /usr/bin/c++
--    C++ defines              = 
--    C++ flags                = -O3 -DNDEBUG  -pthread -Werror=return-type
--    C++ include paths        = -I/home/wqzhang/mygitrepo/amrex/Src/Base -I/home/wqzhang/mygitrepo/amrex/Src/Boundary -I/home/wqzhang/mygitrepo/amrex/Src/AmrCore -I/home/wqzhang/mygitrepo/amrex/Src/Amr -I/home/wqzhang/mygitrepo/amrex/Src/LinearSolvers/MLMG -I/home/wqzhang/mygitrepo/amrex/Src/LinearSolvers/Projections -I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent -I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include -I/usr/lib/openmpi/include/openmpi -I/usr/lib/openmpi/include
--    Link line                = -pthread /usr/lib/openmpi/lib/libmpi.so /usr/lib/openmpi/lib/libmpi_cxx.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wqzhang/mygitrepo/amrex/build
```

**Comment by JBlaschke** [comment]
Anyway, I think _why_ my CPPFLAGS contain include locations is beside the point. The salient point here is that the user config might contain them for various reasons, and so some sanitization might be necessary before calling the mkconfig.py.

**Comment by WeiqunZhang** [comment]
Yes, but I like to understand what cmake does exactly in this case.  What do you do exactly with cmake?  Could you show me you cmake output?

**Comment by JBlaschke** [comment]
I build libamrex:
```
cmake -DAMReX_PARTICLES=ON -DAMReX_AMRDATA=ON -DAMReX_EB=ON -DAMReX_OMP=ON -DBUILD_SHARED_LIBS=ON \
DAMReX_PIC=ON -DAMReX_FORTRAN_INTERFACES=ON -DAMReX_FORTRAN=ON -DCMAKE_INSTALL_PREFIX="." ..
```

@mic84 Can you point @WeiqunZhang to how CMake solves this

I agree with you, btw, that this is a bit odd -- the reason why it is there in the first place is from homebrew's docs on LLVM:
```
For compilers to find llvm you may need to set:
  set -gx LDFLAGS "-L/usr/local/opt/llvm/lib"
  set -gx CPPFLAGS "-I/usr/local/opt/llvm/include"
```

**Comment by WeiqunZhang** [comment]
If you do `make VERBOSE=ON`, do you see `-I/usr/local/opt/llvm/include`?

**Comment by WeiqunZhang** [comment]
I am trying to understand which is better.  Silently ignore it or move it to CXXFLAGS.  I suspect cmake simply ignore it.  But you said nothing disappears.

**Comment by WeiqunZhang** [comment]
I agree we should fix this one way or the other, given that homebrew suggests people to set that.

**Comment by JBlaschke** [comment]
I understand the question now -- no CMake ignores the `-I/usr/local/opt/llvm/include` flag. It doesn't break anything though, because cmake finds lllvm clang, so those flags are not needed.

**Comment by WeiqunZhang** [comment]
We could make gnumake ignore that too.  It does not need that `-I` flag because you are invoking the compiler directly.

**Comment by JBlaschke** [comment]
In general, I don't like ignoring settings -- a pain to debug if you don't know a setting is ignored. On the other hand, if I'm using GNUMake, I already specify which compiler I want to use, and how. So I don't need those flags.

I just don't want to have to `CPPFLAGS= make`

**Comment by WeiqunZhang** [comment]
We can print out a warning and ignore it.

**Comment by JBlaschke** [comment]
I think that's a fair compromise: "You can't say we didn't warn you"

**Comment by mic84** [comment]
I was mistakenly under the impression we were talking about `CXXFLAGS` instead of `CPPFLAGS`. The former is honoured by the CMake, the latter is not. Here is a [list of envirnmental libraries that CMake honours](https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html#manual:cmake-env-variables(7)). As an example consider  `CXXFLAGS`: if it is defined in the environment, it is used to initialize `CMAKE_CXX_FLAGS` ( see https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html). Long time ago amrex CMake was made to honour `CPPFLAGS` too, but then we decided against it because not CMake-standard compliant. I can bring that back if it's needed but I'd rather not.

**Comment by WeiqunZhang** [comment]
I think this should work now.  Note that no warning is given because we do not modify CPPFLAGS, and everything in it will be passed to the compiler.

**Comment by JBlaschke** [comment]
thanks!

**Comment by ax3l** [comment]
Not sure if that helps, but CXXFLAGS/CFLAGS is the right thing to set. CPPFLAGS is indeed the preprocessor.

**Comment by ax3l** [comment]
It would be awesome though, if we add recognition of env var `CXXFLAGS`/`CFLAGS`/`FFLAGS`/`LDFLAGS`[/`CPPFLAGS`] to GNUmake if that is still missing. It's a pretty common unix convention to set them in environments and pick them up in project builds (e.g. in many package managers or `.profile` setups of users). Just asking because I don't remember the status of this.

**Comment by WeiqunZhang** [comment]
That should be just a simple change of `=` -> `+=`.  We have always ignored the environment's CXXFLAGS because we want more controls.  Anyway, we could consider that.  Abort FFLAGS, does cmake use separate flags for Fortran 77 and Fortran 90+?

**Comment by ax3l** [comment]
For Fortran, I think conventions are `FFLAGS`/`FCFLAGS`... I am not too knowledgeable on that one and if e.g. `F90FLAGS` is common.

Since we only use modern Fortran, we might be ok with picking one? CMake seems to accept `FFLAGS`, but we should research properly.

**Comment by WeiqunZhang** [comment]
For cuda, hip and dpcpp, what happens to `CXXFLAGS`?

**Comment by mic84** [comment]
@ax3l  According to [this](https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html#manual:cmake-env-variables(7)), `F90FLAGS` is not honoured by CMake. xSDK guidelines don't mention it either (only `FFLAGS` for Fortran)

@WeiqunZhang for CUDA, CMake honours `CUDAFLAGS`. However, AMReX CMake has the ability to forward any C++ flags to the host compiler, so the content of `CXXFLAGS`  should be passed to the host compiler as well. Regarding HIP and DPCPP: CMake does not support them natively for the time being. However, the current implementation in AMReX CMake is to treat them as regular C++ compilers, therefore  `CXXFLAGS` is honoured accordingly.
