### ISSUE TITLE
Question: Expected behavior of AmrMesh 

### ISSUE THREAD

**Issue by sayerhs** [AMReX-Codes/amrex#1683]
I am wondering about the expected behavior of `AmrMesh::ref_ratio` when `amr.max_level = 0`. I expect `ref_ratio` to be a vector of size 1 just like other arrays (`geom`, `dmap`, etc.). However, it is initialized as a zero size array. Is this a bug in AMReX or some special case that I've not understood? Looking at the code, it appears that `AmrMesh::InitAmrMesh` behaves differently than one of the `AmrMesh::AmrMesh` constructor

https://github.com/AMReX-Codes/amrex/blob/c98be7422796a0e29cb539f805d91d19c2a5ba01/Src/AmrCore/AMReX_AmrMesh.cpp#L90-L95

Here, `ref_ratio` is resized to `max_level` and not `nlev` as the other arrays are. 
https://github.com/AMReX-Codes/amrex/blob/c98be7422796a0e29cb539f805d91d19c2a5ba01/Src/AmrCore/AMReX_AmrMesh.cpp#L73-L81

However, in the other constructor it is resized to `nlev = max_level + 1`

https://github.com/AMReX-Codes/amrex/blob/c98be7422796a0e29cb539f805d91d19c2a5ba01/Src/AmrCore/AMReX_AmrMesh.cpp#L36-L43

**Comment by WeiqunZhang** [comment]
Yes, they are inconsistent, and size of ref_ratio being max_level is the traditional behavior.  I guess we should regard accessing ref_ratio[0] as undefined behavior if max_level is 0.  Is this causing any issues for you?

**Comment by sayerhs** [comment]
I stumbled upon this in the following code snippet

```c++
    for (int lev = 0; lev < nlevels; ++lev) {
        const auto& ba = mesh.boxArray(lev);
        const auto& dm = mesh.DistributionMap(lev);

        // Get all possible intersections at this level
        const auto& isects = ba.intersections(bx);

        // Extract the processor ranks
        for (const auto& is : isects) procs.insert(dm[is.first]);

        bx = bx.refine(mesh.refRatio(lev));
    }
```

Changing the last line to 

```C++
        if (lev < finest_level) bx = bx.refine(mesh.refRatio(lev));
```

fixed the issue for me. However, this only shows up on a debug build and not in an optimized build.

**Comment by WeiqunZhang** [comment]
I see.  By the way `bx.refine(..)` without assignment is sufficient.
