### ISSUE TITLE
linear solve of anisotropic diffusion of a scalar?

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#1717]
Hi,

I'd like to use the linear solvers to solve an equation of the form:

0 = \alpha A + \div \cdot [ T \grad \phi ) ] \, ,

where \alpha is a constant, A is a scalar field, \phi is a scalar field, and T is a (symmetric positive definite) tensor field.
All variables are cell-centered, except T, which is face-centered.

It looks like the tensor solve built into AMReX doesn't support this form. Do I need to write my own linear operator deriving from MLCellLinOp to do this?  If so, what functions do I need to overload and what do they need to do? The derived operator example in Tutorials/ is only for a nodal solver, and the API appears to be different for cell-centered solvers (and the documentation does not specify what the overloaded functions need to do).

**Comment by BenWibking** [comment]
I'd like to use AMReX to solve this problem using the discretization described in the [hypre documentation](https://hypre.readthedocs.io/en/latest/ch-sstruct.html#block-structured-grids-with-stencils). It essentially uses a mixed finite element method with cell-centered and face-centered unknowns. Can I use such a mixed representation by deriving from either `MLCellLinOp `or `MCNodeLinOp`?

**Comment by WeiqunZhang** [comment]
It's probably hard to reuse `MLMG` or `MLCellLinOp` or `MLNodeLinOp` for your purpose.  But maybe you can use `amrex/Src/Extern/HYPRE` as an example of writing a solver based on hypre.  `HypreABecLap`, `HypreABecLap2` and `HypreABecLap3` use `HYPRE_StructGrid`, `HYPRE_SStructGrid` and `HYPRE_IJMatrix`, respectively.

**Comment by BenWibking** [comment]
Yes, this is what I need, thanks! The code in AMReX_HypreABecLap2.cpp is only for a single-level solve, correct?

**Comment by WeiqunZhang** [comment]
Yes, that's single level.

**Comment by BenWibking** [comment]
Is there any example code that illustrates how to call hypre with AMReX data for two (or more) levels? The main solve could be single level, but the sync solve still needs to couple two levels at a time in order to avoid conservation errors.

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Astro/Castro/tree/main/Source/radiation is an example.

**Comment by BenWibking** [comment]
Thanks! I should be able to figure it out from here.
