### ISSUE TITLE
Throw error during build if using unsupported gcc

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#173]
I believe that we are effectively requiring gcc >= 4.8.1 due to the use of -std=c++11. It would be nice if the build system detected that we are using an older version and refused to build with it, printing a helpful error message. The GNUMake directory has the sed magic needed to extract the GCC minor version.

**Comment by WeiqunZhang** [comment]
Yes, we could add a detection.  GCC website says 4.8.1 is their first C++11 feature complete version.  But it's a pain to do this with make.  I will try.

**Comment by WeiqunZhang** [comment]
When I run `gcc -dumpversion` with my gcc 4.8.4, I only get `4.8` without the patchlevel version.  Not sure how to get the patchlevel version reliably.  When I was searching for a way of doing this, I was surprised to find out that some systems only print the major version.  https://stackoverflow.com/questions/45168516/gcc-7-1-1-on-fedora-26-dumpversion-now-only-includes-major-version-by-default

Anyway, I am assuming dumpversion will give me x.y and throw an error if it is less than 4.8.

**Comment by WeiqunZhang** [comment]
This is done in the latest development branch.

**Comment by maxpkatz** [comment]
I verified that the comment in that SO post is correct -- adding -dumpfullversion gives the minor and patch level version on Fedora, and doesn't change the behavior for a couple other OS'es I tried. So I added it.
