### ISSUE TITLE
Get rid of "loop not vectorized" warnings

### ISSUE THREAD

**Issue by MaxThevenet** [AMReX-Codes/amrex#1813]
When compiling with the Clang compiler with `USE_OMP=FALSE`, I get a number of warnings from lines like:
https://github.com/AMReX-Codes/amrex/blob/327c62b150bb23ce01633a4d7ae060291156c62d/Src/Base/AMReX_GpuLaunchFunctsC.H#L118
Should I just change the compilation flags, or should I try and fix these warning in AMReX code?

**Comment by WeiqunZhang** [comment]
In GNU make, we add `-Wno-pass-failed` to Clang based compilers (e.g., clang, hipcc and dpcpp).  See https://github.com/AMReX-Codes/amrex/blob/development/Tools/GNUMake/comps/llvm.mak#L41.  Maybe we should add that to CMake too?  @mic84 @ax3l

**Comment by mic84** [comment]
@WeiqunZhang fine by me. Should I proceed?

**Comment by ax3l** [comment]
Sounds also good to me. I looked at the warnings and most of them are `PRAGMA_SIMD` calls on loops that call functions that cannot be inlined/vectorized per se.

**Comment by WeiqunZhang** [comment]
Yes.  Thank you! @mic84

**Comment by MaxThevenet** [comment]
Awesome, thank you!
