### ISSUE TITLE
[Fortran] creating an amrex_mfiter without an amrex_multifab

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#182]
On certain occasions I need to iterate through the on-process boxes of a multifab where my only interest is in the extents of the boxes.  For this I build a dummy multifab (cell-based, no ghosts), and then build a multifab iterator from it.  I'd like to avoid the dummy multifab if possible.  Looking at the C++ code I see some MFIter constructors that take BoxArray and DistributionMapping arguments instead of a MultiFab.  I'm thinking to expose those in the Fortran interface by adding new specific procedures to the amrex_mfiter_build procedure.  This seems completely straightforward, but thought I should ask if I'm missing something here or if there are particular things I need to pay attention to.

**Comment by asalmgren** [comment]
The question is whether you want to learn about an existing DistributionMapping or you want to build a new one and see what it would be.  Do you know which scenario you're targeting?

**Comment by nncarlson** [comment]
The former, I'm sure.  At this point I have a fixed BoxArray and a FixedDistribution mapping that everything else is built off of.

**Comment by asalmgren** [comment]
So the DistributionMapping itself is a list of box --> processor mapping -- that plus the boxarray has the information I think you want then.    Is the idea that you want it in the format where you can loop from 1, ...n_{boxes on this processor} and print out the lo,hi for example?

**Comment by nncarlson** [comment]
Yes, that's basically what I want.  In the particular case that provoked this question, I'm initializing Hypre's semi-struct system interface and I need to make a series of calls to set the grid/box extents (lo/hi) for the boxes on this processor.  Using amrex_mfiter and its tilebox method (Fortran interface) works just fine for this, except that I need to create a dummy multifab for this, which is something I think I can easily avoid if the Fortran interface exposed more of what is there in the C++ interface.

**Comment by WeiqunZhang** [comment]
Yes, this should be straightforward by using C++ MFIter constructors that take BoxArray and DistributionMapping.   Either you do it and then submit a pull request, or I am happy to do this next week.  Either way is fine with me.

**Comment by nncarlson** [comment]
Thanks for confirming my suspicion that this is straightforward.  I'll go ahead and submit a PR.
