### ISSUE TITLE
Cannot build with CUDA and build_type=Debug

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#1829]
I build AMReX (via Spack) with the options `amrex +cuda cuda_arch=75 ~fortran +openmp +particles +shared build_type=Debug`. (This took a very long time – there is one file that takes more than one hour to compile for each CUDA architecture.) The resulting library leads to the error message
```
ptxas fatal   : Unresolved extern function '_ZN5amrex12Abort_deviceEPKc'
/home/eschnetter/src/CarpetX/Cactus/configs/sim-gpu-debug/config-data/make.config.rules:315: recipe for target 'linsolve.cxx.o' failed
```
when building the Einstein Toolkit. The same build works fine when I don't specify a cmake build type.

-erik

**Comment by eschnett** [comment]
This is with AMReX 21.02.

**Comment by WeiqunZhang** [comment]
What's in `AMReX_Config.H` and `AMReX.H`?  What's the command line used to compile linsolve.cxx?

**Comment by eschnett** [comment]
Below are pointers to the files and the compiler flags:

[`AMReX_Config.H`](https://gist.github.com/eschnett/99d6c32dfcbf926df8ceb58bdcb33a7d)
[`AMReX.H`](https://gist.github.com/eschnett/5c4a4918865be5fceaba9be16f51131f)
[command line](https://gist.github.com/eschnett/b4908450977765182ebff7438b59d90e)

**Comment by WeiqunZhang** [comment]
Maybe you need to add `-dc` to your build system to turn on relocatable device code (rdc) support.

**Comment by eschnett** [comment]
The `-dc` option resolved the problem. I now encounter a different, unrelated error. I don't know whether this is caused by my code or AMReX.

```
Call parameter type does not match function signature!
  %tmp = load double, double* %x.addr, align 8, !dbg !587                        float  %1 = call i32 @__isnanf(double %tmp), !dbg !587
<unnamed>: parse Invalid record (Producer: 'LLVM7.0.1' Reader: 'LLVM 7.0.1')    /home/eschnetter/src/CarpetX/Cactus/configs/sim-gpu-debug/config-data/make.config.rules:315: recipe for target 'io.cxx.o' failed
```

**Comment by WeiqunZhang** [comment]
This seems to be a bug in the llvm 7 based nvcc.  Maybe you can try to narrow down on what triggers it.  @maxpkatz

**Comment by maximumcats** [comment]
Looks like it's related to calling isnan in device code, hopefully that will be easy to figure out where it's coming from

**Comment by eschnett** [comment]
It seems that was caused by compiling multiple files in the same directory. Apparently nvcc needs `--objdir-as-tempdir` for that.
