### ISSUE TITLE
Private Variable in ParallelFor Loop

### ISSUE THREAD

**Issue by irene-garnelo** [AMReX-Codes/amrex#1898]
Dear AMReX Team,

I have a ParallelFor loop in my Code with the goal of filling up an Array4. In the ParallelFor-loop I instantiate a class. I instantiate it inside of the loop, because I need to write to it inside the loop for each set of indices. I then use this class to get the value for this set of indices of the Array4. 

I was wondering, if there is a way to do this, by instantiating the class before the loop and declaring it as private, as would be done in OpenMP with the pragma "#pragma omp parallel private(p)"?

Thank you for your help!

**Comment by WeiqunZhang** [comment]
No, there is no way to declare something `private`, but I think what are you doing is basically equivalent to it. And declaring a local variable inside the loop seems to me a better approach in most cases, even for OpenMP.  Do you have a concrete example so that we can understand more what you are trying to do and what advantage `private` can offer?

**Comment by irene-garnelo** [comment]
Thanks for your quick reply!

So I want to set the values of a MultiFab according to an analytical function given by a string. I do this using the tinyexpr parser (https://github.com/codeplea/tinyexpr). This looks as follows:  

`for ( amrex::MFIter mfi(*MultiF); mfi.isValid(); ++mfi ){

            const amrex::Box& bx = mfi.tilebox();
            amrex::Array4<amrex::Real> const& proj_arr = (*MultiF)[mfi].array();

            ParallelFor(bx, [=] AMREX_GPU_DEVICE (int i, int j, int k)
            {
                // initializing the parser and variables necessary for it
                double x_eval, y_eval, z_eval;
                int err;
                te_variable read_vars[3] = {{"x", &x_eval}, {"y", &y_eval}, {"z", &z_eval}};
                te_expr *function_parse = te_compile(function_string.c_str(), read_vars, varcount, &err);

                // setting the values at which we evaluate the parsed function
                x_eval = geom.ProbLo()[0] + i*dx[0];
                y_eval = geom.ProbLo()[1] + j*dx[1];
                z_eval = geom.ProbLo()[2] + k*dx[2];

                // evaluate parsed function and write into Array4
                proj_arr(i,j,k) = (te_eval(function_parse));

                // freeing parser
                te_free(function_parse);
            });
        }`

The reason I was asking, is because before, instead of a ParallelFor-loop, I was using three nested loops to go over a tile, like this:  

`amrex::IntVect lo = {bx.smallEnd()};
amrex::IntVect hi = {bx.bigEnd()};

for(int k=lo[2]; k<=hi[2]; k++){
  for(int j=lo[1]; k<=hi[1]; k++){
    for(int i=lo[0]; k<=hi[0]; k++){
      ...
    }
  }
}`

For this I could initialize the parser outside of the loop, so it was only done once per MPI-process (but I realize this will not work for GPU-Parallelisation, which I am trying). When changing to the ParallelFor version this loop slowed down significantly because of this.

I think it's a good point you make that the declaration of private would probably do behind the scenes the same thing I am doing. I am not very experienced with parallel paradigms, thank you for your help!

**Comment by WeiqunZhang** [comment]
It does not appear that tinyexpr works on GPUs.  So maybe you can do this on CPU.  If the code is compiled for GPU, you can create a temporary MultiFab in host memory first.  After the values are initialized, copy them to GPU memory.  For example,
```
MultiFab mf_gpu(....);
MultiFab mf_cpu(mf_gpu.boxArray(), mf_gpu.DistributionMap(), mf_gpu.nComp(),
                mf_gpu.nGrowVect(), MFInfo{}.SetArena(The_Pinned_Arena()));
// initialize valies in mf_cpu                                                                                                                                                                             
amrex::htod_memcpy(mf_gpu, mf_cpu);
```

Alternatively, you can use a parser that works on GPUs.  For example, https://github.com/ECP-WarpX/WarpX/tree/development/Source/Parser, which I wrote for the WarpX project.  The parser in WarpX is unfortunately not in a standalone package.  But it should not be too hard to strip it out of WarpX.  I think @RevathiJambunathan has done that in another project.

**Comment by irene-garnelo** [comment]
Thank you very much for your help, both solutions sound good to me. Thanks for your fast and detailed help!
