### ISSUE TITLE
cmake-gui error

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#190]
I want to compile it with cmake-gui. but it gives me the following error. Could you please give me some advices.
Regards

CMake Error at Tools/CMake/AMReX_Utils.cmake:182 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  Tools/CMake/AMReX_Config.cmake:19 (find_git_version)
  CMakeLists.txt:42 (include)

**Comment by mic84** [comment]
Hi,
what are the commands you are using to configure the build? Also, do you have git installed on your workstation?

**Comment by ztdepztdep** [comment]
I have instgalled git. I configured it with cmake-gui. I reconfigured it. It still gave me the following error.

 fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

CMake Error at Tools/CMake/AMReX_Utils.cmake:182 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  Tools/CMake/AMReX_Config.cmake:19 (find_git_version)
  CMakeLists.txt:42 (include)

**Comment by ztdepztdep** [comment]
I solved the problem. 
The package should be downloaded with git clone  not by unzip the zip file. 
not it is working
thank you

**Comment by mic84** [comment]
The issue you were having is a bug indeed. The fix is already in the development branch. Could you please try it out by building amrex from the unzipped sources, and let us know?

**Comment by ztdepztdep** [comment]
dear mic84:
    I just tried the zipped amrex. it works smoothly with cmake-gui.
regards
