### ISSUE TITLE
amrex crashes when built with latest version of intel oneapi

### ISSUE THREAD

**Issue by lucaparisi91** [AMReX-Codes/amrex#1937]
Current version of Amrex crashes with Segfault when initialized. 
Amrex library was built with cmake command from build directory 

export CC=icc
export CXX=icpc
export CF=ifort
cmake ../amrex  -DAMReX_OMP=YES -DAMReX_BASE_PROFILE=YES 

Compilation is successfull but crashes when doing

make test_install

cmake version : 3.20.0
intel oneApi version : 2021.2.0

**Comment by WeiqunZhang** [comment]
I can reproduce it with cmake.  It's also reproducible with
```
cd  amrex/Tests/Amr/Advection_AmrCore/Exec
make -j16 COMP=intel USE_MPI=FALSE
./main2d.intel.ex inputs
```

This seems to be a compiler bug, and I think I have found a workaround.  #1938

**Comment by WeiqunZhang** [comment]
Could you verify the issue is gone with the latest amrex?

**Comment by lucaparisi91** [comment]
I confirm that amrex is now building properly. Thanks for the fix.
