### ISSUE TITLE
Implement a mid-timestep plot capability

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#196]
Normally we only create plotfiles at coarse timestep intervals, but when we are subcycling, there may be many fine timesteps in between coarse timesteps. It would be useful to be able to generate plotfiles at the end of a fine timestep. In order for this to be consistent, it would require a time interpolation on the coarser levels.

**Comment by drummerdoc** [comment]
One potential issue is that the multilevel state will be mid-sync, or completely unsync'd.  This feature may cause more problems than it solves.  It may be that if data is wanted more frequently, you either need a finer coarse grid or a smaller time step?

**Comment by maxpkatz** [comment]
Yes, the state will not be fully synchronized. Indeed, this functionality can only reveal what the effective state of the simulation is at that time, but that may still be valuable to look at to understand what the fine levels are seeing as they advance. I don't see why it creates problems to have, so long as one understands what one is looking at in the plot.

**Comment by drummerdoc** [comment]
I'm an old guy, and have a concept of what's in a "plotfile" that your suggestion would violate.  To me, you're talking about a more generic diagnostic utility -- a snapshot of temporary data across multiple levels.  You can easily accomplish what you want with a couple of VisMF::Write statements, and if you have specific groups of such data that you find useful, you can make a function for it in your app.  Although you're talking about adding an option people don't need to use, it's my humble opinion that it would invite trouble down the road.  There's models for your hack already laying around in the AMReX C_utils folder called WritePlotFile which takes arrays of MultiFabs and fakes up a plotfile.  I'm not thrilled about overloading that label, but at least the intention is clear enough.  I'd vote for that route.

**Comment by maxpkatz** [comment]
OK, I'll implement this in Castro.
