### ISSUE TITLE
GNUmake dependency issues

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#1978]
Hello, is there anything we need to do with GNUmake in our projects to accommodate #1975 and #1967 ? We are getting:
```
make: *** No rule to make target `AMReX_Config.H', needed by `tmp_build_dir/o/3d.llvm.EXE/prob.o'.  Stop.
```

**Comment by drummerdoc** [comment]
See if upgrading your GNU make has an impact.  If so, there's a fix to make the GNUmake stuff in AMReX backward compatible, but I see conflicting results so did not make a PR

**Comment by WeiqunZhang** [comment]
It might be the case we need to spell out the full path of AMReX_Config.H as a target.

**Comment by WeiqunZhang** [comment]
@jrood-nrel Are you using Mac?

**Comment by jrood-nrel** [comment]
Yes, Catalina, but I have heard from another person on our project it's happening for them on Linux as well.

**Comment by WeiqunZhang** [comment]
Could you give this a try?   #1979

**Comment by jrood-nrel** [comment]
#1979 succeeds for me.
