### ISSUE TITLE
Physical Boundary Conditions - Fortran

### ISSUE THREAD

**Issue by pbrady** [AMReX-Codes/amrex#2]
I cannot find any example fortran code that uses the amrex_physbc fortran interface to supply boundary conditions.  The current examples in Tuturials/*_CF use periodic bcs.  I did notice that in some of the _C tutorials, an f77 file was present which provided a `filcc` routine.  To impose boundary conditions, should I customize the filcc routines or is there a better way utilizing amrex_physbc?

**Comment by drummerdoc** [comment]
`filcc` is an app-generic routine to handle reflections, extrapolations, etc, i.e., grow cells that don't require user intervention to fill.  Typically, one calls `filcc` first to fill grow cells on such boundaries, and then follows in the bc routine with loops over each face of the box to be filled, checking for Dirichlet conditions that weren't handled by filcc (i.e., bc(dir,lohi,comp) == EXT_DIR, where dir=1,2,3 and lohi=1,2) and if the box to be filled sticks out past the boundary on that face.  If such cases are found, the user-supplied code will need to set the Dirichlet values explicitly.  Note that the values set in these grow cells will be enforced on the boundary FACE.  We should add such an example to the tutorials.

**Comment by WeiqunZhang** [comment]
I will update `amrex/Tutorials/AMR_Adv_CF/Source/fillpatch_mod.F90`'s `subroutine fill_physbc` to show an example of setting physical boundary conditions.

**Comment by zingale** [comment]
here's an example from Castro:

https://github.com/BoxLib-Codes/Castro/blob/development/Exec/hydro_tests/double_bubble/bc_fill_2d.F90

**Comment by pbrady** [comment]
Thanks for the example.  What's the use case of the amrex_physbc_* routines in `AMRex_physbc_mod.F90`?

**Comment by WeiqunZhang** [comment]
The Castro example was built with C++.  As I understand, you are trying to use the Fortran interfaces `Src/F_Interfaces`.

**Comment by WeiqunZhang** [comment]
Please check out the latest development branch.  `Tutorials/AMR_Adv_CF/Exec/SingleVortex` has been modified to use a simple extrapolation for physical boundaries (https://github.com/AMReX-Codes/amrex/tree/development/Tutorials/AMR_Adv_CF).  In `inputs.physbc`, we have `geometry.is_periodic =  0    0    0` to set the boundaries to non-periodic.  In https://github.com/AMReX-Codes/amrex/blob/development/Tutorials/AMR_Adv_CF/Source/my_amr_mod.F90#L74, we set the non-periodic bc to first-order extrapolation.  The fillpatch module (https://github.com/AMReX-Codes/amrex/blob/development/Tutorials/AMR_Adv_CF/Source/fillpatch_mod.F90#L62) is modified accordingly.  

If there are any problems, let us know.

**Comment by pbrady** [comment]
Thanks for the updated example.  It's very helpful.

So, if my problem specific boundary conditions are not handled by `amrex_fillcc` I would modify the `fill_physbc` subroutine to appropriately account for this (i.e. time dependent dirichlet bc).  In that case, I wouldn't need to change to the `fillpatch/fillcoarsepatch` wrappers in the AMR_Adv_CF example, just the `fill_physbc` subroutine which is passed to the `amrex_fillpatch` routines.

However, If my boundaries warranted a unique discretization stencil, then I would have to take this explicitly into account in whatever problem specific "advance" routine I write.  And based on @drummerdoc's comments, a custom discretization may be required depending on if the boundary conditions are interpreted as face of cell data.  

Does this sound right?

**Comment by WeiqunZhang** [comment]
First, I forgot to commit a new file.  So you need to pull the latest version.

What Marc (@drummerdoc) said about face is true in some cases where filcc is used.  It is however not always true.  For example, in the hyperbolic solver of Castro, the ghost cells values are always treated as cell centered, not on faces.  So it depends on how the application code views it.

**Comment by pbrady** [comment]
I pulled the latest version and everything seems clear.  This issue can be closed unless you think it would be better left open for a while as guide

**Comment by ruihai0925** [comment]
Hello all,

I am now struggling with the physical boundary condition in the code.

It seems the above links provided by @WeiqunZhang about setting physical boundary conditions are useless, I just wonder if I can find these examples in the latest amrex-master?

Thanks so much!

Ruohai

**Comment by WeiqunZhang** [comment]
The tutorial mentioned above has been moved to https://github.com/AMReX-Codes/amrex/tree/master/Tutorials/Amr/Advection_F/
