### ISSUE TITLE
Questions about using the cell centered composite solver for all amr levels 

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#204]
Hello all,

I want to use the cell center composite solver to solve the Poisson equation among all amr levels, which kinds of solvers under the directory /linear solvers in the amrex package?

I knew that IAMR used the node center composite solver to solve the Poisson equation among all amr levels at the initialization process (see: https://github.com/AMReX-Codes/IAMR/blob/29f74453b9ef0bb4c69db43354887a840cbc6fa4/Source/Projection.cpp#L1048). I also noticed that there is a new released MLMG solver. In the release notes, it says this solver is used to solve for mac projection, mac sync solves, and scalar diffusion, yet all these three steps are level solvers according to the paper. But from the name "MLMG", I guessed it refers to the "Multi Level Multi Grid" solver, so I am confused whether I can use this solver.

Thanks so much.

Best.

Ruohai

**Comment by ajnonaka** [comment]
Please use the new MLMG solver.  There is a new tutorial at amrex/Tutorials/LinearSolvers/ABecLaplacian_C that shows how to do a multilevel composite solve for a cell-centered field.  I started a chapter in the documentation on linear solvers that shows how to do the implicit heat equation using the new interface (it's only single level, but in conjunction with the ABecLaplacian_C tutorial I think it has what you need).

**Comment by WeiqunZhang** [comment]
MLMG solves `(alpha * a - beta * (del dot b grad)) phi = rhs`, where `alpha` and `beta` are scalars, and `a`, `b`, `phi` and `rhs` are MultiFabs.   For cell-centered `phi`, `rhs` and `a` are also cell-centered.  But `b` is face-centered and there are 3 of them.  For cell-centered solve, the generic linear operator class that is needed to construct a `MLMG` object is `MLABecLaplacian`.   However, if you are solving just `del dot grad phi = rhs`, you can use `MLPoisson`.

The tricky part of setting up the solver is probably the boundary conditions.   There are some comments in `AMReX_MLLinOp.H` that might be of help.

**Comment by WeiqunZhang** [comment]
After the solver finishes, if you want `grad phi`, you should ask `MLMG` to do it instead of computing your own because of how boundaries are treated.

**Comment by ruihai0925** [comment]
@ajnonaka @WeiqunZhang Thanks so much. I have solved the equation on composite levels correctly. 

After this I want to make the velocity divergence free on composite levels. Now the question is that I want to calculate the grad phi (**also a cell center not a edge center variable** ) on composite levels, does amrex provide this kind of operation?

Thanks.

**Comment by ruihai0925** [comment]
I noticed that MLCellLinOp::compGrad is used to calculate the grad solution on edge centered, maybe I can re-write these codes. I just wonder if there are other ways to facilitate this process.

**Comment by ajnonaka** [comment]
Is your velocity face-centered?  If you don't have the IAMR code in the AMReX-Codes repo, clone that and look at the end of mlmg_mac_level_solve() in MLMG_Mac.cpp.  The "getFluxes" function returns "-bcoeff * grad(phi)".  In a typical projection method you update your velocity field by setting Unew = Uold - bcoeff * grad(phi)

**Comment by ruihai0925** [comment]
@ajnonaka Our velocity is cell centered and the grid is collocated. It seems that Unew = Uold - bcoeff * grad(phi) is for face-centered velocity.

**Comment by ajnonaka** [comment]
We support a "nodal" approximate projection for cell-centered co-located velocity, where the solution 'phi' lives on nodes.  The divergence maps cell-centered velocities to nodes, and the gradient maps nodal phi back to cell-centered.  The interface still needs to be cleaned up but it works.  If you want to see an example you can clone my astro code MAESTRO_C at https://github.com/AMReX-Astro/MAESTRO_C.git and look at MaestroNodalProj.cpp for how to set it up.  You could also look at Projection.cpp in the IAMR code.  We don't have a simple tutorial for this yet since this code is very new.

**Comment by ruihai0925** [comment]
@ajnonaka Thanks for your previous suggestions. I am now considering using the "getFluxes" function in MLMG class and then average the fluxes from the face center to the cell-center. But after I compiled my codes fraction successfully, there is an running error.

Here are the codes fraction I added. In fact, I defined a vector: a_flux, whose elements are array of mf pointers. Then I tried to initialize a_flux. The following codes has no problem in compiling stage. But in the run time stage, it has a segfault error. When debugging, it shows that error  is about the mf.define function,, but I am really confused why this happens. 

```
// Use vel to calu composite div_vel as the new rhs
// 1st, getFluxes
//
Vector< std::array<MultiFab*,AMREX_SPACEDIM> > a_flux(nlevel);
// Initialize its ba and dm
       for (int ilev = 0; ilev < nlevel; ++ilev)
        {
            for (int idim = 0; idim < AMREX_SPACEDIM; ++idim)
            {

             **(*a_flux[ilev][idim]).define(mg_grids[ilev], mg_dmap[ilev], 1, `0);**`
             (*a_flux[ilev][idim]).setVal(0.0);

            }
        }
//
mlmg.getFluxes(a_flux);
```

Thanks for providing me some information.

Ruohai

**Comment by ajnonaka** [comment]
Ruohai,

The main issue I see in your code is that each level of a_flux needs to be nodal in each direction.  Take a look at this code I am writing right now ( https://github.com/AMReX-Astro/MAESTRO_C ) and look at Source/MaestroMacProj.cpp lines 134-145.  This is a solve for cell-centered phi (solves div sig grad phi = RHS) and the getFluxes command returns "sig * grad phi".  You can basically do the same thing in your code.

`    // storage for "-B grad_phi"
    Vector< std::array<MultiFab,AMREX_SPACEDIM> > mac_fluxes(finest_level+1);
    for (int lev = 0; lev <= finest_level; ++lev) {
	AMREX_D_TERM(mac_fluxes[lev][0].define(convert(grids[lev],nodal_flag_x), dmap[lev], 1, 0);,
		     mac_fluxes[lev][1].define(convert(grids[lev],nodal_flag_y), dmap[lev], 1, 0);,
		     mac_fluxes[lev][2].define(convert(grids[lev],nodal_flag_z), dmap[lev], 1, 0););
    }

    for (int lev = 0; lev <= finest_level; ++lev) {
	// fluxes computed are "-B grad phi"
	mac_mlmg.getFluxes({amrex::GetArrOfPtrs(mac_fluxes[lev])});
    }`
