### ISSUE TITLE
Example problems?

### ISSUE THREAD

**Issue by lstewart** [AMReX-Codes/amrex#206]
Is there a collection of problems somewhere that might run for a few minutes on 20 cores or so?  I'm trying to use performance counters to sample memory activity.

**Comment by ajnonaka** [comment]
You could try amrex/Tutorials/Amr/Advection_AmrLevel/Exec/SingleVortex using the inputs file "inputs", but change amr.n_cell = 128 128 128, amr.blocking_factor = 16, and amr.max_grid_size = 32

This is advection only, with 3 levels of AMR, so it's not particularly heavy on computation compared to problems with linear solves.
