### ISSUE TITLE
CMake: Fortran+MPI Warning

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/amrex#2071]
It looks like we are still adding `BL_USE_MPI` to the compiler defines in CMake, but I think we should just rely on the one set in `AMReX_Config.H`:
 
```
... Src/Boundary/AMReX_lo_bctypes_mod.F90 ...
AMReX_Config.H:17:0:

   17 | #define BL_USE_MPI
      | 
Warning: "BL_USE_MPI" redefined
<command-line>:5:0:

note: this is the location of the previous definition
```

cc @kngott

**Comment by ax3l** [comment]
@WeiqunZhang am I correct in the assumption above?
In that case, this block that adds the `-D` needs to go :)
https://github.com/AMReX-Codes/amrex/blob/55ad11dae86fca6737e6e7b8c1656100e5a3bead/Tools/CMake/AMReXSetDefines.cmake#L84-L88

**Comment by ax3l** [comment]
I do see this block in `Tools/GNUMake/Make.defs` though:
```
Tools/GNUMake/Make.defs
614:    CPPFLAGS += -DBL_USE_MPI -DAMREX_USE_MPI
632:    CPPFLAGS  += -DBL_USE_MPI3 -DAMREX_USE_MPI3
```

If we want `-DBL_USE_MPI` to be set, then we need to remove the define in
https://github.com/AMReX-Codes/amrex/blob/55ad11dae86fca6737e6e7b8c1656100e5a3bead/Tools/CMake/AMReX_Config.H.in#L17

But this one is also used for C/C++ code, so probably the first solution is more in the direction we want (forcing Fortran users to include `AMReX_Config.H` if they need `BL_USE_MPI` preprocessor defines in Fortran source files.

**Comment by WeiqunZhang** [comment]
Don't do anything yet.  I will explain the reason later and what I think we should do.

**Comment by WeiqunZhang** [comment]
We need those definitions passed to the Fortran compiler because they are used.  The warning comes from AMReX_lo_bctypes_mod.F90, which also includes AMReX_LO_BCTYPES.H, which in turn is used by both C++ and Fortran files and includes AMReX_Config.H.  I will fix this.
