### ISSUE TITLE
Forward declarations for AMReX

### ISSUE THREAD

**Issue by lucafedeli88** [AMReX-Codes/amrex#2098]
Hi everyone!

We have recently started using `iwyu` (https://include-what-you-use.org/)  on https://github.com/ECP-WarpX/WarpX and we think that WarpX could greatly benefit from few forward declarations of AMReX classes. 

We've been discussing this option with @WeiqunZhang , who has proposed to add some forward declarations in a `AMReX_Base_fwd.H`  file (similarly to what is done for `iosfwd` in the standard library).

In case you finally decide to add this forward declaration file, as far as WarpX is of concern it would be great to have forward declarations of the following classes (in decreasing order of priority):

#### Top priority:
	namespace amrex { class MultiFab; }

#### High priority:
	namespace amrex { class DistributionMapping; }
	namespace amrex { class Box; }
	
#### Medium priority:
	namespace amrex { class IntVect; }
	namespace amrex { class AmrCore; }
	namespace amrex { class FArrayBox; }
	namespace amrex { struct RandomEngine; }
	
#### Low priority:
	namespace amrex { class BoxArray; }
	namespace amrex { class Geometry; }
	namespace amrex { class iMultiFab; }
	namespace amrex { class RealBox; }
	namespace amrex { class ParmParse; }
	
#### Very Low priority:
	namespace amrex { class IArrayBox; }
	namespace amrex { class TagBoxArray; }
	namespace amrex { class MFIter; }
	namespace amrex { template <typename T> struct Array4; }
	namespace amrex { template <typename FAB> class FabFactory; }
	namespace amrex { template <typename T> class LayoutData; }
	namespace amrex { class RealBox; }
	namespace amrex { class AMReX; }
	namespace amrex { namespace Gpu { class Elixir; } }
	namespace amrex { struct MFItInfo; }
	namespace amrex { template <class T, std::size_t N> struct GpuArray; }

**Comment by WeiqunZhang** [comment]
Could you give #2100 a try?  `AmrCore` and `TagBoxArray` are in `AMReX_AmrCoreFwd.H`, and the others are in `AMReX_BaseFwd.H`.
