### ISSUE TITLE
Spack-installed AMReX 21.06 has wrong version number

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#2099]
I installed AMReX 21.06 via Spack. It  thinks of itself that it is
```
#define AMREX_GIT_VERSION "21.05.0"
```
(from `AMReX_Config.H`).

**Comment by WeiqunZhang** [comment]
I made a mistaking in AMReX 21.06 release.  The tar.gz file uploaded to https://github.com/AMReX-Codes/amrex/releases/tag/21.06 missed the last commit of the 21.06 release that updated the CHANGES file.  AMReX's build system checks that file for version information if `.git/` directory is not present.  Note that the version you installed is indeed 21.06's source and the only thing it gets wrong is the version number.  If this is important for you, we could make a 21.06.1 release.

**Comment by eschnett** [comment]
No, I'm not worried about the version number itself. Thanks for clarifying!

**Comment by WeiqunZhang** [comment]
Thanks for reporting this!
