### ISSUE TITLE
Use of std::size_t in AMReX_BaseFwd.H can be problematic

### ISSUE THREAD

**Issue by lucafedeli88** [AMReX-Codes/amrex#2107]
Hi everyone,

I am currently working on a WarpX PR  which uses heavily  the new forward declaration headers available in AMReX (thanks @WeiqunZhang !). I've just observed this error:
```
In file included from /home/lfedeli/projects/warpx/WarpX/Source/Utils/RelativeCellPosition.cpp:7:
In file included from /home/lfedeli/projects/warpx/WarpX/Source/Utils/RelativeCellPosition.H:10:
/home/lfedeli/projects/warpx/amrex/Src/Base/AMReX_BaseFwd.H:17:20: error: use of undeclared identifier 'std'
template <class T, std::size_t N> struct GpuArray;
                   ^
```
I was wondering if having such a declaration in the forward headers requires to always include one of the STL headers containing the definition of `std::size_t` ...

**Comment by WeiqunZhang** [comment]
I think that's case.  However, we could also simply use `unsigned int` here.  It's for fixed size array on the stack.  So the size is small.
