### ISSUE TITLE
FillPatch not filling up corner cells for periodic boundary conditions (GPU/CNS tutorial)

### ISSUE THREAD

**Issue by ashwathsv** [AMReX-Codes/amrex#2111]
I was testing out the GPU/CNS tutorial changing the number of ghost cells (NUM_GROW) and running the executable using pure MPI. The code works as expected for upto 2 ghost cells but gives out NaN's when FillPatch is used on the Sborder MultiFab in the CNS::advance() function when NUM_GROW > 2. 

Attaching the relevant lines from CNS_advance.cpp below:

//--------------------------------------------------------------------------------------------------------------
```
    if (fr_as_crse) {
        fr_as_crse->setVal(Real(0.0));
    }

    // RK2 stage 1
    FillPatch(*this, Sborder, NUM_GROW, time, State_Type, 0, NUM_STATE);

    Print() << "after FillPatch, Snew NaN= " << S_new.contains_nan() << "Sold NaN " << S_old.contains_nan()  
            << "SBorder NaN= " << Sborder.contains_nan(URHO,NUM_STATE,NUM_GROW) << "\n";

// The above Print() statement gives Sborder.contains_nan() == 1 when NUM_GROW > 2 but gives no NaN when NUM_GROW <= 2

    compute_dSdt(Sborder, dSdt, Real(0.5)*dt, fr_as_crse, fr_as_fine);
```
//--------------------------------------------------------------------------------------------------------------
 
Hence, FillPatch does not seem to be working on domain edge cells ( eg. (-4,-4,-4) to (-3,-3,-3) and similarly for the upper edge of the domain).

Has this got something to do with the specific tutorial or is it the expected behaviour for FillPatch? I am trying to use this tutorial template to replace the Riemann solver with another hydro solver that requires data from four ghost cells. Any help on how to overcome this issue would be much appreaciated. Thanks in advance!

**Comment by WeiqunZhang** [comment]
This is supposed to work.  Could you give more details on how we could reproduce this?  What version of amrex? How you compile it?  What inputs file do you use?  The modification you made shown by `git diff`?

**Comment by ashwathsv** [comment]
Thanks for your reply! It looks like a mistake with the input file from my end. I set NUM_GROW=4 but had only a 32 x 32 x 2 cell domain. The issue has been resolved now.
