### ISSUE TITLE
Unable to get the version number in the output of HelloWorld_C Program

### ISSUE THREAD

**Issue by rsiddu0511** [AMReX-Codes/amrex#2124]
After I type make and created an executable, I ran the program as follows

`./main3d.gnu.DEBUG.ex`

I got the output as

`AMReX () initialized`
`Hello world from AMReX version` 
`AMReX () finalized`

I fail to understand why I am not able see the version of AMReX inside the given brackets. The same applies when I tried with parallelizing with OpenMP.

**Comment by WeiqunZhang** [comment]
We use `git describe --abbrev=12 --dirty --always --tags` to obtain the version.  What do you see if you run the command in your amrex directory?

**Comment by rsiddu0511** [comment]
I get the following:

`fatal: not a git repository (or any of the parent directories): .git`

**Comment by WeiqunZhang** [comment]
That explains it.  That means your copy of amrex is not in a git repo.

**Comment by maximumcats** [comment]
It doesn't look to me like there's any way to obtain version information when the code is downloaded as a ZIP file (I don't see any information injected in the file which clues us in to this). So maybe if git is unavailable we should not print the "()" to avoid confusion.

**Comment by WeiqunZhang** [comment]
We could add something to the makefile to extract the information from the `CHANGES` file like we do in cmake.

**Comment by rsiddu0511** [comment]
Alright @WeiqunZhang Thank you. Finally, will I be losing any of the functionalities of AMReX if I run the codes as a zip file?

**Comment by WeiqunZhang** [comment]
There should not be any difference in functionality.
