### ISSUE TITLE
Missing MPI directive? 

### ISSUE THREAD

**Issue by etpalmer63** [AMReX-Codes/amrex#2127]
I get the following error when I try to build FHDeX/multispec with the command `make -j4 USE_MPI=FALSE`.

```
.../AMReX/amrex/Src/Extern/SWFFT/distribution_c.h:58:10: fatal error: mpi.h: No such file or directory
   58 | #include <mpi.h>
```

It looks like there is no directive to check if MPI is enabled.

**Comment by WeiqunZhang** [comment]
I assume SWFFT is not meant to be used without MPI.
