### ISSUE TITLE
Replace NO_CUDA_8 macro with CUDA_UM_LITE

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#213]
There are a few places where we use the macro NO_CUDA_8 macro, but what we really mean by this is that we only want the "UM-lite" features, i.e. cudaMallocManaged() but without the additional functionality introduced in CUDA 8 (cudaMemPrefetchAsync(), cudaMemAdvise()). This will make it clearer what the macro means, and also address the fact that there's now CUDA 9. This will make it easier to disable the UM features at compile time. We should also have an inputs parameter that disables the non-UM-lite functionality.

**Comment by zingale** [comment]
runtime parameter should be in the `device` namespace.

**Comment by maxpkatz** [comment]
This is now unnecessary since CUDA toolkit versions older than 8.0 are no longer supported.

For pre-Pascal GPUs, the CUDA runtime API has a way to test if the GPU supports the fuller UM features, and we now have this check enabled.
