### ISSUE TITLE
Crash In Conduit

### ISSUE THREAD

**Issue by nicholasbl** [AMReX-Codes/amrex#2133]
Hi,

I'm attempting to add Ascent support to https://github.com/Exawind/amr-wind , and I've encountered a crash in the `MultiLevelToBlueprint` Conduit code, and I'm a little confused. 

Looking at `AMReX_Conduit_Blueprint.cpp` with the for loop that starts here: 

https://github.com/AMReX-Codes/amrex/blob/14dde9aaf741f84cf85adb67a7cdc5bef4c0764a/Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp#L363-L376

We have box_offsets starting out as zero-sized. In the first loop `i` is `0`, so box_offsets gets a `0` pushed back, so its size is 1. 

The next run through the loop hits this line

https://github.com/AMReX-Codes/amrex/blob/14dde9aaf741f84cf85adb67a7cdc5bef4c0764a/Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp#L374

Which causes the crash as box_offsets is size 1, and `i == 1`, which doesn't exist. As my code passes the asserts at the top of the function, I don't think I'm violating any contract, but it seems to me like this would always crash. 

I was able to fix it in my current patch by adding `box_offsets.resize(n_levels);` before the loop and changing the push back to `box_offsets[i] = 0;`, but I can't be sure I'm reading the code correctly. Any help would be appreciated. 

Thanks,
Nicholas

**Comment by WeiqunZhang** [comment]
I agree with @nicholasbl's fix.

@cyrush
