### ISSUE TITLE
Nestsets Conduit Crash

### ISSUE THREAD

**Issue by nicholasbl** [AMReX-Codes/amrex#2135]
Hello, 

While using the `MultiLevelToBlueprint` function, I have encountered another issue. The code has a function to build nest sets:

https://github.com/AMReX-Codes/amrex/blob/14dde9aaf741f84cf85adb67a7cdc5bef4c0764a/Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp#L80-L123

The crash happens at these lines:

https://github.com/AMReX-Codes/amrex/blob/14dde9aaf741f84cf85adb67a7cdc5bef4c0764a/Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp#L116-L120

Specifically, `level + 1` is out of bounds for the `ref_ratios` list that I am passing in. In this case, I have a `n_levels == 3` and `ref_ratios.size() == 2`. Now, based on the assert here 
https://github.com/AMReX-Codes/amrex/blob/14dde9aaf741f84cf85adb67a7cdc5bef4c0764a/Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp#L354
this appears to be a legal configuration. However, when we get to lines 116-120 with `level == 1`, this will be out of bounds for my `ref_ratios` list. 

My current fix, which successfully runs and has correct output is to change the if at line 80 from 
https://github.com/AMReX-Codes/amrex/blob/14dde9aaf741f84cf85adb67a7cdc5bef4c0764a/Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp#L80
to 
`if((level < n_levels - 1) && (level < ref_ratio.size() - 1))`.

But with my limited understanding of the codebase, this is just me grasping in the dark. What do you folks think?

I apologize in advance if I have done something very stupid.

**Comment by WeiqunZhang** [comment]
I think the fix should be `ref_ratio[level+1]` -> `ref_ratio[level]`.

Could you submit a PR to fix this and the other issue you found?

**Comment by nicholasbl** [comment]
Certainly! Submitted PR.
