### ISSUE TITLE
ICPC: Fallthrough Attribute

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/amrex#2172]
Saw this warning with Intel `icpc` (classic):
```
Src/Base/AMReX_ParmParse.cpp(659): warning #1292: unknown attribute "fallthrough"
              AMREX_FALLTHROUGH;
Src/Base/AMReX_ParmParse.cpp(703): warning #1292: unknown attribute "fallthrough"
              AMREX_FALLTHROUGH;
```

We probably need to define `AMREX_FALLTHROUGH` separately for the (classic) Intel compiler.

**Comment by ax3l** [comment]
Reminder to myself: let's add an `icc`/`icpc` test with this fix.
Location: https://github.com/AMReX-Codes/amrex/blob/development/.github/workflows/intel.yml
Blueprint in WarpX: https://github.com/ECP-WarpX/WarpX/blob/730e9f416363a6f31a19a06c8c0654aa79b928ce/.github/workflows/intel.yml#L8-L56

**Comment by WeiqunZhang** [comment]
The Intel icpc compiler has a bug in its feature test.  In c++14 mode, it warns about not knowing fallthrough, but `#if defined(__has_cpp_attribute) && __has_cpp_attribute(fallthrough) >= 201603L` is true.

**Comment by ax3l** [comment]
Oh no, not fair :D
