### ISSUE TITLE
Test fails in C_CellMG with error BaseFab<Real>::norm(): only p == 0 or p == 1 are supported !!!

### ISSUE THREAD

**Issue by drhansj** [AMReX-Codes/amrex#223]
in Tests/LinearSolvers/C_CellMG on master HEAD, building with DIM=2, MPI=FALSE or TRUE, DEBUG=FALSE or TRUE:
`cs-it-6967821:C_CellMG hans$ ./main2d.gnu.DEBUG.ex inputs.2d 
Reading in grids from file: grids/gr.2_19boxes
Norm = 2097152
Run time = 2.002690183
amrex::Error::0::BaseFab<Real>::norm(): only p == 0 or p == 1 are supported !!!
0::SIGABRT !!!`
Debugging led me to main.cpp routine "mfnorm_2_valid" line 40, where it asks for a p=2 from BaseFab<double>::norm (Src/Base/AMReX_BaseFab.cpp:299).

One easy fix is to just ask for a 1-norm instead :-). I have implemented that and the test completes - let me know if you want a pull request or a different fix.

**Comment by WeiqunZhang** [comment]
The test was written a while ago.  Now MultiFab class has norm2 methods.  So you could use that and remove the norm function in the test.

**Comment by asalmgren** [comment]
I have replaced the local definitions of the multifab 0-norm and 2-norm but versions that live in AMReX_MultiFab.cpp in Src/Base.

**Comment by drhansj** [comment]
Thanks for fixing this - is it ok to report issues this way?

**Comment by asalmgren** [comment]
Yes - definitely!!

This is why the more the merrier- only way to find all these things
