### ISSUE TITLE
CMake Error at while installing amr-wind: string sub-command STRIP requires two arguments.

### ISSUE THREAD

**Issue by maxshatsky** [AMReX-Codes/amrex#2240]
I posted such an issue at the amr-wind project, but then were told that the issue comes from  the original AMReX. That seems to be true.

I was following instruction from here:
https://exawind.github.io/amr-wind/user/build.html

Running command
$ cmake -DAMR_WIND_ENABLE_TESTS:BOOL=ON ../

has led to the following error:
CMake Error at submods/amrex/Tools/CMake/AMReXUtils.cmake:20 (string):
string sub-command STRIP requires two arguments.

Investigation of the mentioned file has shown the difference between strings containing STRIP command:

![image](https://user-images.githubusercontent.com/46995837/129211436-1acd936c-6f22-4fa0-a6ef-be6ab9a1ecee.png)

string( STRIP ${_tmp} _tmp ) at line 20
VS
string(STRIP "${_tmp}" _tmp ) at line 32

Solution:
I followed a tip described here:
https://stackoverflow.com/questions/26585513/cmake-error-with-string-sub-command-strip-requires-two-arguments

adding the same quotas to line 20 seemed to solve the problem.

Original amr-wind issue: https://github.com/Exawind/amr-wind/issues/472

**Comment by ax3l** [comment]
Hi @maxshatsky,

Thanks a lot for the report and suggestion!
Yes perfect, that's the right fix! Do you like to submit a PR for it? :)

**Comment by maxshatsky** [comment]
> Hi @maxshatsky,
> 
> Thanks a lot for the report and suggestion!
> Yes perfect, that's the right fix! Do you like to submit a PR for it? :)

It seems to be done, https://github.com/AMReX-Codes/amrex/pull/2244

**Comment by ax3l** [comment]
Thank you for your contribution, that's superb! :rocket: :sparkles:
