### ISSUE TITLE
NaN's in the ghost cells near the domain boundary of a newly created patch of refined mesh when using amrex::FillPatchTwoLevels

### ISSUE THREAD

**Issue by ComputationalMultiphaseFlowLab** [AMReX-Codes/amrex#2298]
Dear Developers and AMReX support team,

I am using the AMReX framework to develop an incompressible flow solver on staggered mesh[1]. I am currently using a staggered mesh, where, x-component of velocities are stored at the x-face and the y-component of the velocities are stored at the y-face of a cell-centered mesh. I have been having an issue while using amrex::FillPatchTwoLevels with face divergence-free interpolation(amrex::face_divfree_interp) and no-operation on boundaries(amrex::PhysBCFunctNoOp).Please refer to the c++ function FillPatch given below for details. I have noticed that few grid cells in the ghost layer near the domain boundary on a freshly created patch of a refined mesh turn into NaNs after using amrex::FillPatchTwoLevels to populate them. However, the ghost layers away from the domain boundary are populated accurately from the underlying coarse mesh using the function FillPatch given below.

I was wondering if I am making any obvious mistake in using amrex::FillPatchTwoLevels. I truly appreciate any help or suggestion regarding this issue.

Thanks a lot.

Sincerely,

Pratik Das

C++ function used for the patch filling:
void incFSI::FillPatch
(
    int lev,//Refienement level of the destination multifab(mf) 
    amrex::Real time,
    amrex::Array<amrex::MultiFab*, AMREX_SPACEDIM> const& mf,                  // destination mf, contains u and v for 2D
    const amrex::Vector<amrex::Array<amrex::MultiFab*, AMREX_SPACEDIM>>& cmf,  // coarse mf, contains u and v for 2D
    const amrex::Vector<amrex::Real>& ct,                                      // coarse time
    const amrex::Vector<amrex::Array<amrex::MultiFab*, AMREX_SPACEDIM>>& fmf,  // fine mf, contains u and v for 2D
    const amrex::Vector<amrex::Real>& ft,                                      // fine time
    int icomp, int ncomp
)
{
    //! No need to fill external boundary values
    amrex::Array<amrex::Vector<amrex::BCRec>,AMREX_SPACEDIM> bcs;
    for (int n = 0; n < AMREX_SPACEDIM; ++n)
    {
        bcs[n].resize(1);
        for (int idim = 0; idim < AMREX_SPACEDIM; ++idim)
        {
            bcs[n][0].setLo(idim, amrex::BCType::int_dir);
            bcs[n][0].setHi(idim, amrex::BCType::int_dir);
        }
    }

    if (lev == 0)
    {
        amrex::PhysBCFunctNoOp physbc;
        for (int dir = 0; dir < AMREX_SPACEDIM; dir++)
        {
            amrex::Vector<amrex::MultiFab *> fmf_tmp(fmf.size());
            for (size_t i = 0; i < fmf_tmp.size(); i++)
            {   
                fmf_tmp[i] = fmf[i][dir];
            }
            amrex::FillPatchSingleLevel(*mf[dir], time, fmf_tmp, ft, 0, icomp, ncomp,
                                        geom[lev], physbc, 0);
        }
    }
    else
    {
        amrex::Interpolater* mapper = &amrex::face_divfree_interp;
        amrex::Array<amrex::PhysBCFunctNoOp, AMREX_SPACEDIM> cphysbc_arr;
        amrex::Array<amrex::PhysBCFunctNoOp, AMREX_SPACEDIM> fphysbc_arr;

        amrex::FillPatchTwoLevels(mf, time, cmf, ct, fmf, ft,
                            0, icomp, ncomp, geom[lev-1], geom[lev],
                            cphysbc_arr, 0, fphysbc_arr, 0, refRatio(lev-1),
                            mapper, bcs, 0);

    }
}

Reference:
[1] Kim, John, and Parviz Moin. "Application of a fractional-step method to incompressible Navier-Stokes equations." Journal of computational physics 59.2 (1985): 308-323.

**Comment by WeiqunZhang** [comment]
The issue is the no-op phys bc will not work unless the fine grids do not touch the domain boundary.  This is because the interpolater's stencil will include ghost cells.  You can try the default `GpuBndryFuncFab` without user provided `f`.  Note that although the class has `Gpu` in its name, it works for CPU builds too.  For x-direction domain BC, I think you can set x-velocity BC type to `BCType::hoextrap` and y-velocity BC type to `BCType::foextrap`.  For y-direction domain, you do first-order extrapolation on x-velocity and second-order linear extrapolation on y-velocity.  This will make the ghost cells outside the domain divergence free too.  My guess is this is desirable.

**Comment by ComputationalMultiphaseFlowLab** [comment]
Dear Dr. Zhang,

Thanks a lot for your reply. I tried to use GpuBndryFuncFab without user-provided f(please refer to the code given below). However, I get the following runtime error message:
" amrex::Abort::2::GpuBndryFuncFab: mixed type not supported !!!"

I followed the demonstration given on "https://amrex-codes.github.io/amrex/docs_html/Basics.html#boundary-conditions". It would be kind of you to let me know how to use GpuBndryFuncFab on a staggered grid(face-centered velocity).

I truly appreciate your help.

Sincerely,

Pratik Das


Code:

void incFSI::FillPatch
(
    int lev, 
    amrex::Real time, 
    amrex::Array<amrex::MultiFab*, AMREX_SPACEDIM> const& mf,                  // destination mf, contains u and v for 2D
    const amrex::Vector<amrex::Array<amrex::MultiFab*, AMREX_SPACEDIM>>& cmf,  // coarse mf, contains u and v for 2D
    const amrex::Vector<amrex::Real>& ct,                                      // coarse time
    const amrex::Vector<amrex::Array<amrex::MultiFab*, AMREX_SPACEDIM>>& fmf,  // fine mf, contains u and v for 2D
    const amrex::Vector<amrex::Real>& ft,                                      // fine time
    int icomp, int ncomp
)
{
    //! No need to fill external boundary values

    amrex::Array<amrex::Vector<amrex::BCRec>,AMREX_SPACEDIM> bcs;
    //for (int n = 0; n < AMREX_SPACEDIM; ++n)
    {
        bcs[0].resize(1);
        for (int idim = 0; idim < AMREX_SPACEDIM; ++idim)
        {
            bcs[0][0].setLo(idim, amrex::BCType::hoextrap);
            bcs[0][0].setHi(idim, amrex::BCType::hoextrap);
        }

        bcs[1].resize(1);
        for (int idim = 0; idim < AMREX_SPACEDIM; ++idim)
        {
            bcs[1][0].setLo(idim, amrex::BCType::foextrap);
            bcs[1][0].setHi(idim, amrex::BCType::foextrap);
        }
    }

    if (lev == 0)
    {
        //amrex::PhysBCFunctNoOp physbc;
        amrex::GpuBndryFuncFab<MyExtBCFill> gpu_bndry_func;//default GpuBndryFuncFab
        amrex::PhysBCFunct<amrex::GpuBndryFuncFab<MyExtBCFill> > physbc(geom[lev-1],bcs[0],gpu_bndry_func);
        for (int dir = 0; dir < AMREX_SPACEDIM; dir++)
        {
            amrex::Vector<amrex::MultiFab *> fmf_tmp(fmf.size());
            for (size_t i = 0; i < fmf_tmp.size(); i++)
            {
                fmf_tmp[i] = fmf[i][dir];
            }
            amrex::FillPatchSingleLevel(*mf[dir], time, fmf_tmp, ft, 0, icomp, ncomp,
                                        geom[lev], physbc, 0);
        }
    }
    else
    {
        amrex::Interpolater* mapper = &amrex::face_divfree_interp;
        //amrex::Array<amrex::PhysBCFunctNoOp, AMREX_SPACEDIM> cphysbc_arr;
        //amrex::Array<amrex::PhysBCFunctNoOp, AMREX_SPACEDIM> fphysbc_arr;

        //amrex::FillPatchTwoLevels(mf, time, cmf, ct, fmf, ft,
        //                    0, icomp, ncomp, geom[lev-1], geom[lev],
        //                    cphysbc_arr, 0, fphysbc_arr, 0, refRatio(lev-1),
        //                    mapper, bcs, 0);

        amrex::GpuBndryFuncFab<MyExtBCFill> gpu_bndry_func;//default GpuBndryFuncFab
        amrex::PhysBCFunct<amrex::GpuBndryFuncFab<MyExtBCFill> > cphysbc(geom[lev-1],bcs[0],gpu_bndry_func);
        amrex::PhysBCFunct<amrex::GpuBndryFuncFab<MyExtBCFill> > fphysbc(geom[lev-1],bcs[0],gpu_bndry_func);

        amrex::Array<amrex::PhysBCFunct<amrex::GpuBndryFuncFab<MyExtBCFill> >, AMREX_SPACEDIM> cphysbc_arr = {cphysbc, cphysbc};
        amrex::Array<amrex::PhysBCFunct<amrex::GpuBndryFuncFab<MyExtBCFill> >, AMREX_SPACEDIM> fphysbc_arr = {fphysbc, fphysbc};

        amrex::FillPatchTwoLevels(mf, time, cmf, ct, fmf, ft,
                            0, icomp, ncomp, geom[lev-1], geom[lev],
                            cphysbc_arr, 0, fphysbc_arr, 0, refRatio(lev-1),
                            mapper, bcs, 0);


    }
}

**Comment by WeiqunZhang** [comment]
Are you using an old version of AMReX?

As for the BCRec array, what I meant was something like
```amrex::Array<amrex::Vector<amrex::BCRec>,AMREX_SPACEDIM> bcs;
for (int n = 0; n < AMREX_SPACEDIM; ++n)
{   
    bcs[n].resize(1);
    for (int idim = 0; idim < AMREX_SPACEDIM; ++idim)
    {   
        if (idim == n) { // we could drop the test and set everything to either hoextrap or foextrap.
            bcs[n][0].setLo(idim, amrex::BCType::hoextrap);
            bcs[n][0].setHi(idim, amrex::BCType::hoextrap);
        } else {
            bcs[n][0].setLo(idim, amrex::BCType::foextrap);
            bcs[n][0].setHi(idim, amrex::BCType::foextrap);
        }
    }
}
```
However, you should try other options too to see which works the best.  See my comments above.

**Comment by ComputationalMultiphaseFlowLab** [comment]
Dear Dr. Zhang,

Thank you so much for your feedback and suggestion. I was using amrex version 21.04-3-g5ec3d3799ff2. I just downloaded the latest version(21.08-75-g889686189996) and working on getting our code to work with this version. GpuBndryFuncFab works with the mixed type mesh in the new version. I do not get the error message " amrex::Abort::2::GpuBndryFuncFab: mixed type not supported !!!" anymore. 

Thanking you for your help.

Sincerely,

Pratik Das
