### ISSUE TITLE
The Fortran postprocessing tools don't compile with OpenMP

### ISSUE THREAD

**Issue by atmyers** [AMReX-Codes/amrex#230]

**Comment by zingale** [comment]
it is likely that we'd need to explicitly insert the OMP directives over the loops in the various tools, as I don't think there is OpenMP embedded in the plotfile.f90 functionality.

**Comment by atmyers** [comment]
It looks like that approach was taken - some of the tools have `!$omp` directives in them, anyway - but the current code doesn't compile if you try to enable it. I can take a look at this at some point - just making an issue so I don't forget.

**Comment by zingale** [comment]
how are you compiling? probably unhelpful, but `fcompare` compiles for me with OpenMP:

```
make OMP=t programs=fcompare
```

**Comment by atmyers** [comment]
I didn't try that one, but `faverplot.f90` and `plt_compare_diff_grids` at least don't seem to work.

**Comment by mic84** [comment]
I confirm that `plt_compare_diff_grids.f90` does not compile when OpenMP is enabled. In particular, variable `ng` is not defined in the file, yet it is used in the OpenMP statement around line 412.

**Comment by atmyers** [comment]
I fixed the `plt_compare_diff_grids.f90` one - I think some copy/pasting just went awry. They all seem to work now, provided I use a compiler that supports OpenMP 4.0.
