### ISSUE TITLE
Question: Can you import a datafile as an embedded boundary geometry?

### ISSUE THREAD

**Issue by jameslehoux** [AMReX-Codes/amrex#231]
In Chombo there was a 'DataFileIF.cpp' for importing ASCII data and generating an implicit function for use as an embedded boundary geometry. 

Is there already/will there be a similar functionality in AMReX? 

Also is it/will it be possible to deal with domains consisting of multiple materials? 

Thank you in advance,

James

**Comment by asalmgren** [comment]
We do not have plans to support EB specification with an ASCII file, although it might be helpful in some cases.   Some applications have their own "short-hand" ways of specifying certain types of geometry.  If this is still something of interest, could you let us know more about the level of generality that would be useful?   For now I'm going to close this issue but feel free to open a new issue on this topic.
