### ISSUE TITLE
Mixed-language failure with get_command

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#233]
I've got a tricky problem involving failure of the Fortran intrinsic `get_command` and a mixed-language use case.  My code is Fortran and working fine with a Fortran main.  I'm now developing a library interface to the code, but have hit an obstacle with the C interface.  Things are dying in `amrex_init` with a failure of the `get_command` Fortran intrinsic.  I haven't dug into the actual code, but I'm sure this little example duplicates what is happening:

```fortran
subroutine fortran_code() bind(c)
  character(80) :: string
  integer :: status, length
  call get_command(string, length, status=status)
  print '(a,i0,a)', 'status=', status, ', "'//trim(string)//'"'
end subroutine
```
And the C main program:
```C
void fortran_code();

int main(int argc, char **argv) {
  fortran_code();
  return 0;
}
```
Here are the results from compilers I have ready access to.
* GFortran:
  ```
  $ gcc -c mixed-main.c
  $ gfortran mixed.f90 mixed-main.o
  $ ./a.out foobar
  status=0, ""
  ```
* NAG:
  ```
  $ gcc -c mixed-main.c
  $ nagfor mixed.f90 mixed-main.o
  $ ./a.out foobar
  status=0, ""
  ```
* Intel:
  ```
  $ icc -c mixed-main.c
  $ ifort -nofor-main mixed.f90 mixed-main.o
  $ ./a.out foobar
  status=1, ""
  ```
None of them can see the command line at all, which is perhaps not surprising since the main is not Fortran (and I'm perfectly fine with that -- more on that in a sec), but the Intel compiler returns an error status that indicates the command line could not be retrieved.  That is arguably the correct result.  Unfortunately Intel and NAG are the two compilers I need to use.

Can something be done to fix this?

Note that I  **really** want to use AMReX like a numerical library, and not a computational framework or environment.  In my use case it shouldn't be doing anything at all with the command line.  I previously managed to get it to ignore the command line by using the `proc_parmparse` callback argument to `amrex_init` but apparently there is still some some poking about that I think is unnecessary if one isn't interested in using AMReX's parameter facility, which I'm not.

**Comment by WeiqunZhang** [comment]
Thanks for reporting this.  I think what we could do is AMReX provides a C wrapper to `amrex::Initialize`.  Let's call it `AMReX_Init`.  For main in C, one calls `AMReX_init` and skips Fortran version of amrex_init, even if all other calls to AMReX are through Fortran interface.  I will get this done in a couple of days.

For main in C++, I believe calling just `amrex::Initialize` without calling the Fortran version of `amrex_init` should currently work.

**Comment by nncarlson** [comment]
I think you might have misunderstood what I'm looking for.  My Fortran library uses AMReX internally, but I don't want to expose that to the client of my library, and I don't see any reason I should have to.  I think you're suggesting that I need to push up the initialization of AMReX to the client (or whoever does the main program), and that's what I specifically don't want to do.

Perhaps this will help explain my perspective. What we (the ExaAM ECP project) ultimately hope to be able to do is run very complex multi-scale, multi-physics calculations with a code that drives and couples many different physics packages, just one of which is my library.  Further, we would hope to be able to run multiple, independent, possibly concurrent instances of my physics solver.  To what extent is AMRex a "singleton" (in design pattern-speak)?

**Comment by WeiqunZhang** [comment]
I was thinking your user might call something like truchas_init that has C and Fortran versions.  Then truchas could call either C or Fortran version of amrex_init.

Anyway, we could do something about `get_command`.   If `get_command` fails, we don't have to stop unless MPI has not been initialized (assuming MPI is used).

I think multiple instances of AMReX as a result of mulitple instances of your solver on different processes are fine.  (I will give this a test.)  But repeatedly calling amrex_init and then amrex_finalize may cause some issues.  However, I believe we could fix that.

By the way, AMReX by default will intercept SIGSEGV, SIGINT, etc.   So you may want to turn it off by ParmParse parameter `amrex.signal_handling = 0`.

**Comment by WeiqunZhang** [comment]
Changes have been made in the development branch that address the `get_command` issue and make AMReX safe for being used a third-party library.   Please give this a try.  There is also a test at amrex/Tests/ThirdPartyLib/.  In that test, AMReX C++ and Fortran instances are being used one after the other in the same communicator, and being run simultaneously in separate sub-communicators.

**Comment by nncarlson** [comment]
@WeiqunZhang, outstanding!  I'll give it a try and let you know how it goes.  Replies to some remarks...

We had noticed earlier while developing some unit tests, that repeatedly calling amrex_init and amrex_finalize didn't work (independent tests in a single process), so if that's now possible that's great.

I do have a separate 'truchas_init' for C, but it's just a thin wrapper around the native Fortran version, something like
```fortran
function new_truchas_Isolver(...) result(solver) bind(c)
  type(truchas_solver), pointer :: tsol
  type(c_ptr) :: solver
  allocate(tsol)
  call tsol%init(...)
  solver = c_loc(tsol)
end function
```
I expect I could manage to have it instead call the C version of amrex_init, but it's complicated by the fact that that is not the first thing that 'truchas_init' does, and particularly that the proc_parmparse that amrex_init needs practically must be a Fortran procedure.  So if this can be avoided it would save having to do some fairly awkward coding.

**Comment by nncarlson** [comment]
@WeiqunZhang I was negligent in following up.  My colleague tried your changes with a C main with our Fortran library shortly after you committed them and it's working fine.  I've since successfully tested the same use case.  I haven't yet tried the repeated init/finalize case, or the concurrent-in-separate-communicator case, but based on your testing I expect it will be fine.  Thanks again for addressing this, and so quickly!
