### ISSUE TITLE
GCC-7 fails to compile after commit: `3573b890b1dd139db8ec3d2093acc98ae181fdbb`

### ISSUE THREAD

**Issue by JBlaschke** [AMReX-Codes/amrex#236]
After [this](https://github.com/AMReX-Codes/amrex/commit/3573b890b1dd139db8ec3d2093acc98ae181fdbb) commit, gcc-7 fails to compile:
```
Src/GeometryShop/AMReX_LSProblemImplem.H:76:24: error: exponent has no digits
   m_lowerBound.assign(-HUGE, m_lowerBound.size());
```
gcc-4.9 and earlier does compile. I don't know exactly why, but it seems that `HUGE` is not defined anywhere (I don't know if `HUGE` is part of the C/C++ standard library, and seeing that it's also a common English word, google is not helping me either).

The error above seems to indicate that (in the absence of a definition), gcc is interpreting `HUGE` as an invalid HEX. My recommendation is to define `HUGE`. @dtgraves maybe you should do that, as I'm not sure why you need a large number there, or what kind of number you want....

**Comment by WeiqunZhang** [comment]
I don't think `HUGE` is part of C or C++ standard.  Instead of defining it, I am going to use `std::numeric_limits<Real>::lowest()` to replace `-HUGE` and `std::numeric_limits<Real>::max()` to replace `HUGE`.

**Comment by JBlaschke** [comment]
Thanks (And thank your for responding on a weekend!). I was wondering if I had missed something....

**Comment by WeiqunZhang** [comment]
Just pushed a commit.  Could you test it?

**Comment by JBlaschke** [comment]
Testing now...

**Comment by WeiqunZhang** [comment]
> thank your for responding on a weekend!

This is not Germany or France.  Checking work email hasn't been outlawed.

**Comment by JBlaschke** [comment]
> This is not Germany or France. Checking work email hasn't been outlawed.
LOL! I better make sure that the germans don't see this issue (otherwise I might not be let back into the country...)

AMReX compiles now. I don't think I was using any of the codes, so I don't expect any side effects of your fix on my end.

**Comment by zingale** [comment]
I'll run the Castro test suite

**Comment by WeiqunZhang** [comment]
Those are in EB codes.  So Castro is not affected.

**Comment by zingale** [comment]
ah... very well :)

**Comment by WeiqunZhang** [comment]
But my fix might be wrong.  @dtgraves needs to take a look.

**Comment by JBlaschke** [comment]
I can also report that the MFiX tests (which are using the EB stuff) are passing also.

**Comment by WeiqunZhang** [comment]
Good.  We need to keep this issue open till Dan looks at it because I think those are in the new high-order moment codes no one is using yet.

**Comment by JBlaschke** [comment]
I agree.
