### ISSUE TITLE
Compiling with MPI is showing errors in mpi.h itself

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#238]
I work on PeleC and I have been able to reproduce this error on multiple machines. I am using the `development` branch of AMReX and OpenMPI 1.10.0 (also tried with 1.10.4 on another machine). It appears a file `AMReX_ParallelContext.H` appeared 5 days ago where this error is originating from. If I compile PeleC without MPI, it seems to work fine. The MPI related errors look like this:

```
/projects/ExaCT/Pele/PeleTests/AMReX//Src/Base/AMReX_ParallelContext.H:42:48: error: cannot convert 'MPI_Group {aka ompi_group_t*}' to 'MPI_Comm {aka ompi_communicator_t*}' in return
 inline MPI_Comm GroupAll () { return frames[0].group; }
                                                ^
In file included from /projects/ExaCT/Pele/PeleTests/AMReX//Src/Base/AMReX_ccse-mpi.H:13:0,
                 from /projects/ExaCT/Pele/PeleTests/AMReX//Src/Base/AMReX.H:5,
                 from /projects/ExaCT/Pele/PeleTests/AMReX//Src/Base/AMReX_FabConv.cpp:7:
/nopt/nrel/apps/openmpi/1.10.0-serial-gcc-5.2.0/include/mpi.h:330:16: note: class type 'ompi_group_t' is incomplete
 typedef struct ompi_group_t *MPI_Group;
                ^
```

**Comment by WeiqunZhang** [comment]
There was a typo.  Could you try again with the latest development branch?  Thanks!

**Comment by jrood-nrel** [comment]
@WeiqunZhang Thanks. That's seems to have fixed the MPI errors.
