### ISSUE TITLE
commit ebb652d4a995a3d5dcdbda0fe62ba221ba257f97 broke AMReX Astro codes

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#244]
it seems that this commit gives failures for any of our tests that use the helmeos, e.g.,

http://bender.astro.sunysb.edu/Microphysics/test-suite/test-suite-gfortran/2018-04-09-002/index.html

Castro too.

**Comment by atmyers** [comment]
I think there is maybe a collision between this change:

real(kind = amrex_real), parameter :: FORTH   = 0.25_amrex_real

and the use of 'forth' to mean 4/3 in helmholtz/actual_eos.F90

**Comment by WeiqunZhang** [comment]
`FORTH` was added to amrex_constants_module because `AMReX_REAL.H`'s Fortran part always has `FORTH`.

**Comment by drummerdoc** [comment]
I'm going to go out on a limb and suggest that FORTH is a terrible name for 4/3....

**Comment by zingale** [comment]
I don't disagree, but I am concerned that the compiler didn't even warn about a name clash.

**Comment by WeiqunZhang** [comment]
`FORTH` has been in CCSE's old Fortran codes since the beginning probably because shorter names were preferred in old Fortran.

**Comment by drummerdoc** [comment]
Well, I think that particular one is easy to fix, once and for all, by removing its definition completely.  If something like it is desired, use `FOURTH` (and `FOURTHIRDS`).  The compiler should tell us when things needs to be changed (provided `implicit none` was used...as STRONGLY recommended).  I know this sounds arrogant, but I think it's the correct thing to do.

**Comment by maxpkatz** [comment]
I second Marc's comment that we should remove FORTH, even if that means breaking codes.

**Comment by zingale** [comment]
I think we all agree.  

I just don't understand why the compiler even allowed the two parameters with the same name in the first place.

**Comment by atmyers** [comment]
I've already removed it from `amrex_constants_module`. I'll remove it from `AMReX_CONSTANTS.H` as well.

**Comment by maxpkatz** [comment]
@zingale forth was a preprocessor variable not a module variable. So it was probably getting replaced before the compiler even saw the clash.

**Comment by zingale** [comment]
oh, didn't notice that.  That makes sense then.

**Comment by WeiqunZhang** [comment]
No `forth` is not a macro.  `FORTH` is.  But `FORTH` has nothing to do with the failure in eos because that macro is not seen by `actual_eos.F90`.  That was due to name conflicts in modules.

**Comment by WeiqunZhang** [comment]
In the future we should remove `AMReX_CONSTANTS.H` because the constants there are defined as macros.  However, please be aware that it will break some codes.  Fixing it will take time.  The reason is the codes that use `AMReX_CONSTANTS.H` are `.F` files that do not go through a process of finding module dependency.  So we cannot simply switch to use modules.  Changing `.F` files to `.F90 files will solve the dependency issue, but will require some work to reformat the source codes.

**Comment by maxpkatz** [comment]
If AMReX_CONSTANTS.H wasn't seen by actual_eos.F90 then I'm confused again -- the compiler should definitely have complained about the name conflict.

**Comment by maxpkatz** [comment]
Here is a reproducer:

```
module testmod

  double precision, parameter :: B = 0.25

end module testmod

module testmod2

  double precision, parameter :: b = 0.5

contains

  subroutine testsub

    use testmod

    double precision :: a

    a = b * 2

  end subroutine testsub

end module testmod2
```

**Comment by WeiqunZhang** [comment]
The code above compiles just fine and the compiler is probably not wrong.  It might be nice if they give a shadow warning, but the code above is legitimate, I think.  `subroutine testsub` accesses `module testmod`'s variable `b` via use association, whereas its access to `module testmod2` (its own hosting module) is via so-called host association. Use association is like a local variable and shadows the host associated variable.  One could argue the Fortran standard has a defect, but that's how the language is defined.   Also note the following code is also legitimate for the same reason.

    module testmod
         double precision, parameter :: b = 0.5
    contains
         subroutine testsub
             double precision :: b
             b = 1.0
        end subroutine testsub
    end module testmod

**Comment by WeiqunZhang** [comment]
It seems one can think of `use fortran_module,only : a` as `double& a = fortran_module::a`, then we see Fortran is consistent with C++.
