### ISSUE TITLE
Fortran tutorial fails to build

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/amrex#245]
1. I am describing the overall error. Can give any details needed. The error occurs when I go into Tutorials/Basic/main_F and then do 'make'. The .o files are compiled just fine, and the error occurs at the linking stage. This is the error.

Undefined symbols for architecture x86_64:
  "std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocator()", referenced from:
      _amrex_fi_init in AMReX_init_fi.o
  "std::allocator<amrex::MultiFab const*>::allocator()", referenced from:
      _amrex_fi_write_plotfile in AMReX_plotfile_fi.o
  "std::allocator<amrex::MultiFab*>::allocator()", referenced from:
      _amrex_fi_fillpatch_single in AMReX_fillpatch_fi.o
      _amrex_fi_fillpatch_two in AMReX_fillpatch_fi.o
ld: symbol(s) not found for architecture x86_64

2. All C tutorials compile just fine. (main_C, HeatEquationEX1_C etc.)

3. I am using mpicxx (CXX) , mpicc (CC) and mpif90  (FC,F90) as the compilers in Make.local.

4. The configure, make and make install in the amrex directory works perfectly fine.

I am on Mac OS X Sierra. It is a linking error when fortran binaries are tried to link to c++ binaries. Is there any idea of how to resolve this? Any help is deeply appreciated.

**Comment by WeiqunZhang** [comment]
What's the output of `make help` in `main_F/`?

**Comment by hsitaram** [comment]
When you say "It is a linking error when fortran binaries are tried to
link to c++ binaries." -

I had this issue before. This is because the gfortran you have is not
compatible with the mac's clang gcc compiler.
I suggest installing gcc6/gcc7 from macports and "port selecting" this gcc
instead of the Mac's gcc.

Hari

**Comment by nataraj2** [comment]
The output of make help in main_F

Loading ../../..//Tools/GNUMake/comps/gnu.mak...
Loading ../../..//Tools/GNUMake/sites/Make.unknown...
Loading ../../..//Tools/GNUMake/Make.local...

The rule for compiling foo.cpp  is: $(CXX) $(CXXFLAGS) $(FINAL_CPPFLAGS) $(includes) -c foo.o foo.cpp
The rule for compiling foo.c    is: $(CC) $(CFLAGS) $(FINAL_CPPFLAGS) $(includes) -c foo.o foo.c
The rule for compiling foo.f90  is: $(F90) $(F90FLAGS) $(fincludes) -c foo.o foo.f90
The rule for compiling foo.F90  is: $(F90) $(F90FLAGS) $(FINAL_CPPFLAGS) $(fincludes) -c foo.o foo.F90
The rule for compiling foo.[fF] is: $(FC) $(FFLAGS) $(fincludes) -c foo.o foo.f
    Note that .F files are preprocessed with cpp into .f files before being compiled.
The rule for linking            is: $(CXX) $(CXXFLAGS) $(FINAL_CPPFLAGS) $(includes) $(LDFLAGS) -o $(executable) *.o $(libraries)

Here the variables are set to:
    CXX        = /Users/natarajan/opt/usr/local/bin/mpicxx
    CC         = /Users/natarajan/opt/usr/local/bin/mpicc
    FC         = /Users/natarajan/opt/usr/local/bin/mpif90
    F90        = /Users/natarajan/opt/usr/local/bin/mpif90
    CPPFLAGS   = -DDEBUG -DBL_USE_MPI -DAMREX_GIT_VERSION="18.04" -DBL_GCC_VERSION=7.1.0 -DBL_GCC_MAJOR_VERSION=7 -DBL_GCC_MINOR_VERSION=1 -DAMREX_LAUNCH= -DAMREX_DEVICE= -DBL_SPACEDIM=3 -DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DBL_Darwin -DBL_USE_ASSERTION -DBL_USE_F_INTERFACES
    FINAL_CPPFLAGS   = -DDEBUG -DBL_USE_MPI -DAMREX_GIT_VERSION="18.04" -DBL_GCC_VERSION=7.1.0 -DBL_GCC_MAJOR_VERSION=7 -DBL_GCC_MINOR_VERSION=1 -DAMREX_LAUNCH= -DAMREX_DEVICE= -DBL_SPACEDIM=3 -DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DBL_Darwin -DBL_USE_ASSERTION -DBL_USE_F_INTERFACES
    CXXFLAGS   =  -g -O2 -fno-inline -ggdb -Wshadow -Wall -Wno-sign-compare -ftrapv -Wno-unused-but-set-variable -Wnull-dereference  -lstdc++ -std=c++11
    CFLAGS     = MY_AWESOME_CFLAGS
    includes   = -I. -I../../..//Src/Base -I../../..//Src/F_Interfaces/Base
    FFLAGS     =  -g -O0 -ggdb -fcheck=bounds -fbacktrace -Wuninitialized -Wunused -ffpe-trap=invalid,zero -finit-real=snan -finit-integer=2147483647 -ftrapv -ffixed-line-length-none -fno-range-check -fno-second-underscore -Jtmp_build_dir/o/3d.gnu.DEBUG.MPI.EXE -I tmp_build_dir/o/3d.gnu.DEBUG.MPI.EXE  -fcheck=array-temps -lstdc++
    F90FLAGS   =  -g -O0 -ggdb -fcheck=bounds -fbacktrace -Wuninitialized -Wunused -ffpe-trap=invalid,zero -finit-real=snan -finit-integer=2147483647 -ftrapv -ffree-line-length-none -fno-range-check -fno-second-underscore -Jtmp_build_dir/o/3d.gnu.DEBUG.MPI.EXE -I tmp_build_dir/o/3d.gnu.DEBUG.MPI.EXE -fimplicit-none  -fcheck=array-temps -lstdc++
    fincludes  = -I. -I../../..//Src/Base -I../../..//Src/F_Interfaces/Base
    LDFLAGS    = -L. -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0/../../../ -L./
    libraries  = -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/lib -L/usr/local/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -L/Users/natarajan/opt/usr/local/lib -lgfortran -lquadmath
    executable = main3d.gnu.DEBUG.MPI.ex

Read Tools/GNUMake/README.md for details on tweaking the make system.

**Comment by WeiqunZhang** [comment]
If you remove your `Make.local`, it probably will compile.

**Comment by nataraj2** [comment]
Compiled using the compiler from MacPorts and all works fine. Thanks a lot. However, there were a few issues (fixed) which is probably useful for Mac users. I am listing them below.

1.  `#include <cstdlib>` is required in  AMREX_IntVect.H. Else there is an error during the build.

2. `sed` in Mac does not recognize the next line character '\n' and this creates lines like

     `#include <AMReX_Config.H>\n#ifndef BL_BOX_H`

in *.H files in tmp_install_dir/include, which creates issues while compiling tutorials. Use gnu-sed (gsed) in the Tools/GNUMake/Make.rules instead of sed in the install_headers section.

     gsed -i -e '1s/^/#include <AMReX_Config.H>\n/' $$newf; \
           
3. Visualization in VisIt 2.13 is supported, but earlier versions may not be (2.9.2 is not).

**Comment by atmyers** [comment]
Thank you for the bug fixes. AMReX should work out-of-the-box on Mac now on the development branch.
