### ISSUE TITLE
File names in `Src/Extern/SWFFT/` will break operations in case-insensitive file systems

### ISSUE THREAD

**Issue by JBlaschke** [AMReX-Codes/amrex#247]
Commit `dc39d17dc9296e9b1be3b759e778142c4f664367` introduces the directory `Src/Extern/SWFFT/`, containing both capitalized and lower-case `Distribution.H` (and `distribution.h`). This will break if the user has a case-insensitive file system (I'm looking at you Apple!). Essentially `Distribution.H` `distribution.h` get mangled.

**Comment by atmyers** [comment]
I believe this has been addressed - the `distribution.h` file as been renamed.
