### ISSUE TITLE
illegal preprocessor directive

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#250]
GCC complains about an illegal preprocessor directive in `AMReX_bc_types.fi`:
```
AMReX_bc_types.fi:1:2:

Warning: Illegal preprocessor directive
AMReX_bc_types.fi:20:2:

Warning: Illegal preprocessor directive
```

**Comment by zingale** [comment]
maybe we can create a module with this info to allow codes to switch over from a Fortran include?

**Comment by WeiqunZhang** [comment]
There is a module `amrex_bc_types_modules` that has the same information but with slightly different names.

**Comment by WeiqunZhang** [comment]
I assume the issue here is it is included by a .f or .f90 file.  I am going to remove the ifndef because it is actually unnecessary.
