### ISSUE TITLE
Paraview visualization supported on MacOS?

### ISSUE THREAD

**Issue by mattbement** [AMReX-Codes/amrex#251]
Running Paraview 5.5 on macOS 10.12.6.  I follow the instructions for opening AMReX plot files in paraview, but Boxlib 3D files isn't a choice.  Is there an expectation that this should work on a Mac? If so, it is likely a Paraview issue.

**Comment by drummerdoc** [comment]
Just curious, is this just a choice of the configuration they setup for the Paraview prebuilt execs, or is there something fundamentally unsupported (which seems not likely)?  If this is the case, then if one were to build their own Paraview on the Mac, could they then have AMReX plotfile support?

**Comment by utkarshayachit** [comment]
@drummerdoc, we have had build issues with getting BoxLib reader working in ParaView on macOS and hence it is currently only supported for Windows and Linux. It is on the agenda to update the reader and subsequently support all platforms.

**Comment by drummerdoc** [comment]
Interesting.  I am aware of potential issues associated with supporting both 2d and 3d in the same build, and we have ideas to address that (someday), but I wasn't aware of build issues other than that.  If you can pinpoint issues, you can post an "issue" here at GitHub and some magic may occur :).  It is worth noting that macOS is supported in two ways: via the native LLVM based compiler, and via the GNU compiler managed through "homebrew".  If you do report problems, it would help to have specifics.  (this also suggests that if you have problems, to try the "other" setup).

**Comment by utkarshayachit** [comment]
let me ping the developer who looked into this. I only have second hand knowledge about the issue, I am afraid.

**Comment by utkarshayachit** [comment]
@mathstuf looked at it, but he's on vacation for a few months. From what I could gather from various emails etc. is that the issue was building Boxlib on macOS without Fortran. Here's a ref: https://gitlab.kitware.com/paraview/paraview-superbuild/issues/48

**Comment by drummerdoc** [comment]
Ahh.  If you wait long enough, I think FLANG is or will be usable for building the fortran bits.  But, I think that there is nothing in BoxLib/AMReX that is written in Fortran that is actually required for IO operations, so there's a couple of paths forward...but yeah, it's some amount of work for someone to sort that out (in addition to the 2d vs 3d thing...).  thanks for the link.

**Comment by WeiqunZhang** [comment]
In AMReX's gnu make build system, there is `BL_NO_FORT`.  When that make variable is not `TRUE`, Fortran files are not included.  See `amrex/Src/Base/Make.package`.  In the source code, `#if !defined(BL_NO_FORT)` is used to disable the calls to Fortran.

@mic84 Do we have this option for cmake?

**Comment by mic84** [comment]
@WeiqunZhang No, that option was no included in CMake, thus the fortran files are always included. I can add it if necessary.

**Comment by mathstuf** [comment]
@WeiqunZhang On macOS, when disabling the Fortran bits by hand in CMake code, it came up with undefined symbols, so the Fortran stuff isn't completely optional on macOS (or I missed some step).

**Comment by WeiqunZhang** [comment]
Thanks for letting use know.  It's currently broken.  I will try to fix ti.

**Comment by WeiqunZhang** [comment]
I just pushed a commit to development branch.  I am able to build `amrex/Base/` with `-DBL_NO_FORT` using our GNU make system.  Please see `amrex/Base/Make.package` to see what files need to be excluded when BL_NO_FORT is defined.

By the way, we have recently made some changes to IntVect.  We can now read 2d plotfiles with 3d executable.  I don't know how ParaView read amrex plotfiles.  In principle, one executable should be able to read both 2d and 3d files.
