### ISSUE TITLE
AMReX_SPACEDIM issue with CMake -- Spack installed AMReX

### ISSUE THREAD

**Issue by SudhakarYogaraj** [AMReX-Codes/amrex#2552]
Hi,

I have installed AMReX 21.10 using spack. It works perfectly fine in 3D. However, when I try to compile the code in 2D with

_find_package(AMReX REQUIRED 2D)_

CMake throws an error. Changing 2D to 3D works fine. Do I need to use any special command other than _spack install amrex_ while installation?

Thanks

**Comment by sayerhs** [comment]
@SudhakarYogaraj  If you just do `spack install amrex` it will build AMReX with `AMREX_SPACEDIM = 3` [see spack definition](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/amrex/package.py#L54). 

You will have to build a variant of AMReX

```
spack install "amrex dimensions=2"

**Comment by SudhakarYogaraj** [comment]
Thank you Shreyas. It worked.
