### ISSUE TITLE
add indication at start of AMReX application that we are on CUDA

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#26]
We should have something output near the 

```
MPI initialized with 4 MPI processes
```

that indicates we are running on the GPUs with CUDA

**Comment by maxpkatz** [comment]
This work is now done on the `gpu` branch, when you're using GPUs, you'll see a message like

```
MPI initialized with 8 MPI processes
CUDA initialized using 8 GPUs out of 8 available
```

You can use the inputs parameter `device.v = 1` to get more specific information about CPU to GPU mappings.
