### ISSUE TITLE
No final output files

### ISSUE THREAD

**Issue by AMReX-Fusion** [AMReX-Codes/amrex#2608]
Hello,

I am trying a simple Sedov test on my Ubuntu in Windows Subsystem for Linux (WSL) and Castro doesn't want to produce proper output files. It creates only temporary output files:

drwxrwxrwx 1 ondrej ondrej      512 Jan 31 15:08 sedov_1d_sph_chk00000.temp
drwxrwxrwx 1 ondrej ondrej      512 Jan 31 15:09 sedov_1d_sph_chk00119.temp
drwxrwxrwx 1 ondrej ondrej      512 Jan 31 15:08 sedov_1d_sph_plt00000.temp
drwxrwxrwx 1 ondrej ondrej      512 Jan 31 15:09 sedov_1d_sph_plt00119.temp

I digged a bit into the AMReX code and found the following.
In "AMReX_Amr.cpp" around line 1044 the code the "std::rename(pltfileTemp.c_str(),pltfile.c_str())" returns -1, that is "Error: Permission denied".
Do you have an idea what can go wrong?

On one forum I found that this can happen when a previously opened file was opened but not closed.
Can this be an issue?
https://stackoverflow.com/questions/11840611/permission-denied-for-rename-function-in-c-on-windows/13383026

Thanks

**Comment by AMReX-Fusion** [comment]
Actually I found the culprit.

I am not sure if this was intended, but currently the HeaderFile of the output directory opened on line 987 is not closed before "std::rename(xxx,yyy)" is called. Since this file resides in the "_plt" folder, it effectively blocks the renaming of the folder.

I suggest to close it on line 1039:

HeaderFile.close()

The same case is with the "_chk" output folders. So there are actually errors on two places.

https://stackoverflow.com/questions/24509989/rename-function-doesnt-work-using-c

**Comment by WeiqunZhang** [comment]
Thanks for reporting this and finding the culprit!
