### ISSUE TITLE
Nonexistent HIP Paths

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#2686]
HIP in GNUmake works on the early DOE AMD machines, but if you are merely cross-compiling on a system with the ROCm/HIP package libraries installed, the directory layout is different. The main issue is `/opt/rocm/hiprand/lib` and `/opt/rocm/rocrand/lib` do not exist like they do in the layout on the DOE machines with several ROCm versions installed. Therefore this fails to find `libhiprand` and `librocrand`:
https://github.com/AMReX-Codes/amrex/blob/3aafa306ad820bbcc50a4b7c14fe912406427d1d/Tools/GNUMake/comps/hip.mak#L117

My current solution is to add `LIBRARY_LOCATIONS=/opt/rocm/lib` to the `make` command.

**Comment by WeiqunZhang** [comment]
We can replace `-Wl,--rpath=$(ROC_PATH)/rocrand/lib -Wl,--rpath=$(ROC_PATH)/hiprand/lib` with `-Wl,--rpath=$(ROC_PATH)/lib`.  I just checked on those DOE machines.  There are links to `libhiprand` and `librocrand` in `$(ROC_PATH)/lib`.

**Comment by jrood-nrel** [comment]
It looks like these changes are necessary for ROCm 5.1.0 on Crusher?
```
ld.lld: error: unable to find library -lhiprand
ld.lld: error: unable to find library -lrocrand
ld.lld: error: unable to find library -lmpi_gtl_hsa
```

**Comment by jmsexton03** [comment]
I made PR #2717 with the version I was testing (for the GNUMake at least, the only CMake part that seems like it would be affected might be roctracer which seems little used)
