### ISSUE TITLE
New rt type is not defined

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#269]
Should the `rt` type that appears in https://github.com/AMReX-Codes/amrex/commit/641bcae975e4aa21fc2d6123099bb8782c3c8f73 be defined in `Src/F_BaseLib/bl_types.f90`? Or is this type to be defined in some new `Src/F_BaseLib/amrex_types.f90`? Right now AMReX is writing `extern.f90` files with `rt` not defined and PeleC does not currently compile due to this change.

**Comment by asalmgren** [comment]
We are in the process of migrating existing application codes to not need to use amrex/Src/F_BaseLib (and amrex/Src/LinearSolvers/F_MG) -- Weiqun is working on this now.  Once this is complete we will in fact move F_BaseLib and F_MG out of amrex itself since they are no longer being maintained.

**Comment by WeiqunZhang** [comment]
Already emaild Marc the fix in PeleC.

**Comment by WeiqunZhang** [comment]
```
diff --git a/Source/extern_probin.template b/Source/extern_probin.template
index 586a7aa..10d08b2 100644
--- a/Source/extern_probin.template
+++ b/Source/extern_probin.template
@@ -3,8 +3,7 @@

 module extern_probin_module

-  use bl_types
-  use bl_space
+  use amrex_fort_module, only : rt => amrex_real

   implicit none

```

**Comment by jrood-nrel** [comment]
Excellent, thanks! I can implement the fix in PeleC.
