### ISSUE TITLE
CodeQL: possible integer overflows

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#2713]
https://github.com/AMReX-Codes/amrex/blob/fc55c67f72d2842caa6bd7b908dfe82df910ec75/Src/Base/AMReX_FabConv.cpp#L996

The CodeQL scan on the Quokka repo reports: `Multiplication result may overflow 'int' before it is converted to 'streamsize'.`

Is this a real issue, or a false positive? There are several alerts like this for AMReX_FabConv.cpp.

The scan was run on the Quokka repo, so it doesn't show the code scanning alerts unless you have write access, so I've taken a screenshot here:
![image](https://user-images.githubusercontent.com/1781919/163505438-e98119be-bb7d-4b6a-b33b-566e1744ba6e.png)

**Comment by BenWibking** [comment]
This is the full list of CodeQL alerts I get (almost all about int conversions to larger types):

![image](https://user-images.githubusercontent.com/1781919/163505990-fdc99ca8-4cc6-4fec-92ff-5d7ac4ec1822.png)

**Comment by WeiqunZhang** [comment]
I don't think this can be considered a real issue. In `id.numBytes()*get`, `id.numBytes()` is 8 for double and `get` is not greater than `readBufferSize`, which is set to 262144 (i.e., 2^18).  So the maximum value for the product is 2^21, unless one calls `RealDescriptor::SetReadBufferSize` to set it to a real big number.  I guess we can make sure `readBufferSize` is not too big in `SetReadBufferSize` to be completely safe.  Not sure if it will quiet codeQL.

**Comment by WeiqunZhang** [comment]
Maybe we can just cast one of the numbers first, then the warning will be gone.

**Comment by BenWibking** [comment]
The warnings in VisMF and DistributionMapping look similarly harmless. I can't quite figure out what the code in AMReX_Random is doing.

Casting one of the operands to size_t should silence the warning.

**Comment by BenWibking** [comment]
PR #2716 satisfied CodeQL.

Can you confirm whether the rest (below) also appear to be harmless?
![image](https://user-images.githubusercontent.com/1781919/163991254-003c89d2-be22-49e9-955e-ad574453e1ba.png)

**Comment by WeiqunZhang** [comment]
They all look harmless.  If you want to fix the warnings, please feel free to submit a PR.  We don't have CodeQL set up, so I cannot be sure my attempt to fix it would work.

**Comment by BenWibking** [comment]
Since the rest are harmless, I'll just suppress them manually.
