### ISSUE TITLE
Shouldn't have MAESTRO and CASTRO-specific files in amrex

### ISSUE THREAD

**Issue by asalmgren** [AMReX-Codes/amrex#272]
In amrex/Tools/Postprocessing/F_Src there is a CASTRO_radiation directory and several MAESTRO* directories.   These don't belong in amrex.

Does anyone have any objection to my moving the CASTRO_radiation/* files to the Castro repo and the MAESTRO* directories to MAESTRO and/or MAESTROex?

**Comment by drummerdoc** [comment]
Delete away!

**Comment by maxpkatz** [comment]
+1

**Comment by ajnonaka** [comment]
Sounds good.  Put in MAESTRO for now please.

**Comment by asalmgren** [comment]
Ok those files have been moved to the Castro and Maestro codes, respectively.
