### ISSUE TITLE
ability to compare HDF5 plotfile with AMReX native format plotfile

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#2720]
It would be very useful to be able to compare HDF5 format plotfiles with AMReX native format plotfiles with `fcompare`. Giving the two plotfiles as command-line arguments to `fcompare` doesn't work.

Is there a straightforward way to add this? I'd be happy to submit a PR for this if I can get a pointer on where to start.

**Comment by WeiqunZhang** [comment]
If you can add HDF5 support to `PlotFileDataImpl` class, `fcompare` should then work on HDF5 plotfiles.

**Comment by BenWibking** [comment]
I've decided to stick with native format plotfiles for now. This can be re-opened if anyone else needs this functionality.
