### ISSUE TITLE
'i' undeclared idenfier Visual Studio 2019 build AMREX when fillNeighbors() is used

### ISSUE THREAD

**Issue by ramsampath** [AMReX-Codes/amrex#2738]
The following compilation error appears in building AMREX after ParticleContainer.fillNeighbors() is called

(Compiler = Visual Studio 2019).

and ParticleContainer is an object of class derived from amrex::NeighborParticleContainer<22,0,13,0>

AMReX_ParticleTransformation.H:160: error: C2065: 'i': undeclared identifier

D:\FDYNAMICS\Neutrino\trunk\neutrino\External\windows\include\amrex\AMReX_NeighborParticlesCPUImpl.H(405): note: see reference to function template instantiation 'void amrex::copyParticles<amrex::ParticleTile<22,0,13,0,Allocator>,amrex::ParticleTile<22,0,13,0,Allocator>,int,int,0>(DstTile &,const SrcTile &,Index,Index,N) noexcept' being compiled
        with
        [
            Allocator=amrex::DefaultAllocator,
            DstTile=amrex::ParticleTile<22,0,13,0,amrex::DefaultAllocator>,
            SrcTile=amrex::ParticleTile<22,0,13,0,amrex::DefaultAllocator>,
            Index=int,
            N=int
        ]
AMReX_NeighborParticlesCPUImpl.H(271): note: while compiling class template member function 'void amrex::NeighborParticleContainer<22,0,13,0>::updateNeighborsCPU(bool)'
AMReX_NeighborParticlesCPUImpl.H(13): note: see reference to function template instantiation 'void amrex::NeighborParticleContainer<22,0,13,0>::updateNeighborsCPU(bool)' being compiled
AMReX_NeighborParticlesCPUImpl.H(8): note: while compiling class template member function 'void amrex::NeighborParticleContainer<22,0,13,0>::fillNeighborsCPU(void)'
AMReX_NeighborParticlesI.H(616): note: see reference to function template instantiation 'void amrex::NeighborParticleContainer<22,0,13,0>::fillNeighborsCPU(void)' being compiled
AMReX_NeighborParticlesI.H(22): note: while compiling class template member function 'amrex::NeighborParticleContainer<22,0,13,0>::NeighborParticleContainer(const amrex::Geometry &,const amrex::DistributionMapping &,const amrex::BoxArray &,int)'
NReXISphNeighborParticleContainer.h(19): note: see reference to function template instantiation 'amrex::NeighborParticleContainer<22,0,13,0>::NeighborParticleContainer(const amrex::Geometry &,const amrex::DistributionMapping &,const amrex::BoxArray &,int)' being compiled
NReXISphNeighborParticleContainer.h(7): note: see reference to class template instantiation 'amrex::NeighborParticleContainer<22,0,13,0>' being compiled

the following is where the error appears 
AMREX_HOST_DEVICE_FOR_1D( n, i,
    {
        copyParticle(dst_data, src_data, src_start+i, dst_start+i);
    });

Has anyone encountered this issue and/or guide on how to fix this , would be very much appreciated.

Thank you
Ram.

**Comment by atmyers** [comment]
Hi Ram,

I have not encountered this before. It looks like something is going wrong in the macro expansion - this only happens after you add the `pc.fillNeighbors` call? Can you do the Visual Studio equivalent of `gcc --save-temps` so we can see the output of the preprocessor? 

Are you able to compile amrex itself as a library as in one of our windows tests, [here](https://github.com/AMReX-Codes/amrex/blob/development/.github/workflows/windows.yml)?

**Comment by ramsampath** [comment]
Hello Andrew,

 thank you for your response. yes this only happens after I add the .fillNeighborsCall - I will try to google for the save-temps equivalent .  So far I haven't been able to find an equivalent. 

and yes I am able to compile amrex as a library by itself but haven't tried the windows tests.  I did try to build NeighborList tutorial and that was giving similar errors. 

Ram.

**Comment by ramsampath** [comment]
After a lot of iterations and searches the following compiler option works /Zc:preprocessor .
