### ISSUE TITLE
Use a smarter GPU reduction strategy

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#275]
Right now we are using the most naive possible reduction strategy on the GPU: atomically update a single variable in global memory. We can be smarter about this to reduce the effects of atomic collisions, by doing some of the work at the threadblock level.

**Comment by maxpkatz** [comment]
I may end up using [CUB](http://nvlabs.github.io/cub/) here, if it makes sense.

**Comment by atmyers** [comment]
@maxpkatz This has been addressed now, correct?

**Comment by maxpkatz** [comment]
Yeah, we're doing better reductions in both Fortran and C++ so I'll close this.
