### ISSUE TITLE
Currently Supported CUDA SM?

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/amrex#2760]
What is the currently supported CUDA compute capability minimum again?

I thought we only support Pascal+ (sm_60+), but I cannot find it in docs...

I also see PRs like #1512 that seem to relax this?
Let's document this :)

cc @WeiqunZhang @maxpkatz

**Comment by WeiqunZhang** [comment]
https://amrex-codes.github.io/amrex/docs_html/GPU_Chapter.html
> AMReX supports NVIDIA GPUs with compute capability >= 6 and CUDA >= 10.

Unofficially, we support >= 3.5.  An AMReX user wanted to run on an old GPU.  So that was the origin of #1512.

**Comment by ax3l** [comment]
Thanks! Huh, I must have used the wrong keywords in my search :+1: Sphinx docs search is quite particular xD
