### ISSUE TITLE
Enhancement request: Multiple, concurrent, independent instances of AMReX

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#278]
In an earlier [issue](https://github.com/AMReX-Codes/amrex/issues/233#issuecomment-375894407) I wrote,

> What we (the ExaAM ECP project) ultimately hope to be able to do is run very complex multi-scale, multi-physics calculations with a code that drives and couples many different physics packages, just one of which is my library. Further, we would hope to be able to run multiple, independent, possibly concurrent instances of my physics solver.

A reply suggested this was probably possible, but this turns out not to be the case; see issue #277. AMReX is in fact a singleton. So this is a request to for a capability to have multiple concurrent and independent instances of "amrex".

NB: The direct problem #233 was concerned with was quickly resolved long ago.

**Comment by WeiqunZhang** [comment]
Could you clarify on the meaning of "multiple, independent, possibly concurrent instances"?  Suppose there are solvers A and B that both use AMReX.   If this means threads with even ID are calling A, while threads with odd ID are calling B, then I would say it will not be easy.

**Comment by nncarlson** [comment]
If you replace "threads" with mpi ranks, where even ranks are the subcommunicator that solver A is using and passed to AMReX, and similarly the odd ranks are the subcommunicator that solver B is using and passed to its "instance" of AMReX, then yes.  It's the use case behind #277.  Maybe @sslattery can explain it better than this non-CS person.

I expect it would hard to do if AMReX is inherently a singleton.

**Comment by WeiqunZhang** [comment]
This works (assuming there are no hidden calls to `amrex::Initialize` and `Finalize`)

    if (is_odd_rank) {
        amrex::Initialize(..., odd_comm, ...);
        solve_A_in_odd_comm();
        solve_B_in_odd_comm();
        amrex::Finalize();
    } else {
        amrex::Initialize(..., even_comm, ...);
        solve_B_in_even_comm();
        solve_A_in_even_comm();
        amrex::Finalize();
    }

This also works

    amrex::Initialize(..., comm_1, ...);
    solve_A_comm_1();
    amrex::Finalize();

    amrex::Initialize(..., comm_2, ...);
    solve_B_in_comm_2();
    amrex::Finalize();

This does NOT work

    amrex::Initialize(..., comm_1, ...);
    solve_A_in_comm_1();
    amrex::Initialize(..., comm_2, ....);
    solve_B_in_comm_2();

However, if `comm_1 == comm_2`, one can do

    amrex::Initialize(..., comm_1, ....);
    solve_A();
    solve_B();
    amrex::Finalize();

Note that `solve_B` might see side-effects due to the call to `solve_A`.  For example, the I/O in solve_A might write data in `amrex::FArrayBox` in single precision, then solve_B will write in single precision too if the format is not reset.  In some sense, this is similar to C++ cout that is global.  We could document these kind of side-effects better.  We could also add an `bool amrex::IsInitialized()` function to help determine if amrex::Initialize has been called.

**Comment by nncarlson** [comment]
Not sure, but I think I may understand your examples. Let's see if I have it right...

In my setup, instantiation of a solver object takes a communicator, and it (internally) calls amrex::Initialize with that communicator (and only the processes in that communicator participate in the instantiation). The destructor for the object calls amrex::Finalize.  It sounds like 1) having multiple solvers running concurrently will work as long as the communicators are disjoint, having no processor in common. But 2) I can't have two different instances whose communicators share a processor (because that would mean a double call to amrex::Initialize on that process).  And 3) if I free an instance and create a new instance with the same communicator, that works too.  Have I got that right?  If so, that is a long way toward what I was asking for and what would be ideal for a library.

**Comment by WeiqunZhang** [comment]
Yes, you have got it right.   But it seems to me you could in your end manage how and when `amrex::Initialize` and `amrex::Finalize` get called.   In some sense, most AMReX applications use multiple solvers (e.g., AMR, linear solves, particles, etc.) that use AMReX, and they share the same "instance" of AMReX.

**Comment by nncarlson** [comment]
Yes, you are right, the solvers could delegate management of AMReX to the client, but this is a poor choice from a software design perspective as it exposes unnecessary internal details to the client. This is defensible if all the "solvers" belong to the same application, but hard if the "solver software" have independent lives as libraries, as in our case.

Anyway, this was intended as food for thought. I expect you will be encountering potential users who want to use AMReX as a library, and not as a framework within which to develop an application, and it's not quite there.

**Comment by WeiqunZhang** [comment]
Thanks for the feedback!  It seems to me the difficulty we have is to allow multiple independent instances of amrex we would have to pass an amrex object around, just like most MPI functions must take a communicator argument.  It would be too disruptive to existing AMReX users.

**Comment by nncarlson** [comment]
> [...] we would have to pass an amrex object around [...]

Yeah, that's exactly right for a non-object oriented interface (like MPI's). But I would think in your primary C++ interface that that object would buried inside your other objects -- most of your functionality is exposed as class methods anyway (I think).

**Comment by nncarlson** [comment]
@WeiqunZhang I think there may be something wrong in the Fortran amrex_init procedure with regards to the concurrent use of AMReX on disjoint communicators.  As you indicated, this C example works fine
```c
int main(int argc, char** argv) {

  int nproc, rank, color;
  MPI_Comm comm;
  
  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &nproc);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  
  // This works
  color = rank % 2;
  MPI_Comm_split(MPI_COMM_WORLD, color, rank, &comm);
  amrex::Initialize(argc, argv, comm);
  amrex::Finalize();
  
  MPI_Finalize();
  
  return 0;
}
```
But the Fortran analog segfaults somewhere in the amrex_init call:
```fortran
program example

  use mpi
  use amrex_base_module
  implicit none
  
  integer :: ierr, nproc, rank, color, comm
  
  call MPI_Init(ierr)
  call MPI_Comm_size(MPI_COMM_WORLD, nproc, ierr)
  call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
  
  ! This works
  !call amrex_init(MPI_COMM_WORLD)
  !call amrex_finalize()
  
  ! But this doesn't work
  color = modulo(rank,2)
  call MPI_Comm_split(MPI_COMM_WORLD, color, rank, comm, ierr)
  call amrex_init(comm)
  call amrex_finalize()
  
  call MPI_Finalize(ierr)

end program
```

**Comment by WeiqunZhang** [comment]
Which MPI implementation are you using? Which version?  I can reproduce the error with openmpi 1.10.2, but it runs fine with mpich 3.0.4.  The problem seems to be that `MPI_Comm_get_attr(m_comm, MPI_TAG_UB, ...)` failed.  (The segfault is amrex's fault after the failure of MPI_Comm_get_attr.)

**Comment by nncarlson** [comment]
Interesting.  I'm using openmpi 2.1.3 for both the C and Fortran examples.  I'll try the latest openmpi 3.1 and report back.

**Comment by WeiqunZhang** [comment]
It looks like Open MPI has a bug.  `MPI_Comm_get_attr` fails for subcommunicators in both C and Fortran.

```
program main

  use mpi
  implicit none

  integer :: ierr, rank, color, comm, rank2
  integer(kind=MPI_ADDRESS_KIND) :: attrval
  logical :: flag

  call MPI_Init(ierr)

  call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierr)
  call MPI_Comm_get_attr(MPI_COMM_WORLD, MPI_TAG_UB, attrval, flag, ierr)
  if (.not.flag) then
     print *, "MPI_COMM_WORLD: rank ", rank, " failed to get MPI_TAG_UB."
  else
     print *, "MPI_COMM_WORLD: rank ", rank, " succeeded to get MPI_TAG_UB."
  end if

  color = modulo(rank,2)
  call MPI_Comm_split(MPI_COMM_WORLD, color, rank, comm, ierr)
  call MPI_Comm_rank(comm, rank2, ierr)
  call MPI_Comm_get_attr(comm, MPI_TAG_UB, attrval, flag, ierr)
  if (.not.flag) then
     print *, "Subcommunicator ", color, " rank ", rank2, " failed to get MPI_T\
AG_UB."
  else
     print *, "Subcommunicator ", color, " rank ", rank2, " succeeded to get MP\
I_TAG_UB."
  end if

  call MPI_Finalize(ierr)

end program main
```

```
#include <stdio.h>
#include <mpi.h>

int main(int argc, char** argv)
{
    MPI_Init(&argc, &argv);

    int rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    void* p; int flag;
    MPI_Comm_get_attr(MPI_COMM_WORLD, MPI_TAG_UB, &p, &flag);
    if (!flag) {
        printf("MPI_COMM_WORLD: rank %d failed to get MPI_TAG_UB\n", rank);
    } else {
        printf("MPI_COMM_WORLD: rank %d succeeded to get MPI_TAG_UB\n", rank);
    }

    int color = rank%2;
    MPI_Comm comm;
    MPI_Comm_split(MPI_COMM_WORLD, color, rank, &comm);
    int rank2;
    MPI_Comm_rank(comm, &rank2);
    MPI_Comm_get_attr(comm, MPI_TAG_UB, &p, &flag);
    if (!flag) {
        printf("Subcommunicator %d rank %d failed to get MPI_TAG_UB\n", color, \
rank2);
    } else {
        printf("Subcommunicator %d rank %d succeeded to get MPI_TAG_UB\n", colo\
r, rank2);
    }

    MPI_Finalize();
}
```

**Comment by WeiqunZhang** [comment]
I asked if this behavior is expected on Open MPI users mailing list. (https://www.mail-archive.com/users@lists.open-mpi.org/msg32491.html)  They pointed me to MPI standard 3.1 section 8.1.2.  Here is an unofficial html page to the section, https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node210.htm#Node210.  Apparently the standard only requires `MPI_TAG_UB` in `MPI_COMM_WORLD`, even though `MPI_Comm_get_attr` takes an `MPI_Comm` argument.  Anyway, I updated the development branch of amrex and `amrex::Initialize` with a subcommunicator should work with Open MPI now.

**Comment by nncarlson** [comment]
Thanks @WeiqunZhang! It is working for me now.
