### ISSUE TITLE
amrex::Distribute() segfaults when compiled with Cray compiler and using > 1 MPI process

### ISSUE THREAD

**Issue by bcfriesen** [AMReX-Codes/amrex#280]
When compiled with the Cray compiler (CCE), all applications which use the `Amr` object segfault in the `amrex::Distribute()` function:
```
friesen@nid00393:~/amrex/Tutorials/Amr/Advection_AmrLevel/Exec/UniformVelocity> srun -n 2 -c 4 --cpu_bind=cores ./main3d.cray.mic-knl.MPI.ex inputs
Successfully read inputs file ...
Successfully read inputs file ...
Starting to call amrex_probinit ...
Successfully run amrex_probinit
Application 40001000515 is crashing. ATP analysis proceeding...

ATP Stack walkback for Rank 1 starting:
  _start@start.S:118
  __libc_start_main@0x2aaab2b526d4
  main@main.cpp:48
  amrex::Amr::init(double, double)@AMReX_Amr.cpp:1105
  amrex::Amr::initialInit(double, double, amrex::BoxArray const*, amrex::Vector<int, std::allocator<int> > const*)@AMReX_Amr.cpp:1218
  amrex::Amr::InitializeInit(double, double, amrex::BoxArray const*, amrex::Vector<int, std::allocator<int> > const*)@AMReX_Amr.cpp:1256
  amrex::Amr::defBaseLevel(double, amrex::BoxArray const*, amrex::Vector<int, std::allocator<int> > const*)@AMReX_Amr.cpp:2300
  amrex::DistributionMapping::DistributionMapping(amrex::BoxArray const&, int)@AMReX_DistributionMapping.cpp:354
  amrex::DistributionMapping::SFCProcessorMap(amrex::BoxArray const&, int)@AMReX_DistributionMapping.cpp:1173
  amrex::DistributionMapping::SFCProcessorMapDoIt(amrex::BoxArray const&, std::vector<long, std::allocator<long> > const&, int, int, bool)@AMReX_DistributionMapping.cpp:1025
  _ZN27_INTERNAL_b7fec3ab_0f7d3ae85amrex10DistributeERKSt6vectorINS0_29_GLOBAL__N__b7fec3ab_0f7d3ae88SFCTokenESaIS3_EEidRS1_IS1_IiSaIiEESaIS9_EEi$$CFE_id_b7fec3ab_0f7d3ae8@AMReX_DistributionMapping.cpp:929
  [empty]@0x0
ATP Stack walkback for Rank 1 done
Process died with signal 11: 'Segmentation fault'
```
Line 929 of `AMReX_DistributionMapping.cpp` is this:

```
vol += tokens[K].m_vol;
```

The crash does *not* occur if any of the following are true:
 - print `vol` immediately before line 929, e.g., `amrex::Print() << vol << std::endl;`
 - run with 1 MPI process
 - compile with DEBUG=TRUE
 - compiles with Intel or GCC (any optimization level)

It is possible that this is a bug in the Cray compiler, but I would first like to know if there is anything obviously wrong with `amrex::Distribute()`.

To reproduce with the `Amr/Advection_AmrLevel/Exec/UniformVelocity` tutorial, use commit 8516211a5 and compile with `COMP=cray USE_MPI=TRUE USE_OMP=FALSE`, and use the `inputs` file.

**Comment by maxpkatz** [comment]
I reproduce this using CCE 8.6.4 on Titan with the current tip of development.

**Comment by bcfriesen** [comment]
This is the first bad commit:

```
commit 65a6e8ded89fd357db1fa906917ffacd962673c2
Author: Weiqun Zhang <weiqunzhang@lbl.gov>
Date:   Wed Jun 20 09:52:11 2018 -0700

    add an argument to makeSFC to limit the maximal number of boxes a process can get
```

**Comment by WeiqunZhang** [comment]
I think this is probably a cray bug.  I just pushed a commit that seems to make it happy.

    --- a/Src/Base/AMReX_DistributionMapping.cpp
    +++ b/Src/Base/AMReX_DistributionMapping.cpp
    @@ -912,6 +912,12 @@ Distribute (const std::vector<SFCToken>&     tokens,
                 int                              nmax = std::numeric_limits<int>::max())
    
     {
    +#ifdef _CRAYC
    +    // Without this, we get segfault with Cray.
    +    std::stringstream ss;
    +    amrex::Print(ss) << nmax << std::endl;
    +#endif
    +
         BL_ASSERT(static_cast<int>(v.size()) == nprocs);
    
         int  K        = 0;

**Comment by maxpkatz** [comment]
Isn't it incorrect to have the default value in the function definition as well as the function declaration?

**Comment by maxpkatz** [comment]
Or maybe there's no separate declaration here? Sorry, didn't look too closely.

**Comment by bcfriesen** [comment]
Thanks @WeiqunZhang, your patch avoids the crash. I'll submit this bug to Cray.

**Comment by WeiqunZhang** [comment]
It is OK to have default argument in function definitions.   Especially for this case that there is no declaration for file scope static function, function definition is the only place for default argument.

https://stackoverflow.com/questions/2842928/default-value-of-function-parameter

**Comment by bcfriesen** [comment]
Oops, sorry, your fix did *not* work; the `stringstream` thing needs to go inside the `for ( int TSZ ...` loop for it to work.

**Comment by WeiqunZhang** [comment]
I just removed the `nmax` argument.  Let me know if there are still problems with cray.

**Comment by bcfriesen** [comment]
This works. I submitted the bug report to Cray anyway.
