### ISSUE TITLE
InterpFromCoarseLevel no longer works for face data

### ISSUE THREAD

**Issue by maximumcats** [AMReX-Codes/amrex#2824]
[InterpFromCoarseLevel](https://github.com/AMReX-Codes/amrex/blob/22.06/Src/AmrCore/AMReX_FillPatchUtil_I.H#L935-L946) calls into `FillPatchInterp`, which in turn calls the interpolater's `interp` method, but #2539 renamed the method for face data to be `interp_face` rather than `interp`; the `interp` method now errors out with the `FaceLinear` interpolater. So to restore this functionality the corresponding call in `InterpFromCoarseLevel` needs to be made conditionally correct for that interpolater (or we could have FaceLinear's `interp` method be functional again).

**Comment by maximumcats** [comment]
Note for context: Castro is using `InterpFromCoarseLevel` on face data for [interpolating the gradient of the gravitational potential](https://github.com/AMReX-Astro/Castro/blob/22.06/Source/gravity/Gravity.cpp#L801-L814) to fine levels in certain contexts.

**Comment by maximumcats** [comment]
A test case that uses this functionality in Castro, and that can be used for regression testing, would be to use `Castro/Exec/gravity_tests/DustCollapse` compiled with `make DIM=2` and executed with `mpirun -np 4 ./Castro2d.gnu.MPI.ex inputs_2d_poisson_regtest gravity.max_solve_level=1`. (This last parameter tells the code to interpolate phi and grad_phi on level 2 rather than to solve the Poisson equation.) Release 22.01 of Castro and AMReX could be used to generate the benchmark plotfile (this test runs for 20 timesteps and should be fairly quick).

**Comment by cgilet** [comment]
@maxpkatz Would it matter for Castro whether this is implemented with one kernel launch vs two?

**Comment by maximumcats** [comment]
> @maxpkatz Would it matter for Castro whether this is implemented with one kernel launch vs two?

No. Go for whatever seems easiest to implement :-)
