### ISSUE TITLE
Intel compiler produces NaNs using physical BCs with Advection_AmrCore 

### ISSUE THREAD

**Issue by rhouim** [AMReX-Codes/amrex#285]
The Intel compiler produces NaNs when physical BCs are used with the cell_cons_interp interpolater and non-periodic domains with the Advection_AmrCore tutorial. The Intel compiler will produce correct results if the piecewise constant interpolation is used in the FillPatch routines (pc_interp) is used.The GNU compiler works fine and produces correct results.  We have not checked other compilers.

The steps to replicate this are:
1:   Switch to first-order extrapolation by commenting lines 47, 48 and uncommenting lines 52, 53 in AmrCoreAdv.cpp
2: Turn off periodic BCs in inputs file.
3: Compile with Intel and run

I have verified this on the Intel 17.0.4, 18.0.1, and 18.0.3. The occurs when the tutorial is compiled in debug or production mode, with or without OpenMP, and with or without MPI, and occurs in 2D and 3D.  I also just verified and checked that this issue occurs with latest development branch. 

The above is a minimal working example.  The same issue occurs with our in-house code based on AMReX AmrCore. We did some poking around with our code and found that:

1: The NaNs start at coarse-fine box edges/faces at physical domain boundaries.
2: The problem seems to be with the FillPatch routines. We initialized the solution, immediately called FillPatch, and then wrote a plot file. (Note: we include the ghost cells on all the levels in our conserved variable multifabs.) Plot variables that require a gradient (vorticity, schlieren, etc.) are fine everywhere except for grid points that (in 2D) are at the corner of the finer level at coarse-fine box edges along physical boundaries.  
3: This occurs regardless of the BC (reflect even, reflect odd, ext_dir (set to fill with zeros)) etc. 

We see a pretty large performance benefit of using Intel over the GNU compilers for our application, so our current work around is to use pc_interp.

**Comment by WeiqunZhang** [comment]
Thanks for your excellent bug report that allows us easily reproduce the error.  This is an AMReX bug in `PhysBCFunct`.  I believe it is now fixed in the latest development branch.  Note that this bug did not affect `AmrLevel` or Fortran interface based codes.

**Comment by rhouim** [comment]
Thanks for fixing this! I just verified that this issue is solved on our own codes and with the tutorial.
