### ISSUE TITLE
Return status change for hipDeviceSetSharedMemConfig

### ISSUE THREAD

**Issue by afanfa** [AMReX-Codes/amrex#2883]
Hello all,
AMD devices do not support shared cache banking (https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP_API/Device-management.html#hipdevicesetsharedmemconfig) and so hipDeviceSetSharedMemConfig has a dummy implementation for AMD platforms.
In the past hipDeviceSetSharedMemConfig was always returning hipSuccess, which gives wrong information to user as it does not do any effect on AMD. Recently hipDeviceSetSharedMemConfig has been modified to always return hipErrorNotSupported and this causes all unit tests to fail.
Could you please adjust your code accordingly? Here are some options:

Change in AMReX's Device::initialize_gpu() code to either:
Not to use API hipDeviceSetSharedMemConfig (as it is not supported), or
Not to abort when hipDeviceSetSharedMemConfig returns hipErrorNotSupported

Thanks.

**Comment by WeiqunZhang** [comment]
Thanks for reporting the issue!
