### ISSUE TITLE
Blocking factor divisibility 

### ISSUE THREAD

**Issue by mehdivahab** [AMReX-Codes/amrex#289]
Why is the domain size in all directions checked against the blocking factor in the first dimension? Shouldn't the domain size in each direction be checked against blocking factor in the same dimension?

From "amrex/Src/Amr/AMReX_Amr.cpp" 
```
    // Check that domain size is a multiple of blocking_factor[0].
    //
    for (int i = 0; i < AMREX_SPACEDIM; i++)
    {
        int len = domain.length(i);
        if (len%blocking_factor[0][i] != 0)
            amrex::Error("domain size not divisible by blocking_factor");
    }
```

**Comment by drummerdoc** [comment]
[0] is level, not dimension.
