### ISSUE TITLE
GPU test cases problem with windows subsystem of linux (WSL)

### ISSUE THREAD

**Issue by FR13ndSDP** [AMReX-Codes/amrex#2892]
- OS: Windows 11 21H2
- WSL: Ubuntu 20.04 LTS
- GPU: RTX 3080 10GB

Issue: CUDA toolkits are properly installed on WSL . Running test cases like `Tests/GPU/RandomNumberGeneration` will throw an error 
> amrex::Abort::0::CUDA error 2 in file ../../..//Src/Base/AMReX_Arena.cpp line 166: out of memory !!!
SIGABRT"

I tried to modify AMReX_Arena.cpp line 166 by changing `cudaMallocManaged` to `cudaMalloc`, it seems worked for this case and 3/4 
of the device memory was allocated. **But** running `Tests/GPU/CNS/Exec/RT` at step about 1100 will suddenly crash. Windows system crashed without vedio signal output and I only had to reboot. This is not accidental but every time it will crash.

**Comment by WeiqunZhang** [comment]
There is a runtime parameter for switching to non-managed memory, `amrex.the_arena_is_managed=0`.  In addition to that, you can also use `amrex.the_arena_init_size=0` to see if it solves the crash issue.

**Comment by FR13ndSDP** [comment]
After setting these two parameters to 0, I saw the device memory allocated in `Tests/GPU/RandomNumberGeneration` is 51 MB. The crash issue still happen. I know my situation is somewhat special and this problem is most likely WSL related, I still wish you can look into this problem.

**Comment by FR13ndSDP** [comment]
I've just found that this may have to do with my hardware because running CUDA demo suite `nbody` will cause the same issue. While on another machine with exactly the same hardware configuration, test code works fine.
