### ISSUE TITLE
Double counted in cells at boundary

### ISSUE THREAD

**Issue by FoamerSv** [AMReX-Codes/amrex#2906]
I noticed that in TagBoxArray::local_collate_cpu, it will transfer data from Array4 arr(i,j,k) to Vector v. Simply to say, convert 3D vector to 1D vector. The original function has defection. Since the iteration goes through all the fabbox of TagBoxArray this, the value at the boundary of each box may count twice. For example, the cell[-1] in box[1] has a global index 5, and arr(5,0,0)=TagBox::BUF. The cell is a ghost cell in Array4 arr. However in the neighbour box[2], the cell[7] also has a global index 5, and it is a valid cell here. They are the same cell in physics but belonging to different boxes. And it's possible that arr(5,0,0)=TagBox::CLEAR or arr(5,0,0)=TagBox::BUF. The latter could count twice during the data transfer. And it could result a efficient > 1 when calculating grid eff.

**Comment by WeiqunZhang** [comment]
Have you noticed any issues in your runs?  Note that in AMReX_AmrMesh.cpp, there is a call to `tags.mapPeriodicRemoveDuplicates` that removes duplicates.  It's possible that that function has a bug, but otherwise it's not supposed to have duplicates when `collate` is called.

**Comment by FoamerSv** [comment]
Ah I didnt realize it! I have tested it and the problem is solved.
