### ISSUE TITLE
MPI Fork Warning

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#292]
Can we be certain that this isn't an issue that would cause an application to hang?
```
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.
```
I see this warning sometimes with OpenMPI (3.1.1) when our PeleC application fails at certain times and I've seen our application hang until the walltime limit kills the job on two different machines now, but I am not able to faithfully reproduce the hang yet which is what I'm currently investigating and why this warning concerns me. Our application does its best at hanging after a segfault appears to occur when running our largest cases on ~4000 Cori KNL nodes, but difficult to reproduce otherwise 🙂 .

Also, I don't seem to be able to pinpoint exactly where AMReX forks within a rank, but I see code involving fork/join, so that would be helpful if someone could point me to that as well, or maybe it's possible that I could disable the forking for testing purposes?

**Comment by WeiqunZhang** [comment]
AMReX doesn't explicitly make any calls to `fork`.  (The fork/join model in AMReX is a high-level concept, not low level system calls.)   But some glibc functions AMReX calls in the signal handler may invoke `fork`.

The signal handler in AMReX is not Async-Signal-Safe.  You can disable signal handling of AMReX by `ParmParse` parameter `amrex.signal_handling=0`.

**Comment by WeiqunZhang** [comment]
Forgot to mention that I did see this kind of hang before due to signal handling.  Disabling signal handling fixes the hang (but not the original problem of course).

**Comment by jrood-nrel** [comment]
Great, thanks! I will try this. As long as I can get the hanging to stop so that I don't waste CPU hours, that will be extremely helpful. I will close this unless I have any further information or problems regarding this.
