### ISSUE TITLE
Can't compile on OSX Monterey 12.5.1

### ISSUE THREAD

**Issue by dunhamsj** [AMReX-Codes/amrex#2938]
Hi all, I upgraded my mac to Monterey and can no longer compile amrex. I'm using gcc 12.2.0 and mpich, both installed via homebrew. I attached the output from `make` and also my compiler versions.
[m.txt](https://github.com/AMReX-Codes/amrex/files/9496486/m.txt)
<img width="696" alt="Screen Shot 2022-09-06 at 07 33 39" src="https://user-images.githubusercontent.com/9784969/188625839-496b0a02-5036-49fb-8ae7-f48538e8028f.png">

**Comment by drummerdoc** [comment]
What happens is you try with COMP=llvm?

**Comment by dunhamsj** [comment]
Ah, I had commented out the line `COMP = gnu` before because it didn't seem to do anything. Putting that back in I can almost compile, I think this new issue is on my end though. Thanks!
