### ISSUE TITLE
EB reflux for only certain components of a MultiFab

### ISSUE THREAD

**Issue by ashwathsv** [AMReX-Codes/amrex#2975]
HI all,

I am using a solver based on the Tests/EB_CNS case and need an option to specify the number of components for the Reflux function. My state variable also stores some variables that do not need refluxing at the end of AMR. The current refluxing function (in CNS::post_timestep) does not have an argument to specify the number of components and is of the following form:

// The Reflux function is defined in Src/EB/AMReX_EBFluxRegister.cpp
fine_level.flux_reg.Reflux(S_crse, *volfrac, S_fine, *fine_level.volfrac); 

What would be the best way to explicitly specify the number of components for refluxing? I presume there is such a function for the non-EB FluxRegister but not for the EB case.

Thanks in advance.

**Comment by WeiqunZhang** [comment]
You can work around the issue by using alias FArrayBox and alias MultiFab.  For example,
```
FArrayBox tmpfab(fab, amrex::make_alias, start_component, numcomps);
MultiFab tmpmf(mf, amrex::make_alias, start_component, numcomps);
```
These operations are cheap.
