### ISSUE TITLE
InterpHooks are incompatible between FillPatcher class and FillPatch function

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#2989]
The FillPatcher class requires PreInterpHook and PostInterpHook to have the signature:
`void InterpHook(amrex::MultiFab &mf, int scomp, int ncomp);`

whereas the FillPatch function requires the interpolation hooks to have the signature:
`void InterpHook(amrex::FArrayBox &fab, const amrex::Box& box, int scomp, int ncomp);`

This means that different interp hooks have to be used for each way of doing the fillpatch, which doesn't really make sense. The MultiFab version should be more efficient, since we can use the MultiFab ParallelFor, so it would be ideal if we can change the signature used in `AMReX_FillPatchUtil_I.H:548` and similar.

Problem appears here: https://github.com/BenWibking/quokka/pull/133

**Comment by WeiqunZhang** [comment]
I don't think we should break backward compatibility.  But we could support both by detecting the function signature at compile time.

**Comment by BenWibking** [comment]
> I don't think we should break backward compatibility. But we could support both by detecting the function signature at compile time.

That works just as well for me.
