### ISSUE TITLE
Current EB support

### ISSUE THREAD

**Issue by rmrsk** [AMReX-Codes/amrex#299]
What is the current status for EB functionality? I have a Chombo code that I'd like to port, but I'm dependent on an EB maturity close to Chombo's. Multigrid with EB is particularly important to us. Is there an ETA for when one can expect to start writing elliptic operators? 

Also, there are things we'd like to see improve vis-a-vis Chombo, for example aggressive irregular stencil optimizations for all the basic EB operations, faster EBIS generation, and sparse IO formats that get rid of the dense EB data in output files.

**Comment by asalmgren** [comment]
Core EB functionality is up and running.   Multigrid solvers for
cell-centered data in EB geometries are also newly up and working.  We also
have a newer much faster form of geometry generation.

What is the functionality that you need specifically?  How large is the
code you want to port?

**Comment by rmrsk** [comment]
We need support for variable and discontinuous coefficient Helmholtz equations with EB, so an operator ala ebconductivityop is what we're after. In Chombo we wrap two of these in another operator that matches two EBIS domains so that Dirichlet, Neumann, or "matching" can be applied to individual irregular cells. We use this for electrostatic field calculations with electrodes and dielectrics, and also for diffusion radiative transport. 

Support for scalar advection equation is also something that we need - we've been using EBAdvectPatchIntegrator for the high order stuff, and have some internal code for lower order. Don't know what AMReX offers here...

We sometimes use polygonal tessellations for geometry generation, which is why we want faster EB generation. Ideally, we'd like to see that BaseIF is complemented with optional voxels that inform where to generate graphs. 

The code is about 60k lines, but a lot of that is interface. The actual core consist of scalar advection, diffusion, and elliptic solves.

**Comment by drummerdoc** [comment]
AMReX has a different interface than you'd be expecting, and the way you get the advection stuff working would be more like copying code from some other "app" that has similar needs. But much of what you describe is definitely available.  For advection, you can look at the EB tutorials, such as CNS.  

The main thing missing compared to Chombo, I think, is the multi-valued cell stuff.  that has not been a priority for us.

**Comment by drummerdoc** [comment]
Also, in AMReX for performance design reasons we would never make an operator that can be applied to individual cells.  So, that part of what you do might have to be rethought a bit.

Finally, I believe the conductivity operator in Chombo is what AMReX would call an ABec Laplacian, named (for historical reasons, mostly) to indicate that the transport coefficients (B) are face (edge) centered.

**Comment by rmrsk** [comment]
I think you misread my reply, we're not applying the operator to individual cells, but segregate between wall and interface boundary conditions in the MG relaxation stage. 

Are there benchmarks for the (newly developed?) cell centered elliptic solvers against e.g. Chombo or other solvers? 

Also, where do I find them? :)
