### ISSUE TITLE
ParReduce return value is uninitialized when there are no boxes

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#3000]
I am refactoring my code to use ParReduce to compute the CFL timestep like this:

```
amrex::Real max_signal =
 amrex::ParReduce(amrex::TypeList<amrex::ReduceOpMin>{}, amrex::TypeList<amrex::Real>{},
                          cons_mf, amrex::IntVect(0), // no ghost cells
      [=] AMREX_GPU_DEVICE (int bx, int i, int j, int k)
          noexcept -> amrex::GpuTuple<amrex::Real>
      {
        const auto rho = cons[bx](i, j, k, HydroSystem<problem_t>::density_index);
        const auto px  = cons[bx](i, j, k, HydroSystem<problem_t>::x1Momentum_index);
        const auto py  = cons[bx](i, j, k, HydroSystem<problem_t>::x2Momentum_index);
        const auto pz  = cons[bx](i, j, k, HydroSystem<problem_t>::x3Momentum_index);
        const auto kinetic_energy = (px*px + py*py + pz*pz) / (2.0*rho);
        const double abs_vel = std::sqrt(2.0 * kinetic_energy / rho);
        double cs = NAN;

        if constexpr (is_eos_isothermal()) {
          cs = cs_iso_;
        } else {
          const auto Etot = cons[bx](i, j, k, HydroSystem<problem_t>::energy_index);
          const auto Eint = Etot - kinetic_energy;
          const auto P = Eint * (HydroSystem<problem_t>::gamma_ - 1.0);
          cs = std::sqrt(HydroSystem<problem_t>::gamma_ * P / rho);
        }
        return { cs + abs_vel };
      });
amrex::ParallelDescriptor::ReduceRealMax(max_signal);
```

This works if there are boxes on every level on every rank, but if some levels have ranks without boxes, the result is wrong (it usually returns the uninitialized values returned by ParReduce on those ranks).

**Comment by WeiqunZhang** [comment]
Thanks for reporting this!  We introduced a bug back in April 2021.

**Comment by WeiqunZhang** [comment]
Are you sure there is a bug?  I cannot reproduce it.  In your case, if a process has no boxes, the return value of `ParReduce` is `std::numeric_limits<Real>::max()` because the operator is `Min`.  Then `amrex::ParallelDescriptor::ReduceRealMax` will produce the correct final result.  What else could `ParReduce` return?

**Comment by WeiqunZhang** [comment]
I think your issue might be `amrex::ReduceOpMin`.  Should it be `amrex::ReduceOpMax` considering `amrex::ParallelDescriptor::ReduceRealMax` is called afterwards and the variable name contains `max`?

**Comment by BenWibking** [comment]
> I think your issue might be `amrex::ReduceOpMin`. Should it be `amrex::ReduceOpMax` considering `amrex::ParallelDescriptor::ReduceRealMax` is called afterwards and the variable name contains `max`?

Yes, you are correct. It is a typo.

**Comment by BenWibking** [comment]
@WeiqunZhang would `ReduceRealMax` still work if `ParReduce` instead returned `NaN` on ranks with no boxes? The current behavior is semantically confusing.

**Comment by zingale** [comment]
jumping in on this -- would we expect ParReduce to give roundoff diffs compared to the old way?  When I switched our timestep loops in Castro to this, I got diffs:
https://github.com/AMReX-Astro/Castro/pull/2273

**Comment by zingale** [comment]
I was wondering if maybe it is because of TilingIfNotGpu is not part of ParReduce?

**Comment by zingale** [comment]
I verified that I still see diffs with the latest AMReX

**Comment by WeiqunZhang** [comment]
@zingale I will follow up in  https://github.com/AMReX-Astro/Castro/pull/2273.

**Comment by WeiqunZhang** [comment]
@BenWibking I don't think it's a good idea to return `NaN` on processes with no boxes.  First, one would then have to test the return value before calling MPI reduce.  Second, the function template can be used for non floating point types too.  There is no `NaN` for integral types or structs.  Third, `NaN` might come from the original data used for reduction.  So from the return value, we cannot determine whether the `NaN` is a result of the data or distribution of the data.

**Comment by BenWibking** [comment]
Would it make sense to return an empty tuple, e.g. `std::tuple()`, on processes with no boxes? This would make use of `ParallelDescriptor::ReduceRealMax` more complicated, though.

**Comment by WeiqunZhang** [comment]
Empty tuple and non-empty tuple are different types.  So we would have to use type erasure to wrap the two types.  That seems to make things unnecessarily complicated.
