### ISSUE TITLE
Cannot build AMReX 20.11 with PETSc (?)

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#3009]
I see this build error:
```C++
COMPILING CarpetX/PDESolvers/src/solve.cxx
In file included from /Users/eschnett/Cactus/view/include/AMReX_FabArrayBase.H:8,
                 from /Users/eschnett/Cactus/view/include/AMReX_MFIter.H:5,
                 from /Users/eschnett/Cactus/view/include/AMReX_Reduce.H:8,
                 from /Users/eschnett/Cactus/view/include/AMReX_BaseFab.H:20,
                 from /Users/eschnett/Cactus/view/include/AMReX_FArrayBox.H:7,
                 from /Users/eschnett/Cactus/arrangements/CarpetX/Loop/src/loop.hxx:4,
                 from /Users/eschnett/Cactus/configs/sim-debug/bindings/include/loop.hxx:4,
                 from /Users/eschnett/Cactus/arrangements/CarpetX/PDESolvers/src/../../CarpetX/src/driver.hxx:4,
                 from /Users/eschnett/Cactus/arrangements/CarpetX/PDESolvers/src/solve.cxx:4:
/Users/eschnett/Cactus/view/include/AMReX_ParallelReduce.H:131:78: error: macro "MPI_Allreduce" passed 7 arguments, but takes just 6
  131 |                       ParallelDescriptor::Mpi_op<T,amrex::Greater<T>>(), comm);
      |                                                                              ^
```

The complete statement in this line is
```C++
        MPI_Allreduce(&tmp, &vi, 1,
                      ParallelDescriptor::Mpi_typemap<T>::type(),
                      ParallelDescriptor::Mpi_op<T,amrex::Greater<T>>(), comm);
```

Clearly, this function call has 6 arguments, as it should.

I think the problem is the following. The caller uses PETSc, and includes various PETSc include files as well. PETSc contains this line
```C++
    #define MPI_Allreduce(sendbuf, recvbuf, count, datatype, op, comm) (petsc_allreduce_ct += PetscMPIParallelComm((comm)), MPI_Allreduce((sendbuf), (recvbuf), (count), (datatype), (op), (comm)))
```
in its header file `petsclog.h`. This turns `MPI_Allreduce` into a macro (sneaky!), and the C++ preprocessor is then getting confused by the comma in the template argument to `Mpi_op`.

Obviously, PETSc should not be doing this. In the spirit of defensive programming, do you nonetheless want to add parentheses around this argument, as in `(ParallelDescriptor::Mpi_op<T,amrex::Greater<T>>())`?

**Comment by WeiqunZhang** [comment]
I thought it was fixed in https://github.com/AMReX-Codes/amrex/pull/3005.  Are you including PETSc headers in Cactus?  Yes, I guess we should fix it in a different way as you have suggested instead.  Anyway we have trying to be very careful not to include any PETSc headers in our headers.
