### ISSUE TITLE
builds with Fortran code fail on arm64

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#3017]
I've tried to build `amrex/Tests/FortranInterface/Advection_F/Exec/SingleVortex` with the GNUMakefile on my M1 MacBook. It fails at the final link step with the error:

```
/usr/bin/ld: cannot find -lquadmath: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [../../../../../Tools/GNUMake/Make.rules:56: main2d.gnu.MPI.ex] Error 1
```

This prevents, e.g., Castro from building on recent-model MacBooks (https://github.com/AMReX-Astro/Castro/issues/2293).

System details:
```
[benwibking@lima-fedora SingleVortex]$ uname -a
Linux lima-fedora 5.19.16-301.fc37.aarch64 #1 SMP PREEMPT_DYNAMIC Fri Oct 21 15:22:13 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by WeiqunZhang** [comment]
If you remove `-lquadmath` from `amrex/Toold/GNUMake/comps/gnu.mak`, does it compile?

At one point, gfortran started to require libquadmath.  Maybe that's not the case on Fedora.  On my Unbuntu (20 and 22), I got something like
```
$ ldd `gfortran --print-file-name=libgfortran.so`
	linux-vdso.so.1 (0x00007ffd7b761000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fa229de2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa229cfb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa229cdb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa229ab3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa22a11c000)
```
You can see `libquadmath` there.  What do you see on your fedora?

**Comment by BenWibking** [comment]
Yes, it builds and runs successfully if I remove `-lquadmath`.

I get this:
```
[benwibking@lima-fedora benwibking]$ ldd `gfortran --print-file-name=libgfortran.so`
	linux-vdso.so.1 (0x0000ffff8e142000)
	libm.so.6 => /lib64/libm.so.6 (0x0000ffff8ded0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000ffff8de90000)
	libc.so.6 => /lib64/libc.so.6 (0x0000ffff8dcd0000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff8e105000)
```

**Comment by BenWibking** [comment]
The issue appears to be that `libquadmath` does not support arm: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016

**Comment by WeiqunZhang** [comment]
Thanks for the information.  We should update our make file.

**Comment by WeiqunZhang** [comment]
I think #3018 should fix the issue.
