### ISSUE TITLE
Interfacing using PETSc 

### ISSUE THREAD

**Issue by karthichockalingam** [AMReX-Codes/amrex#3029]
Hello,

I am new to AMReX. I would like to implement a `finite element` scheme in AMReX and solve it implicitly using PETSc (without AMR in the first instance). I copied the relevant pieces of code from AMReX_PETSc.cpp. Most of my questions are related to C++ -- I hope to ask the right questions.

Below `BaseFab<Real>` is created

```
    BaseFab<Real> mat_aos_fab, mat_vec_fab;
    mat_aos_fab.resize(bx,max_stencil_size);
```

Q(1)`tmpmatfab` is of type `BaseFab<GpuArray<Real,stencil_size> >` so the data size must be stencil_size times the number of nodes or cells depending on the box type?

```
                BaseFab<GpuArray<Real,stencil_size> > tmpmatfab
                    (bx, 1, (GpuArray<Real,stencil_size>*)mat_aos_fab.dataPtr());
```

Q(2) Is the `stencil_size=5`? Is the total number of `nodes/cells = nrows`  in `A`?

Q(3) Why is it necessary to pass `mat_aos_fab.dataPtr()` to the constructor of  `tmpmatfab`? Why can't we work with `tmpmatfab` and directly pass it to `mat_in` as `Real const* mat_in = tmpmatfab.dataPtr()`?

Q(4) Below I believe `sten` is used to populate `tmpmatfab` at every index `i`, `j` and `k`?
```
              amrex::fill(tmpmatfab,
                [=] AMREX_GPU_HOST_DEVICE (GpuArray<Real,stencil_size>& sten,
                                           int i, int j, int k)
                {
                    habec_ijmat(sten, ncols_a, diaginvfab, i, j, k, cid_a,
                                sa, afab, sb, dx, bfabs, bctype, bcl, bho,
                                Array4<int const>());
                });
```

Below `mat_aos_fab.dataPtr()` is passed to `mat_in` as a raw pointer 

```
            PetscInt nelems = nrows * max_stencil_size;
            PetscInt const* cols_in = cols_aos_fab.dataPtr();
            Real const* mat_in = mat_aos_fab.dataPtr();
            PetscInt* cols;
            Real* mat;
```

Q(5) Is the size of `mat_in[]` equal to `nelems = nrows * max_stencil_size`? In other words is `mat_in` the pointer to first element of an array of size `nelems`?

Q(6) At the end of the below loop is `m` equal to `nrows`? 
```
                cols = const_cast<PetscInt*>(cols_in);
                mat = const_cast<Real*>(mat_in);
                PetscInt m = 0;
                for (PetscInt ielem = 0; ielem < nelems; ++ielem) {
                    if (mat_in[ielem] != Real(0.0)) {
                        if (m != ielem) {
                            cols[m] = cols_in[ielem];
                            mat[m] = mat_in[ielem];
                        }
                        ++m;
                    }
                }
```

Q(7) Is `&mat[matid]` a pointer to the first element of the data array to be stored in `A` for each row in `A`?

```
            int matid = 0;
            for (int rit = 0; rit < nrows; ++rit)
            {
                MatSetValues(A, 1, &rows[rit], ncols[rit], &cols[matid], &mat[matid], INSERT_VALUES);
                matid += ncols[rit];
            }
```

Q(8) In my case I don't have a stencil which is inserted for each reach row in  `A`, but an element matrix (elem_mat) of size 4x4 for each cell which assembled/added using `MatSetValues` into `A`. I am hoping to replace `sten` with `elem_mat` ?

I highly appreciate your response.

**Comment by WeiqunZhang** [comment]
I will try to answer a couple of questions at a time.  If it answers your question,  let us know and we can then move on to the next ones.

> Q(1)tmpmatfab is of type BaseFab<GpuArray<Real,stencil_size> > so the data size must be stencil_size times the number of nodes or cells depending on the box type?

                BaseFab<GpuArray<Real,stencil_size> > tmpmatfab
                    (bx, 1, (GpuArray<Real,stencil_size>*)mat_aos_fab.dataPtr());

Yes.

> Q(2) Is the stencil_size=5? Is the total number of nodes/cells = nrows in A?

I assume you are only looking at the non-EB code (i.e., `fabtyp == FabType::regular`).  The code for defining `stencil_size` is `constexpr int stencil_size = 2*AMREX_SPACEDIM+1;`.  So it's 5 for 2D and 7 for 3D.

Yes, the total number of cells is equal to `nrows` if there is no EB.  If you don't care about EB, let us know.  EB makes things more complex, and we can simplify the discussion if we don't need to talk about it.  But if the index type is nodal, it could be greater than `nrows`, because some nodes might exist in multiple boxes. Are your data nodal or cell-centered?

**Comment by karthichockalingam** [comment]
Thank you for your response. 

I am not looking into EB. In finite elements I would loop over every element (which would be cells) in the entire simulation domain . However, the size of the element stiffness matrix would be 4x4. The `four` corresponds to the number of vertices for a given cell, which makes the state variables to live on the nodes. Finally, we assemble the element matrix for every cell into a global system matrix, which would be a square matrix of size equal to the total number of nodes, `N`  in the entire simulation domain. I am aware that PETSc would do the global assembly, though the nodal data might exist in multiple boxes or processes. Since, common nodal data is added together for assembly purposes. For now, I am working without AMR.

In the below image both `i` and `j` would loop from 1 up to 4,  `E` is the total number of cells in the entire domain,  `M`  is four, `K` is the global system matrix of size `N x N` and `l` is the global RHS of size `N x 1`.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/39724615/201179163-4b1b211c-a348-44d4-b331-810194668514.png">

**Comment by WeiqunZhang** [comment]
The PETSc setup you are looking at is for cell data only. We never used PETSc for our nodal solvers.  But you can probably use our HYPRE setup as an example.  See AMReX_HypreNodeLap.cpp and AMReX_MLNodeLaplaican_hypre.cpp.

**Comment by karthichockalingam** [comment]
Thank you, I will look into the above files. It would be great if you have time to answer the questions I posed, though it is implemented for cell data only.

**Comment by WeiqunZhang** [comment]
> Q(3) Why is it necessary to pass mat_aos_fab.dataPtr() to the constructor of tmpmatfab? Why can't we work with tmpmatfab and directly pass it to mat_in as Real const* mat_in = tmpmatfab.dataPtr()?

Yes, we could do it in different ways.  But it's how we did it, because for GPU performance we want to use the `amrex::fill` function that works on BaseFab of GpuArray.  In our GPU kernels, each thread works on one cell.   Because the data is an array of struct, the memory access is not coalesced.  In `amrex::fill`, we use shared memory to make the global memory access coalesced.

**Comment by karthichockalingam** [comment]
Thank you for your response. I am closing the issue.
