### ISSUE TITLE
segfault when using TINY_PROFILE=TRUE and OpenMP

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#3135]
Since yesterday, the combination of TINY_PROFILE=TRUE and OpenMP causes segfaults immediately when Castro is run.  See the tests here:

http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2023-02-08/index.html

**Comment by zingale** [comment]
This seems to be caused by this PR: https://github.com/AMReX-Codes/amrex/pull/3105

**Comment by AlexanderSinn** [comment]
Thanks for reposting. It looks like TinyProfiler is initialized too late, after the first profile is already take in mempool.
