### ISSUE TITLE
Derived quantities from multiple states with varying grid type

### ISSUE THREAD

**Issue by darylbond** [AMReX-Codes/amrex#314]
I have the situation where I am attempting to calculate a derived quantity from multiple face centred grids and the agglomeration of all contributing components into a single array is failing due to the mismatch in grid type. Is there a way to get around this issue or does it require a modification of the offending routine (AmrLevel::derive())?

**Comment by darylbond** [comment]
@drummerdoc That makes sense, and is what I was half expecting to hear. I am only just starting to get a feel for amrex and knowing the design intent of some of the functionality is very useful. In this case my assumption was that the derive function should be able to take whatever data it is pointed at and hand it over to the users function where they can do whatever they like with it. 

I have already done as you suggested with introducing a custom routine into writePlotFile() and so if this change to derive() is not seen as desirable I will close this thread.

**Comment by drummerdoc** [comment]
Yeah.  If the plotfile format is generalized to support all the centerings, then we'll have to address this then.  I guess the underlying mysterious assumption is that the derive functionality was developed primarily to generate plotfile data.  Perhaps it should have named "deriveForPlotfile" instead of derive...

**Comment by asalmgren** [comment]
Note that we use the proposed alternative for plotting particle data on the
grid in plotfiles, for example.

It's more intrusive than just defining in the setup routine but still
pretty easy

For an example take a look at the Nyx code (
https://github.com/AMReX-Astro/Nyx)
