### ISSUE TITLE
FabArray::shift broken on GPU

### ISSUE THREAD

**Issue by timrlaw** [AMReX-Codes/amrex#3145]
Hi,

FabArray::shift seems to be broken for GPU. The reproducer below fails consistently for me on an A100 with a variety of CUDA versions and the latest AMReX 23.02. I've tried to dig into the guts of what is going wrong and it seems to be related to the fused routines that are only used by the GPU version. I think perhaps some cached metadata needs to be updated following the shift but is not? Building in Debug mode shows a great many invalid accesses.

The workaround, as shown, is to copy onto a new multi-fab using an explicit fab-loop (the Copy routine uses a fused approach).

```
#include <AMReX.H>
#include <AMReX_iMultiFab.H>

int
main(int argc, char **argv)
{
    using namespace amrex;

    Initialize(MPI_COMM_WORLD);

    int constexpr N = 128;
    Box b(IntVect(0,0,0), IntVect(N-1,N-1,N-1));
    BoxArray ba(b);
    ba.maxSize(32);

    DistributionMapping dm {ba};

    // Fill a multi-fab with ones, confirm it sums to the right number.
    iMultiFab mf(ba, dm, 1, 0);
    mf.setVal(1);
    AMREX_ASSERT(mf.sum(0) == N*N*N);

    // Build a new multi-fab offset in index space.
    IntVect shift(64,64,64);
    BoxArray ba_shift = ba;
    ba_shift.shift(shift);
    iMultiFab mf_shift(ba_shift, dm, 1, 0);

    // Shift the first multi-fab and copy its contents to the new one.
    // The contents should be unchanged, just located at different indices.
    mf.shift(shift);

#if 1
    // This routine does not (always?) work on GPU. Internally it calls
    // FabArray::Copy which uses a different implementation on GPU. This
    // implementation does not (always?) work after calling shift. The CPU
    // implementation does always work.
    iMultiFab::Copy(mf_shift, mf, 0, 0, 1, 0);
#else
    // This way works on both CPU and GPU
    for (MFIter mfi(mf_shift, TilingIfNotGPU()); mfi.isValid(); ++mfi) {
        auto const &bx = mfi.tilebox();
        auto const &src = mf.array(mfi);
        auto const &dst = mf_shift.array(mfi);

        ParallelFor(bx, mf.nComp(),
                [=] AMREX_GPU_DEVICE(int i, int j, int k, int n)
                {
                    dst(i,j,k,n) = src(i,j,k,n);
                });
    }
#endif

    int sum = mf_shift.sum(0);
    Print() << "sum = " << sum << std::endl;
    if (sum != N*N*N) Abort("The bug happened");

    Finalize();
    return 0;
}
```

**Comment by drummerdoc** [comment]
@WeiqunZhang  Could this be at all associated with the fact that, at least years ago, Fab::shift didn't touch the data but just shifted the underlying box, and did so in the direction opposite to the box::shift function.  This was originally added back when Crutchfield was building BoxPython and his own Mathematica-like notebook interface.  Perhaps the sense of this routine got confused over the years?

**Comment by WeiqunZhang** [comment]
@timrlaw Thanks for reporting the issue and providing a reproducer! 

> I've tried to dig into the guts of what is going wrong and it seems to be related to the fused routines that are only used by the GPU version. I think perhaps some cached metadata needs to be updated following the shift but is not?

I think you are correct.  Will fix it soon.

@drummerdoc Yes, the shift function only shift the metadata without touch the data.  The new fused gpu kernel launch uses cached metadata that needs to be updated after shift.

**Comment by WeiqunZhang** [comment]
@timrlaw  BTW, it's more efficient to shift the MultiFab first and then get a BoxArray from it.  Otherwise mf_shift and mf do not share the metadata.  For example,
```
mf.shift(...);
iMultiFab mf_shift(mf.boxArray(), ...);
```

**Comment by timrlaw** [comment]
Thanks @WeiqunZhang, for the quick fix and the tip :)
