### ISSUE TITLE
The_Pinned_Arena uses a CArena on CPU

### ISSUE THREAD

**Issue by AlexanderSinn** [AMReX-Codes/amrex#3156]
If `AMREX_USE_GPU=FALSE`, then The_Arena, The_Device_Arena and The_Managed_Arena are all BArenas rather than CArenas like on GPU. However, The_Pinned_Arena stays a CArena but returns false when Arena::isPinned() is called. This causes it to share TinyProfiler memory diagnostics with amrex_mempool:
```
Cpu (amrex_mempool) Memory Usage:
---------------------------------------------------------------------------------------------------------------------
Name                            Nalloc  Nfree  AvgMem min  AvgMem avg  AvgMem max  MaxMem min  MaxMem avg  MaxMem max
---------------------------------------------------------------------------------------------------------------------
Hipace::Notify()                   150    150      10 MiB      10 MiB      11 MiB      12 MiB      12 MiB      12 MiB
Hipace::Wait()                     150    150     424 KiB     424 KiB     425 KiB      12 MiB      12 MiB      12 MiB
The_Pinned_Arena::Initialize()       2      2      11   B      12   B      14   B    8192 KiB    8192 KiB    8192 KiB
amrex_mempool_init()                 4      4    7219   B    7222   B    7225   B    8192 KiB    8192 KiB    8192 KiB
Hipace::Evolve()                     2      2     452 KiB     475 KiB     497 KiB     500 KiB     500 KiB     500 KiB
main()                              62     62      15   B      15   B      15   B      48   B      48   B      48   B
---------------------------------------------------------------------------------------------------------------------
```
This is an issue because the underlying map used for profiling relies on the mutex of the CArena to be thread save, but now there are two mutexes for the same map.
The following setup should maybe cause a race condition with AMREX_USE_GPU=FALSE.
```
#pragma omp parallel
{
    BL_PROFILE("Test");
    if (omp_get_thread_num() == 0) {
        // allocate from The_Pinned_Arena
    } else {
        // allocate from amrex_mempool
    } 
}
```

**Comment by WeiqunZhang** [comment]
The issue also exists when `BL_COALESCE_FABS` is defined, because in that case The_Arena is a CArena.

**Comment by WeiqunZhang** [comment]
So there is also a race condition in
```
#pragma omp parallel
{
    BL_PROFILE("Test");
    if (omp_get_thread_num() == 0) {
        // allocate from The_Pinned_Arena
    } else {
        // allocate from The_Arena
    } 
}
```

**Comment by WeiqunZhang** [comment]
Maybe should rename `MemStat::cpu` to `MemStat::cpupool`.  And make the following change
```
--- a/Src/Base/AMReX_CArena.cpp
+++ b/Src/Base/AMReX_CArena.cpp
@@ -47,6 +47,7 @@ CArena::alloc (std::size_t nbytes)
 
     MemStat* stat = nullptr;
 #ifdef AMREX_TINY_PROFILING
+#ifdef AMREX_USE_GPU
     if (isDevice()) {
         stat = TinyProfiler::memory_alloc(nbytes, MemStat::device);
     } else if (isManaged()) {
@@ -56,6 +57,15 @@ CArena::alloc (std::size_t nbytes)
     } else {
         stat = TinyProfiler::memory_alloc(nbytes, MemStat::cpu);
     }
+#else
+    if (The_Arena() == this) {
+        // MemStat::device
+    } else if (The_Pinned_Arena() == this) {
+        // MemStat::pinned
+    } else {
+        // MemStat::cpumempool
+    }
+#endif
 #endif
 
     if (static_cast<Long>(m_used+nbytes) >= arena_info.release_threshold) {
```
However, if one makes their own CArena, it will have race conditions again.

**Comment by WeiqunZhang** [comment]
In fact, in the GPU case, one could break it if one tries hard.  A cpu thread could be used and one could make a CArena that is not The_Arena but still passes `isDevide()`.

So I think maybe we should redo this by only tracking CAreas that are known to us (e.g., The_Arena, The_Device_Arena, etc.).  We need to be aware that there is aliasing.  We could simply ignore the cpu memory pool to make things simple, since we are not tracking CPU memory in BArena anyway.

**Comment by AlexanderSinn** [comment]
I didn’t know amrex supports making additional CArenas. In that case I would suggest to make the map for profiling a member variable of CArena. Since the mutex is also a member variable this would guarantee thread safety. The challenge then becomes collecting and assigning names to every relevant CArena for profiling.

I agree with renaming or removing mempool form the profile. I didn’t know it existed until it showed up in the first profiles I made.

**Comment by WeiqunZhang** [comment]
The mempool stuff was added when we were working on OpenMP in Fortran years ago.  We found that `allocate` inside omp parallel was very slow, and amrex_mempool_alloc solved the issue.

**Comment by AlexanderSinn** [comment]
> I didn’t know amrex supports making additional CArenas. In that case I would suggest to make the map for profiling a member variable of CArena. Since the mutex is also a member variable this would guarantee thread safety. The challenge then becomes collecting and assigning names to every relevant CArena for profiling.

Should I make a PR with this change? If so should some of the function interfaces be added to Arena instead of CArena so it would be easier to add profiling for BArena and PArena in the future?

**Comment by WeiqunZhang** [comment]
Yes to both. Thanks!
