### ISSUE TITLE
I compile the hello.c exapmle file in my own project with cmake file , met the following error.

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#316]
/home/ztdep/Projects/AMReX/build> make -j12
[ 50%] Linking CXX executable amrex
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_add_stringarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:524: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:531: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:531: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:521: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_add_realarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:509: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:509: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:509: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_add_intarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:502: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:502: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:502: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_add_string':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:495: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:495: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:495: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:495: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_add_logical':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:488: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:488: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_add_real':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:475: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:475: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_add_int':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:468: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:468: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_query_stringarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:457: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:457: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_query_realarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:444: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:444: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:446: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:446: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_query_intarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:431: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:431: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:433: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:433: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_query_string':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:413: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:413: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:416: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_query_logical':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:397: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:397: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_query_real':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:387: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:387: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_query_int':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:377: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:377: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_get_stringarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:353: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:353: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:357: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:357: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:368: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:355: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:360: undefined reference to `_gfortran_runtime_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_get_realarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:335: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:335: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:339: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:339: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:341: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:338: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_get_intarr':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:320: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:320: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:324: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:324: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:326: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:323: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_get_string':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:306: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:306: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:308: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_get_logical':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:294: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:294: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_get_real':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:286: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:286: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_get_int':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:279: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:279: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `amrex_init_namelist':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:545: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_parmparse_mod.o): In function `__amrex_parmparse_module_MOD_amrex_parmparse_build':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:250: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_parmparse_mod.F90:250: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_string_mod.o): In function `__amrex_string_module_MOD_amrex_string_f_to_lower':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_string_mod.F90:57: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_string_mod.o): In function `__amrex_string_module_MOD_amrex_string_build':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_string_mod.F90:48: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_string_mod.F90:49: undefined reference to `_gfortran_os_error'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_string_mod.F90:49: undefined reference to `_gfortran_runtime_error'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_string_mod.o): In function `__amrex_string_module_MOD_amrex_string_f_to_c':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_string_mod.F90:20: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_BLBoxLib_F.o): In function `bl_error_':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_BLBoxLib_F.F90:10: undefined reference to `_gfortran_st_flush'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_BLBoxLib_F.o): In function `bl_warning_':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_BLBoxLib_F.F90:24: undefined reference to `_gfortran_st_flush'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_BLBoxLib_F.o): In function `bl_abort_':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_BLBoxLib_F.F90:38: undefined reference to `_gfortran_st_flush'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_error_mod.o): In function `__amrex_error_module_MOD_amrex_abort':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:63: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:63: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_error_mod.o): In function `__amrex_error_module_MOD_amrex_error1_r':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:57: undefined reference to `_gfortran_st_write'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:57: undefined reference to `_gfortran_transfer_real_write'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:57: undefined reference to `_gfortran_st_write_done'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_string_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_string_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_string_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:58: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_error_mod.o): In function `__amrex_error_module_MOD_amrex_error1_i':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:48: undefined reference to `_gfortran_st_write'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:48: undefined reference to `_gfortran_transfer_integer_write'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:48: undefined reference to `_gfortran_st_write_done'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:49: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:49: undefined reference to `_gfortran_string_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:49: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:49: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:49: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_error_mod.o): In function `__amrex_error_module_MOD_amrex_error1_ch':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:41: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:41: undefined reference to `_gfortran_string_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:41: undefined reference to `_gfortran_concat_string'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:41: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:41: undefined reference to `_gfortran_internal_pack'
/home/ztdep/Downloads/amrex/lib/libamrex.a(AMReX_error_mod.o): In function `__amrex_error_module_MOD_amrex_error0':
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:36: undefined reference to `_gfortran_string_len_trim'
/home/ztdep/Downloads/amrex/Src/Base/AMReX_error_mod.F90:36: undefined reference to `_gfortran_internal_pack'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/amrex.dir/build.make:95: amrex] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/amrex.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
*** Failure: Exit code 2 ***

**Comment by WeiqunZhang** [comment]
I think you also need to link to gfortran, `-lgfortran`.

**Comment by ztdepztdep** [comment]
thanks it works.
