### ISSUE TITLE
what is the meaning of "amrex.v=1"

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#317]
Dear friends:
     When we run the parallel version amrex, we should use 
      mpiexec -np 12 ./amrex amrex.v=1
    But what is the meaning of "amrex.v=1".
Regards

**Comment by zingale** [comment]
`amrex.v` is a runtime parameter.  In this case, it sets the level of verbosity of the amr library.  You can set it to 0, `amrex.v=0` to make the code output less to stdout.  Runtime parameters in amrex are managed by the ParmParse class, and generally have a namespace (`amrex` in this case) and a parameter name within that namespace (`v` here).

You can put the runtime parameters in an inputs file and/or specify them on the commandline when you run.  In your case, the runtime parameters are specified on the commandline after the executable name.

**Comment by ztdepztdep** [comment]
thank you very much. But why it is needed when we use mpi.

**Comment by WeiqunZhang** [comment]
It's optional.

**Comment by ztdepztdep** [comment]
no, the mpi version cann't run sucessfully if i don't use the "amrex.v" .

**Comment by WeiqunZhang** [comment]
If you are using the master branch, without `amrex.v=1`, it will not print
out a message about how many MPI processes are used.  But it does run.  Did
you see `Hello world from AMReX version 18.09.1`?  If so, it did run.

We recently made a change.  If you are using the development branch, the
default is now `amrex.v=1`.  In fact, you have to use `amrex.v=0` to not
see the message about MPI.
