### ISSUE TITLE
paraview doesn't has the boxlib fiel type support.

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#318]
I just installed paraview 5.4 , but it cann't support boxlib filetype. how to resolve this problem.

**Comment by WeiqunZhang** [comment]
I do not use Paraview personally.  But I don't think it supports 2D AMReX
plotfiles.  That might be why.

**Comment by ztdepztdep** [comment]
Thank you. The tutorial use 5.5 version. is seems that i have installed an old one.

**Comment by ruihai0925** [comment]
@ztdepztdep 

Visit is also ok with boxlib file type. I tried both the 2.13.1 on Windows 7 and another Linux version of this software. Both of them work well. See here: https://wci.llnl.gov/simulation/computer-codes/visit/executables

**Comment by Leixushu** [comment]
@ztdepztdep 
Have you solved your problem. It still do not work afer I installed paraview 5.5. Thanks!
