### ISSUE TITLE
Error while defining embedded geometry using CUDA 

### ISSUE THREAD

**Issue by ashwathsv** [AMReX-Codes/amrex#3182]
Hi Team,

I am trying to define a domain with a series of equally spaced box-shaped obstacles (more than 100). I am unable to compile this using CUDA as it throws up an error for the EB geometry saying "uses too much parameter space" (screenshot attached).
![amrex_eb_error](https://user-images.githubusercontent.com/45438278/222002849-81254183-d820-45f1-b287-cc8356f11bb8.png)

Below is the function definition for the intended EB geometry defined in the header file for problem definition. I would really appreciate if someone could provide a solution for this issue. It would be really nice if someone could also help with AMReX functions that might provide a more concise way of defining the geometry. Thanks in advance. 

`AMREX_GPU_HOST
AMREX_FORCE_INLINE
void
init_eb_geometry (const amrex::Geometry& geom, const int max_coarsening_level)
{
    const Real* prob_lo = geom.ProbLo();
    const Real* prob_hi = geom.ProbHi();

    ParmParse pp("ddt");

    // br : Blockage ratio, D : Width of channel (twice of domain height)
    Real br, D;
    pp.get("br", br);

    D  = 2. * (prob_hi[1]  - prob_lo[1]);
    // obsw : obstacle width, h : obstacle height
    Real obsw   =  0.25 * D;
    Real obshgt =  0.5 * br * D;
    Real eps = 0.01;

    // SEPARATION BETWEEN TWO OBSTACLES IS "D"
    // FIRST OBSTACLE IS AT A DISTANCE D/2 FROM LEFT END OF DOMAIN
    Real xlo = 0.5 * D;
    Real xhi = xlo + obsw;
    Real ylo = prob_lo[1]-eps; Real yhi = prob_lo[1]+obshgt;

    EB2::BoxIF box0({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box1({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box2({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box3({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box4({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box5({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box6({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box7({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box8({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box9({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu0 = EB2::makeUnion(box0, box1, box2, box3, box4, box5, box6, box7, box8, box9);

    EB2::BoxIF box10({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box11({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box12({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box13({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box14({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box15({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box16({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box17({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box18({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box19({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu1 = EB2::makeUnion(box10, box11, box12, box13, box14, box15, box16, box17, box18, box19);

    EB2::BoxIF box20({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box21({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box22({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box23({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box24({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box25({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box26({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box27({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box28({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box29({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu2 = EB2::makeUnion(box20, box21, box22, box23, box24, box25, box26, box27, box28, box29);

    EB2::BoxIF box30({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box31({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box32({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box33({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box34({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box35({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box36({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box37({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box38({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box39({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu3 = EB2::makeUnion(box30, box31, box32, box33, box34, box35, box36, box37, box38, box39);

    EB2::BoxIF box40({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box41({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box42({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box43({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box44({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box45({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box46({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box47({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box48({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box49({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu4 = EB2::makeUnion(box40, box41, box42, box43, box44, box45, box46, box47, box48, box49);

    EB2::BoxIF box50({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box51({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box52({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box53({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box54({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box55({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box56({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box57({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box58({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box59({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu5 = EB2::makeUnion(box50, box51, box52, box53, box54, box55, box56, box57, box58, box59);

    EB2::BoxIF box60({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box61({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box62({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box63({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box64({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box65({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box66({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box67({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box68({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box69({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu6 = EB2::makeUnion(box60, box61, box62, box63, box64, box65, box66, box67, box68, box69);

    EB2::BoxIF box70({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box71({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box72({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box73({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box74({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box75({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box76({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box77({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box78({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box79({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu7 = EB2::makeUnion(box70, box71, box72, box73, box74, box75, box76, box77, box78, box79);

    EB2::BoxIF box80({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box81({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box82({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box83({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box84({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box85({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box86({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box87({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box88({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box89({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu8 = EB2::makeUnion(box80, box81, box82, box83, box84, box85, box86, box87, box88, box89);

    EB2::BoxIF box90({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box91({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box92({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box93({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box94({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box95({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box96({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box97({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box98({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;
    EB2::BoxIF box99({xlo, ylo}, {xhi, yhi}, false); xlo = xlo + obsw + D; xhi = xlo + obshgt;

    auto bu9 = EB2::makeUnion(box90, box91, box92, box93, box94, box95, box96, box97, box98, box99);

    auto box_union = EB2::makeUnion(bu0, bu1, bu2, bu3, bu4, bu5, bu6, bu7, bu8, bu9);

    auto gshop = EB2::makeShop(box_union);
    EB2::Build(gshop, geom, max_coarsening_level, max_coarsening_level, 8);

}           `

**Comment by esclapez** [comment]
Hi @ashwathsv,

It might likely be similar to the last question of AMReX FAQ:
https://amrex-codes.github.io/amrex/docs_html/Faq.html

even though the error message slightly differs. Can you try to implement passing device pointers to the EB2::makeUnion instead of the union themselves ?

**Comment by WeiqunZhang** [comment]
@esclapez I assume you meant `EB2::makeShop`.

**Comment by WeiqunZhang** [comment]
@ashwathsv You could also write your own implicit function class, since it's just a simple pattern.

**Comment by esclapez** [comment]
@WeiqunZhang indeed, either `EB2::makeShop` or even before, the parameter space could already be overflowing in the last `EB2::makeUnion`, I can't tell from the error/code without the line numbers.

**Comment by WeiqunZhang** [comment]
All those makeUnions are in CPU memory.  So there is no GPU parameter space overflow.

**Comment by ashwathsv** [comment]
@WeiqunZhang @esclapez Thank you for your suggestions. I was able to resolve this issue by passing device pointers as you suggested.
