### ISSUE TITLE
amrex::Abort::0::CUDA error 2 in file ../../../../amrex/Src/Base/AMReX_Arena.cpp line 169: out of memory !!!

### ISSUE THREAD

**Issue by passerLR** [AMReX-Codes/amrex#3189]
I built a gpu example project in 'amrex-tutorials/ExampleCodes/Basic/HelloWorld_C/' with command 'make COMP=gnu USE_CUDA=TRUE' and run with './main3d.gnu.DEBUG.CUDA.ex', then it print the error 'amrex::Abort::0::CUDA error 2 in file ../../../../amrex/Src/Base/AMReX_Arena.cpp line 169: out of memory !!!'. How can I debug?

**Comment by WeiqunZhang** [comment]
What do you get from `nvidia-smi`?  Maybe some  other processes are using a lot of GPU memory?  By default, AMReX tries to allocate 3/4 of the system's memory during initialization.  You can change it by running with `./main3d.gnu.DEBUG.CUDA.ex amrex.the_arena_init_size=0`.

**Comment by passerLR** [comment]
> What do you get from `nvidia-smi`? Maybe some other processes are using a lot of GPU memory? By default, AMReX tries to allocate 3/4 of the system's memory during initialization. You can change it by running with `./main3d.gnu.DEBUG.CUDA.ex amrex.the_arena_init_size=0`.

It works when `amrex.the_arena_init_size=0` is added. Thank you for your response.
