### ISSUE TITLE
Does AMReX support solving poission equation implicitly.

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#319]
I need to use the fully implicit method to solve the poission equations. 
     Does AMReX support it.

**Comment by asalmgren** [comment]
AMReX has geometric multigrid solvers to solve the poisson equation.

Do your solution and right hand side live on cell centers or on nodes?

**Comment by ruihai0925** [comment]
@ztdepztdep 

Hello,

This tutorial (https://github.com/AMReX-Codes/amrex/tree/master/Tutorials/LinearSolvers/ABecLaplacian_C) provides a great example to solve Poisson equation on both multi-levels (composite solver) and single level (level solver). It is cell based. 

The disadvantage is that it can only handle simple boundary conditions (pure neumann, simple dirichlet by using the setCoarseFineBC subroutine, etc). If you want to solve the Poisson equation on multi-levels, some coarse-fine interpolations may be needed. 

Feel free to @me if you have more questions.

Best.

Jordan

**Comment by ztdepztdep** [comment]
thank you . I am studying it.
