### ISSUE TITLE
Particels Module in window

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#320]
I make a build system for windows. All work right without particle module. Something wrong when including particles.

The issue comes when redistributing. Can anyone help me out?

![image](https://user-images.githubusercontent.com/30617135/45661829-cb18ec80-bb31-11e8-9538-324f752f6b11.png)

**Comment by GumpXiaoli** [comment]
By the way, all work right under linux system.

**Comment by GumpXiaoli** [comment]
I think i found the problem.

In line 961 of AMReX_ParticleContainerI.H, there is a comparison between unsigned (pindex) and long (last). Under windows (32-bit and 64-bit), long is only 4-byte type, while under linux-like system, 4-byte for 32-bit and  8-byte for 64-bit.

The issue can be fixed when pindex and last variabes  are both changed into long to avoid this problem. 

![image](https://user-images.githubusercontent.com/30617135/45668570-d9760100-bb4f-11e8-93db-140e3340f65e.png)

**Comment by atmyers** [comment]
Glad you found the problem! In general, I'd be very careful about using AMReX on Windows - we don't officially support or test on it, and I'd be surprised if there weren't other issues as well.
