### ISSUE TITLE
AMRVis build error

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#323]
I try to build amrvis to visualize the profile data. When i set USE_PROFPARSER=TRUE, there is always two compiling errors in RegionPicture.cpp as below:

![_20180925205508](https://user-images.githubusercontent.com/30617135/46015635-5fbcb500-c105-11e8-9b05-e83777892c9c.jpg)

Can anyone help fix this error?

**Comment by GumpXiaoli** [comment]
By the way, i build AMRVis successfully when turn off USE_PROFPARSER flag. However, it seems that profile data cannot be loaded.

**Comment by kngott** [comment]
I believe you're using the wrong branch of AmrVis. I recreate your error when using the "profvis" branch. However, that branch is in the middle of adding new functionality.

Try using amrvis/master.

**Comment by GumpXiaoli** [comment]
yes! you are right. I build amrvis successfully.

However, when i open profile database, there is one confusing error: "You are using 2D amrvis to look at a 0D file."

**Comment by kngott** [comment]
That error message is from the standard Amrvis stuff, not the ProfParser stuff. So, the program thinks you are pointing to a standard plotfile.

Are you pointing the executable at a database that starts with "bl_prof"? That's currently the way to identify to Amrvis that the folder is a profiling database.

**Comment by GumpXiaoli** [comment]
Fix it!!  Many thanks!
