### ISSUE TITLE
Hi! Is there one pdf format for https://amrex-codes.github.io/amrex/docs_html?

### ISSUE THREAD

**Issue by xumustc** [AMReX-Codes/amrex#325]
Hi! 
Is there one pdf format for https://amrex-codes.github.io/amrex/docs_html?
Thanks in advance!

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/amrex/blob/master/Docs/Readme.sphinx#L42

We probably should have put those into the documentation.

**Comment by atmyers** [comment]
There is now a pdf form of the documentation here: https://amrex-codes.github.io/amrex/docs_html/

**Comment by drummerdoc** [comment]
@atmyers Where is the pdf?

**Comment by atmyers** [comment]
It's at the bottom of the linked page.

**Comment by xumustc** [comment]
Thanks all of you for reply!
