### ISSUE TITLE
Embedded Boundary Behavior

### ISSUE THREAD

**Issue by serazo97** [AMReX-Codes/amrex#3257]
Hi all, I'm having an issue with the geometry I'm using with PeleC. I want to create an injection geometry like the one in the first picture. The problem is for some reason flow does not interact with the injector part of the geometry even though it is all recognized as a single material. The second picture simplifies the geometry to a single duct in the domain and you can see that the fluid doesn't seem to interact at all - it treats it as a wall. To create the desired geometry I've been using the makeDifference IF function which is when I started noticing this behavior. In the second image I have created two boxes, A wide one to create a solid boundary and a small one to act as the duct. The geometry is created by getting the geometric difference of the two boxes to get this result. Any idea on what I may be doing wrong?
![image](https://user-images.githubusercontent.com/110516591/232271217-cb7dfad2-b599-43c8-9f5a-de10ecb991a9.png)

![image](https://user-images.githubusercontent.com/110516591/232271031-d64ee399-3629-46ec-b003-fa45ab778bbf.png)

Thanks in advance!

**Comment by WeiqunZhang** [comment]
Could you show how the geometry in the second picture is generated and how many cells are used etc.?

**Comment by serazo97** [comment]
Thanks for the reply, here is the code that defines the domain:
```
# PROBLEM SIZE & GEOMETRY
geometry.is_periodic = 0 0 0
geometry.coord_sys   = 0  # 0 => cart, 1 => RZ  2=>spherical
geometry.prob_lo     =   40.0        0.0       0.0
geometry.prob_hi     =   100.0      20.0     1.0

amr.n_cell           =   240        80       4
``` 

And here is the geometry definition:
```
EBTest::build(
  const amrex::Geometry& geom, const int max_coarsening_level)
{

   amrex::EB2::BoxIF Duct({62.0,9.0,0.0},{64.0,10.0,1.0},false); // Injection Region 
   amrex::EB2::BoxIF Wall({55.0,9.0,-1.0},{65.0,10.0,2.0},false); // Injection Region
   auto Main = amrex::EB2::makeDifference(Wall,Duct);
   auto gshop = amrex::EB2::makeShop(Main);
   amrex::EB2::Build(
        gshop, geom, max_coarsening_level, max_coarsening_level);
}
```
I can post the entire files if that is not enough. There is no refinement used currently but the issue persisted when I did try to refine in case that matters. Thanks!

**Comment by WeiqunZhang** [comment]
What if you make BoxIF Duct a little longer in y-direction?

**Comment by serazo97** [comment]
That worked, thanks for your help! I'll try it on the more complex geometry and see if there's trouble but it seems like it should work.
![image](https://user-images.githubusercontent.com/110516591/232863332-ade43d2a-6cb7-4403-9ad1-798b481ed7ec.png)

**Comment by WeiqunZhang** [comment]
Great! The reason for the issue was the original `makeDifference` created a infinitely thin sheet with an implicit function value of zero.

**Comment by serazo97** [comment]
Last check in, everything is working as intended now, I'll mark the issue as closed. Thanks again!
![image](https://user-images.githubusercontent.com/110516591/232871614-6fb3d63e-c608-4bbc-b723-beca86853a69.png)
