### ISSUE TITLE
Possible case of missing memory allocation for N_VMake_MultiFab in AMReX_NVector_MultiFab

### ISSUE THREAD

**Issue by jAnirudh** [AMReX-Codes/amrex#3258]
Hi,

I have run into a problem while using the amrex::sundials::N_VMake_MultiFab method in the AMReX_NVector_MultiFab module. 

Essentially, my problem requires information stored in an AMReX MultiFab to be made available to the SUNDIALS RHS function. For this I created an N_Vector struct member, allocated it and tried using the N_VMake_MultiFab method to point to the allocated N_Vector. However, when I tried to access it I ran into a segfault. The only way I could get around this was to abandon N_VMake_MultiFab altogether and write a method which copied the multifab data into the allocated UserData N_Vector member. I think there is a memory allocation step within N_VMake_MultiFab which is missing.

I'm not sure if I've found a bug or if I have misunderstood the correct usage of the N_VMake_MultiFab method, but I'll be grateful for any clarifications.

Thanks.

**Comment by WeiqunZhang** [comment]
I am not familiar with the code in `Src/Extern/SUNDIALS`. The source code seems to suggest that `N_NNew_MultiFab` does not take ownership of the memory in MulitFab. So you need to make sure your MultiFab lives as long as the N_Vector is being used.

**Comment by jAnirudh** [comment]
Thanks for the clarification :)
