### ISSUE TITLE
Question: What is the lifetime of an amrex_mfiter object? 

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#326]
I've been using this pattern for building an amrex_mfiter object:
```fortran
  subroutine mfiter_build(this, mfi)
    class(amrex_mesh), intent(in) :: this
    type(amrex_mfiter), intent(out) :: mfi
    type(amrex_multifab) :: mf
    call amrex_multifab_build(mf, this%ba, this%dm, nc=1, ng=0)
    call amrex_mfiter_build(mfi, mf)
  end subroutine mfiter_build
```
The `amrex_mesh` type is my own creation that bundles the box array (`%ba`) and distribution map (`%dm`) for the problem, along with some other stuff.  What I'm doing is creating a local dummy multifab that is used to build the mfiter that is passed back.  My belief is that the mfiter has really nothing to do with the multifab other than the underlying box array and distribution map.

This has worked just fine with the Intel and NAG compilers, but I'm back to trying to get the code working with the gfortran compiler and it's not working. On statements like
```fortran
      dp => mf%dataptr(mfi)
```
it is throwing this assertion
```
0::Assertion `DistributionMap() == mfi.DistributionMap()' failed, file "/opt/src/amrex/amrex/Src/Base/AMReX_FabArray.H", line 812 !!!
```
So I'm wondering if the mfiter object should be expected to survive the deallocation of the multifab it was built from. It could be that I just got lucky with Intel and NAG. But gfortran has numerous problems with finalization, so I wouldn't be surprised if it is doing things it shouldn't when finalizing the local multifab.

**Comment by WeiqunZhang** [comment]
The amrex_mfiter built with amrex_multifab won't survive the destruction of the multifab.  But we do have versions of `MFIter` that take `BoxArray` and `DistributionMapping`.  They will work for your usage.  We need to port that to Fortran.

**Comment by nncarlson** [comment]
That would be sweet!

**Comment by WeiqunZhang** [comment]
Could you give the latest development a try?

    call amrex_mfiter_build(mfi, this%ba, this%dm)

PS. I notice `intent(out)` is used for the mfi argument.  Due to concern about the argument becoming undefined according to Fortran standard, I always use `inout`.  Suppose we call your `mfiter_build` function repeatedly, is there danger of undefined behaviors?

**Comment by nncarlson** [comment]
Great, I'll try it right now.

The intent(out) was intentional to cause finalization of the argument on entry. That way the object is in its default-initialized state at the start of the procedure.  It's appropriate for the way I typically define my derived types and is sort of habit, but might not be appropriate for these amrex objects.  What is this concern about "arguments becoming undefined"?  I'm not following you here.

**Comment by WeiqunZhang** [comment]
https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/303746

> INTENT(OUT) means that the initial value on entry to the routine becomes undefined. Given that, the actual values can be anything.

**Comment by nncarlson** [comment]
That's not entirely true.  From the 12.5.2.4 of the 2008 standard:

    If a dummy argument has INTENT (OUT), the actual argument becomes undefined
    at the time the association is established, except for direct components of an object
    of derived type for which default initialization has been specified.

And with regard to finalization (4.5.6.3):

    When a procedure is invoked, a nonpointer, nonallocatable object that is an actual
    argument corresponding to an INTENT (OUT) dummy argument is finalized.

I can't find it right now (I'll keep looking), but the standard also says that components
that are default initialized are defined with those values. This happens after the finalization.

**Comment by WeiqunZhang** [comment]
That seems to be the case since Fortran 2003.  So intent(out) should be fine.  In the past, we were burned by intent(out) with Fortran 90/95.

**Comment by nncarlson** [comment]
Tried your new amrex_mfiter_build function and it looks to be working fine.  Lots of my regression test failures are gone now.  Just a few left (and certainly due to something else).  Thanks!
