### ISSUE TITLE
Stability issues in EB_CNS/Sod Test

### ISSUE THREAD

**Issue by Sqvid** [AMReX-Codes/amrex#3273]
I am trying to run the EB_CNS Tests in 2D for circle and an equilateral triangle (Schardin test) for which I have defined the geometry. I seem to be having stability issues in the form of negative temperature values developing. I have split the test off into its own repository for simplicity [Sqvid/amrex-eb_cns](https://github.com/Sqvid/amrex-eb_cns).

On 800x800 cells with the following geometry

```
eb2.geom_type = sphere
eb2.sphere_radius = 0.02
eb2.sphere_center = 0.12 0.1 0.0
eb2.sphere_has_fluid_inside = 0
```

I experience a crash with the following failure:
```
[Level 0 step 57] ADVANCE with dt = 2.236139745e-07
amrex::Abort::0::Negative temperature sent to cns_diffcoef_eb !!!
SIGABRT
See Backtrace.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 6.
```
I have attached the relevant backtrace for your consideration. I have also tried various combinations of viscosity and eb.weights to no avail. Thank you.
[Backtrace.0.txt](https://github.com/AMReX-Codes/amrex/files/11315759/Backtrace.0.txt)

**Comment by WeiqunZhang** [comment]
Maybe you can try a smaller cfl number.

**Comment by Sqvid** [comment]
Thanks for the response. It was found that changing the eb weights type to 3 improved the stability for strong shocks.
