### ISSUE TITLE
AMReX_MLMG compilation failure

### ISSUE THREAD

**Issue by ajnonaka** [AMReX-Codes/amrex#328]
In the LinearSolvers/MLMG directory, this commit 

6c3e75f5726372819ade8b54a57fccc1f652d6d4
Date:   Tue Oct 2 14:28:33 2018 -0700
    Merge branch 'development' of github.com:AMReX-Codes/amrex into development

breaks compilation of the MLMG tutorial, as well as MAESTROeX with an error like:

amrex/Src/LinearSolvers/MLMG/AMReX_MLMG.cpp:1198:38: error: ‘class amrex::MLLinOp’ has no member named ‘getBScalar’
     const Real betainv = 1.0 / linop.getBScalar();

**Comment by WeiqunZhang** [comment]
Which MLMG tutorial?

**Comment by WeiqunZhang** [comment]
OK. `Tutorials/LinearSolvers/ABecLaplacian_C`

**Comment by ajnonaka** [comment]
LinearSolvers/ABecLaplacian_C  sorry...

**Comment by drummerdoc** [comment]
Weiqun, did I undo your code rearrangement??

**Comment by WeiqunZhang** [comment]
This should be fixed now.

**Comment by ajnonaka** [comment]
Thanks!
