### ISSUE TITLE
Inhomogeneous Neumann on EBs?

### ISSUE THREAD

**Issue by eebasso** [AMReX-Codes/amrex#3282]
Hi there. As far as I can tell, AMReX currently supports inhomogeneous Dirichlet and homogeneous Neumann conditions on embedded boundaries (EBs), but not inhomogeneous Neumann. What are the plans for adding that feature? Perhaps I could take a crack at it. Please correct me if I'm wrong and inhomog. Neumann is already implemented for EBs.

**Comment by WeiqunZhang** [comment]
I saw a similar WarpX issue posted at https://github.com/ECP-WarpX/WarpX/issues/3876. Are you using Warpx or is this a question unrelated to WarpX? There are several different types of discretization. The one used by WarpX does not support Neumann BC on EB. As for inhomogeneous Neumann, one can often move the inhomogeneous part to the RHS and solve a system with homogeneous Neumann  BC.

**Comment by eebasso** [comment]
Thank you for the reply. Yes, this is related to using WarpX. Under what conditions can one move the inhomogeneous part to the RHS?

**Comment by WeiqunZhang** [comment]
For the solver in WarpX, it's not clear to me how to extend it to Neumann BC on EB.

As for inhomogeneous Neumann, here is a simple example. Suppose it is
```
((phi_{i+1} - phi_i) / dx - (phi_i - phi_{i-1}) / dx) / dx = rhs
```
and dphi/dx is foo on the face between i and i+1. Then it becomes
```
- (phi_i - phi_{i-1}) / dx) / dx = rhs - foo
```

**Comment by eebasso** [comment]
That example makes sense. I'll look more into how inhomogeneous Dirichlet BC is implemented for EB in AMReX, and specifically for the MLEBABecLap solver. I'm looking at MLEBABecLap_3D_K and MLEBABecLap_F at the moment.
