### ISSUE TITLE
Linear Solvers Broken

### ISSUE THREAD

**Issue by ajnonaka** [AMReX-Codes/amrex#330]
One of the 2 most recent commits:

ce5d30d09d090be5bbc280bfa681262693e5ef2d

92174343a3a59c3cdf36d4d2291bb2d72639ef6f

Breaks MAESTROeX.  The first MAC projection linear solver now fails due to too many MG cycles.  MAESTROeX/Exec/SCIENCE/wdconvect inputs_3d_regression

These are pretty big merge commits, but there are changes to MLMG that have to do with subtracting off mean RHS for solvability-- things like that.

**Comment by asalmgren** [comment]
If I run MAESTROeX development branch hash 5e419c4678802f77a77ff5874d5957787f1 with amrex development branch hash 94b1db4b57d3a7da8ff668c9e02d38aa9322b49b with Exec/SCIENCE/wdconvect/inputs_3d_regression it seems to run fine (this is before Weiqun's commenting out)

**Comment by WeiqunZhang** [comment]
Is the problem singular?

The changes I commented out are some new codes trying to make rhs solvable in each iteration of bicgstab.

**Comment by WeiqunZhang** [comment]
I works for me too with 94b1db4.  But there are several merges from mlmg to development.  What might happen was Andy probably ran with an early merge that contained a bug that did subtraction even for non-singular problem.

**Comment by ajnonaka** [comment]
I just updated to the current development be8ef9dc07252d3ecd1b4f3e42250d13f1c97fd4 and MAESTROeX runs fine now.  The problem was not singular - it had outflow on all walls.

**Comment by sireeveslbl** [comment]
The current development has the singular changed commented out. 

Within ce5d30d I accidentally merged an older version of MLMG into development which was applying the residual mean subtraction without checking for singularity. 

The commit that Ann was working had the singular flags in it.
