### ISSUE TITLE
CNS Test code error on GPU

### ISSUE THREAD

**Issue by zhangruoyao68** [AMReX-Codes/amrex#3300]
The following error shows up when I compiled and ran the `/home/XX/amrex/Tests/GPU/CNS/Exec/RT` example code on an RTX 3090 with CUDA-12.1

```
->./CNS3d.gnu.TPROF.MPI.CUDA.ex

MPI initialized with 1 MPI processes
MPI initialized with thread support level 0
Initializing CUDA...
CUDA initialized with 1 device.
amrex::Abort::0::CUDA error 2 in file ../../../../../Src/Base/AMReX_Arena.cpp line 173: out of memory !!!
SIGABRT
See Backtrace.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

For it to compile correctly, I changed the `/home/XX/amrex/Tools/GNUMake/sites/Make.unknown` to have `-arch=compute_86 -code=sm_86`, so compilation was not a problem.

**Comment by WeiqunZhang** [comment]
You don't need to modify any make file. You can set `export AMREX_CUDA_ARCH=86` in the environment or pass that as an argument to `make`. But I don't know what is causing the error. You can try to run with
```
./CNS3d.gnu.TPROF.MPI.CUDA.ex inputs-rt amrex.the_arena_init_size=0`
```
Note that you need to provide an inputs file because the CNS expects one, even though that's not why you have the out of memory error. `amrex.the_arena_init_size=0` sets the initial size of the arena to zero. This will likely resolve the issue.

Could you provide more information by running `nvidia-smi` and `free`? I wonder if your machine has more GPU memory than CPU memory. Could you also modify amrex as follows, compile and run with your old way? I want to see how much memory it is trying to allocate.
```
diff --git a/Src/Base/AMReX_Arena.cpp b/Src/Base/AMReX_Arena.cpp
index 7e7157e66c..5ff3adc9c5 100644
--- a/Src/Base/AMReX_Arena.cpp
+++ b/Src/Base/AMReX_Arena.cpp
@@ -168,6 +168,7 @@ Arena::allocate_system (std::size_t nbytes) // NOLINT(readability-make-member-fu
 
         if (arena_info.device_use_managed_memory)
         {
+            std::cout << "nbytes = " << nbytes << std::endl;
             AMREX_HIP_OR_CUDA_OR_SYCL
                 (AMREX_HIP_SAFE_CALL(hipMallocManaged(&p, nbytes));,
                  AMREX_CUDA_SAFE_CALL(cudaMallocManaged(&p, nbytes));,
```

**Comment by zhangruoyao68** [comment]
`./CNS3d.gnu.TPROF.MPI.CUDA.ex inputs-rt amrex.the_arena_init_size=0` this solves the issue right away. Thanks!

**Comment by WeiqunZhang** [comment]
That's great. To help us understand, could you provide more information following the instruction in my previous comment?

**Comment by zhangruoyao68** [comment]
> Could you provide more information by running `nvidia-smi` and `free`? I wonder if your machine has more GPU memory than CPU memory. Could you also modify amrex as follows, compile and run with your old way? I want to see how much memory it is trying to allocate.
> 

Yes, 3090 has 24 GB of memory and my PC has 16 GB of RAM. Also, `free` returns
```
               total        used        free      shared  buff/cache   available
Mem:         8063260     1523900     3895212        1876     2644148     6266468
Swap:        2097152      960032     1137120
```
`nvidia-smi` gives
```
Fri May  5 20:15:51 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.37                 Driver Version: 531.30       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         On | 00000000:01:00.0  On |                  N/A |
| 30%   35C    P8               37W / 350W|   2128MiB / 24576MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        24      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

By changing the part you indicated above, the compilation is fine, running it returns
```
./CNS3d.gnu.TPROF.MPI.CUDA.ex inputs-rt
MPI initialized with 1 MPI processes
MPI initialized with thread support level 0
Initializing CUDA...
CUDA initialized with 1 device.
nbytes = 19326959616
amrex::Abort::0::CUDA error 2 in file ../../../../../Src/Base/AMReX_Arena.cpp line 174: out of memory !!!
SIGABRT
See Backtrace.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

Also, is it normal to take 10+ minutes for a single compilation? Thanks.

**Comment by WeiqunZhang** [comment]
Thanks for the information!

Looks like you have 8GB of CPU memory and 24GB of GPU memory. The CUDA managed memory needs CPU memory to back it up. I think the "out of memory" message is complaining about not enough CPU memory. Usually one has more CPU memory than GPU memory. Anyway, maybe we should add a check in amrex to protect against this.

As for compilation time, it will depend on how faster your CPU is and how many parallel make jobs you can run. Note that if your machine does not have enough CPU memory, `make -j` might hurt if it runs out of memory. Also, you should try ccache. That can help a lot.

**Comment by zhangruoyao68** [comment]
Thanks a lot, again!
