### ISSUE TITLE
Can we provide homogeneous Neumann boundary condition at the coarse-fine boundary in the MLMG solver?

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/amrex#332]
Hello all,

In this example,
https://github.com/AMReX-Codes/amrex/blob/master/Tutorials/LinearSolvers/ABecLaplacian_C/MyTest.cpp

I found the mlmg solver could provide the homogeneous Neumann boundary condition for physical boundary. Can we provide homogeneous  Neumann boundary condition at the coarse-fine boundary for finer levels if we want to use the level solve only for the finer level?

Thanks

Jordan

**Comment by ruihai0925** [comment]
Additional supplements:

In this tutorial, it seems that every time we want to do the level solve, we have to call the setCoarseFineBC function. But this function seems to provide a Dirichlet type boundary condition for the coarse-fine boundary, not Neumann. What I want to do now is just to pick a single patch for finer levels, like an "island", Neumann boundary condition is given not matter its boundary is physical or coarse fine boundary.

**Comment by WeiqunZhang** [comment]
I don't think we have the time to implement this.  But you could hack it.  I think the following should work.

(1) At the end of `AMReX_MLMGBndry.cpp`, change the last block from

```
            // Internal bndry.
            bctag[face] = AMREX_LO_DIRICHLET;
            bloc[face]  = ratio > 0 ? 0.5*ratio*dx[dir] : a_loc[dir];
```
to
```
            // Internal bndry.
            bctag[face] = AMREX_LO_NEUMANN;
            bloc[face]  = 0.0;
```

(2)  In `AMReX_MLLinOp.H`, make `bool needsCoarseDataForBC () const` always return `false`.

(3) You need to call `setDomainBC` and `setLevelBC` with `nullptr`.

(4) If your equation is Poisson, or ABecLaplacian with **zero** A coefficient, you need to worry about solvability.  You need to set `m_is_singular` to `true` in `MLPoisson::prepareForSolve()` or `MLABecLaplacian::prepareForSolve()`.

Hopefully, that's all you need to do.

**Comment by ruihai0925** [comment]
@WeiqunZhang Thanks so much. I will do it this weekend.
