### ISSUE TITLE
Potential problem on 32-bit platforms

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#3344]
Does AMReX support 32-bit platforms?

When building on such a platform (where `long long` has 64 bits while `long` has 32 bits) I see this compiler warning:
```
[09:46:20] /workspace/srcdir/amrex/Src/Particle/AMReX_Particle.H:18:41: warning: overflow in conversion from ‘long long int’ to ‘amrex::Long’ {aka ‘long int’} changes value from ‘549755813887’ to ‘-1’ [-Woverflow]
[09:46:20]    18 |     constexpr Long GhostParticleID    = 549755813887L; // 2**39-1
[09:46:20]       |                                         ^~~~~~~~~~~~~
```

This might mean that this code is not working as intended on 32-bit platforms.

**Comment by WeiqunZhang** [comment]
Is `int` 32 bits or 16 bits on that platform?

**Comment by eschnett** [comment]
This is a "normal" platform with 32-bit ints, longs, and pointers, and 64-bit long longs.

**Comment by WeiqunZhang** [comment]
This is how we define amrex long in AMReX_Int.H
```
#ifdef _WIN32
typedef          long long amrex_long;
typedef unsigned long long amrex_ulong;
#else
typedef          long amrex_long;

typedef unsigned long amrex_ulong;
#endif
```
Seems that we could change it to
```
#if (LONG_MAX == INT_MAX)
typedef long long amrex_long
#else 
typedef long amrex_long
#endif
```
so that amrex_long is always a type longer than int.

**Comment by eschnett** [comment]
Why don't you use `long long` in all cases? That's (today) always a 64-bit integer. `std::int64_t` would also work.

**Comment by WeiqunZhang** [comment]
In the past, we did not have `amrex::Long`, we simply used `int` and `long` without worrying much about the width of long. Then we added `amrex::Long` to address the width issue on Windows. But we did not worry about 32 bits machines and we wanted to minimize the changes for LP64 systems . After all, long, long long and int64_t are different types.

**Comment by WeiqunZhang** [comment]
As an example, if a user (who only runs on LP64 systems) may have a function `void f (long& a)`. Currently, one can call it with amrex::Long. But it will break if we change amrex::Long to long long.
