### ISSUE TITLE
RK problem with `amrex::almostEqual` when time step is small

### ISSUE THREAD

**Issue by FR13ndSDP** [AMReX-Codes/amrex#3374]
This issue is related to the RK method integrated into `AmrLevel`.
You can reproduce this problem in `/Tests/GPU/CNS/Exec/Sod` by setting: 
```
cns.refine_max_dengrad_lev = 3
cns.refine_dengrad = 0.1
amr.max_level       = 2       # maximum level number allowed
```
in `inputs` and run the simulation. If everything goes as expected, you will receive the following error:
```
0::Assertion `amrex::almostEqual(time,t_old) && amrex::almostEqual(time+dt,t_new)' failed, file "../../../../../Src/Amr/AMReX_AmrLevel.H", line 617 !!!
SIGABRT
```

**Comment by WeiqunZhang** [comment]
The issue is the times stored in StateData on different levels are slightly out of sync (~ 4e-17). We could fix this by calling AmrLevel::postCoarseTime in the override version of CNS::postCoarseTime. But since this is a common mistake, we will try to fix in the Amr class.
