### ISSUE TITLE
EB-Physical-Boundary interaction

### ISSUE THREAD

**Issue by Sqvid** [AMReX-Codes/amrex#3376]
I seem to be having a persistant issue with irregular cells interacting with physical boundaries of my domain. I have attached a mininmum working example. Essentially this is just the EB_CNS test but with constant density (1.225), constant pressure (101325), and constant velocity (30 units at 0.3 radians). I also have a pipe (specified via parser) at a 0.3 rad incline.

When the simulation is run I expect to see nothing interesting in the density plot as the field is just advected along. However I notice oscillations at the intersection of the pipe with the physical boundary.

Timestep 0:
![incPipeAllConst0](https://github.com/AMReX-Codes/amrex/assets/42359201/b15b4e05-7d10-441b-9702-7857dce9f612)

Timestep 1:
![incPipeAllConst1](https://github.com/AMReX-Codes/amrex/assets/42359201/e3774b33-6e2c-4207-8691-aa4f6735b578)

Timestep Final:
![incPipeAllConstLast](https://github.com/AMReX-Codes/amrex/assets/42359201/ccd1fdc3-588c-4453-abe9-7aebc61ddb0c)

I do not have this issue with a horizontal (0 rad) pipe.

Apologies in advance if I have missed something simple.

Thank you for your help.

Minimum working example:
[pipe.tar.gz](https://github.com/AMReX-Codes/amrex/files/11793555/pipe.tar.gz)

**Comment by Sqvid** [comment]
Just adding detail for a potential tester:

The tar.gz has a file structure ass follows:
```
amrex
├── Docs
├── Src
├── Tests
├── Tools
├── Tutorials
└── paper
amrex-eb_cns
└── EB_CNS
```
`amrex/` is the current working tree of amrex and `amrex-eb_cns` is my example.

##To build:
```sh
cd ./amrex-eb_cns/EB_CNS/Exec/Sod
make DIM=2 USE_MPI=TRUE
```

The only modifications I have made from the default EB_CNS are documented in the included diff files.

Thank you for your time

**Comment by WeiqunZhang** [comment]
Could you add `eb2.extend_domain_face=0` to the inputs file to see if it helps?

By default, that parameter is 1 (i.e., true). That means the geometry outside the domain is extended from the domain face.

**Comment by Sqvid** [comment]
Thank you very much, that seems to have fixed it.
