### ISSUE TITLE
how to set the AMREX_SPACEDIM .

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#340]
Dear sir:
     How to set AMREX_SPACEDIM in the program. The default value is 2 in my program.
Regadrs

**Comment by dwillcox** [comment]
AMREX_SPACEDIM is set at compile time using the preprocessor based on the `DIM` variable for make.

If you're using the GNUMake build system, add `DIM=N` to your make line where `N` is 1, 2, or 3.

**Comment by ztdepztdep** [comment]
> AMREX_SPACEDIM is set at compile time using the preprocessor based on the `DIM` variable for make.
> 
> If you're using the GNUMake build system, add `DIM=N` to your make line where `N` is 1, 2, or 3.

Dear friends: 
    I use cmake with kdevelop 5. I do not have a make file. Could you please tell me how to define it in cmake.
  Regards

**Comment by WeiqunZhang** [comment]
https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html#tab-cmakevar
