### ISSUE TITLE
can't read particle output from ElectrostaticPIC in Paraview 5.11.1

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#3409]
When running the ElectrostaticPIC tutorial code, it produces plotfiles that have this directory structure:
```
% ls plt00000
Header    Level_0   Level_1   particle0
```

However, Paraview can't read this plotfile and emits an error:
```
ERROR: In vtkAMReXParticlesReader.cxx, line 77
vtkAMReXParticlesReader (0x12feb2cd0): Failed to open file '/Users/benwibking/amrex-tutorials/ExampleCodes/build/Particles/ElectrostaticPIC/plt00000/particles/Header'.

ERROR: In vtkExecutive.cxx, line 741
vtkPVCompositeDataPipeline (0x600002f69e00): Algorithm vtkAMReXParticlesReader (0x12feb2cd0) returned failure for request: vtkInformation (0x60000f74bd20)
  Debug: Off
  Modified Time: 393339
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
```

However, if I rename `plt00000/particle0` to `plt00000/particles`, then Paraview can read the files and appears to display the particles correctly.

**Comment by atmyers** [comment]
I believe there's also a way to change the particle type name from the default `particles` in Paraview, see here: https://amrex-codes.github.io/amrex/docs_html/Visualization.html#visualizing-particle-data

**Comment by BenWibking** [comment]
Ah, I see. I did not understand what that sentence meant in the documentation. Changing "Particle Type" in the Properties panel to `particle0` fixes the issue.

**Comment by BenWibking** [comment]
Is there an equivalent setting for yt?

Doing
```
import yt
ds = yt.load("./plt00000/")
ds.field_list
```
only lists the fields:
```
[('boxlib', 'Ex'), ('boxlib', 'Ey'), ('boxlib', 'phi'), ('boxlib', 'rhs')]
```

**Comment by atmyers** [comment]
No, but for yt you sometimes have to hint that it's an AMReX dataset:

`
import yt
from yt.frontends.boxlib.data_structures import AMReXDataset

ds = AMReXDataset("./plt00000")
...
`

**Comment by BenWibking** [comment]
That fixed it! Thanks.
