### ISSUE TITLE
Fortran modules missing

### ISSUE THREAD

**Issue by rajeeja** [AMReX-Codes/amrex#3410]
No .mod files are installed.

Sha `bacaa10a76366ed40b90b422cf5c7da43565281a` had it. The current version doesn't work.

I'm specifically interested in amrex_flash_fluxregister_module.mod @houjun

**Comment by WeiqunZhang** [comment]
Could you provide more detail on about amrex is installed?

**Comment by rajeeja** [comment]
> Could you provide more detail on about amrex is installed?

On current AMReX development, a cmake build with AMReX_FORTRAN_INTERFACES and  AMReX_FORTRAN turned on.  
.mod files are missing, see below:

@kweide 

```
(bacaa10a7) ==> ~/install/amrex2d/include/AMReX_Fl
AMReX_FlashFluxRegister.H            AMReX_FluxReg_C.H                    amrex_flash_fluxregister_module.mod
AMReX_FluxReg_2D_C.H                 AMReX_FluxRegister.H                 amrex_fluxregister_module.mod
```

```

(development) ==> l /lustre/orion/geo130/world-shared/gnu/amrex.2d.dev/include/AMReX_Fl
AMReX_FlashFluxRegister.H  AMReX_FluxReg_2D_C.H       AMReX_FluxReg_C.H          AMReX_FluxRegister.H
```
