### ISSUE TITLE
Can ABecLaplacian be used for Nodal data

### ISSUE THREAD

**Issue by smahesh14** [AMReX-Codes/amrex#342]
Hello all,

I want to solve the equation of the form (αA−β∇⋅B∇)ϕ=f,  for ϕ which is on nodes. For this form ABecLaplacian is used. In the tutorial amrex/Tutorials/LinearSolvers/ABecLaplacian_C it is used to solve for cell-centered data.

Is it possible to use it to solve for Nodal data? Or there is any other solver for above mentioned form of equation on nodal data?

Thanks 

Mahesh

**Comment by WeiqunZhang** [comment]
For nodal data, we have a solver for variable coefficient Poisson's
equation (i.e., A =0), but not the full ABecLapacian like type.

**Comment by smahesh14** [comment]
@WeiqunZhang Thanks,

Is there any reference about the implementation of nodal solvers like MLNodeLaplacian? Is it possible to extend the existing cell centered or Nodal solvers for Nodal ABecLaplacian form?

**Comment by WeiqunZhang** [comment]
The nodal project algorithm was described in Almgren et al. paper.

https://ccse.lbl.gov/Publications/almgren/abchw.pdf

If you're not doing AMR, adding the A term should be fairly
straightforward.  But if you do AMR, I am not sure how the coarse fine
boundary should be handled.

Ann (@almgren) might be able to comment on this.

**Comment by maikel** [comment]
> But if you do AMR, I am not sure how the coarse fine boundary should be handled.

Does the existent nodal Poisson solver handle multiple levels? If not, what would we have to add to make it work?

**Comment by WeiqunZhang** [comment]
Yes.

**Comment by maikel** [comment]
Perfect, Is it difficult to extent the nodal poisson tutorial with an Example using a Composite Solve over multiple Levels?

**Comment by WeiqunZhang** [comment]
Shouldn't be hard.
