### ISSUE TITLE
the boundary values in example heat equation exe2 

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#343]
In the example heat equation exe2, how to set the values of Direchelet boundary condition

**Comment by ruihai0925** [comment]
Hello @ztdepztdep ,

Could you explain more about your questions?  I think the value of Dirichlet bc lie on the domain boundary. These values are given by you not the AMReX packages. Also, it depends on the grid structure. See the codes: https://github.com/AMReX-Codes/IAMR/blob/304a3f02819605e80f7e3394b84c9559eb5c485c/Exec/run2d/PROB_2D.F#L1904

These codes fraction gives the dirichlet boundary condition for the cell centered x velocity.

In the Tutorial, https://amrex-codes.github.io/amrex/docs_html/Basics.html#boundary-conditions
You can also learn how to set the Dirichlet boundary condition by using bctype ext_dir.

Jordan

**Comment by ztdepztdep** [comment]
> Hello @ztdepztdep ,
> 
> Could you explain more about your questions? I think the value of Dirichlet bc lie on the domain boundary. These values are given by you not the AMReX packages. Also, it depends on the grid structure. See the codes: https://github.com/AMReX-Codes/IAMR/blob/304a3f02819605e80f7e3394b84c9559eb5c485c/Exec/run2d/PROB_2D.F#L1904
> 
> These codes fraction gives the dirichlet boundary condition for the cell centered x velocity.
> 
> Besides, in the Tutorial, https://amrex-codes.github.io/amrex/docs_html/Basics.html#boundary-conditions
> You can also learn how to set the Dirichlet boundary condition by using bctype ext_dir.
> 
> Jordan

  Thank you Jordan, I have run the tutorial. 
 The tutorial only set the boundary type. but where is the input value for the Direchlet boundary condition in the tutorial. 
    For example, i want to set the temperature at the boundary with  T=10.   how to resolve this.
regards

**Comment by ruihai0925** [comment]
The first link explains how to set the boundary value, https://github.com/AMReX-Codes/IAMR/blob/304a3f02819605e80f7e3394b84c9559eb5c485c/Exec/run2d/PROB_2D.F#L1904.
If ext_dir is used as the numerical boundary, it is the user's responsibility to set the boundary value. 

In the line 1907,
u(i,j) = x_vel
This it to set the dirichlet boundary value.

Best.
