### ISSUE TITLE
Plans for AMD GPU support

### ISSUE THREAD

**Issue by crtrott** [AMReX-Codes/amrex#345]
Hi,

I was wondering what your current plans are to support AMD GPUs. Is this something you thought about how to do?

**Comment by asalmgren** [comment]
That's good to know.

What is the kokkos strategy for AMD GPUs?

**Comment by crtrott** [comment]
Originally AMD recommended using the HCC native frontend directly. This is C++ AMP based interface wise. We have a backend for this, which passes practically the whole Kokkos UnitTest suite, but our applications expose a number of compiler bugs which are show stoppers (we explicitly worked around those compiler bugs in Kokkos internals). Recently AMD recommended a shift to using the HIP front end which apparently is a bit more robust at this point. We are starting a new backend based on that (AMD is putting staff on that work too) but keep the other one around in order to help with compiler maturation. The reason is that strategically the native HCC frontend is supposed to getting better aligned with the evolving C++ standard.

**Comment by crtrott** [comment]
Btw. this question came up in discussion with some folks here at Sandia. They were trying to use Trillions for a geometric multi grid code which also uses BoxLib or going forward AMReX. From our point of view Trillions is probably not the right thing for that, since it is intended for unstructured problems - but as part of that discussion we were talking about how we are planning to support the possible ExaScale machine contenders (Intel,NVIDIA,AMD,ARM,IBM).

**Comment by ax3l** [comment]
Are you considering HIP or SYCL? At least those are candidates we are looking into with [Alpaka](https://github.com/ComputationalRadiationPhysics/alpaka).

**Comment by WeiqunZhang** [comment]
We are considering HIP.  SYCL is not listed on Frontier Spec Sheet. https://www.olcf.ornl.gov/wp-content/uploads/2019/05/frontier_specsheet_v4.pdf
