### ISSUE TITLE
Bug in AMReX_INTERP_1D.F90

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#347]
I think there is a bug in the line 163 of  AMReX_INTERP_1D.F90:

![image](https://user-images.githubusercontent.com/30617135/47263756-64c12880-d53a-11e8-810e-909f2f6b9597.png)

x = denom*(two*lx+one) should be right.

**Comment by WeiqunZhang** [comment]
Yes I agree with you.  Will fix it.  Thanks.

**Comment by WeiqunZhang** [comment]
Fixed.  Thanks!
