### ISSUE TITLE
Only TheCellType will be written to PlotFiles?

### ISSUE THREAD

**Issue by jpmeng** [AMReX-Codes/amrex#3495]
Dear AMReX team,

By looking at the codes, e.g., those in function AmrLevel::writePlotFile, it appears that only a state variable with IndexType::TheCellType() will be written to the plotfiles by using the nice Amr and AmrLevel classes.  

```c++
 std::vector<std::pair<int,int> > plot_var_map;
    for (int typ = 0; typ < desc_lst.size(); typ++)
    {
        for (int comp = 0; comp < desc_lst[typ].nComp();comp++)
        {
            if (amrex::Amr::isStatePlotVar(desc_lst[typ].name(comp)) &&
                desc_lst[typ].getType() == IndexType::TheCellType())
            {
                plot_var_map.emplace_back(typ,comp);
            }
        }
    }
```

I was wondering if this understanding is correct. If so,  what kind of  motivation for doing this? 

If we would like to implement a finite difference scheme, which indextype (nodeType or cellType) will you recommend?  

Many thanks and kind regards.

Jianping

**Comment by WeiqunZhang** [comment]
Yes, the data in plotfiles are at cell centers. If you have nodal data and want to set them in plotfiles, you can use derived data type and add that to `amr.derive_plot_vars`. See https://github.com/AMReX-Codes/IAMR/blob/02a2bd59bcdb1e3d9a5aed1e1415cdf0a56a241f/Source/NS_setup.cpp#L447 for an example.

**Comment by drummerdoc** [comment]
Also, note that you can add your own code to write anything you want in the plot file folders.  However, there are a few software visualization and analysis packages that understand how to read and display AMReX data structures (such as paraview, yt, Vis-It).  These packages can't natively deal with the various centerings and display the hierarchical meshes correctly.  So, although it might be handy to keep data with various centerings grouped together, these packages will simply ignore them when reading the data.  That said, you can develop your own post-processing analysis tools that can make use of whatever data you want to store within the plot file folder....as long as you don't disrupt the Header and data files expected by those packages.  Reach out to me at Marc.Day@nrel.gov if you have specific needs or plans.  I might be able to suggest something helpful.

**Comment by jpmeng** [comment]
Many thanks for your promot response, and apologise for my very late reponse. 

@WeiqunZhang I am not sure if I fully undestand the  derived data type, I tried to set it as  IndexType::TheNodeType() or IndexType::TheCellType(), but it seems Paraview always read the data as cell type?

@drummerdoc  Thanks for the offer. I will definitely bother you when I am going to develop such a specifc postprocess tools.

**Comment by WeiqunZhang** [comment]
The example in IAMR I pointed to you averages nodal pressure to cell centers first and then saves it in plotfiles.

**Comment by jpmeng** [comment]
> The example in IAMR I pointed to you averages nodal pressure to cell centers first and then saves it in plotfiles.

@WeiqunZhang Thanks. Yes, I read a bit through the IAMR code, and realise that. I think using cell-type and making the coordinate correct should do for me.  Thanks for your nice help again.
