### ISSUE TITLE
limited slopes calculation in AMREX_LINCCINTERP

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#352]
When calculating limited slopes in fortran subroutin "AMREX_LINCCINTERP", i wonder why it be multiplied by a factor of two, as shown in the pic.

`forw = two*(crse(i+1,j,n)-crse(i,j,n)) 
back= two*(crse(i,j,n)-crse(i-1,j,n))`

Can above codes be revised as below or not?

`forw = crse(i+1,j,n)-crse(i,j,n)
back= crse(i,j,n)-crse(i-1,j,n)`

![image](https://user-images.githubusercontent.com/30617135/47367392-2ed69c80-d712-11e8-8723-2135d231f748.png)

**Comment by zingale** [comment]
The `TWO` is what you get for the standard MC slope limiter from van Leer 1966

**Comment by zingale** [comment]
it's Eq. 66 here: https://www.researchgate.net/publication/266987705_Towards_the_Ultimate_Conservative_Difference_Scheme_IV_A_New_Approach_to_Numerical_Convection
