### ISSUE TITLE
Location of ext_dir

### ISSUE THREAD

**Issue by WeiqunZhang** [AMReX-Codes/amrex#3580]
I just looked more carefully into this. When we need to fill a fine cell from spatial interpolation and it is near the physical boundary, we may need to use the physical boundary conditions stored in coarse level ghost cells to compute slopes. The BC type bug does not affect how ghost cells outside physical boundary are filled, because it calls a user provided function that does not use the BC type we set. For Flash-X, this function is `gr_fillPhysicalBC`. What the BC type bug affects is how slopes are computed. See https://github.com/AMReX-Codes/amrex/blob/87556458d867cb9cb2f148b4bcfc920c67bc918a/Src/AmrCore/AMReX_MFInterp_C.H#L13 for an example. You may wonder whether we treat `ext_dir` and `hoextrap` differently. This is because historically BoxLib codes assumed that the boundary location of `ext_dir` and `hoextrap` is exactly on the face, not half cell outside. So this is actually a known defect for codes that assume the location is at half cell outside. Maybe we should introduce a new type called `ext_dir_cc`. So I assume some Flash-X tests have `ext_dir` BC. If so, in the interpolation function, it was treated as being at cell centered before that bug fix and now as being on the domain face.

_Originally posted by @WeiqunZhang in https://github.com/AMReX-Codes/amrex/discussions/3578#discussioncomment-7190999_

**Comment by WeiqunZhang** [comment]
@kweide  I assume that Flash-X puts ext_dir data at cell centers. So the old results are actually more correct. I will try to fix this soon.

**Comment by kweide** [comment]
I haven't yet fully understood how the GC filling by interpolation near a domain boundary works in AMReX. (More specifically, when we used AMReX from Flash-X.). But meantime, yes another bunch of related question:

Is this interpolation aware of curvilinear coordinates? (SPHERICAL or RZ)
In particular, in the Flash-X test I mentioned several tiimes, the coordinates are RZ, and the domain bdry where results changed is actually the R=0 axis (which in Flash-X we handle basically as a REFLECTING [silp] boundary).

Could or should this interpolation be made curvilinear-aware?

Finally as a larger question - where else is or isn't AMReX aware of curvilinear coordinates? (for interpolation, but also for averaging)

[Maybe this should be one or several new isssues...]

**Comment by WeiqunZhang** [comment]
> Is this interpolation aware of curvilinear coordinates? (SPHERICAL or RZ) In particular, in the Flash-X test I mentioned several tiimes, the coordinates are RZ, and the domain bdry where results changed is actually the R=0 axis (which in Flash-X we handle basically as a REFLECTING [silp] boundary).

Yes, `amrex_interp_cell_cons` is aware of 1d spherical and 2d rz cooridinates.

> Finally as a larger question - where else is or isn't AMReX aware of curvilinear coordinates? (for interpolation, but also for averaging)

The interpolation function used by Flash-X is aware of coordinates.  (Only one cell-centered version of the average down functions is exposed in the Fortran interface.) The flux register used by Flash-X has functions that take area as argument. So it can handle curvilinear coordinates. Similarly for amrex::FluxRegister, it has functions that take volume and area for curvilinear corrdinates. `amrex::YAFluxRegister` supports curivilinear cooridiantes too.

**Comment by kweide** [comment]
I intend to write a UniTest in Flash-X, to verify that we actually make use of features like curvilinear-correct interpolation, and that they work as expected. I'll make sure the test includes a constellation where f/c boundary meets domain boundary.

By browsing through AMReX code I got the impression that curvilinearness is only considers for 1D and 2D configurations, not 3D. Is that correct and as intended?

**Comment by WeiqunZhang** [comment]
Yes, in 3D, only Cartesian is considered.

**Comment by kweide** [comment]
Regarding "restriction" (average down) functionality -

> (Only one cell-centered version of the average down functions is exposed in the Fortran interface.)

Does this imply that curvilinear-aware averaging is currently not available to Flash-X because FLash-X uses the Fortran interface, and the latter currently does not expose that functionality (which does exist at the C++-implementation level)?

**Comment by WeiqunZhang** [comment]
The exposed version is curvilinear-aware. (The function takes Geometry. That's how it knows the coordinates type.)
