### ISSUE TITLE
DataIF EB Functionality

### ISSUE THREAD

**Issue by jameslehoux** [AMReX-Codes/amrex#360]
Hi all,

I'm currently trying to develop an implicit function that generates EB surface data based on an input file (csv or space separated) the ultimate aim being able to read a tomographic dataset to use as the computational domain. 

I have written code that reads in the data, arranges it into a 3 dimensional array and then outputs a negative value for fluid, positive for solid or 0 for the boundary based on position. 

Having run this code I have encountered an error that I'm trying to understand. Specifically cells between the covered and regular cells often appear to be cut when I don't expect them to be (however not all the time). For example I have used a simple 4x4 grid for the attached photos:

-1      -1      -1     -1
 1      -1        1     -1
-1      -1      -1     -1
-1      1       -1       1 

All I have varied for these photos is the number of cells; I can see for the finest mesh its mostly(!) correct, however the coarser the mesh, the more pronounced the issue. 

Having run through a number of tests on my code I think it is performing correctly so I want to better understand how AMReX is working and how to use it correctly. Is there something obvious I am missing here? I haven't used any 0's to specify the boundary in my input data, could this be causing the issue? 

Many thanks for any help!

James

![volume fraction eb plot 8 cells](https://user-images.githubusercontent.com/37665786/47957339-f2296180-dfab-11e8-9f8f-0baa614c3304.PNG)
![volume fraction eb plot 16 cells](https://user-images.githubusercontent.com/37665786/47957340-f2c1f800-dfab-11e8-9eb7-baf94720feec.PNG)
![volume fraction eb plot 80 cells](https://user-images.githubusercontent.com/37665786/47957341-f2c1f800-dfab-11e8-8389-c3b2beb42ce7.PNG)

**Comment by asalmgren** [comment]
I'm not sure I understand how much of AMReX code you're using.   I'm
guessing from your description that you're bypassing the implicit function
approach to generating geometry.

Are you creating the volfrac array or is the EB machinery making it?

One possibility that might explain what you're seeing is that if you have a
cell with area fractions = 1 on top and right, and area fractions = 0 on
bottom and left, the EB machinery will create a diagonal line/plane cutting
through the cell since it needs to think of a cut cell as being cut by a
unique line/cell (this is something we're planning a workaround for but
don't have yet)

So that will create volume fractions = .5 at corners and 3d edges

Does that seem relevant given what you've done?

**Comment by jameslehoux** [comment]
I am still using the EB machinery to create the volfrac array. 

That looks exactly like what is happening here and explains why the cut (0.5) cells move as the coarseness of the grid varies. 

Thanks for your help.

**Comment by asalmgren** [comment]
Unfortunately this is one of the ways in which the EB algorithm is too
sensitive..

If you set

            Real box_lo = -.1 - 1.e-12;
            Real box_hi =  .1 + 1.e-12;
            EB2::BoxIF cube({box_lo,box_lo,box_lo}, {box_hi,box_hi,box_hi},
false);

you'll find that the box looks good (vf = 0 or 1) at n_cell = 10, 15, 20,
25.

So in this case setting the box_hi to .1 - 1e-12 (or in the case you found,
even .1) would result in an interior volume fraction of 1/2  but setting
box_hi to .1 + 1e-12 would have the interior volume fraction be 0

**Comment by WeiqunZhang** [comment]
The reason is fine structure within a cell is not resolved, and is essentially approximated by a plane.

**Comment by asalmgren** [comment]
But in cases like this there is an O(1) difference in volume fraction for
an O(1e-12) difference in position of the face -- this is one of the issues
with the fundamental EB discretization (not the AMReX version in particular
-- the overall EB approach in general)

**Comment by jameslehoux** [comment]
Thanks for your previous help, I've mostly got my code working correctly now.

However there is now an error if there are adjacent bodies, separated by a single fluid cell. 

For example if I set n_cell=5 and draw two boxes:

`            Real box_lo = -.1 - 1.e-12;
            Real box_hi =  .1 + 1.e-12;

            EB2::BoxIF cube2({box_lo,Real (.1 - 1.e-12),box_lo}, {box_hi,Real (.3 + 1.e-12),box_hi}, false);
            EB2::BoxIF cube3({box_lo,Real (-.3 - 1.e-12),box_lo}, {box_hi,Real (-.1 + 1.e-12),box_hi}, false);

            auto cubes = EB2::makeUnion(cube2,cube3);

            auto gshop = EB2::makeShop(cubes);
            EB2::Build(gshop, geom, 0, 0);`

The central cell is also filled in when I don't expect it to be. (I guess this is because it can see solid now at both  (-.1 +1.e-12) and (.1 - 1.e-12) and is approximating the structure) 

![image](https://user-images.githubusercontent.com/37665786/49147155-ca53c200-f2fb-11e8-8d25-094e7e29e564.png)

How do you deal with this case?

**Comment by jameslehoux** [comment]
This is also viewable if you put two body cells diagonally adjacent e.g.

![image](https://user-images.githubusercontent.com/37665786/49235100-2ea47d80-f3f1-11e8-9577-6b6da2ae3915.png)

```
            Real box_lo = -.1 - 1.e-12;
            Real box_hi =  .1 + 1.e-12;

            EB2::BoxIF cube1({Real (-.1 - 1.e-12),Real (.1 - 1.e-12),box_lo}, {Real (.1 + 1.e-12),Real (.3 + 1.e-12),box_hi}, false);
            EB2::BoxIF cube2({Real (.1 - 1.e-12),Real (-.1 - 1.e-12),box_lo}, {Real (.3 + 1.e-12),Real (.1 + 1.e-12),box_hi}, false);

            auto cubes = EB2::makeUnion(cube1,cube2);

            auto gshop = EB2::makeShop(cubes);
            EB2::Build(gshop, geom, 0, 0);
```
Except now you end up with half populated cells again.

**Comment by asalmgren** [comment]
Yes, this latter case is the same thing as the first ones in which a corner
has to get approximated as a diagonal (with volume fraction = .5)

AMReX doesn't currently have support for multiple-valued cells -- it
assumes one surface within the cell and fluid (or the quantity being
solved) existing only on one side of the interface.

It's not hard to hack the corner cells to have volume fraction = 1 but you
have to be careful in your application if you use the normals -- there is
no unique normal obviously.

But if you know that you're only going to use area and volume fractions you
can make a slight in the code where the volume fractions and normals are
calculated from the area fractions.  Basically you test on the cases you've
identified and over-ride the existing logic.
