### ISSUE TITLE
What is the default schedule type in the openmp implementation of AMReX?

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#363]
Static, dynamic, auto or runtime? or decided by the complier?

**Comment by WeiqunZhang** [comment]
Are you asking about `omp parallel for/do` or how AMReX schedules work in `MFIter`?  The former is up to the compiler.  As for the latter, the default is static and one could switch to dynamic.

**Comment by GumpXiaoli** [comment]
I am asking about MFIter. How can i change to dynamic?

**Comment by asalmgren** [comment]
An example of how to set dynamic can be found in
amrex/Src/EB/AMReX_EBMultiFabUtil.cpp  -- see the line in bold below.

We should definitely add that to the documentation -- thank you for
pointing that out!

*************************************************************

void EB_average_down_boundaries (const MultiFab& fine, MultiFab& crse,
                                 const IntVect& ratio, int ngcrse)
{
    ...
#ifdef _OPENMP
#pragma omp parallel
#endif
            for (*MFIter mfi(crse,
MFItInfo().EnableTiling().SetDynamic(true)); mfi.isValid(); ++mfi)*
            {
                const Box& tbx = mfi.growntilebox(ngcrse);
                FabType typ = flags[mfi].getType(amrex::refine(tbx,ratio));

                if (FabType::covered == typ || FabType::regular == typ) {
                    crse[mfi].setVal(0.0, tbx, 0, 1);
                } else {
                    amrex_eb_avgdown_boundaries(tbx.loVect(), tbx.hiVect(),

BL_TO_FORTRAN_ANYD(fine[mfi]),

BL_TO_FORTRAN_ANYD(crse[mfi]),

BL_TO_FORTRAN_ANYD(barea[mfi]),
                                                ratio.getVect(), &ncomp);
                }
