### ISSUE TITLE
amrex::Error::22::FABio::read_header(): expected 'F' !!!

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#365]
When reading file, there is error as title. I can't figure it out. Could anyone help?

**Comment by maxpkatz** [comment]
This usually means there is some error in reading the checkpoint, because it was not fully written out correctly, or perhaps because you're trying to restart using a different number of state variables than what the checkpoint has.

**Comment by GumpXiaoli** [comment]
Ok. I fix it. Thank you!!!
