### ISSUE TITLE
WriteMultiLevelPlotfile nfiles

### ISSUE THREAD

**Issue by ThomasHowarth** [AMReX-Codes/amrex#3657]
When plotting files using WriteMultiLevelPlotfile the number of files from VisMF seems to be hardcoded at min(256,ncores). I see that in AMReX_amr.cpp the plot_nfiles is read through ParmParse, however the various writePlotFile functions in here are never called which set this for writing with the VisMF::SetNOutFiles function call.

**Comment by WeiqunZhang** [comment]
It's called in VisMF::Initialize, which is in turned called in amrex::Initialize. A user can also call it before calling WriteMultiLevelPlotfile to change the default, and change it back if they choose to.

**Comment by ThomasHowarth** [comment]
Great - thanks for letting me know
