### ISSUE TITLE
Is this related to a possible bug in the halo implmentation in NeighborParticleContainer?

### ISSUE THREAD

**Issue by congyao23** [AMReX-Codes/amrex#3660]
Hello,

I am developing an AMReX-based SPH solver. Currently, I use a particle container derived from the `NeighborParticleContainer` and the number of halo cells equal to 1. After reading input data and some initial setup, I call `fillNeighbors()` and then `buildNeighborLists()` to generate a neighbor list for each particle. At the end of each time step, I call `clearNeighbors()`.

In the video below, there are two types of particles: fluid particles of rectangular shape and the remaining boundary particles. I applied a rigid motion to fluid particles, whereas boundary particles remain fixed. I call `Redistribute()` every time I updated particle position during time stepping. The fluid particles are colored by the SPH evaluation of divergence of position vector. In 2D, this value should be close to 2 inside the domain where particles have full support, whereas it is smaller than 2 adjacent to free surface where particles are not fully supported. 

Two cases are shown. One with `max_grid_size=8` where the domain is split into subdomains, the other with `max_grid_size=256` such that there is only one domain. I used a color scale of 1.92~1.99. We can see the result is OK when `max_grid_size=256`. However, slight oscillation exists under `max_grid_size=8`, which seems to be mainly on the border of subdomains.

Given particles are uniformly distributed, particles in halo cells should be uniform as well. Any ideas on the possible cause of such a behavior? 

Thank you.
Cong

https://github.com/AMReX-Codes/amrex/assets/122297432/75e08298-b2c6-45f4-abe4-9c70f63ea64b

**Comment by congyao23** [comment]
Hi again,

I debug through the code and found the neighbor list is correct. No issue has been detected in the AMReX's `NeighborParticleContainer`.

According to the documentation, the neighbor list only saves the ID of neighbor particles. The information of the neighbor particles is fetched from the main array according to this ID. The bug is that, I put the SPH computation and the position update inside the same function. As particle data is fetched by reference, when we update a particle's position, it will affect the later calculation where this particle becomes the neighbor of another particle.

Sorry for my own mistake. Thank you for developing such a great framework.

Cong

**Comment by atmyers** [comment]
Hi Cong,

Glad it is working for you! Please don't hesitate to reach out if you run into other issues.

Best,
Andrew
