### ISSUE TITLE
Re: Copying custom data types in AMReX

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/amrex#367]
Consider the remake level routine like the one in the Advection_F tutorial. I want to do the things in bold italics inside that (both are basically the same thing). localizer is a custom data type that the multifab holds.

call amrex_multifab_build(multifab2, ba, dm, ncomp, ngrow)
_**copy multifab1%localizer to multifab2%localizer in the regions of intersection**_
call amrex_multifab_destroy(multifab1)
call amrex_multifab_build(multifab1, ba, dm, ncomp, ngrow)
_**copy multifab2%localizer to multifab1%localizer**_ 
call amrex_multifab_destroy(multifab2)

I see there are some copyTo routines in AMReX_FabArray.H which probably can achieve this. It probably does not have a Fortran interface, but thats alright. I can write that. Can you point me to the copy routine that can do this?

Your help is deeply appreciated.

**Comment by WeiqunZhang** [comment]
I think you can use `multifab2.parallel_copy(multifab1,....)`.

Also, you don't need to call the second copy.  You can do `amrex_multifab_swap(multifab1,multifab2)` and then destroy `multifab2`.
