### ISSUE TITLE
remove undefined behavior uses of `reinterpret_cast`

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#3678]
It is undefined behavior to use `reinterpret_cast` for type punning (*except* when casting to `char`, or between unsigned and signed variants of the same type) [1].

This is done in several places in AMReX (https://github.com/search?q=repo%3AAMReX-Codes%2Famrex%20reinterpret_cast&type=code), and should be removed as soon as possible. This has caused incorrect results for our AMReX code with the AMD HIP compiler.

[1] https://www.youtube.com/watch?v=_qzMpk-22cc

**Comment by BenWibking** [comment]
This is apparently ok for `std::complex` in order to access its elements: https://en.cppreference.com/w/cpp/numeric/complex. (Thanks @WeiqunZhang for pointing this out.)

**Comment by BenWibking** [comment]
This appears to be undefined behavior:
https://github.com/AMReX-Codes/amrex/blob/798ca3356d16049b9d1b48c30f2d31f68aee088d/Src/Base/AMReX_GpuElixir.cpp#L22

**Comment by WeiqunZhang** [comment]
I am not sure it is. It's like
```
auto p = new T(...);
void* q = p;
auto p_pa = reinterpret_cast<T*>(q);  // casting to T*, not T
```
where the type of `T` does not matter.

**Comment by BenWibking** [comment]
> I am not sure it is. It's like
> 
> ```
> auto p = new T(...);
> void* q = p;
> auto p_pa = reinterpret_cast<T*>(q);  // casting to T*, not T
> ```
> 
> where the type of `T` does not matter.

Ah ok. I did not see that it was cast back to the original type.

**Comment by asalmgren** [comment]
@BenWibking - Closing this now due to inactivity -- please let us know if you have more questions!
