### ISSUE TITLE
An unreproducible error about using FillPatchIterator

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/amrex#370]
Hello all,

When I wrote the codes, I used the FillPatchIterator function to filling cells on higher levels. An unreproducible error appears every time I rerun the codes.

The "unreproducible error" means every time I rerun the code, it will get the segfault error at different places where FillPatchIterator function is used. Then the program stopped. Here are three codes fractions about errors and a related Backtrace file. Could someone help me why these errors (all about using the FillPatchIterator function) appear?

1. 
const Real current_time = state[State_Type].curTime();
FillPatchIterator fpi(*this,rho,1,current_time,State_Type,Density,1);

2.
FillPatchIterator s_old_fpi(*this,S_old1,nSgrow,previous_time,State_Type,0,nScomp);
MultiFab& S_old = s_old_fpi.get_mf();

3.
for (FillPatchIterator U_fpi(*this,visc_terms,3,previous_time,State_Type,0,2)

Backtrace file:
https://github.com/ruihai0925/Qs-about-AMReX/blob/master/Backtrace1.txt

Thanks so much.

Jordan

**Comment by asalmgren** [comment]
Have you built your executable with DEBUG = TRUE? If not please try that

**Comment by asalmgren** [comment]
Yes, it does take much more time to run.   Often we run the non-DEBUG
version out to a checkpoint then restart with the DEBUG version.   But it
all depends on what type of error you're tracking down.   You may also
discover that with the DEBUG version you may see an error earlier than
before.

Your debugging strategy also depends on whether you can identify something
that changes after the long time (like you suddenly have more or fewer
grids, or a new level is formed) or whether it appears to happen out of
nowhere

**Comment by ruihai0925** [comment]
Hello all,

I rerun the case with non-DEBUG first and then use the DEBUG version starting from 3000 step, the bug appears at the 3600 step. Here is its Backtrace file:
https://github.com/ruihai0925/Qs-about-AMReX/blob/master/Backtrace1_withdebug.txt

Here are my thoughts.
1. For the Backtracefile without debug, it says amrex::boxDiff went wrong. In this function, there is an Assert BL_ASSERT(b1in.sameType(b2)). It might be this assert stops the program. Yet, in my codes, all boxes are cell-centered. The type of boxes "should be" the same. Also, this error does not happen at the beginning of running, it happens after several hundred time steps. During this process, the mesh dynamically changes to refine the area where the intensity of scalar is large. Meshes on Level 2 (there are three levels in my codes) can also touch the physical boundary in this process. I am not quite sure if it because of the mesh changing, some "unexpected" grids structure appear, which causes this error.

2. For the Backtracefile with debug, it seems says that the Assert "mfi.LocalIndex() < indexArray.size()" in the function amrex::FabArray<amrex::FArrayBox>::operator[] is voliated, which is different from the case without debugging.

3. Again, both of this error arises from using the FillPatchIterator in my codes.

Hope someone can give me more directions and suggestions.

Thanks and best.

Jordan

**Comment by asalmgren** [comment]
Jordan -- does this problem occur reliably after restart?

My next suggestion is to create a checkpoint right before it dies so that
you only have to run one or two steps before dying.

Then we can add some more print statements to figure out exactly what is
going wrong.  There may be some combination of grids that is not what we
were expecting ... :-)
