### ISSUE TITLE
Question: retrieve arbitrary FArrayBox from MultiFab in parallel

### ISSUE THREAD

**Issue by darylbond** [AMReX-Codes/amrex#376]
I am attempting to retrieve a subset of the data from a `MultiFab`, where the subset is defined by a `Box` given by `FabArrayBase::TheFPinfo`. I have success using `FabArray::copyTo()`  when running in serial but get errors when running in parallel:

```Assertion `subbox == bx0' failed, file "../../../amrex/Src/Base/AMReX_FabArrayCommI.H", line 1478```

 This is very likely related to the following comment provided above the definition of `copyTo`
```// In the following `copyTo` functions, the destination FAB is identical on each process!!```

My question is therefore how do I go about safely retrieving a subset of the data from a `MultiFab.` I have had a poke around but can't see any other functions that provide the same functionality as `copyTo` but in parallel.

Addendum: I am doing this in order to find where new cells are being created when regridding. I need this information so that I can perform a divergence free reconstruction of face centered EM fields where coarse and fine data is present for the same coarse cell. All I need is a masked array on the fine grid, indicating where data exists from the pre-regridded mesh, so that my interpolation function knows where to apply certain rules. If there is an existing approach for doing this then I am very interested (Note that `InterpCrseFineBndryEMfield()` from AMReX_FillPatchUtil.cpp does not achieve this goal).

**Comment by drummerdoc** [comment]
There are a couple of things wrong with how you are trying to go about this.  First off, `copyTo` is a parallel operation for gathering data that is distributed across the ranks in a `MultiFab`.  The result is a fab of data either on a single rank, or copied to all ranks.  But what you you really want is a `BoxArray` that is the difference between two `BoxArray`s.  The important distinction is that `BoxArray` data is not distributed...all the ranks know about the complete `BoxArray`, so these "box calculus" types of operations do not require parallel communication.
