### ISSUE TITLE
Should we add portable assumptions (e.g., something like `AMREX_ASSUME`) in `AMReX_Extension.H` ?

### ISSUE THREAD

**Issue by lucafedeli88** [AMReX-Codes/amrex#3766]
C++23 supports the [assume](https://en.cppreference.com/w/cpp/language/attributes/assume) attribute, which can be useful to give some hints to the compiler to optimize some code.
Many compilers already support such feature with vendor-specific extensions, such as `__attribute__((assume(...)))`for the GNU compiler or `__builtin_assume` for LLVM or NVCC.
I was wondering if we could maybe consider adding something like  `AMREX_ASSUME` in AMReX, e.g.:

```
#if defined(__clang__) 
    #define AMREX_ASSUME(assumption) __builtin_assume(assumption)
#elif defined(__GNUC__)
    #define AMREX_ASSUME(assumption) __attribute__((assume(assumption)))
#else
//...
#endif
```
 
Do you think that this could be a useful feature for AMReX?

**Comment by zingale** [comment]
along these lines, what about adding a likely attribute:
https://en.cppreference.com/w/cpp/language/attributes/likely

**Comment by WeiqunZhang** [comment]
Yes, you are welcome to add these attributes. We might need to check the compiler versions unless all recent compilers (e.g., GCC >= 8) support it.

**Comment by zingale** [comment]
added `[[likely]]` and `[[unlikely]]` in PR #3767

**Comment by lucafedeli88** [comment]
`AMREX_ASSUME`  is implemented, but it needs a fix (see https://github.com/AMReX-Codes/amrex/pull/3773) .

Also, since `AMREX_ASSUME` can potentially lead to undefined behaviors if the assumptions are not correct, I am wondering if we should maybe add an assert when AMReX is compiled in debug mode, e.g. (simplified version):

```
#if defined(AMREX_DEBUG)
#    define AMREX_ASSUME(ASSUMPTION)  AMREX_ASSERT (ASSUMPTION); [[assume(ASSUMPTION)]]
#else
#    define AMREX_ASSUME(ASSUMPTION) [[assume(ASSUMPTION)]]
#endif
```

@WeiqunZhang , @zingale , what do you think?

**Comment by WeiqunZhang** [comment]
Or maybe we can add this to AMReX_BLassert.H
```
#define AMREX_ASSERT_AND_ASSUME(ASSUMPTION)  AMREX_ASSERT(ASSUMPTION); AMREX_ASSUME(ASSUMPTION)
```

**Comment by WeiqunZhang** [comment]
Or maybe just let people explicitly write AMREX_ASSERT (or AMREX_ALWAYS_ASSERT) followed by AMREX_ASSUME if there is any doubt. Not sure which is better.

**Comment by asalmgren** [comment]
@lucafedeli88  - Closing this now due to inactivity -- please let us know if you have more questions!
