### ISSUE TITLE
Inconsistent results between fextrema and fextract

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#377]
When I analyze the variable t_sound_t_enuc in the 1D, single-level plotfile [smallplt45003.tar.gz](https://github.com/AMReX-Codes/amrex/files/2637206/smallplt45003.tar.gz), I find that fextrema tells me that its maximum value is about 1.15. However, if I do fextract -v t_sound_t_enuc and then scan the column of values, the largest value seems to be 0.723. So, there is inconsistency in the reporting here, and at least one of the two approaches must be giving me incorrect data.

**Comment by maxpkatz** [comment]
Correction pointed out by @zingale: this is a two-level plotfile, not single-level.

**Comment by zingale** [comment]
the issue here is that the max is being set on level 0, but that data is covered by a level 1 with a lower max.  So we should mask out the coarser data in this case.

**Comment by zingale** [comment]
The fix is #291.  I'll do that now.
