### ISSUE TITLE
HDF5 benchmark not working under debug mode

### ISSUE THREAD

**Issue by khou2020** [AMReX-Codes/amrex#379]
Hi:

I got this error when running the benchmark built under debug mode, it does not happen when building without debug mode.

MPI initialized with 1 MPI processes
OMP initialized with 8 OMP threads
0::Assertion `geom.ProbDomain().contains(containing_bx)' failed, file "../..//Src/Particle/AMReX_ParticleInit.H", line 805 !!!
SIGABRT
See Backtrace.0.0 file for details
application called MPI_Abort(MPI_COMM_WORLD, 6) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=6
:
system msg for write_line failure : Bad file descriptor

**Comment by atmyers** [comment]
Could you pull the most recent changes on development and try again?

**Comment by khou2020** [comment]
Sorry for late reply.
I was indeed using the latest pull from master branch. I pulled again and the result is the same.
I am using ubuntu 18.04, gcc 7.3. HDF5 version 1.10.3.

**Comment by atmyers** [comment]
Can you try the development branch, not master?

**Comment by khou2020** [comment]
It does not build under development branch. 

Loading ../..//Tools/GNUMake/comps/gnu.mak...
Loading ../..//Tools/GNUMake/sites/Make.unknown...
make: *** No rule to make target '../..//Src/Base/AMReX_FabArrayUtility.H', needed by 'tmp_build_dir/o/3d.gnu.DEBUG.TPROF.MPI.EXE/main.o'.  Stop.

**Comment by atmyers** [comment]
You might need to do `make realclean` and then try again.

**Comment by khou2020** [comment]
It build, but I got the same error when running.

MPI initialized with 1 MPI processes
0::Assertion `geom.ProbDomain().contains(containing_bx)' failed, file "../..//Src/Particle/AMReX_ParticleInit.H", line 805 !!!
SIGABRT
See Backtrace.0 file for details
application called MPI_Abort(MPI_COMM_WORLD, 6) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=6
:
system msg for write_line failure : Bad file descriptor

**Comment by atmyers** [comment]
The master branch of AMReX contains that assertion at line 805 of `AMReX_ParticleInit.H`, but the development one does not: https://github.com/AMReX-Codes/amrex/blob/development/Src/Particle/AMReX_ParticleInit.H#L805

Could you double check that you are building the correct version (the latest commit on development right now is e8b8cd2b72bde36a66d24804c907869473bbd4fc), and that you're running the correct executable?

**Comment by khou2020** [comment]
It worked. Thanks.
