### ISSUE TITLE
EB example code error . no matching function for call to ‘amrex::STLtools::read_ascii_stl_file

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3809]
main-EB.cpp:62:45: error: no matching function for call to ‘amrex::STLtools::read_ascii_stl_file(std::__cxx11::string&)’         stlobj.read_ascii_stl_file(stl_fname);
/home/ztdep/2T/Projects/AMRex/main-EB.cpp:67:16: error: ‘class amrex::STLtools’ has no member named ‘stl_to_markerfab’

**Comment by WeiqunZhang** [comment]
That example in amrex-tutorials repo is outdated. The latest documentation on EB can be found here. https://amrex-codes.github.io/amrex/docs_html/EB.html#initializing-the-geometric-database If you want a MultiFab filled with level set, you can use https://github.com/AMReX-Codes/amrex/blob/3fe7aadc23c94a038b306af54ff732ce5564c3d1/Src/EB/AMReX_EBFabFactory.H#L51.
