### ISSUE TITLE
HYPRE example?

### ISSUE THREAD

**Issue by mattbement** [AMReX-Codes/amrex#381]
Is there a HYPRE example available?  The discussion in the documentation is a bit brief.

**Comment by WeiqunZhang** [comment]
HYPRE can be used as a bottom solver in AMReX MLMG.  See `Tutorials/LinearSolvers/ABecLaplacian_C` for an example.  By default, we coarse as much as we can before calling HYPRE.  But you can change it with `LPInfo::setMaxCoarseningLevel`.  You can set it to zero and pass the `LPInfo` object to the linear operator constructor, if you want HYPRE to solve the whole problem.

**Comment by mattbement** [comment]
Ok. Even dumber question (as a someone more familiar with Cmake, and not at all familiar with GNU make).  When building the ABecLaplacian_C example, how do I tell it where I have HYPRE installed?

**Comment by asalmgren** [comment]
You need to set HYPRE_DIR=/path/to/hypre/

I do it as an environment variable.

**Comment by mattbement** [comment]
Thanks- I was trying HYPRE_HOME, which obviously didn't work.

**Comment by mattbement** [comment]
Still having trouble. Getting the following error message:
```
use amrex_hypre_fort_module, only : hypre_int
      1
Fatal Error: Can't open module file 'amrex_hypre_fort_module.mod' for reading at (1): No such file or directory
compilation terminated.
```
Here's my GNUmakefile, and I building with `make DIM=3 HYPRE_DIR=/home/bement/truchasdir/hypre/install_x86`
```
DEBUG = FALSE

USE_MPI  = TRUE
USE_OMP  = FALSE

USE_HYPRE = TRUE
USE_PETSC = FALSE

COMP = gnu

DIM = 3

AMREX_HOME ?= ../../..

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package

Pdirs 	:= Base Boundary AmrCore LinearSolvers/C_CellMG LinearSolvers/MLMG

ifeq ($(USE_HYPRE),TRUE)
    Pdirs += Extern/HYPRE
endif

ifeq ($(USE_PETSC),TRUE)
    Pdirs += Extern/PETSc
endif

Ppack	+= $(foreach dir, $(Pdirs), $(AMREX_HOME)/Src/$(dir)/Make.package)

include $(Ppack)

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
```

**Comment by WeiqunZhang** [comment]
Could you do `make realclean; make DIM=3 HYPRE_DIR=/home/bement/truchasdir/hypre/install_x86 >& make.ou` and show us the `make.ou` file?

**Comment by mattbement** [comment]
Doing `make realclean` worked.  I should've tried that before bugging y'all.  Apologies!

**Comment by chaw0023** [comment]
As a note to future users compiling this example with hyore version 2.11.0-44 or lower, `HYPRE_BoomerAMGSetOldDefault` called in `Src/Extern/HYPRE/AMReX_HypreABecLap2.cpp` `Src/Extern/HYPRE/AMReX_HypreABecLap3.cpp` and `Src/Extern/HYPRE/AMReX_HypreNodeLap.cpp` does not exist in this version. Instead this must be called: `HYPRE_BoomerAMGSetCoarsenType(solver, 6)` for _Falgout coarsening_.

See [ex5](https://github.com/LLNL/hypre/blob/a29d7c0592ca205be29bf49899d0a252e1fdd801/src/examples/ex5.c) in hypre for reference.
