### ISSUE TITLE
how to compile 2D and 3D AMReX   shared-libs at one. 

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3813]
It seems we should set dimenionsl either to 2 or 3. can we combine these two libs at one.

**Comment by WeiqunZhang** [comment]
You can build with `-DAMReX_SPACEDIM=3;2", but there will still be two amrex libraries.

In your application code, you probably could treat 2D as a special case of 3D and always use the 3d amrex library.

**Comment by ztdepztdep** [comment]
> You can build with `-DAMReX_SPACEDIM=3;2", but there will still be two amrex libraries.
> 
> In your application code, you probably could treat 2D as a special case of 3D and always use the 3d amrex library.

THanks, but how to set the DIM before compiling the example.

**Comment by WeiqunZhang** [comment]
You set it to the same value as the amrex library you use.

**Comment by ztdepztdep** [comment]
> You set it to the same value as the amrex library you use.

I am wandering what  the "parallel for " will do if i set the z direction has one layer cell. will the "phiOld(i,j,k-1))" report error?

**Comment by WeiqunZhang** [comment]
In that case, k is always zero. So you may need to add a test. You can do it the tradition way or use https://amrex-codes.github.io/amrex/doxygen/namespaceamrex.html#a7bcd0763fa57d502f90cd74ff93ba547
