### ISSUE TITLE
Could NOT find HYPRE (missing: HYPRE_LIBRARIES HYPRE_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3815]
I have installed hypre sucessfully with cmake to the default places. But it still cann't find by the AMReX package.
I don't know how to set it . the error is about :

Could NOT find HYPRE (missing: HYPRE_LIBRARIES HYPRE_INCLUDE_DIRS)

I set the system var HYPRE_LIBRARIES HYPRE_INCLUDE_DIRS, but it still doesn't work.

**Comment by WeiqunZhang** [comment]
Could you try to set `HYPRE_ROOT` in the environment or cmake command line?

https://cmake.org/cmake/help/latest/variable/PackageName_ROOT.html#variable:%3CPACKAGENAME%3E_ROOT

**Comment by ztdepztdep** [comment]
> Could you try to set `HYPRE_ROOT` in the environment or cmake command line?
> 
> https://cmake.org/cmake/help/latest/variable/PackageName_ROOT.html#variable:%3CPACKAGENAME%3E_ROOT

Great, it works.
