### ISSUE TITLE
RichardsonConvergenceTest does not compile

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#382]
The `RichardsonConvergenceTest`` utility in `anrex/Tools/C_util//Convergence/` does not compile.  

It complains about `pout()`.  If I change that to `amrex::Print()`, then it still fails to compile because of:
```
AMReX//Src/Base/AMReX_FabArray.H:240:48: error: ‘class amrex::FabFactory<amrex::FArrayBox>’ has no member named ‘getDomain’
     Box getDomain () const { return m_factory->getDomain(); }
                                     ~~~~~~~~~~~^~~~~~~~~
```
was this removed?

**Comment by WeiqunZhang** [comment]
Yes, it was removed.

**Comment by zingale** [comment]
what is the replacement for it?

**Comment by WeiqunZhang** [comment]
should work now

**Comment by zingale** [comment]
yes, works now.  I'll push the `pout` fix.
