### ISSUE TITLE
Updating Ghost Cells with Periodic Boundary Conditions in Multi-Box Domain

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3821]
In the "heat equation simple" example, 
I'm working with code that uses phi_old.FillBoundary(geom.periodicity()); to fill the periodic boundary conditions (BCs) for the physical domain. 
However, I'm unsure how to update the ghost cells between different boxes in this multi-box domain setup.

**Comment by WeiqunZhang** [comment]
FillBoundary always fills ghost cells between boxes. The periodicity information is an optional argument. If present, periodic boundary conditions will be applied in addition to ghost cells between boxes.
