### ISSUE TITLE
Does AMREX hasan example for scalar transport with a finite volume method (FVM) application？

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3831]
I need to solve the scalar transport problem with the convection shcmem QUICK scheme implicitly.

**Comment by WeiqunZhang** [comment]
I don't think we have a standalone example of scalar advection-diffusion code. However, we do have examples of incompressible CFD codes that include scalar diffusion and advection components.

- https://github.com/AMReX-Fluids/IAMR
- https://github.com/AMReX-Fluids/incflo
