### ISSUE TITLE
It appears that the same code is being executed four times, but it is not running in parallel mode."

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3836]
When i run IAMR tutorial code "liddriven cavity" , I have set the "use mpi" in the make file. but it gives:
```
NavierStokesBase:mac_project(): lev: 0, time: 0.612060768
... advect velocities
NavierStokesBase:mac_project(): lev: 0, time: 0.621101572
... advect velocities
NavierStokesBase:mac_project(): lev: 0, time: 0.630732893
... advect velocities
NavierStokesBase:mac_project(): lev: 0, time: 0.633282912
... advect velocities
... advect scalars
... advect scalars
... advect scalars
... advect scalars
... update scalars
... update scalars
... update velocities 
... update scalars
... update scalars
... update scalars
... update velocities 
... update scalars
... update scalars

```

**Comment by drummerdoc** [comment]
Did you compile with USE_MPI=TRUE in the GNUmakefile or cmake command?

**Comment by ztdepztdep** [comment]
> Did you compile with USE_MPI=TRUE in the GNUmakefile or cmake command?

yes, i have set it in the GNUmake file.

**Comment by drummerdoc** [comment]
Does the executable you are running have MPI in its name?   Can you paste in how you are actually running the code?  Also a the top of the stdout output, it should report how many procs it thinks it's running with.  Can you include that as well?

**Comment by WeiqunZhang** [comment]
Also the diff of GNUmakefile. You could use `git diff` and then post the output. It would help, if more and precise information could be provided. This is because where `USE_MPI=TRUE` appears matters. For example, with
```
USE_MPI=TRUE
USE_MPI=FALSE
```
USE_MPI=FALSE will be used.

**Comment by WeiqunZhang** [comment]
I assume the issue has been resolved.
