### ISSUE TITLE
EB with fortran interface as future development ?

### ISSUE THREAD

**Issue by avergnaud002** [AMReX-Codes/amrex#3838]
if I'm not mistaken, EB are not available with the AMReX fortran interface?
Are there plans to integrate this functionality soon?
Me and my coworkers would be interested in this feature.
Best regards
Alban Vergnaud

**Comment by WeiqunZhang** [comment]
Unfortunately we do not have immediate plans for this. However, if you can implement the feature and contribute to the amrex repo, that would be great and we can certainly help.

**Comment by nw236** [comment]
Appologies for my ignorance, but what does EB stand for?

**Comment by asalmgren** [comment]
Embedded Boundary

Ann Almgren
Senior Scientist; Dept. Head, Applied Mathematics
Pronouns: she/her/hers

**Comment by asalmgren** [comment]
@nw236 - Closing this now due to inactivity -- please let us know if you have more questions!
