### ISSUE TITLE
Real type in ParticleTile

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#384]
![screenshot from 2018-12-12 21-15-03](https://user-images.githubusercontent.com/30617135/49872111-0b4aeb00-fe53-11e8-8f16-2dff2e1ce3a4.png)

Why setting Real to double in ParticleTile?

When calling push_back_real (const std::array<Real, NArrayReal>& v), there will some compiling errors when we set compile precision flag to FLOAT.

**Comment by asalmgren** [comment]
This does get confusing  -- we have that line "using Real = double" in
*AMReX_ParticleTile.H* but we also have

in *AMReX_Particles_F.H*
#ifdef BL_SINGLE_PRECISION_PARTICLES
typedef float amrex_particle_real;
#else
typedef double amrex_particle_real;
#endif

and in *AMReX_Particle.H (which is included by AMReX_ParticleTile.H) and in
AMReX_Particles.H*
#ifdef BL_SINGLE_PRECISION_PARTICLES
    typedef float RealType;
#else
    typedef double RealType;
#endif

This can get confusing.    Maybe we can add a comment in
AMReX_ParticleTile.H pointing to where "double" is defined?

**Comment by atmyers** [comment]
That line is an error that snuck in during our recent GPU work. It should be removed. As @asalmgren said, you should be able to define the USE_SINGLE_PRECISION_PARTICLES flag on compilation, which will make all the particle data use float instead of double.
