### ISSUE TITLE
is this ok to turn the nested MFiter on by calling MFIter::allowMultipleMFIters(true)"

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3846]
I want to use a FMIters with (i,j,k,n), and compiler feedbacks the errors:

Msg: "Nested or multiple active MFIters is not supported by default.  This can be changed by calling MFIter::allowMultipleMFIters(true)". !!!

**Comment by WeiqunZhang** [comment]
It's very unlikely you want to do that. What do you want to achieve with building MFIter for a cell? Please tell us your original problem.

https://en.wikipedia.org/wiki/XY_problem
