### ISSUE TITLE
what is the definition of cell size in the node based domain

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3851]
I get the cell size array with " CellSizeArray" . my pyysical region has a size of 1.0x1.0, and I declare domain with box 

	amrex::Box domain({AMREX_D_DECL(0,0,0)}, {AMREX_D_DECL(9,9,1)},{AMREX_D_DECL(1,1,1)});

I see the CellSizeArray has a dx value of 0.1. I think it should be 1.0/9.0. 
 Am i right?

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/amrex/blob/b892132f6144461fb7cdb339e40b1f7e0a81ccd2/Src/Base/AMReX_Geometry.H#L102

The Box passed to Geometry is expected to be cell-centered. We probably should add an assertion in the code besides the comment. (Note that this does not mean nodal domain is not supported.)
