### ISSUE TITLE
how to sum all the value of a multifabs?

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3858]
I tried to use 
amrex::ParallelAllReduce::Sum(f ,MPI_COMM_WORLD) ;
but it doesn't work.
Could you please give me some advices.

**Comment by WeiqunZhang** [comment]
`my_multifab.sum()`

https://github.com/AMReX-Codes/amrex/blob/47347f785f5c26f1f9e65bef8e10f2d383406ef7/Src/Base/AMReX_MultiFab.H#L238
