### ISSUE TITLE
Difficulty Understanding AmrCore Examples - Need Help

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3863]
ello everyone,

I hope you're all doing well. I'm currently having some difficulty understanding the AmrCore examples, and I was hoping someone could provide some guidance or clarification.
           
     get_face_velocity_psi(tbx, time, psi, geomdata);

I'm trying to understand the meaning and significance of the variable psi. Specifically, I'm curious about its relationship with velocity variables and its role within the computation.

Could someone kindly shed some light on what psi represents in this context and how it relates to velocity variables? Any insights or explanations would be greatly appreciated.

Thank you in advance for any assistance you can provide.

Best regards,

**Comment by zingale** [comment]
it looks like psi here is the stream function used to define the velocity

**Comment by ztdepztdep** [comment]
thanks.  it is pusi function.
