### ISSUE TITLE
Could you please provide some references about the godnuove schemem used in the AmrCore tutorials?

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3868]
I cann't understand what is the godnuve schemem for the convection term? could you please help me out?

**Comment by zingale** [comment]
can you be more specific?  which tutorial exactly?

**Comment by q86091483** [comment]
@ztdepztdep r You can read Eleuterio F. Toro's "Riemann Solvers and Numerical Methods for Fluid Dynamics", chapter 4-5, which introduces Godunov scheme nicely.

**Comment by zingale** [comment]
I have some notes on these methods that I wrote for my students here:
https://open-astrophysics-bookshelf.github.io/numerical_exercises/

**Comment by ztdepztdep** [comment]
> I have some notes on these methods that I wrote for my students here: https://open-astrophysics-bookshelf.github.io/numerical_exercises/

ok, great books. thank you very much. I have many experience in incompressible flow computation with minmod and muscl scheme , could you please give me some instruction about what is the difference between th3ee Riemann solver and those tvd schemes. what is its advantages.
