### ISSUE TITLE
how to get the averaged value from the mutlilevel  MultiFabs?

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3891]
I want to get the total averaged value from the  mutlilevel  MultiFabs? Which function does this job?

**Comment by WeiqunZhang** [comment]
There is a function called `volumeWeightedSum` in AMReX_MultiFabUtil.H that probably does what you want. It returns a volume weighted sum of all "leaf" cells.

**Comment by ztdepztdep** [comment]
I got this error:"error: invalid initialization of reference of type ‘const amrex::Vector<const amrex::MultiFab*>&’ from expression of type ‘amrex::Vector<amrex::MultiFab, std::allocator<amrex::MultiFab> >’
   Real average=volumeWeightedSum(Rho,1,geom,nsubsteps);"
I declar the first parameter as 
amrex::Vector<amrex::MultiFab> Rho;
