### ISSUE TITLE
Some confusion about the "FillPatchSingleLevel " function

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#3930]
```
FillPatchSingleLevel (MF& mf, Real time,
                      const Vector<MF*>& smf, const Vector<Real>& stime,
                      int scomp, int dcomp, int ncomp,
                      const Geometry& geom,
                      BC& physbcf, int bcfcomp)``
```
In this funtion, what is the meaning of the "scomp" "dcomp" and ncomp. 
does it mean the index of the source component; destination compoent  and the total number of components.

**Comment by asalmgren** [comment]
Yes, that is correct.

Ann Almgren
Senior Scientist; Dept. Head, Applied Mathematics
Pronouns: she/her/hers
