### ISSUE TITLE
Periodic amr with non-periodic linear operator

### ISSUE THREAD

**Issue by bsrunnels** [AMReX-Codes/amrex#394]
Is it possible to specify different periodicity for a Linear Operator than for the rest of the simulation? I have an AMR time integration with periodic boundary conditions coupled with an implicit solve (for different variables) that has non-periodic boundary conditions. 

It seems like the best way to do this is to create a new Geometry object with different periodicity to be passed to the LinOp when it is created; however, I don't think there is currently any way to specify periodicity other than `geometry.is_periodic` in the input file. It seems like adding a `SetPeriodicity` function to `Geometry` would solve the problem, but would doing so create other issues?

**Comment by WeiqunZhang** [comment]
We could add a set function to Geometry, but the periodicity is stored as **static** data.  So it will be your responsibility to set and reset around the linear solver.

**Comment by WeiqunZhang** [comment]
I added the following.  The return value is the old periodicity so that it can be used to reset it back.

    static Array<bool,AMREX_SPACEDIM> setPeriodicity (Array<bool,AMREX_SPACEDIM> const& period)
