### ISSUE TITLE
Segfault using FillPatcher with recent AMReX versions

### ISSUE THREAD

**Issue by amg56** [AMReX-Codes/amrex#3940]
Since commit [1735fd5](https://github.com/AMReX-Codes/amrex/commit/1735fd5c65d6c73d667233437357de91a629b9e0), I have been getting segfaults in my code when using the FillPatcher class in AmrCore.  It happens at [this line](https://github.com/AMReX-Codes/amrex/blob/af6e77226cdb1668a8936ee3b35cf0d441409869/Src/AmrCore/AMReX_FillPatcher.H#L393C14-L393C32) in FillPatcher.H, currently 393:

`        cbc(*m_cf_crse_data_tmp, 0, ncomp, nghost, time, cbccomp);`

From what I can gather, m_cf_crse_data_tmp doesn't have any ghost cells, so expanding m_cf_crse_data_tmp's validbox by the 'nghost' values of the parent MultiFabs (as per commit 1735fd5) can lead to it trying to fill in boundary conditions of non-existent cells.  Which might well be expected to cause segfaults.  However, I can't seem to reproduce the segfaults I'm getting with Tests/Amr/Advection_AmrCore, after turning off periodicity and uncommenting the 'walls (Neumann)' BC code lines.  So I'm not completely sure that it isn't something I'm doing wrong in my code.

For me, changing `nghost` in the code above to `m_cf_crse_data_tmp->nGrowVect()`, i.e. setting nghost to (0,0,0), gets rid of the segfaults.  But I'm not sure if this is the correct fix or not.

Would be good to hear what you think.  Thanks!

**Comment by cgilet** [comment]
Could you try this [https://github.com/AMReX-Codes/amrex/pull/3941](url) ; compiling with USE_ASSERTION = TRUE or DEBUG = TRUE

**Comment by amg56** [comment]
Yes, that runs fine in my code with DEBUG on, no issues.  Unless I revert the changes to FillPatcher, then it correctly flags the problem with `Assertion 'nghost <= mf.nGrowVect()' failed`.

Thanks for the prompt response!

**Comment by WeiqunZhang** [comment]
Thanks for reporting!
