### ISSUE TITLE
Question about different interpolation schemes in AMReX

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/amrex#396]
Hello all,

Happy new year.

I have a question about different interpolation schemes in AMReX. The following interpolation schemes apeear both in the tutorial and codes:

NodeBilinear
CellBilinear
CellConservativeLinear
CellConservativeProtected
CellQuadratic
PCInterp
CellConservativeQuartic

After search, I found many cases in the AMReX used the CellConservativeLinear interpolation scheme for cell centered variables. Why does it like this? Can someone give me a short explanation of the differences among these interpolation schemes? (It might facilitate me to pick up a proper interpolation scheme and learned the coding details of that scheme.)

Thanks so much. 

Jordan

**Comment by ruihai0925** [comment]
**What also confuses me is when to fill the ghosts cell of the finer levels in the coarse-fine boundary by using these interpolation schemes, are the interior values of the finer level used for calculation?** 

Thanks for the clarification.

**Comment by ruihai0925** [comment]
Could someone please recommend some papers for us to follow the interpolation schemes in AMReX? 

Recently, I am discussing this question with one of another Ph.D. student in Turkey. He used the staggered grid so he wants to embed the face-centered interpolation scheme. I used the collocated grids. Both of us have some problems here. 

Thanks so much.

Jordan

**Comment by WeiqunZhang** [comment]
- `PCInterp pc_interp`: Piecewise constant interpolation for cell-centered data.
- `NodeBilinear node_bilinear_interp`: Bi-linear interpolation for nodal data.
- `CellBilinear cell_bilinear_interp`: Linear interpolation for cell-centered data.  3D not implemented.
- `CellQuadratic quadratic_interp`: Quadratic polynomial interpolation for cell-centered data. 1D version not implemented.
- `CellConservativeLinear lincc_interp`: Dimension-by-dimension linear interpolation with MC limiter (https://en.wikipedia.org/wiki/Flux_limiter) for cell-centered data.   For multi-component data, the strictest limiter is used for all components.  For example, if one component after its own limiting has a slope of zero, all other components will have zero slopes as well eventually.  The interpolation is conservative in finite-volume sense for both Cartesian and curvilinear coordinates.
- `CellConservativeLinear cell_cons_interp`:  Similar to `lincc_interp`.  There are two differences.  First, the interpolations for each component are independent of each other.  Second, after the dimension-by-dimension linear interpolation with limiting, there is a further limiting to ensure no new min or max are created in fine cells.
- `CellConservativeProtected pretected_interp`:  Similar to `lincc_interp`.  Additionally, it has a `protect` function one can call to ensure no values are negative.
- `CellConservativeQuartic quartic_interp`: Quartic polynomial conservative interpolation for cell-centered data.

For fine ghost cells at coarse/fine boundaries, the interpolation only uses coarse data.
