### ISSUE TITLE
use HIP stream-ordered allocator

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/amrex#3979]
It looks like there is support for stream-ordered allocations in HIP now: https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___stream_o.html

Although it says: "This API is marked as beta, meaning, while this is feature complete, it is still open to changes and may have outstanding issues."

Has this been tested? Would a PR be accepted adding support for this?

**Comment by WeiqunZhang** [comment]
A PR would be great.
