### ISSUE TITLE
Read from a plotfile?

### ISSUE THREAD

**Issue by mattbement** [AMReX-Codes/amrex#399]
To initialize an AMReX calculation, it would be very convenient for me to just read certain fields from a previously written plotfile.  Is there a relatively easy way to do this?

**Comment by WeiqunZhang** [comment]
You can use `VisMF::Read` as follows

    MultiFab mf;
    VisMF::Read(mf, "my_plotfile/Level_0/Cell");

If you have multiple AMR levels, you can do multiple reads with different level number in `Level_*`.

You might want to read https://amrex-codes.github.io/amrex/docs_html/IO_Chapter.html for more information.

**Comment by WeiqunZhang** [comment]
In particular, this paragraph at the end of the chapter,

> It should be emphasized that calling VisMF::Read with an empty MultiFab (i.e., no memory allocated for floating point data) will result in a MultiFab with a new DistributionMapping that could be different from any other existing DistributionMapping objects and is not recommended.

**Comment by asalmgren** [comment]
Can this issue be closed?
