### ISSUE TITLE
Document Cmake DIM range inconsistency

### ISSUE THREAD

**Issue by 837951602** [AMReX-Codes/amrex#400]
https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html

Table 1 Important make variables DIM : 1 or 2 or 3

Table 2 AMReX build options DIM Possible values: 2, 3

Tested and it doesn't seem that Cmake  can't handle 1D model, and the inconsistency is unnecessary

**Comment by mic84** [comment]
Fixed in commit 1be04740cc240bf6f6604f614625c63b99e79f70
