### ISSUE TITLE
which function calls the ParallelCopy_nowait()  , it consumes  58.44 % of cose in my program

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#4001]
in My program, it consumes about 58% of my cost. how to improeve it. 
![image](https://github.com/AMReX-Codes/amrex/assets/8356693/b450e6ef-e956-4f3d-bd3f-e9c928a42651)

**Comment by WeiqunZhang** [comment]
What does your code do besides FillPatchSingleLevel? If the floating point calculation is really cheap, the cost will be dominated by communication.

**Comment by asalmgren** [comment]
@ztdepztdep -- Closing this now due to inactivity -- please let us know if you have more questions!
