### ISSUE TITLE
HDF5 + managed memory off

### ISSUE THREAD

**Issue by marchdf** [AMReX-Codes/amrex#4007]
I am using `amrex::WriteMultiLevelPlotfileHDF5SingleDset` with `amrex.the_arena_is_managed=0` and it segfaults. Here's the backtrace.  It seems to work with `amrex.the_arena_is_managed=1`. The application code is amr-wind.
[Backtrace.0.txt](https://github.com/user-attachments/files/15991841/Backtrace.0.txt)

**Comment by atmyers** [comment]
I made a fix for this here: https://github.com/AMReX-Codes/amrex/pull/4047

**Comment by asalmgren** [comment]
@marchdf -- closing this issue now -- please re-open if PR 4047 does not fix the issue.

**Comment by marchdf** [comment]
Thank you!
