### ISSUE TITLE
does fextract support extract values at a points.

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#4023]
I want to extract values along sveral coordinates (x,y). how to resolve this.

**Comment by zingale** [comment]
do you mean you want that data at a single point?

or for a 3-d dataset, you want the line to go through a specific (x,y) and give all the z values along that line?

**Comment by ztdepztdep** [comment]
> do you mean you want that data at a single point?
> 
> or for a 3-d dataset, you want the line to go through a specific (x,y) and give all the z values along that line?

Thanks. I mean I need data at a single points, not along a line with fextract tool.

**Comment by zingale** [comment]
It does not do that currently, but it would be reasonably straightforward to write such a tool 

In the meantime, yt can do this for you:


https://yt-project.org/doc/examining/low_level_inspection.html#finding-data-at-fixed-points

**Comment by asalmgren** [comment]
@ztdepztdep -- Closing this now due to inactivity -- please let us know if you still have questions!
