### ISSUE TITLE
hypre GPU run failing at run time

### ISSUE THREAD

**Issue by hsitaram** [AMReX-Codes/amrex#4054]
Hi,

I was trying to do a linear solve with hypre on gpu on some of my application codes and I get this error on nvidia A100

terminate called after throwing an instance of 'thrust::THRUST_200301_700_NS::system::system_error'
what(): after determining tmp storage requirements for exclusive_scan: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

I am able to see the same error when building and running amrex/Tests/LinearSolvers/Hypre as well:
I built hypre using instructions here - https://amrex-codes.github.io/amrex/docs_html/LinearSolvers.html#external-solvers
I did ./configure --with-cuda to build hypre. Instructions from here - https://hypre.readthedocs.io/en/latest/ch-misc.html

 I built this test using make -j USE_CUDA=TRUE HYPRE_DIR=/scratch/hsitaram/echemAMR/hypre_gpu/hypre/src/hypre/

I didnt have any build problems, only this error at runtime.
Thank you for your help!

Hari

**Comment by WeiqunZhang** [comment]
The issue seems to be a mismatch of CUDA ARCH. Make sure both hypre and amrex use the same cuda arch.

**Comment by hsitaram** [comment]
Thank you, @WeiqunZhang . No more run time errors. I used this to build hypre now:
./configure --with-cuda --with-gpu-arch='80 90'

should I add it to amrex docs?

**Comment by WeiqunZhang** [comment]
Yes, that would be great! I think the issue comes from hypre uses `70` by default if the user does not specify cuda arch, whereas amrex will try to detect the cuda arch if it's not specified.
