### ISSUE TITLE
Reflux operation for pressure in staggered-grid

### ISSUE THREAD

**Issue by iyildiran** [AMReX-Codes/amrex#407]
Dear all,

I have fully-staggered flow solver and I try to couple it with Amrex. The velocities are stored at cell faces. I calculate advective and viscous fluxes at cell faces and now I want to update the pressure at cell center with Reflux() operations after time synchronization of coarse and fine levels.

I think I could reflux the velocities and for the pressure, I followed the same procedure given in AmrLevelAdv tutorial but it didn't work. 

I checked IAMR but unfortunately, couldn't implement it in my case. I would appreciate if you can help.

The second thing, can I use average_down_face( ) function directly for velocities on the faces?

Thank you so much
Ibrahim

**Comment by asalmgren** [comment]
@iyildiran -- it looks like your question fell through the cracks -- could you let us know if this is still a problem or if it's been resolved?  Thanks,

**Comment by iyildiran** [comment]
Thank you for your answer Ann.

I tried to couple my staggered grid solver with AMReX. After I posted this issue I developed an algorithm;

- First I advance the solution in all levels separately as time synchronization suggests. I store the area weighted temporary velocity and gradient of pressure mismatch at the coarse/fine interface.
- For prolongation, I implemented Balsara's scheme that he offered for staggered grid MHD solver.
- After the finest level is advanced, I solve an additional Poisson equation. The RHS is the divergence of mismatch I calculated in the previous step.
- Then I correct the new time velocity field.

I run it for very simple benchmark flow problems. div(u) is in the order of 10e-5 - 10e-6 at the interface.

What do you think about this algorithm? Do you think I can use AMReX with the staggered grid arrangement? If so, how should I perform all the interlevel operations, such as refluxing?

Thank you so much,
Ibrahim

**Comment by asalmgren** [comment]
Ibrahim -- if you're doing what we call a "MAC project", ie enforcing div(u) = 0 by solving div (1/rho grad phi) = div (ustar) then setting u = ustar - 1/rho grad phi, with u and ustar on x-edges, v and vstar on y-edges, and phi at cell centers, then this is an exact projection, and your divergence near the coarse-fine boundary should be smaller (assuming you've set tolerance to smaller, e.g. 1e-8 or 1-e12 or the like).    AMReX can definitely support this type of algorithm but I think you may have something not quite right at this point.   I'm happy to help more but perhaps we can move this conversation to email -- could you email me directly at asalmgren@lbl.gov?
