### ISSUE TITLE
How to extract multilevel data along some line

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#4074]
feextract only extract single level data, does it support multilevel data?

**Comment by zingale** [comment]
fextract works for multilevel data.  By default it will look at all the levels in the AMR hierarchy.  At any point in space, it will use the finest-level data available.  This is accomplished by using a mask in the loop over blocks in `fextract.cpp`.  You can control the finest level considered by using the `--fine_level` parameter.

If you want to see the data from all the levels, without masking out the coarse level data at each spatial location, you can likely do that by running for each level you want and setting `--coarse_level` and `--fine_level` equal to one another.

**Comment by ztdepztdep** [comment]
> fextract works for multilevel data. By default it will look at all the levels in the AMR hierarchy. At any point in space, it will use the finest-level data available. This is accomplished by using a mask in the loop over blocks in `fextract.cpp`. You can control the finest level considered by using the `--fine_level` parameter.
> 
> If you want to see the data from all the levels, without masking out the coarse level data at each spatial location, you can likely do that by running for each level you want and setting `--coarse_level` and `--fine_level` equal to one another.

thanks, but how to control the number of interpolation points.

**Comment by zingale** [comment]
there is no interpolation.  It just gives you the cell-centered data that the line passes through, along with the coordinates.  When you have AMR, the data points will reflect the box-structure of the finest grid at each spatial location.
