### ISSUE TITLE
how to know the number of all "leaf" cells.

### ISSUE THREAD

**Issue by ztdepztdep** [AMReX-Codes/amrex#4082]
which function output  the number of all "leaf" cells.

**Comment by WeiqunZhang** [comment]
No, there is no function for that. But you can write one like this (assuming `boxArray(int level)` is a function that that level's `BoxArray`, `finestLevel()` returns the finest level number, and `refRatio(int level)` returns the refinement ratio for that level)
```
Long nleaves = boxArray(0).numPts();
for (int ilev = 1; ilev <= finestLevel(); ++ilev) {
    int rr = AMREX_D_TERM(refRatio(ilev-1)[0], *refRatio(ilev-1)[1], *refRatio(ilev-1)[2]);
    Long nfine = boxArray(ilev).numPts();
    nleaves += nfine - nfine/rr;
}
```

**Comment by ztdepztdep** [comment]
OK,  but how to count the valid cell not covered by the next level?

**Comment by WeiqunZhang** [comment]
The function above gives the total number of uncovered cells on all levels. Are you asking for the number for each level? I am not sure I understand your question.

**Comment by ztdepztdep** [comment]
![image](https://github.com/user-attachments/assets/a277e92e-9e14-4c6d-90f0-0bcf26fdd6d9)
I want to know does the visit also show the ghost layer when I disply the mutilevel grid. 
I only refine the first layer mesh along the lid wall, but it seems it display more cells than i want

**Comment by ztdepztdep** [comment]
In the FillPatch, we have 
"  Interpolater* mapper = &cell_cons_interp", 
I want to try other interpolater, I want to know which file define the name of the interpolater "cell_cons_interp", how to find it.

**Comment by WeiqunZhang** [comment]
> how to find it.

Sorry if it sounds rude. But since you asked, `git grep` is your friend.
```
$ git grep -n "cell_cons_interp" Src/
Src/AmrCore/AMReX_Interpolater.H:965:extern AMREX_EXPORT CellConservativeLinear    cell_cons_interp;
Src/AmrCore/AMReX_Interpolater.cpp:41:CellConservativeLinear    cell_cons_interp(false);
Src/AmrCore/AMReX_MFInterpolater.H:124:extern AMREX_EXPORT MFCellConsLinInterp mf_cell_cons_interp;
Src/AmrCore/AMReX_MFInterpolater.cpp:11:MFCellConsLinInterp mf_cell_cons_interp(false);
Src/EB/AMReX_EBInterpolater.H:32:extern AMREX_EXPORT EBCellConservativeLinear  eb_cell_cons_interp;
Src/EB/AMReX_EBInterpolater.cpp:10:EBCellConservativeLinear  eb_cell_cons_interp(false);
Src/EB/AMReX_EBMFInterpolater.H:21:extern AMREX_EXPORT EBMFCellConsLinInterp eb_mf_cell_cons_interp;
Src/EB/AMReX_EBMFInterpolater.cpp:7:EBMFCellConsLinInterp eb_mf_cell_cons_interp(false);
Src/F_Interfaces/AmrCore/AMReX_fillpatch_fi.cpp:15:        &amrex::cell_cons_interp,        // 5
```
You can find other interpolaters in `Src/AmrCore/AMReX_Interpolater.cpp`.

**Comment by WeiqunZhang** [comment]
As for your "single layer" question, amrex refines a whole block, not a single cell.

If you have questions that are not exactly related, it might be better to start a new thread.
