### ISSUE TITLE
FillPatchSingleLevel and FillPatchTwoLevel with non uniform grow vector

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#410]
It is currently not possible to use these utility functions with non-uniform grow vectors.

Lines like https://github.com/AMReX-Codes/amrex/blob/7d428cb321208d9fd501d42f4077c780a6ec76aa/Src/AmrCore/AMReX_FillPatchUtil.cpp#L57 are problematic and should be probably changed to
```cpp
mf.copy(*smf[0], scomp, dcomp, ncomp, IntVect(0), mf.nGrowVect(), geom.periodicity());
```

Any thoughts? I am currently implementing a dimensional split method and stumbled across that one.

**Comment by WeiqunZhang** [comment]
Thanks for reporting this.  Please check out the latest development branch to see if the problem is fixed.  Having IntVect grow cells is a relatively new feature.  Many functions in AMReX still assume the number of grow cells is an int.  If you notice any other issues, please let us know.  Thanks!

**Comment by maikel** [comment]
Your commit ca573ae47f449cf3f977b5bdda6b9180909fa497 on develop fixed this issue.
