### ISSUE TITLE
[Feature Request] Face operations in one direction only

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#412]
Many functions which manipulate face data are not 'split' by their normal direction. Instead, they assume to be used in all directions at once. E.g. `FluxRegister::Reflux`, or `average_down_face`.

Would it be possible to also provide function overloads with a specified normal direction? What are your thoughts?

**Comment by WeiqunZhang** [comment]
In the latest development branch, there are new versions of `FluxRegister::Reflux` for single direction.  There are also versions of `average_down_faces` and `average_down_edges` for single direction.

**Comment by maikel** [comment]
Wow, you are blazingly fast! Thank you!
