### ISSUE TITLE
[Q] Is anybody using the Fortran interface with the IBM compiler?

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#416]
I'm trying to get our Fortran code running on an IBM power9 system using the IBM XL compilers (16.1.1.2) and while I've finally managed to get things to compile, almost none of our tests are passing. We're using the Fortran AMReX interface and I'd like to know whether anyone has been successfully using that interface with the IBM compiler (we're building with just -comp=ibm). I haven't yet pinned down where things are going south, but knowing that AMReX is probably not the issue would be helpful.

**Comment by WeiqunZhang** [comment]
I tested `amrex/Tutorials/LinearSolvers/ABecLaplacian_F` on summit with `xl/16.1.1-1`.  It was compiled with `make COMP=ibm` and ran with 4 MPI processes.  The result looks OK.  There are only roundoff errors compared to my run on my desktop with GCC.  I also tested the build of the library with `./configure --comp ibm; make` and checked the flags passed to the compiler.  Didn't see anything suspicious.
