### ISSUE TITLE
The WriteMultiLevelPlotfile or Paraview seems to overflow for large data sheet

### ISSUE THREAD

**Issue by pkufourier** [AMReX-Codes/amrex#4167]
[test_readwrite.zip](https://github.com/user-attachments/files/17142067/test_readwrite.zip)
Please see the above testing code. AMReX is compiled with MPI+OMP, CPU only,  double precision.  The problem is, when the cubic box have a grid number n_cell=420 and I load the generated plt file with Paraview 5.13.0 (the latest version),  statistics in Paraview shows the variable v5 is not resolved correctly as following: 
<img width="398" alt="420" src="https://github.com/user-attachments/assets/b96ac998-0288-447c-bbc3-17c6132c213c">

If I set n_cell=400, the result for v5 seems to be normal:
<img width="391" alt="400" src="https://github.com/user-attachments/assets/e3807f3d-f963-481b-8eec-e8e477d99bf4">

I have tested the cases with AMReX 24.01 and 24.09. The results are the same.  So I'm not sure whether the problem is inside WriteMultiLevelPlotfile  or Paraview.

**Comment by WeiqunZhang** [comment]
I cannot reproduce what you are seeing on my Linux machine with Paraview. Previously, you mentioned you are using Windows. Is it possible that's the issue? Note that `long` on Windows is 4 bytes. I wonder if this is a Paraview issue on Windows.

**Comment by pkufourier** [comment]
Sorry for the late reply. Yes, you are correct, it's the problem for the Windows-version of Paraview. I have also tested this code with the Linux Paraview, and the data loading works well even for 1024 cubic data.  I will report this issue for Paraview. And I also find a similar question on the Paraview forum (https://discourse.paraview.org/t/paraview-large-dataset-visualisation/15499). Maybe it is the same reason.
