### ISSUE TITLE
Error building AMReX without Blitz

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#418]
Lately I get errors if I try to use AMReX 19.03 via CMake and without having Blitz on my machine. I reproduced it on multiple machines.

Steps to reproduce the problem:

  - configure CMake on AMReX side via `cmake ${AMREX_SOURCE_PATH} -DDIM=2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${AMREX_INSTALL_PREFIX}`
  - Invoke `make install`
  - configure CMake on application side via `cmake ${APPLICATION_SOURCE_PATH} -DAMReX_DIR=${AMREX_INSTALL_PREFIX}/lib/cmake/AMReX/`

The error message I get is 

```
Make Error at /usr/local/Cellar/cmake/3.13.3/share/cmake/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  Could not find a package configuration file provided by "blitz" with any of
  the following names:

    blitzConfig.cmake
    blitz-config.cmake

  Add the installation prefix of "blitz" to CMAKE_PREFIX_PATH or set
  "blitz_DIR" to a directory containing one of the above files.  If "blitz"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Is this dependency required?  

Edit:

Even if Blitz is mandatory this should be captured at configuration time of AMReX and not of the application.

**Comment by maikel** [comment]
This issue is related with commit 89d262b6cee38e75467cd175204337be776356bd. In particular https://github.com/AMReX-Codes/amrex/blob/884d3194c9d890fcd135e44ef48b8b9886d87c9c/Tools/CMake/AMReXConfig.cmake.in#L61-L67

Could this potentially be 

```cmake
 if (NOT _NO_BLITZ_DEPENDENCY_NEEDED) 
    if (BLITZ_INSTALL_PREFIX) 
       find_dependency(blitz HINTS @BLITZ_INSTALL_PREFIX@) 
    else () 
       find_dependency(blitz REQUIRED HINTS @CMAKE_INSTALL_PREFIX@)    
    endif () 
 endif () 
```

**Comment by mic84** [comment]
Fixed in development branch.
