### ISSUE TITLE
The build of  libamrex with GNUMakefile with HDF5 lost the  copy of AMReX_PlotFileUtilHDF5.H

### ISSUE THREAD

**Issue by pkufourier** [AMReX-Codes/amrex#4212]
If shell environment  variables are set as 

export USE_HDF5=TRUE
export HDF5_HOME=HDf5_DIR

and use configure, make to build libamrex, the AMReX_PlotFileUtilHDF5.H will be forgotten to copy to the installed dir. 

But built with CMake and  -DAMREX_USE_HDF5=YES, this head file will be copied  correctly.

**Comment by WeiqunZhang** [comment]
Thanks for reporting this! We will fix it.
