### ISSUE TITLE
Suggestion for adding host/device setVal and copy on MultiFabs 

### ISSUE THREAD

**Issue by pkufourier** [AMReX-Codes/amrex#4237]
1 setVal on MultiFabs 
Right now the setVal<RunOn::Host> or Runon::Device can be only applied on fabs. For the MultiFabs only the setVal() can be called, which is operated on device by default if GPU is enabled. Therefore, an iteration over all fabs is required if the MultiFab is on host when calling the setVal().

2 Gpu::copy(Gpu::deviceToHost/hostToDevice) 
This function only accept the data pointers for arguments.  Considering add a function like the ParallelCopy which can be applied on Multifabs between host and devices, and have the instruction of  deviceToHost/hostToDevice. 

Of course these functions are gramma sugars, which can be easily realized by an iteration over all fabs of the MultiFab.  Yet with these functions the initialization and IO processes will be more convenience.

**Comment by WeiqunZhang** [comment]
For MultiFab I/O, you don't need to do anything special. AMReX will do memcpy between host and device if necessary.

To run setVal on the host,
```
{
    Gpu::LaunchSafeGuard lsg(false); // Disable GPU kernel launch
   mf.setVal(...);
   // ~LaunchSafeGuard inserted by the compiler will restore the previous setting
}
```

For memcpy, there are `dtoh_memcpy` and `htod_memcpy` for MultiFabs in AMReX_FabArrayUtility.H.

**Comment by pkufourier** [comment]
Get it. Thanks very much!
