### ISSUE TITLE
Interpolating data for face-centered multifabs

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/amrex#424]
Hi,

Is there a way of interpolating the data on a face-centered multifab built on a previous mesh onto the face-centered multifab built on the newly adapted mesh?

**Comment by asalmgren** [comment]
@nataraj2 we have been talking about this. Do you know what interpolation scheme you would want to use to fill fine face-centered data from coarse face-centered data?

**Comment by asalmgren** [comment]
Going to close this issue wince we are talking about face-centered multifabs in another issue. see #327.
