### ISSUE TITLE
runtime ERROR for 3D case

### ISSUE THREAD

**Issue by spring-png** [AMReX-Codes/amrex#4249]
During 3D program execution, the computer's memory keeps increasing until the program eventually exits. But it didn't happen for 2D case, even the number of grids is far more than 2D case.
Below is the exit message. I wonder what may cause the problem. And our program is based on Fortran.

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 26 with PID 0 on node DESKTOP-KGLUC53 exited on signal 9 (Killed).
--------------------------------------------------------------------------

**Comment by WeiqunZhang** [comment]
Try to use valgrind. For example,
```
mpiexec -n 4 valgrind --leak-check=yes --track-origins=yes --log-file=vallog.%p ./foo.exe ......
```

You can also try to compile the code in debug mode and run to see if there are any issues. (For GNU Make, build with `DEBUG=TRUE`.)

**Comment by spring-png** [comment]
Thank you very much for your kindly advice! We have solved the problem successfully. It's just a temporary multifab we forgot to release after usage. Thank you again for your advise!




At 2024-12-02 08:40:30, "Weiqun Zhang" ***@***.***> wrote:

Try to use valgrind. For example,

mpiexec -n 4 valgrind --leak-check=yes --track-origins=yes --log-file=vallog.%p ./foo.exe ......


You can also try to compile the code in debug mode and run to see if there are any issues. (For GNU Make, build with DEBUG=TRUE.)
