### ISSUE TITLE
PeleC stopped building with the Intel compiler

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#429]
After the baselib_f stuff changed it seems to have broken our ability to build PeleC with the Intel compiler due to it not linking `stdc++` any longer and now it also seems to produce duplicate `main` functions during linking. Here is the diff of how I solved it for us in the meantime, but not sure of the best way for it to be solved generally.
```
$ git diff Tools/GNUMake/comps/intel.mak
diff --git a/Tools/GNUMake/comps/intel.mak b/Tools/GNUMake/comps/intel.mak
index 81f73914f..0c5f0a6f0 100644
--- a/Tools/GNUMake/comps/intel.mak
+++ b/Tools/GNUMake/comps/intel.mak
@@ -23,15 +23,15 @@ ifeq ($(DEBUG),TRUE)
 
   CXXFLAGS += -g -O0 -traceback -Wcheck
   CFLAGS   += -g -O0 -traceback -Wcheck
-  FFLAGS   += -g -O0 -traceback -check bounds,uninit,pointers
-  F90FLAGS += -g -O0 -traceback -check bounds,uninit,pointers
+  FFLAGS   += -g -O0 -traceback -check bounds,uninit,pointers -nofor_main
+  F90FLAGS += -g -O0 -traceback -check bounds,uninit,pointers -nofor_main
 
 else
 
   CXXFLAGS += -g -O2 -ip -qopt-report=5 -qopt-report-phase=vec
   CFLAGS   += -g -O2 -ip -qopt-report=5 -qopt-report-phase=vec
-  FFLAGS   += -g -O2 -ip -qopt-report=5 -qopt-report-phase=vec
-  F90FLAGS += -g -O2 -ip -qopt-report=5 -qopt-report-phase=vec
+  FFLAGS   += -g -O2 -ip -qopt-report=5 -qopt-report-phase=vec -nofor_main
+  F90FLAGS += -g -O2 -ip -qopt-report=5 -qopt-report-phase=vec -nofor_main
 
 endif
 
@@ -72,7 +72,7 @@ ifeq ($(USE_OMP),TRUE)
   override XTRALIBS += -lifcoremt
 endif
 
-LINK_WITH_FORTRAN_COMPILER ?= $(USE_F_INTERFACES)
+LINK_WITH_FORTRAN_COMPILER ?= TRUE
 
 ifeq ($(LINK_WITH_FORTRAN_COMPILER),TRUE)
   override XTRALIBS += -lstdc++
```

**Comment by WeiqunZhang** [comment]
Does PeleC use `amrex/Src/F_Interfaces`?  If not, taking that out of `Make.PeleC` should solve the issue.

**Comment by WeiqunZhang** [comment]
OK. Without `F_Interfaces`, PeleC fails to compile with

    ../../../../PelePhysics/Eos/eos.F90(32): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PARALLEL]
        use parallel

I suggest PelePhysics switch to use `module amrex_paralleldescriptor_module` in `Src/Base/AMReX_ParallelDescriptor_F.F90`.

**Comment by jrood-nrel** [comment]
Thanks @WeiqunZhang . @drummerdoc  Can this go in with the other current changes to PelePhysics?

**Comment by jrood-nrel** [comment]
So I think this is a problem. I don't see how to remove the `use parallel` (It's unused in `eos.F90`, but used other places, unless we don't need `call amrex_parallel_init()`. I can add `USE_F_INTERFACES = TRUE` to `Make.PeleC`, but I can't inject `-nofor_main` I seem to need in the Fortran flags externally from AMReX because in `intel.mak`, the `FFLAGS` and `F90FLAGS` are cleared.

**Comment by WeiqunZhang** [comment]
Just remove F_Interfaces from Make.PeleC.

    diff --git a/Exec/Make.PeleC b/Exec/Make.PeleC
    index 70f925e..1d5a75e 100644
    --- a/Exec/Make.PeleC
    +++ b/Exec/Make.PeleC
    @@ -119,9 +119,9 @@ endif
     Bdirs   := Source Source/param_includes Source/Src_nd Source/Src_$(DIM)d Source/TurbInflow
    
     ifeq ($(USE_EB), TRUE)
    -  Pdirs := Base EB Amr Boundary AmrCore F_Interfaces/Base
    +  Pdirs := Base EB Amr Boundary AmrCore
     else
    -  Pdirs := Base Amr Boundary AmrCore F_Interfaces/Base
    +  Pdirs := Base Amr Boundary AmrCore

     endif

No, you don't need to call amrex_parallel_init().

**Comment by jrood-nrel** [comment]
It turns out `amrex_parallel_module` is used in more places than I anticipated. I think it will take more changes with PeleC than I am comfortable making on my own without Ray or Marc.

**Comment by drummerdoc** [comment]
I don't believe there is anything subtle here.  Just wail away on it until it compiles.

**Comment by asalmgren** [comment]
Can this issue be closed?

**Comment by jrood-nrel** [comment]
@asalmgren Yes I will close it since removing `amrex_parallel_module` from PeleC seems to be our issue now.
