### ISSUE TITLE
PeleC stopped building with the Clang/LLVM compiler

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#437]
It looks like the problem is the exact same as described here which seems to be accepted as a bug in the newest Clang compilers: https://stackoverflow.com/questions/43819314/default-member-initializer-needed-within-definition-of-enclosing-class-outside 

I was able to work around it by doing this:
```
$ git diff Src/Amr/AMReX_StateDescriptor.H
diff --git a/Src/Amr/AMReX_StateDescriptor.H b/Src/Amr/AMReX_StateDescriptor.H
index 0cabac24d..ab7b60f82 100644
--- a/Src/Amr/AMReX_StateDescriptor.H
+++ b/Src/Amr/AMReX_StateDescriptor.H
@@ -47,7 +47,7 @@ public:
         /**
         * \brief Bogus constructor.
         */
-        BndryFunc () noexcept = default;
+        BndryFunc () noexcept {}// = default;
 
         /**
         * \brief A Constructor.
```

**Comment by WeiqunZhang** [comment]
The fix you suggested has been implemented in the latest development.  Thanks!
