### ISSUE TITLE
Help with the MultiLevelToBlueprint function

### ISSUE THREAD

**Issue by freemalloc** [AMReX-Codes/amrex#438]
Hello,

My name is David Camp, I work at LBL.
I am using Amrex + IAMR with SENSEI (using Ascent/Conduit back-end) and having a problem with the output image. So I am trying to debug the problem.

I would like to use your MultiLevelToBlueprint and WriteBlueprintFiles functions to save the data before the SENSEI update call.

What I would like help with is filling in the arguments to the MultiLevelToBlueprint function with data from the Amr class. It would also be great to have the step value for the WriteBlueprintFiles function. IE...

AmrInSituBridge::update(Amr *dataSource)
{
    int ret = 0;
#if defined(BL_USE_SENSEI_INSITU)
    if (doUpdate())
    {

    // new debug code
    conduit::Node bp_mesh;
    MultiLevelToBlueprint( /* dataSouce would fill in the variables */,
                           bp_mesh);
    WriteBlueprintFiles(bp_mesh, "bp_example_hdf5", 0, "hdf5");

I hope for someone with knowledge of AMRex This would not be hard.

Thanks,
David

**Comment by drummerdoc** [comment]
There's probably cool and clever ways to do this.  Here's a in-your-face way to do it:
```
    void MultiLevelToBlueprint (int n_levels,
                                const Vector<const MultiFab*> &mfs,
                                const Vector<std::string> &varnames,
                                const Vector<Geometry> &geoms,
                                Real time_value,
                                const Vector<int> &level_steps,
                                const Vector<IntVect> &ref_ratio,
                                conduit::Node &bp_mesh);

So

   Amr amr;
   ...<code that initializes and loads up amr>...
  auto& levs = amr.getAmrLevels();
  int Nlevs = levs.size(); 
  Vector<Geometry> geoms(Nlevs);
  for (int lev=0; lev<geoms.size(); ++lev) {
    geoms[lev] = levs.Geom();
  }
  Vector<int>& level_steps(Nlevs);
  for (int lev=0; lev<level_steps.size(); ++lev) {
    level_steps[lev] = amr.levelSteps(lev);
  }
  // I assume you have your vector of MultiFabs for the data, the bp_mesh object, and time_value
  MultiLevelToBlueprint(Nlevs,mfs,varnames,geoms,time_value,level_steps,rrs,bp_mesh);
```

**Comment by burlen** [comment]
Hi David, I will help you. Next time you are at the lab, lets meet.

**Comment by asalmgren** [comment]
Burlen, David -- can we close this issue?

**Comment by freemalloc** [comment]
yes, thanks for the help.
David

    On Sunday, April 21, 2019, 5:34:57 PM PDT, asalmgren <notifications@github.com> wrote:  
 
 
Burlen, David -- can we close this issue?
