### ISSUE TITLE
binary output format (HDF5?)

### ISSUE THREAD

**Issue by darylbond** [AMReX-Codes/amrex#441]
The native output format for AMReX generates an excessive number of files and uses non-binary format for the header files. This leads to unnecessary overhead in both storage and time when undertaking data management tasks. For example, it took over an hour for me to delete the results from a small AMR simulation (<80GB) simply due to the number of files involved. Transferring results to my local machine (rsync) also takes excessive amounts of time when compared to previous transfers of equivalent simulation data using the HDF5 output of Chombo.

While there is an example hdf5 output included in the source this has not been integrated into the core functionality and is thus only useful for specific use cases rather than as a general option for plot and checkpoint output. Using this example as a template I have implemented hdf5 plot output for my own use but this required modification of core AMReX files (AMReX_Amr and AMReX_AmrLevel).  Checkpointing is a somewhat more involved task although not particularly difficult to implement.

Essentially I am asking that HDF5 output (or similar) be implemented in the core code such that there is a built in option for single file binary output with checkpointing. If this already exists and I have simply missed it then please enlighten me!

**Comment by asalmgren** [comment]
Daryl -- if I read your comment correctly you have implemented an improved
hdf plotfile writer -- would you be willing to share the source files so we
could look at integrating those into the repo?

We haven't had the resources to date to improve the hdf5 functionality but
we would certainly like to have better/faster I/O.

Thanks

**Comment by darylbond** [comment]
I'm happy to share my work.

This should have all of the functionality for plot file writing as a hdf5 file. The hdf5 library wrapper is incomplete and a bit rough and has compound datatypes for use with the Chombo file format. I believe the hdf5 example in amrex builds these in a different manner. Also note that I encountered issues with writing attributes to file for nProcs > 2 when using the below options, I'm sure a HDF5 guru will know why.

```
        ret = H5Pset_all_coll_metadata_ops(file_access, true);
        ret = H5Pset_coll_metadata_write(file_access, true);
```

I also tried to keep all of the data structure stuff hidden from the user by getting them to just supply a MultiFab. That is, rather than getting them to override the writePlotFile() routine, get them to override a getPlotData() routine instead which just compiles a MultiFab. If the user wants to do anything else they can do it in pre or post write.

I'm sure you have your own ideas/constraints on how to implement a comprehensive binary I/O solution so please take the following and use as little or as much of it as you like.

[share.zip](https://github.com/AMReX-Codes/amrex/files/3041382/share.zip)

**Comment by darylbond** [comment]
I have since implemented HDF5 checkpointing at [https://github.com/darylbond/amrex/tree/cerberus](url) if anyone is interested.

**Comment by drummerdoc** [comment]
Hey Daryl,
Can you say anything about the performance you observe with this new checkpoint format compared to that of the native amrex IO, particularly for large runs (order TB checkpoints, thousands of MPI ranks)?  
Thanks!
-Marc

**Comment by darylbond** [comment]
Unfortunately I don't have any performance benchmarks for I/O with HDF5, especially for large runs. I have very limited access to compute resources so my biggest runs thus far have sub 1000 MPI rank. At this scale I do not see any significant variation in I/O performance but I wouldn't expect to considering how small the output files are (<<1TB).

My incentive for implementing HDF5 was the massive overheads I was experiencing with file management due to the quantity of files produced with the native file system. I also have extremely stringent limitations on the number of files I am allowed to generate on my HPC system and so a unified file format was a necessity.

**Comment by asalmgren** [comment]
Even if the performance isn't great it's something that may be useful for
other users who prefer hdf5, so we are definitely interested in looking at
what you've done

If the hdf5 functionality works correctly (which I assume you've tested),
we have hdf5 folks here who could probably help with performance issues if
there are any.

Thanks

**Comment by darylbond** [comment]
@asalmgren The hdf5 implementation works for my specific use case (plot file output, checkpoint output, checkpoint input for restart) but it definitely needs more general testing.

Please feel free to use this contribution however you wish.
