### ISSUE TITLE
CMake find_dependency(MPI REQUIRED)

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#444]
Since commit 4a8ec6d6e0aa44d1ba35cdae922d5cb0281ab953 I experience problems with my CMake configuration because I do not setup Fortran MPI bindings (and I do not build AMReX Fortran bindings) 

https://github.com/AMReX-Codes/amrex/blob/a64dc49fc0829c9dd9c78c7bb19d2bb4e7f05eec/Tools/CMake/AMReXConfig.cmake.in#L79-L93

using  `find_depedency(MPI REQUIRED)` will also look for Fortran MPI on my machines even if the Fortran interfaces are not going to be built. My current fix to this is to change this line to `find_dependecy(MPI REQUIRED COMPONENTS CXX)`.

Would you consider that change? (@mic84 ?)

**Comment by mic84** [comment]
Hi Maikel,

the MPI Fortran libraries are not needed by AMReX if the Fortran interfaces are not enabled.
It is up to the application code build system to take care of any additional libraries the application code needs. We are not planning on adding library dependencies which are not strictly required by thre AMReX build. I am gonna close this issue. You can re-open it if you have further questions.

**Comment by maikel** [comment]
I think you misunderstood me. Your current Configfile looks for Fortran MPI libraries and this breaks my builds. I proposed to fix that.

**Comment by maikel** [comment]
It is not possible for me to reopen this issue.

**Comment by mic84** [comment]
Hi Maikel,
I did misunderstand you: sorry about that. What you reported is indeed the result of a merge gone wrong :-)
I just pushed a fix to development. Let me know if it works for you.

**Comment by maxpkatz** [comment]
I can reopen it, doing so until you can verify @mic84's fix.

**Comment by maikel** [comment]
The issue is gone. Thank you!
