### ISSUE TITLE
restart bug of ParticleContainer

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#454]
In restart function, when the finest level of current ParticleCon is smaller than the finest level in the file, it will not work as expected. In the worst case, the program will be crashed.

**Comment by atmyers** [comment]
Could you try again on the latest development branch and see if that fixes the issue?

**Comment by GumpXiaoli** [comment]
I don't think the latest development branch has fixed this issue. For now, I have found two points that may cause bugs.

First, when determine whether it is a dual-grid restart or not, the logic may have problems. In my case, the particleCon grid has only one level, while the particle_box_array of the checkpoint file has 4 levels with all particles in the finest level. The `dual_grid` should be true, however it is set to false in the current code of the latest development branch. 

Second, when reading the particle data, the ifstream `ParticleFile` should be opened with binary mode. (in the line 3491) Otherwise, the stream position will come wrong in some cases when reading file. My another case has this problem, and it is fixed after the `ParticleFile` is changed to be opened in binary mode.

**Comment by atmyers** [comment]
First, thanks for the point about opening in binary mode. That has been corrected.

Second, I fixed the logic to handle to the case where a level is lost and restart AND not all levels have particles. I tested this using our code Castro, and it seems to work. Could you let me know if this solves the problem for you? Both of these changes are on the development branch.

**Comment by GumpXiaoli** [comment]
It seems ok for all my cases. Thanks for your work.
