### ISSUE TITLE
Lattice Boltzmann in AMReX?

### ISSUE THREAD

**Issue by EduardoMolina** [AMReX-Codes/amrex#455]
Hi,

I would like to know if there is an ongoing effort to implement Lattice Boltzmann methods in the AMReX framework?

Best,

Eduardo

**Comment by asalmgren** [comment]
Not that I know of but I think it should be very doable.

**Comment by rupertnash** [comment]
Hi! We are working on one here at EPCC at the University of Edinburgh. 

Still at a relatively early stage, but the code is here: https://github.com/otbrown/LAMBReX/tree/AMR

**Comment by EduardoMolina** [comment]
Hi @rupertnash ,

Thanks! I will have a look at the code.

Later, I will contact you to see where I can contribute.

Eduardo
