### ISSUE TITLE
Embed lower dimensional grids in higher dimensional grids

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#456]
I would like to embed a one or two-dimensional mesh into a three-dimensional one while still using algorithms from `AmrCore`. This requirement stems from mixing simulations of different dimension. My idea was to "simply" define a mesh of size `Box{{}, {31, 0, 0}}` with refinement ratio `IntVect{2, 1, 1}`. Using `AmrCore` to generate refinements will lead to base grids sizes like  `Box{{}, {31, 1, 1}}` because of  `AmrMesh::MakeBaseGrids()`:

https://github.com/AMReX-Codes/amrex/blob/a9af990424d9f9b0f7d7ace2c79d984f75bc7a86/Src/AmrCore/AMReX_AmrMesh.cpp#L385-L398

I also encountered problems regarding the `blocking_factor` as I do not use `ParmParse` and the constructor of `AmrCore` unconditionally checks for a blocking factor of 8. My current fix is to call `SetBlockingFactor` after construction and I changed AMReX to not check the input parameters:

https://github.com/AMReX-Codes/amrex/blob/a9af990424d9f9b0f7d7ace2c79d984f75bc7a86/Src/AmrCore/AMReX_AmrMesh.cpp#L63

The first point is more important than the second. Any thoughts on your side?

Thank you!

**Comment by asalmgren** [comment]
Regarding the first question -- size = 0 typically implies there is nothing
there.  What is the reason for not liking size = 1 in the other directions?

Regarding the second question -- calling SetBlockingFactor after
construction seems like a good solution.   Was the issue that you weren't
able to make that call before blocking factor is used?

**Comment by maikel** [comment]
(i) 
I phrased that badly, sorry. I was trying to say size 32x1x1 or a Domain box `amrex::Box{{0,0,0}, {31,0,0}}` which has including lower and upper bounds.

(ii)
to make that approach work I had to change the current source file of AMReX which currently unconditionally checks for blocking factor in the constructor, i.e. before I can even change the blocking factor, at least without using ParamParse.

**Comment by asalmgren** [comment]
It only tries to read the blocking factor if it sees it in the inputs file
(ie if countval returns an integer > 0)

**Comment by maikel** [comment]
Reading the blocking factor is not the problem. Checking the input is by default enabled, as you can see in 

https://github.com/AMReX-Codes/amrex/blob/a9af990424d9f9b0f7d7ace2c79d984f75bc7a86/Src/AmrCore/AMReX_AmrMesh.cpp#L63

and later in that function, it will start `CheckInput()`.

https://github.com/AMReX-Codes/amrex/blob/a9af990424d9f9b0f7d7ace2c79d984f75bc7a86/Src/AmrCore/AMReX_AmrMesh.cpp#L320-L324

While `AmrMesh::CheckInput()` rightfully checks for a valid blocking factor, as can be seen in this reference:

https://github.com/AMReX-Codes/amrex/blob/a9af990424d9f9b0f7d7ace2c79d984f75bc7a86/Src/AmrCore/AMReX_AmrMesh.cpp#L870-L887

As for this second "issue", I would prefer to control that behavior in the constructor or turn it off by default.

Anyway, I have more concerns with my "first" issue, as that one is relevant for my research, where I have multiple 1D reactive simulations providing boundary conditions to a 3D simulation (with EB).

**Comment by WeiqunZhang** [comment]
(1) That can be fixed.  Since AMReX is not usually used in the mode you are using, you might notice more this kind of issues.

(2) Instead of modifying AMReX source code, I suggest you use `ParmParse::add` after `amrex::Initialize` in your code.

    ParmParse pp("amr");
    pp.add("check_input", false);

**Comment by WeiqunZhang** [comment]
Does the latest development branch fix issue 1?

**Comment by maikel** [comment]
The development branch works as intended. Similar to your proposal I now use

```cpp
  amrex::ParmParse pp("amr");
  pp.add("blocking_factor_x", 8);
  pp.add("blocking_factor_y", 1);
  pp.add("blocking_factor_z", 1);
```

prior to the construction. Using multiple classes devived from `amrex::AmrCore` one only has to remember to reset that for each mesh.
