### ISSUE TITLE
Summitdev: Allocate runs out of memory in Microphysics test_react suite with PGI 17.4, GCC 6.3.1

### ISSUE THREAD

**Issue by dwillcox** [AMReX-Codes/amrex#46]
On OLCF Summitdev, the error arises when running the Microphysics test_react test suite on the cudadevice branch with the gpu branch of amrex using PGI 17.4 configured with GCC 6.3.1 with CUDA Fortran enabled.

The compile line is as follows:

`make -j COMP=PGI NDEBUG=t MPI= OMP= ACC= CUDA=t NETWORK_DIR=ignition_reaclib/URCA-simple INTEGRATOR_DIR=VODE90 EOS_DIR=helmholtz`

Error:

`0: ALLOCATE: 281473269719360 bytes requested; not enough memory`

This allocation error originates in `amrex/Src/F_BaseLib/knapsack.f90`, specifically the function `make_box_key` that does not properly import the value of `dm` as the subroutines in the same scope. `dm` is thus essentially uninitialized and takes a large value, leading the declaration `integer :: r(dm)` in `make_box_key` to attempt to allocate this absurd amount of memory.

**Comment by dwillcox** [comment]
Things that do not fix this issue:

- Adding `implicit none` to `make_box_key`
- Changing the declaration of `dm` in `sfc_module` to `integer, save :: dm = 3`
- Importing `dm` to `make_box_key` by adding `use sfc_module, only: dm`

A workaround for this issue:

- Changing the argument list of `make_box_key` to pass `dm` from the calling subroutine `init_sfc_module`

PR incoming.

**Comment by maxpkatz** [comment]
Closed by #47
