### ISSUE TITLE
[Feature Request] AmrMesh::n_error_buf as Vector<IntVect> instead of Vector<int>

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#460]
Hi,

IIUC, `Vector<int> AmrMesh::n_error_buf` is the number of ghost-cells for each refinement level in each direction for the generated `TagBoxArray`. In my case, I would like to use non-uniform ghost cell extents. Would you consider a change? AFAIK it seems fairly easy to do as the infrastructure exists, but it might be a breaking change for others!

Thank you for your consideration,

Maikel Nadolski

Edit:

I can also provide Pull Requests for future "Feature Requests" if this is easier for you. But you have much more insight into details and possible breaks for AMReX than I do.

**Comment by drummerdoc** [comment]
Mailkel,
Actually the Vector is over amr levels, not directions.  And the integer at each level denotes a "buffer" region around the cells that are explicitly tagged by user refinement criteria.  All cells either tagged or in this buffer region are included in cells that are refined in the new BoxArray generated during the regrid process.  It might be a reasonable request to support anisotropic buffering, but the interface would have to be completely changed, and that is likely to break a lot of code.  It might be easier for everyone if you have this need if you can find a way to use the API in place.  For example, you can generate an error tagging routine that explicitly tags cells in an anisotropic fashion directly (before buffering). Alternatively, perhaps you can suggest an API that would (ideally) be backward compatible AND support your need.  I'm happy to try to help you formulate such a thing (or help you write the error tagging routine I suggested above).
-Marc

**Comment by maikel** [comment]
Hi Marc,

> Actually the Vector is over amr levels, not directions

That what I meant to say, sorry for my wrong english. 

> And the integer at each level denotes a "buffer" region around the cells that are explicitly tagged by user refinement criteria.

I observed that setting `n_error_buf` changed the ghost cell width of the generated `TagBoxArray` and thus I assumed that wrong meaning. Thank you for clarifying this.

> It might be a reasonable request to support anisotropic buffering, but the interface would have to be completely changed, and that is likely to break a lot of code.

This is why I wrote it is a breaking(!) change and thus I understand if it is rejected.

> For example, you can generate an error tagging routine that explicitly tags cells in an anisotropic fashion directly (before buffering). 

As one can see in the following reference of `AmrMesh::MakeNewGrids` function, the `TagBoxArray` is always generated with a uniform grow factor.

https://github.com/AMReX-Codes/amrex/blob/46b457fd98997bb83765b83c209318b1154fdfac/Src/AmrCore/AMReX_AmrMesh.cpp#L489-L510

My real issue is, that I sometimes only need ghost cells in one direction (or two out of three). As an example: I embed a one-dimensional grid into a three-dimensional one by having it of size, let's say, 128x1x1. If `n_error_buf` is set to 2, `AmrMesh` constructs a `TagBoxArray` of size 36x3x3 which does not seem helpful. I can write my tagging routines to overcome that, but at the same time I simply wondered if there might be a way to tell `AmrMesh` to use anisotropic ghost cell widths.

Could I clarify my concerns?

Thank you,
Maikel

**Comment by drummerdoc** [comment]
Maikel,
I believe you are still a little mixed up in terminology, and the notes in our code probably did not help matters.  Let me try to clarify.

What happens during a regrid is that coarse cells are tagged by the user's refinement criteria functions.  Those tagged cells define a generalized "region" (a collection of cells), and that region is grown by the `n_error_buf` parameter for that level by adding cells in each coordinate direction around the tagged cells.  Then, through a complicated process, a BoxArray is created to contain all the cells in that grown region, while also satisfying the "proper nesting" condition (that there be at least `n_proper` cells between the boundary of the new fine level and the coarse level boxes originally used to collect tags).  When the final set of boxes are thus generated, they are refined to the desired level (skipping some unnecessary detail here...).  The BoxArray that results from this process is the set of cells in index space that defines the "valid region" of the new amr level object at that refinement level.  

(here's where I believe the misunderstanding is). Data at each level in the amr hierarchy is created based on the BoxArray defined for that level.  This data can be defined with cell, face, edge or node centering, and with as many grow/ghost cells as you like, including an anisotropic number per direction.  The centering and grow cells of data allocated on the level for your use are  *independent* of the BoxArray generated by the regrid process.

So, I believe that you are conflating the process used to define the valid region at an amr level with the process the user follows to allocate data on the valid region.

**Comment by asalmgren** [comment]
I actually believe that it could be very simple to make an IntVect rather
than an int of n_error_buf at each level to accomplish this; the user could
still specify a single value for each level, or different values for each
coordinate direction.

We have done the same with blocking_factor already (allowing the user to
either specify a single "blocking_factor" which is the same for x,y and z
directions or separate blocking_factor_x, blocking_factor_y,
blocking_factor_z).

Let us take a closer look at this.

**Comment by maikel** [comment]
> So, I believe that you are conflating the process used to define the valid region at an amr level with the process the user follows to allocate data on the valid region.

I agree I got confused. The grow size of the tag array should probably not be my concern.

**Comment by asalmgren** [comment]
The importance of n_error_buf is that it gives you an easy way to create
your fine grids in such a way that the coarse-fine boundary is away from
the feature you are tagging on.

Imagine that you have a feature in coarse cell(i,j) that you want to
resolve on a fine grid.   You tag cell (i,j) for refinement.  But if you
aren't going to regrid every time step and the feature will move one coarse
cell every coarse time step for example, then you want to make sure you
create a fine grid large enough to hold the feature for more than one time
step.

For example, if you set n_error_buf = 2, then you are effectively saying
that if you tag cell (i,j), you are also tagging all the cells from
(i-2,j-2) through (i+2,j+2).

Note that if this grown region extends outside of the domain then it gets
cropped, so in your specific case I'm not sure that having n_error_buf in
your "thin" directions will actually be a problem.

But in the more general use case we should allow n_error_buf to be an
IntVect rather than an int -- we have done this with blocking_factor,
max_grid_size, etc ...

I'm testing out now a version with IntVect instead of int to see what
breaks :-)

**Comment by asalmgren** [comment]
Maikel -- I've made the change -- can you give it a try?

**Comment by maikel** [comment]
> I'm testing out now a version with IntVect instead of int to see what
breaks :-)

It should break each code which inherits from `AmrCore` or `AmrMesh` respectively and relies on the accessible member `n_error_buf` for being a `Vector<int>`. My local code breaks already, but the adjustments are very minor. ;o)

> Maikel -- I've made the change -- can you give it a try?

ASAP, most probably on Tuesday.

Have a happy Easter,
Maikel Nadolski

**Comment by asalmgren** [comment]
I agree but not all codes based on AmrCore even reference n_error_buf directly.  Let me know if your code works with the changes (and your fix)

**Comment by maikel** [comment]
> Let me know if your code works with the changes

My embed simulation works perfectly fine and your changes are observable. It helps in my particular case with debugging because the `TagArray` is of similar size as my data now. But... if you are so open to these changes, why leave `n_proper` as is?

I am not sure if there are some nasty interactions with enabled EB, which I have to investigate first. There will be a separate Issue, if any.

If forgot this time, but I will try to append small test cases in future issues.

Thank you,

Maikel Nadolski
