### ISSUE TITLE
Using FillPatchTwoLevels on MultiFabs without EB when EB are enabled

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#468]
Hey,

In my computations, I try to have multiple domains, where one domain makes use of EB and the other domains don't. Each simulation currently works in isolation, but when I want to do an EB-less computation linked against an EB-enabled AMReX, I have to initialize the EB database prior to using FillPatchTwoLevels, with `AllRegularIF` for example. As an example: calling `FillPatchTwoLevels` creates an `FPInfo` object which again queries the EB database to make an EB FAB factory...

Here is a snippet from the constructor of `FPInfo`:
https://github.com/AMReX-Codes/amrex/blob/7252f34ccf209827d430c679330429a84588f14d/Src/Base/AMReX_FabArrayBase.cpp#L1114-L1121

* Now I wonder what implications does it have -- if any -- if I have configured the EB database and the *top* index space does not map the EB geometry of the `MultiFab` which I want to fill (which should be `AllRegularIF`). Shouldn't it take the Factory of the MultiFab which are used as Parameters to FillPatchTwoLevel? 

* Can the interface somehow be changed to tell `FPInfo` which fab factory type to create?

* I do not really understand FPInfo well enough yet. What is its purpose? I tried to search a bit, but couldn't find an explanation and I haven't dug too much into its source code yet.

Thank you,
Maikel Nadolski

**Comment by WeiqunZhang** [comment]
I don't exactly know what you are trying to do and what's the right thing to do in your case.  I will just try to explain what `FillPatchTwoLevels` does.

`FillPatchTwoLevels` fills the destination `MultiFab` on the fine level based on the source `MultiFab` data on the coarse and fine levels.  If fine source data are available, we copy the data from source to destination without using any EB information.  If parts of the destination `MultiFab` are not covered by the source fine `MultiFab`, we need to interpolate from the coarse `MultiFab`.  But we do not want to do interpolation in regions that do not need it. `TheFPinfo` provides `BoxArray`, `DistributionMapping` and `Factory` for the interpolation region.  The interpolation needs to use EB information (unless it is piecewise constant) to avoid using garbage data.  `FillPatchTwoLevels` takes `Interpolater* mapper`.  For EB, one could use `eb_cell_cons_interp`, `eb_lincc_interp`, or their own interpolater. `amrex::EBCellConservativeLinear::interp` gets EB information from `const FArrayBox& crse` parameter, which in turn gets from a MultiFab build with the factory in `TheFPinfo`.

**Comment by maikel** [comment]
> I don't exactly know what you are trying to do and what's the right thing to do in your case. I will just try to explain what FillPatchTwoLevels does.

I have multiple `amrex::EB2::IndexSpace` registered with the EB database and I want to choose one for the FillPatchTwoLevels call.

> FillPatchTwoLevels fills the destination MultiFab on the fine level based on the source MultiFab data on the coarse and fine levels. If fine source data are available, we copy the data from source to destination without using any EB information. If parts of the destination MultiFab are not covered by the source fine MultiFab, we need to interpolate from the coarse MultiFab. 

Yes.

> But we do not want to do interpolation in regions that do not need it. TheFPinfo provides BoxArray, DistributionMapping and Factory for the interpolation region. The interpolation needs to use EB information (unless it is piecewise constant) to avoid using garbage data.

Then my concerns were right. Would you accept a PR where I add an overload which takes an `IndexSpace` as an additional parameter? The current behavior is to take the top one.

**Comment by WeiqunZhang** [comment]
But it seems like you can push your EB2::IndexSpace onto the top first and then pop it when it's done.

As for adding an additional parameter, maybe it is a good idea because it is easier for people to reason about how EB gets used.  Please feel free to submit a pull-request.

**Comment by maikel** [comment]
> But it seems like you can push your EB2::IndexSpace onto the top first and then pop it when it's done.

AFAIK pushing and popping is a very bad idea, because you use a naked pointer for `IndexSpace::push`. That way, you might convert a non-owning pointer to `IndexSpace` into an owning `unique_ptr<IndexSpace>`. This risks a double-free when doing a `IndexSpace::pop`.

A better idea might be to pass `std::unique_ptr`s to `IndexSpace::push`instead of raw pointers. Make `amrex::EB2::Build` return a `std::unique_ptr` instead of pushing to the global `IndexSpace` instance storage. Something along that line. Alternatively let `IndexSpace::pop` return a `std::unique_ptr` by value instead of nothing.

> As for adding an additional parameter, maybe it is a good idea because it is easier for people to reason about how EB gets used. Please feel free to submit a pull-request.

Yes, I will gladly do so. That way one omits possible complications which I mentioned above.

**Comment by WeiqunZhang** [comment]
Yes, the ownership could become an issue.  So my plan is to switch shared ptr next month.

**Comment by maikel** [comment]
Solved by #472.
