### ISSUE TITLE
Some bugs when compiling to float

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#470]
I find two bugs when compiling to float in my recent tests:

1.  `ParticleRealDescriptor ` in `ParticleContainer`:
      If BL_SINGLE_PRECISION_PARTICLES is not used and the BL_FLOAT is used, `ParticleRealDescriptor `should be double. However in current development  branch,  `ParticleRealDescriptor ` will be set to float. 

2. `convertToNativeDoubleFormat` in `RealDescriptor `:
  When BL_FLOAT is used, the convertion will be wrong since `FPC::NativeRealDescriptor` will be float instead of double. It should be noted that this function is designed for converting to native double format.

My current solution is to add `FPC::Native64RealDescriptor`, just like `FPC::Native32RealDescriptor`, and replace `NativeRealDescriptor` in `ParticleContainter` class and `convertToNativeDoubleFormat `function. 

It works for my cases.

**Comment by atmyers** [comment]
Thanks for reporting this. Is https://github.com/AMReX-Codes/amrex/pull/471 equivalent to your fix?
