### ISSUE TITLE
Document installation via spack

### ISSUE THREAD

**Issue by RemiLehe** [AMReX-Codes/amrex#473]
This is part of the review in openjournals/joss-reviews#1370.

It seems that `amrex` can be installed via `spack`, which may be very convenient  for some users. However, this is not documented in the [building section](https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX_Chapter.html) of the documentation. Would it make sense to document the spack installation? Also, will this installation mechanism be maintained (e.g. by adding the latest compilation options, such as enabling GPU support, etc.)

**Comment by asalmgren** [comment]
We have added comments in the "Downloading the Code" section and the "Building AMReX" section to let users know they can use spack to install amrex.  We appreciate the suggestion!
