### ISSUE TITLE
[Feature Request] Purge static variables from amrex::Geometry!

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#477]
`amrex::Geometry` as a class has some static class variables, namely 

```cpp
    static int     spherical_origin_fix;
    static bool    is_periodic[AMREX_SPACEDIM]; //!< 0 means not periodic
    static RealBox prob_domain;
```

This makes it extremely difficult to setup multiple domains with different problem domains while using `AmrCore` capabilities. I.e. constructing two objects of a class derived from `AmrCore` with two different problem domains will silently(!!) use the first problem domain for both objects.

Does AMReX (or any current Application downstream) really, really depend on these member variables being static or could they be changed to normal class variables. What is the rationale for only allowing one problem domain for the whole application.

I can provide PRs if you do not have the capabailities to do so. I am in general very sceptical towards global variables or static class member variables respectively, looking at you `AmrMesh::intialized`.

Thank you,
Maikel

**Comment by WeiqunZhang** [comment]
We will look into this.  Many things are what they are for historical reasons.  Changing them will break people's code.  We will see what we can do.

**Comment by maikel** [comment]
> Many things are what they are for historical reasons.

I understand that really, really well.

> Changing them will break people's code.

I know. :-(

I will craft some 'emergency' ;-) plans for my current multi-domain project:

- Plan 1: maintain an AMReX fork where `amrex::Geometry` is changed
- Plan 2: Try to create local `Geometry`, `AmrMesh` and `AmrCore` classes where most logic is copied from AMReX but with non-static member variables.

I already started to apply some changes to AMReX in a separate branch to see what depends on it internally in AMReX and at the first glance it at least seemed to be possible. I absolutely can not grasp how many application exist downstream who depend on that.

**Comment by WeiqunZhang** [comment]
Some user's functions might call `Geometry::isCartesian()` or other static functions.  If those functions are deep in a hierarchy that makes it hard to get an Geometry object.  The changes required for them would quite extensive.

My current idea is to create an AMReX class and store them the way similar to EB IndexSpace.  (I still need to make changes to EB IndexSpace.  I am going to keep the unique_ptr.  But we can make sure the push function doesn't take ownership if it already owns it.  If it already owns it, it can simply move the existing one to the top.  Something like that.)  Then we can have Geometry member function `isCartesian` and `amrex::isCartesian`.  The latter will get the information via the top of AMReX stack.  It will still break user codes.  But the fix will be easy by switch from `Geometry::isCartesian` to `amrex::isCartesian`.

**Comment by maikel** [comment]
> Some user's functions might call Geometry::isCartesian() or other static functions. If those functions are deep in a hierarchy that makes it hard to get an Geometry object. The changes required for them would quite extensive.

Mhm, yes.

> I still need to make changes to EB IndexSpace. I am going to keep the unique_ptr. But we can make sure the push function doesn't take ownership if it already owns it. If it already owns it, it can simply move the existing one to the top. Something like that.

Please note, that, for me, it is not that urgent anymore since you let me add a function overload to FillPatch.

Thank you for your efforts...

 I will still investigate a way to reuse the existent AmrMesh code without breaking any user code. But everything I come up with will lead to some kind of bifurcation of `AmrMesh` or similar.

**Comment by WeiqunZhang** [comment]
@maikel  Could you give `weiqun/amrex` branch a try?  If it works out, we will merge it to `development` at the beginning of next month.

**Comment by maikel** [comment]
Dear Weiqun Zhang,

it simply works like a charm. I didn't even have to change one line of code and my domains are now correctly set up! You exceeded my expectations with your speed and saved me lots of work. 

Thank you very much!

**Comment by maikel** [comment]
>  we will merge it to development at the beginning of next month.

Any news on this front?
