### ISSUE TITLE
Interpolation Methods in amrex/OldTutorials/HeatEquation_EX3_F/advance.f90

### ISSUE THREAD

**Issue by geoclustc** [AMReX-Codes/amrex#48]
Hello,
I want to know learn more about the interpolation method of **ml_edge_restriction_c** and **ml_restrict_and_fill** in **amrex/OldTutorials/HeatEquation_EX3_F/advance.f90**. 

I partly modified the example and ran the code, but the difference is rather larger between the result with global finer mesh and that with AMR. I set different conditions and find the trouble is most likely the interpolation method.

I'll appreciate it if you can provide some information (method or some paper) for me! Thank you!

**Comment by WeiqunZhang** [comment]
The old Fortran code is no longer supported.
