### ISSUE TITLE
[Tutorial Request] MLMG nodal solve for Poisson equations over multiple Levels

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#482]
I open this issue as a followup of my question in #342. I managed to reproduce the single level solve as in the tutorial but I do not know what to do for the multi-level solve.

**Comment by WeiqunZhang** [comment]
In the development branch, the nodal Poisson tutorial now shows how to do multi-level composite solve.

**Comment by maikel** [comment]
Wonderful!
