### ISSUE TITLE
AMReX_Geometry.cpp:Geometry::periodicShift warning

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#483]
I'm guessing `periodicShift` isn't called anywhere when DIM<2, but since there is no ifdef around https://github.com/AMReX-Codes/amrex/blob/eed6d839b523051b0eb8ca0b71be7fb20bac7f3c/Src/Base/AMReX_Geometry.cpp#L280, if I build with Clang, it will report that `is_periodic[1]` is out-of-bounds if I compile with DIM=1. Should there be some kind of ifdef around this?

**Comment by WeiqunZhang** [comment]
Fixed in commit 58d27d5eea4bf.  Thanks!
