### ISSUE TITLE
AMReX_AmrCore.cpp uninitialized variables

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#484]
Another minor thing because it looks like a print function, but it appears `imax` and `imin` can be uninitialized at `AMReX_AmrCore.cpp`: https://github.com/AMReX-Codes/amrex/blob/eed6d839b523051b0eb8ca0b71be7fb20bac7f3c/Src/AmrCore/AMReX_AmrCore.cpp#L185

**Comment by WeiqunZhang** [comment]
It shouldn't happen, unless there is integer overflow. It goes something like for the first iteration.

    long vmin = std::numeric_limits<long>::max();
    int imin;
    long vmin_this = std::numeric_limits<long>::max();
    int imin_this;
    long v = bx.volume();
    if (v < vmin_this) { // This is expected to be true
        vmin_this = v;
        imin_this = ...;   // imin_this is set here.
    }
    if (vmin_this < vmin || ...) { // expected to be true
        vmin = vmin_this;
    }

**Comment by WeiqunZhang** [comment]
Could you use `amrex::Print()` to print out `bs` when you have the problem?

**Comment by jrood-nrel** [comment]
It's probably not really a problem at runtime and I'm not experiencing it. It's just that static analysis tools don't like seeing that these variables can be uninitialized in a particular situation so I thought I would report it.

**Comment by WeiqunZhang** [comment]
I see.  I made changes in 5242faf9f2cd8bbda37f.  This should get rid of the complaint.  Will like to know what other problems they found.  What are you using?  Thanks!

**Comment by jrood-nrel** [comment]
Thanks! I have cppcheck (http://cppcheck.sourceforge.net) hooked up to PeleC nightly now, which is pulling in AMReX files. It's not perfect because I don't have all the ifdef options being checked, but I'm trying to address some of the error and warning reports it's giving me. The output can be seen here https://my.cdash.org/viewNotes.php?buildid=1653315
