### ISSUE TITLE
Option to abort if amount of data on level overflows GPU memory

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#485]
Performance can suffer greatly if the amount of data on a AmrLevel per rank exceeds the amount of memory in the GPU. It would be useful to have a flag that aborts if we detect that we're using more than the available memory, so that we can go back and tune the load balancing instead of letting the performance tank.

**Comment by WeiqunZhang** [comment]
Currently in AMReX, there are

    std::size_t Device::totalGlobalMem ()

and 

    std::size_t Device::freeMemAvailable ()

I am not sure which is better.  Let the application implement the abort option or have that in AMReX.

**Comment by atmyers** [comment]
Maybe we could have the memory arena in AMReX optionally check one of those values whenever it needs to allocate more?

**Comment by WeiqunZhang** [comment]
Note that the commit message has a typo.  The parameter is `amrex.abort_on_out_of_gpu_memory`.
