### ISSUE TITLE
Problem running the heat equation tutorial (fortran)

### ISSUE THREAD

**Issue by kshariff786** [AMReX-Codes/amrex#490]
I am running the heat equation tutorial (as is; no modifications) on my part

I am in the directory:

Tutorials/Basic/HeatEquation_EX1_F]

and after doing "make" in this directory I typed:

% ./main3d.gnu.DEBUG.MPI.ex
MPI initialized with 1 MPI processes
AMReX () initialized
ParmParse::getval ParmParse::getval(): n_cell not found in table
amrex::Abort::SIGABRT
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 4 DUP FROM 3
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

**Comment by maxpkatz** [comment]
AMReX executables expect an inputs deck that give information about the size of the domain, the number of cells in the mesh, etc. That is provided for this tutorial; please run by passing the inputs as a command-line argument to the executable
```
./main3d.gnu.DEBUG.MPI.ex inputs
```
