### ISSUE TITLE
Archiving commit history

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#493]
Has there ever been any discussion around archiving and pruning the commit history for this project? I'm seeing the first commit from 1993 and depending on what machine I'm on, this repo can take an extraordinary amount of time to clone.

**Comment by WeiqunZhang** [comment]
We did some cleanup and moved documentation web pages to another place.  The fresh clone of the repo should be much smaller now.  It is about 158M, whereas it used to be more than 600M.

**Comment by jrood-nrel** [comment]
Excellent!
