### ISSUE TITLE
Visualization of time series with Paraview

### ISSUE THREAD

**Issue by gknapp1** [AMReX-Codes/amrex#496]
I've been trying to follow the instructions for visualizing with Paraview in the AMReX documentation (https://amrex-codes.github.io/amrex/docs_html/Visualization.html#paraview). I can successfully load individual files, but the method shown in Fig. 17 for loading a time series isn't working for me. How can I successfully load a time series in Paraview? 

**More details**: I can open "plt.." and Paraview will recognize a time series with the correct number of time steps, but the variables aren't accessible for plotting and it never asks for selecting the Boxlib3D reader. I have also tried entering multiple files to load at once (Open > "plt0000/Header;plt0001/Header;etc..."), and this correctly asks for the reader and loads all the files but does not link them to a time series. I'm using Paraview 5.6.1 64-bit on Ubuntu 16.04.

**Comment by jordanm304** [comment]
The original steps were provided to me by Berk Geveci. I've added to them based on some of my experiences. I do not know if it is necessary, but before I visualize files in ParaView, I add a `.boxlib3d` file extension to all my `plt*/Header` files using a simple bash script. 

Let's assume you have 10 plot files (`plt00000`, `plt00100`, ... `plt00900`). Start by loading a plot file in ParaView and setup your scene. Next you have to manually setup the animation time series (View -> Animation View). Setup the end time to be the number of steps-1, and the number of frames to be the number of steps. Using the above example, these are 9 and 10.

Add a Python track and double-click to bring up the text editor. Below is the script Berk provided with his notes. 

```
# Initialization function
from paraview.simple import *

# This function is called at the beginning of each
# animation (every time you press an animation
# button or make a movie).
def start_cue(self):

    # Modules used
    import os, glob

    # Make these global so that the tick() function can access them
    global reader, filenames   
    # Find the reader object. Match the name in the pipeline browser
    reader = FindSource("Header.boxlib3d")   
    # Go to the directory where the plt files are. Adjust as needed
    os.chdir("/lustre/scratch/jmusser/0607/cylindar/")

    # Get the names of all plt files and sort them.
    # Make sure nothing else start with plt in that dir    
    filenames = glob.glob("plt*")
    filenames.sort() 

# This function is called every time
# the animation time changes (time step)
def tick(self):
    # Clock time will be a float matching
    # the time displayed in the animation bar
    t = int(self.GetClockTime())

    # Use the time as an index to the filename list
    reader.FileName = filenames[t] + "/Header.boxlib3d"

# Runs at the end of each animation
def end_cue(self): pass
```

**Comment by drummerdoc** [comment]
Thanks Jordan.  I wonder if this is worth adding to AMReX documentation somewhere in a place and format that is easier to find than this GitHub issue.  More generally, I wonder if we should have a place outside of the formal documentation were such gems could be easily searchable.  Ideas anyone?

**Comment by asalmgren** [comment]
We have a place that such information lives but it may need to be updated

**Comment by drummerdoc** [comment]
Is it a secret place?  :)

**Comment by gknapp1** [comment]
Thank you! That works beautifully. It didn't seem necessary to add the `.boxlib3d ` extension to all my `Header` files, as long as the file extensions are removed accordingly in the filenames in the Python track script.

**Comment by hsitaram** [comment]
I realize this issue is closed, but I do have similar but easier way to
load multiple files in paraview. Thought I would share if it will be useful
for others.

I start by generating a .visit file just like what is in the documentation
by doing ls -1 plt?????/Header > out.visit.
I create this simple python script in the run folder, all it does is to
append all the header files into a list.

from paraview.simple import *
infile=open('out.visit','r')
allheaders=[]
for line in infile:
    spltline=line.split()
    allheaders.append(spltline[0])
header = VisItBoxlib3DReader(FileName=allheaders)

I open paraview, go to macros > add new macro.. Add this python script.
This script now shows as a clickable option on the right side of the
paraview window. Click it and you should be able to load all the files in
the .visit file.

Moving forward, I hope paraview will make our lives simpler.

Thanks,
Hari
