### ISSUE TITLE
Regrid with specific boxes

### ISSUE THREAD

**Issue by bobby-philip** [AMReX-Codes/amrex#498]
Hi:

Is it possible to create an AmrMesh by specifying the set of boxes I would like on each level without having to go through the process of tagging and clustering on each level?

Thanks,
Bobby

**Comment by WeiqunZhang** [comment]
Sure.  `AmrMesh` doesn't have any data other than meshes.  You can call `SetBoxArray` and `SetDistributionMap` with your `BoxArray` and `DistributionMappping`.

**Comment by bobby-philip** [comment]
Thanks! I will give it a shot.

Bobby

**Comment by bobby-philip** [comment]
I should have mentioned I am using the Fortran interface. On the Fortran side, is an AMRMesh defined and similarly are SetBoxArray and SetDistributionMap defined?

**Comment by WeiqunZhang** [comment]
There is a Fortran module called `amrex_amrcore_module` that contains a C pointer to AmrCore.  Currently the module doesn't provide a direct interface for setting BoxArray and DistributionMapping.  But that's easy to add.  I will do that in a minute.

**Comment by WeiqunZhang** [comment]
In the current development branch, there are
```
  subroutine amrex_set_boxarray (lev, ba)
    integer, intent(in) :: lev
    type(amrex_boxarray), intent(in) :: ba
  end subroutine amrex_set_boxarray

  subroutine amrex_set_distromap (lev, dm)
    integer, intent(in) :: lev
    type(amrex_distromap), intent(in) :: dm
  end subroutine amrex_set_distromap
```

in `amrex_amrcore_module`.

**Comment by bobby-philip** [comment]
@WeiqunZhang -- thank you!

**Comment by bobby-philip** [comment]
Hi:

Below is a snippet of code with which I am trying to build a static AMR grid using the new interfaces you provided. In the code below ba refers to BoxArray's and dm to DistributionMapping. Stepping through with totalview I can see that the AmrCore object appears to be built correctly with 3 levels -- I had set max_levels to 3. However, when I make a call to amrex_num_levels I get 0. Are there additional steps I should be taking to ensure the AmrCore object is initialized correctly?

  call truchas_amrex_init(params)
  call amrex_amrcore_init()
  amrcore = amrex_get_amrcore()

  ! create a set of nested boxarrays on each level
  allocate(ba(0:max_level))
  geom = amrex_get_geometry(0)
  dom = geom % domain
  do ilev = 0, max_level-1
     call amrex_boxarray_build(ba(ilev), dom)
     call ba(ilev) % maxSize(max_grid_size)
     call amrex_set_boxarray(ilev, ba(ilev))
     call dom % grow(-n_cell/4)     ! fine level cover the middle of the coarse domain
     call dom % refine(uref_ratio)
  end do

  ! set up the dm's
  allocate(dm(0:max_level))
  do ilev = 0, max_level-1
     call amrex_distromap_build(dm(ilev), ba(ilev))
  end do

  numlevels = amrex_get_numlevels()

**Comment by WeiqunZhang** [comment]
I added a new function, `amrex_set_finest_level` to `amrex_amrcore_module` in the development branch.  You can use that to set the finest level.  Note the value of the finest level must be >=0 and <= max_level.  `max_level` is the finest possible level in the simulation and it's set by the inputs parameter.  `finest_level` is the currently finest level, and it changes during runtime.

In the code you showed, the loop over level range is [0, max_level-1].  I assume you meant [0, max_level].

**Comment by bobby-philip** [comment]
Thank you!

I can use that interface though I am worried this could lead to bugs in future if AmrCore itself is not keeping track of the finest level internally. I do understand that it would be hard to keep track of the finest level on the library side when a user is adding the levels as I am. One thought would be to set finest_level to be the max of the current finest_level and whatever level the user is adding in. Is that viable?

For now I'll just plan on adding more error checking.

Regarding max_level I was interpreting it as max_number_of_levels, though I see I should be interpreting it differently.
