### ISSUE TITLE
Plot Tools files in CMake

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#501]
Is it possible to have the source files listed in a `CMakeLists.txt` for the plot file tools, `fcompare`, `fextrema`, etc? Or is there a way to build those tools with CMake that I am not aware of?

**Comment by mic84** [comment]
The feature you requested is now in development branch. To enable the compilation and installation of plotfile tools, pass ``-DENABLE_PLOTFILE_TOOLS=YES`` to CMake. The plotfile tools are installed in
``path/to/install/directory/bin``.
