### ISSUE TITLE
Data Races in OMP in examples

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#502]
Is it possible to tell if the attached output from `Tutorials/Amr/Advection_AmrCore/Exec/SingleVortex` is innocuous when running under the LLVM thread sanitizer with `-DLIBOMP_TSAN_SUPPORT=ON` in LLVM? Or are these data races that should be fixed?

I see these same data races in PeleC and I would like to get TSAN to report 0 warnings at some point so I can nightly test with it on.
[tsan_output.txt](https://github.com/AMReX-Codes/amrex/files/3298902/tsan_output.txt)

**Comment by WeiqunZhang** [comment]
Thanks for reporting this!  I think this is a data race that could in principle cause problems.  Could you try the latest development branch?

**Comment by jrood-nrel** [comment]
Looks like that fixed it. Thanks!
