### ISSUE TITLE
optional arguments to amrex_amrcore_init

### ISSUE THREAD

**Issue by bobby-philip** [AMReX-Codes/amrex#506]
Hi:

I would like to create an amrcore object using the Fortran interface amrex_amrcore_init following the advice I got when I filed my previous issue regarding creating a static AMR grid. Internally amrex_amrcore_init calls amrex_init with no arguments. amrex_init can take three optional arguments. At present, we are using this capability of amrex_init to set a procedure (proc_parmparse) to parse inputs in from a JSON input file. 

If I were to call the amrex_amrcore_init directly it would seem to me that I would lose the ability to set this procedure. Is there an alternative routine I should be calling that allows me to create an amrcore object and allows me to set this procedure? If an alternative does not exist would it be possible to modify the amrex_amrcore_init interface to take the three optional arguments that amrex_init currently has?

Thanks!
Bobby

**Comment by WeiqunZhang** [comment]
You can do

```
call amrex_init(....);  // with your argument
call amrex_amrcore_init();  // without any arguments
....
call amrex_amrcore_finalize();
call amrex_finalized();
```

If amrex is already initialized when amrex_amrcore_init is called, it will skip amrex_init.

**Comment by bobby-philip** [comment]
Thank you! Let me give that a shot.
