### ISSUE TITLE
An issue while using MLMG solver

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#507]
Hello all,

I have developed a code and am using MLMG solver to solve the cell centered pressure in a 3d channel flow case.  The initial field is u=1, v=w=0. The boundary conditions are:

Top: non-slip;
Bottom: non-slip;
Horizontal: periodic

The issue appears at the 1st step. While using MLMG solver in the projection step, the residual goes to a large value along with the iteration even if the initial residual is small. It blows up at the end. See the below:

MLMG: # of AMR levels: 1
      # of MG levels on the coarsest AMR level: 5
MLMG: Initial rhs               = 6.805050212e-12
MLMG: Initial residual (resid0) = 6.805050212e-12
MLMG: Iteration   1 Fine resid/bnorm = 0.1144755666
MLMG: Iteration   2 Fine resid/bnorm = 0.1284412606
MLMG: Iteration   3 Fine resid/bnorm = 0.2887778806
MLMG: Iteration   4 Fine resid/bnorm = 0.6340613347
MLMG: Iteration   5 Fine resid/bnorm = 1.435459645
MLMG: Iteration   6 Fine resid/bnorm = 3.258554749
MLMG: Iteration   7 Fine resid/bnorm = 7.421544574
MLMG: Iteration   8 Fine resid/bnorm = 16.92686559
MLMG: Iteration   9 Fine resid/bnorm = 38.64434196
MLMG: Iteration  10 Fine resid/bnorm = 88.28021382
MLMG: Iteration  11 Fine resid/bnorm = 201.7528791
MLMG: Iteration  12 Fine resid/bnorm = 461.2100017
MLMG: Iteration  13 Fine resid/bnorm = 1054.539148

I have checked the multifabs of acoef, bcoef, rhs before using the MLMG solver. No nan or inf values appear in these multifabs. 

At the same time, if I set u=1, v=0 for a 2d channel flow case instead of a 3d case. The solver works fine. 

Any ideas?

Best and thanks so much.

Jordan

**Comment by drummerdoc** [comment]
If the bottom solver is a Krylov-based type, you could be seeing the classic instability when trying to reduce a residual that is already very small (leading to divide-by-nearly-zero).  Your initial residual is very small, it seems, so this is possible.  If you run with mg.v=4 or something, you should get a better idea where in the V-cycle things are going bad.

**Comment by asalmgren** [comment]
Jordan -- can you turn on additional verbosity for the solve and send us
the residuals at each level of the V-cycles?

I suspect that what Marc noted is correct -- your problem is essentially
solved when you get there.

In fact if you're just projecting the velocity field (1,0,0) then your
initial rhs should be identically zero -- no-slip walls are just a
homogeneous Neumann condition for pressure.

**Comment by drummerdoc** [comment]
Also, FYI, there is a couple of flags to deal with the "already solved" situation - to recognize that the Krylov iteration is going unstable, and what to do if that happens.  But first, we should confirm.

**Comment by ruihai0925** [comment]
Thanks, Ann and Marc. By the way, the initial grid number is 64*32*64. 

Here are the updated parameters:

    mlmg.setMaxIter(100);
    mlmg.setMaxFmgIter(0);
    mlmg.setVerbose(4);
    mlmg.setCGVerbose(2);
    mlmg.setBottomVerbose(4);

Here are the updated outputs:


MLMG: Subtracting 8.088905766e-33 from rhs
MLMG: # of AMR levels: 1
      # of MG levels on the coarsest AMR level: 5
MLMG: Initial rhs               = 6.805050212e-12
MLMG: Initial residual (resid0) = 6.805050212e-12
MLCGSolver_BiCGStab: Initial error (error0) =        2.542638067e-15
MLCGSolver_BiCGStab: Half Iter           1 rel. err. 0.3651352095
MLCGSolver_BiCGStab: Iteration           1 rel. err. 0.283488705
MLCGSolver_BiCGStab: Half Iter           2 rel. err. 0.2133156066
MLCGSolver_BiCGStab: Iteration           2 rel. err. 0.1531425359
MLCGSolver_BiCGStab: Half Iter           3 rel. err. 0.08415704483
MLCGSolver_BiCGStab: Iteration           3 rel. err. 0.01444501534
MLCGSolver_BiCGStab: Half Iter           4 rel. err. 0.006947191378
MLCGSolver_BiCGStab: Iteration           4 rel. err. 0.002804074707
MLCGSolver_BiCGStab: Half Iter           5 rel. err. 0.001013337087
MLCGSolver_BiCGStab: Iteration           5 rel. err. 0.0005655957632
MLCGSolver_BiCGStab: Half Iter           6 rel. err. 0.0001605182487
MLCGSolver_BiCGStab: Iteration           6 rel. err. 9.73446451e-05
MLCGSolver_BiCGStab: Final: Iteration    6 rel. err. 9.73446451e-05
MLMG: Iteration   1 Fine resid/bnorm = 0.1144755666
MLCGSolver_BiCGStab: Initial error (error0) =        3.564799937e-15
MLCGSolver_BiCGStab: Half Iter           1 rel. err. 0.3306141231
MLCGSolver_BiCGStab: Iteration           1 rel. err. 0.2496899838
MLCGSolver_BiCGStab: Half Iter           2 rel. err. 1.367470197
MLCGSolver_BiCGStab: Iteration           2 rel. err. 0.2028973362
MLCGSolver_BiCGStab: Half Iter           3 rel. err. 0.07563311508
MLCGSolver_BiCGStab: Iteration           3 rel. err. 0.02019163616
MLCGSolver_BiCGStab: Half Iter           4 rel. err. 0.01098885543
MLCGSolver_BiCGStab: Iteration           4 rel. err. 0.004262414438
MLCGSolver_BiCGStab: Half Iter           5 rel. err. 0.001048295607
MLCGSolver_BiCGStab: Iteration           5 rel. err. 0.0003440689518
MLCGSolver_BiCGStab: Half Iter           6 rel. err. 0.0002330136073
MLCGSolver_BiCGStab: Iteration           6 rel. err. 5.985696675e-05
MLCGSolver_BiCGStab: Final: Iteration    6 rel. err. 5.985696675e-05
MLMG: Iteration   2 Fine resid/bnorm = 0.1284412606

......

MLCGSolver_BiCGStab: Initial error (error0) =        3.714737056e+20
MLCGSolver_BiCGStab: Half Iter           1 rel. err. 0.1331047077
MLCGSolver_BiCGStab: Iteration           1 rel. err. 0.03423879655
MLCGSolver_BiCGStab: Half Iter           2 rel. err. 0.0001709904142
MLCGSolver_BiCGStab: Iteration           2 rel. err. 4.50820105e-05
MLCGSolver_BiCGStab: Final: Iteration    2 rel. err. 4.50820105e-05
MLMG: Iteration  99 Fine resid/bnorm = 9.821179882e+33
MLCGSolver_BiCGStab: Initial error (error0) =        8.542748541e+20
MLCGSolver_BiCGStab: Half Iter           1 rel. err. 0.131470267
MLCGSolver_BiCGStab: Iteration           1 rel. err. 0.03350944113
MLCGSolver_BiCGStab: Half Iter           2 rel. err. 0.0001429926533
MLCGSolver_BiCGStab: Iteration           2 rel. err. 4.101892686e-05
MLCGSolver_BiCGStab: Final: Iteration    2 rel. err. 4.101892686e-05
MLMG: Iteration 100 Fine resid/bnorm = 2.254665971e+34
MLMG: Failed to converge after 100 iterations. resid, resid/bnorm = 1.534311514e+23, 2.254665971e+34

Best.

**Comment by asalmgren** [comment]
Personally I would just pass an absolute tolerance of 1e-12 into the solver
:-)

Real
MLMG::solve (const Vector<MultiFab*>& a_sol, const Vector<MultiFab const*>&
a_rhs,
             Real a_tol_rel, *Real a_tol_abs*, const char* checkpoint_file)

**Comment by ruihai0925** [comment]
Now my parameters are mlmg.solve (a_sol, a_rhs, 10^(-12), 10^(-16),checkpoint_file). 
So does it mean a larger absolute tolerance of 1e-12 will be better? Let me try it. 

Yet I have used the above parameters for 2d channel case (just ignoring variables in the z-direction), the solver works fine. That confuses me. Since my code is collocated (all variables are defined at the same location), the 2D and 3D Fortran subroutines should have the same differential form an interpolation scheme.  It seems MLMG solver should not generate different results between 2D and 3D case. Let me recheck it.

**Comment by asalmgren** [comment]
Jordan - have you figured out why with u = 1, v = w = 0, your rhs is not
identically zero?

**Comment by ruihai0925** [comment]
It is because I use a large Froude number 10^(+12) to represent the gravity term. So the gravity term has a small value ~10^(-12), which induces the velocity. Let me reset this term to zero and test it.

Thanks so much.
