### ISSUE TITLE
Doxygen latex pdf generation

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/amrex#509]
Hi,

This is not an AMReX issue, but just wanted to bring to your attention so that latex pdf generation of AMReX works fine.

There is an issue with the doxygen latex pdf generation with current versions of Tex.

While doing ```make``` in ```amrex/Docs/Doxygen/latex```, we get the following error.

```Missing } inserted. \end{DoxyParams}```

It turns out that this is due to ```longtabu*``` environment in doxygen.sty which uses the tabu.sty package that is outdated. Attached is the tabu.sty that works (have changed the extension to .txt as GitHub complained it does allow to attach files with .sty extension). 

[tabunew.txt](https://github.com/AMReX-Codes/amrex/files/3348304/tabunew.txt)

**Comment by asalmgren** [comment]
Thank you for bringing this to our attention!
