### ISSUE TITLE
Looping over ghost zones

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#514]
I assume that using `MFIter` and then calling `mfi.validbox()` returns box descriptions which include the "interior" points of the domain, in the sense that they exclude ghost points (points set from other boxes and points set via prolongation). This means that one has to fill these points by calling `FillBoundary` etc. afterwards.

Is there a way to loop over all grid points, so that one does not need to call `FillBoundary` afterwards?

**Comment by WeiqunZhang** [comment]
Hi Erik, `MFIter::fabbox()` will return a box with ghost cells.  The number of ghost cells is the same as that of the `MultiFab` used to construct `MFIter`.  You can also obtain the same box with `const Box& bx = amex::grow(mfi.validbox(), mf.nGrowVect());`.

**Comment by eschnett** [comment]
Does this also work with tiling? It seems that `fabbox` returns the allocated size of the whole box, not the region that should be traversed by an individual thread.

**Comment by asalmgren** [comment]
I think what you want is growntilebox as opposed to tilebox

**Comment by eschnett** [comment]
Thanks!
