### ISSUE TITLE
Problem with creation of level set when walls aligned with cell boundaries

### ISSUE THREAD

**Issue by asalmgren** [AMReX-Codes/amrex#519]
We have a 3D EB test case where the code dies with a divide by 0 in subroutine calc_facet_edge if the EB walls are specified at exactly a cell boundary.  If the walls are moved slightly in either direction the code works.

**Comment by JBlaschke** [comment]
Was a rounding error when comparing cell indices that occurred when the EB was exactly at the cell boundary. I have pushed a fix to the development branch.

**Comment by asalmgren** [comment]
That seems to fix it, thanks!

**Comment by asalmgren** [comment]
This issue does not appear to be fixed after all -- when the EB boundaries align with cell boundaries *and* the cell boundary is also a domain boundary, we again get divide by zero in subroutine calc_facet_edge in AMReX_EB_geometry.F90.

**Comment by JBlaschke** [comment]
This was an error where we compared a eb facet with a cell face. If they coincided, we where still computing the intercept (which is not defined...)

**Comment by asalmgren** [comment]
This fixes the problem which was breaking in mfix
