### ISSUE TITLE
Don't understand run-time message

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#520]
I receive messages like these at run time (AMReX 19.07):
```
[b09e0bc7129e:07907] Read -1, expected 854496, errno = 1
```
I think these messages began to appear when I built AMReX with `ENABLE_ASSERTIONS=ON`. The messages don't abort the run.

Where do they come from? Should I be worried?

**Comment by WeiqunZhang** [comment]
This doesn't appear to be an AMReX message.

**Comment by eschnett** [comment]
Thanks. Maybe they are emitted by OpenMPI then.
