### ISSUE TITLE
Multiple time levels with AmrLevel?

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#521]
The `AmrLevel` class seems quite convenient when implementing an `AMR` algorithm. Does it support using multiple (more than two) time levels? I am thinking of an explicit three-level scheme, where the current time level is calculated from the two previous time levels. Checkpointing then needs to store two time levels of data.

**Comment by asalmgren** [comment]
Erik -- do you use subcycling in time (ie smaller dt at finer levels)?

AmrLevel is currently hard-wired to "old" data and "new" data so it's
probably better to start with AmrCore rather than AmrLevel

**Comment by eschnett** [comment]
I might be interested in subcycling in the future, but am at the moment not yet using it.

If you think it's feasible to use `AmrCore` then I'll have a closer look.

**Comment by asalmgren** [comment]
Take a look at Tutorials/Amr/Advection_AmrCore
