### ISSUE TITLE
Setting AMREX_SPACEDIM via CMake

### ISSUE THREAD

**Issue by rupertnash** [AMReX-Codes/amrex#524]
So we have a project using AMReX and have been having issues getting the correct `#define`s passed through to the compiler. We have been working around by setting `AMREX_SPACEDIM=3` via `target_compile_definitions`.

However as I understand it, the intended behaviour is that this should be done by CMake through `install(EXPORT...)`

https://github.com/AMReX-Codes/amrex/blob/a5da9eafa0bba73bb594239970bb912809b11097/Tools/CMake/AMReXInstallHelpers.cmake#L115

The definitions are added to the amrex target by `add_amrex_define`, which sets the target build definition to appear only if the `BUILD_INTERFACE` genex is true
https://github.com/AMReX-Codes/amrex/blob/a5da9eafa0bba73bb594239970bb912809b11097/Tools/CMake/AMReX_Utils.cmake#L356

My reading of the CMake docs however suggests that this should also appear in the `INSTALL_INTERFACE` genex. 

I used the somewhat clunky equivalent of `if(BUILD_INTERACE || INSTALL_INTERFACE)`
```
target_compile_definitions( amrex PUBLIC $<$<OR:$<BOOL:$<BUILD_INTERFACE:1>>,$<BOOL:$<INSTALL_INTERFACE:1>>>:${new_define}> )
```
but then I realised that this is *almost* equivalent to not having a conditional generator expression

Is there any reason why we can't just have `add_amrex_define` just make the definition a normal public definition?

This seems to work for my simple cases so I've forked and pushed this code:
https://github.com/rupertnash/amrex/tree/development

**Comment by mic84** [comment]
Hi Rupert,

the amrex installation provides a header file called ``AMReX_Config.H`` which contains all the necessary defines. This header is included automatically when using any other amrex header. 

The reason for doing this instead of exporting defines the CMake way is that we want the amrex library to be easily available also to non-CMake projects.

If this answer your question and you are no having issues using the amrex library as is, I will close the issue. Please let me know. Thanks.

**Comment by rupertnash** [comment]
Thanks for the reply! However this header is NOT included automatically for me. A little digging explains this: you are using `sed` to patch this include during the install step and I had been seeing (and ignoring) `sed: -i may not be used with stdin` when I `make install`. BSD sed requires an argument for the in place flag (which can be an empty string) unlike GNU sed.

I'll figure out how to cross-platform this and make a PR.

As a side note, I don't really like this post-processing of the headers. Surely it is better to `#include` the config header iff it is required in that file? Further the particular way you're doing this (before the include guard) will inhibit the common pre-processor optimisation of entirely skipping (not even opening) of previously included files, thus slowing the compilation of applications.

(See https://gcc.gnu.org/onlinedocs/gcc-8.3.0/cpp/Once-Only-Headers.html#Once-Only-Headers)

**Comment by WeiqunZhang** [comment]
Why not use perl instead of sed assuming it is always installed on Mac?  Perl on Mac should be the same as on any other systems.  In our GNU Make system for building library, we use

    perl -pi -e 's/^/#include <AMReX_Config.H>\n/ if $$. == 1' $$newf; \

Thanks for telling us about the potential performance issue.  We could modify the perl line to

    perl -pi -e 'BEGIN{undef $$/;}  s/(^#ifndef.*?\n^#define.*?$$)/$$1\n#include <AMReX_Config.H>/smg' $$newf; \

Note that `$$` is used in the line above because `$` has special meaning in GNU Make.  Normally, the line would be

    perl -pi -e 'BEGIN{undef $/;}  s/(^#ifndef.*?\n^#define.*?$)/$1\n#include <AMReX_Config.H>/smg' MY_FILE

**Comment by rupertnash** [comment]
Not a bad idea but I think using pure CMake as in my PR #526 is better.

**Comment by WeiqunZhang** [comment]
But you want `#include <AMReX_Config.H` to be inside include guard.  Right?

**Comment by rupertnash** [comment]
Almost fixed - CMake is a bit clunky...

**Comment by rupertnash** [comment]
OK - that was quicker than expected. I have a CMake REGEX to look for the include guard pattern and insert the new include within that.

**Comment by WeiqunZhang** [comment]
> Not a bad idea but I think using pure CMake as in my PR #526 is better.

Just curious.  Is it better because perl may not be on Mac or because it's CMake or because it's perl?  I don't know CMake, and I don't actually like perl.

**Comment by rupertnash** [comment]
I hate CMake, it's just that I hate it less than the alternatives!

The reason I think it's better is that you're doing it with a tool you're already committed to so it doesn't introduce another dependency for users to deal with.

**Comment by WeiqunZhang** [comment]
OK.  Thanks.  Both CMake and perl are notorious.
