### ISSUE TITLE
How to pass an Vector<Vector> from c++ to Fortran in amrex?

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#528]
Hello all,

A small question.

In c++, I define:

```
static amrex::Vector< amrex::Vector<Real>> NLX;
NLX.resize(NRIGID, amrex::Vector<amrex::Real>(NL,0.0));
```

Suppose NRIGID=1 and NL=10 in my case. Then I want to pass this Vector<Vector> into Fortran. So I write:

```
      FORT_DIBMGEO(......
                    &NLX[0][0], 
                    ......);

      SUBROUTINE FORT_DIBMGEO (
     &     NLX, 
             ......)
      REAL_T     NLX(NRIGID,NL)

      DO M=1, NRIGID
          DO I=1,NL
          NLX(M,I)=......
          ENDDO
      ENDDO
```

It reports the segfault bug in the DO loop. Any suggestions? I do not quite know how to pass a 2D vector into the Fortran from c++. In the Tutorial, the index of passed multiarray is related to the box or FArrayBox. However, the index in my case is given a fixed number.

It will be great if I can mimic some codes fractions.

Thanks so much.

Jordan

**Comment by drummerdoc** [comment]
I don't believe there is any reason to think that a vector of vectors will have contiguous data.  This would be required to use as you suggest.  I think you either have to manually flatten the data yourself and pass a 1D vector, or make a multi-D block (such as, e.g., with a FArrayBox), and pass the data pointer to that.

**Comment by ruohai0925** [comment]
Thanks, Marc.  That makes sense. I will flatten all the 2D data I needed to 1D vector.

**Comment by ruohai0925** [comment]
Here is codes fraction. It works for the interface between C++ and FORTRAN.

```
static amrex::Vector< amrex::Vector<Real>> EXWALLX_P;
EXWALLX_P.resize(BL_SPACEDIM, amrex::Vector<amrex::Real>(NIBM,0.0));
Vector<Real*> EXWALLX_P_PT;
for (int i=0; i< BL_SPACEDIM; i++) {
          EXWALLX_P_PT[i]    = EXWALLX_P[i].data();
}

FORT_FORTRAN(......
                      EXWALLX_P_PT[0], 
                      EXWALLX_P_PT[1], 
#if (BL_SPACEDIM == 3)
                      EXWALLX_P_PT[2], 
#endif
                      ......);
```

And then the FORTRAN implementation: 

```
      SUBROUTINE FORT_FORTRAN (
     &     ......
     &     EXWALLX_PX, 
     &     EXWALLX_PY,
     &     EXWALLX_PZ,
     &     ...... )

      REAL_T     EXWALLX_PX(NIBM)
      REAL_T     EXWALLX_PY(NIBM)
      REAL_T     EXWALLX_PZ(NIBM)
      ......
      END
```

Thanks and best.

**Comment by drummerdoc** [comment]
No need to define the temporaries, BTW - can pass address of first element in vector. In fact, if NIBM is known at compile time (and since BL_SPACEDIM is known) you could even use Array's instead of Vectors [no need to resize] (and use the D_DECL macros to tidy things up slightly):

```
using namespace amrex;
const int NIBM = 20;
static Array<Array<Real,NIBM>,BL_SPACEDIM> EXWALLX;

FORT_FORTRAN(......
             D_DECL(&(EXWALLX[0][0]), 
                    &(EXWALLX[1][0]),
                    &(EXWALLX[2][0])), 
                      ......);
```

Also, if flattening the data requires unnatural access in fortran, you can make arrays/vectors of structs (however, they have to be POD structs, and the definitions in C++ and Fortran have to be consistent).  Let me know if you want to do this and I can paste in some example code.

**Comment by ruohai0925** [comment]
Hi Marc,

I have flattened the data into 1D vector in a class. Maybe I will try the Array later. Yet, I still have some confusions about defining a static Vector in a class and its usage in the MPI environment. 

Suppose, I defined 
` static amrex::Vector< amrex::Real> SFTX;` 
as a static member in a class. SFTX is thus a global variable. If I run the codes with 2 cores by using MPI,  how many copies of SFTX during the running time?

My first guessing is that there are 2 copies of SFTX during the running time. Each core has its own copy of SFTX. So I can use ParallelReduce operations to synchronize SFTX in these two cores. But when I initialized the SFTX in the function as  0.0 and checked the output of core 0 and 1, the outputs in core 1 was unreasonable. See here (NRIGID=1):

```
    for (int i = 0; i < NRIGID; i++){
    SFTX[i] = 0.0;
    }

    for (int i = 0; i < SFTX.size(); i++) {
        amrex::Print()  << "0 " << i << " " << *SFTX_PT++ << endl;
    }

    for (int i = 0; i < SFTX.size(); i++) {
        amrex::Print(1) << "1 " << i << " " << *SFTX_PT++ << endl;
    }

```

And the outputs:
```
1 0 5.366094924e-315
0 0 0
```

It seems that I did not initialize the SFTX in the core 1.

My second-guessing is that there is only 1 copy of SFTX during the running and each processor can access it. Because SFTX is defined as "static". So I am not sure which guessing is correct?

Actually, I just want to define a global vector in which each core has its own copy of this vector and modifies its own elements. So that I can synchronize these vectors at the end.

Best.

Jordan

**Comment by asalmgren** [comment]
Jordan --

Actually the problem is that "amrex::Print()" automatically prints from the
I/O processor, which in this case must be processor 0

Try using "std::cout" instead and see what you get

**Comment by ruohai0925** [comment]
I know. 

The output of core 0 (also the IO processor) is:
`0 0 0`
It is reasonable.

The output of core 1 (output by using amrex::Print(1) ) is:
`1 0 5.366094924e-315`
That seems its value was not initialized.

**Comment by maxpkatz** [comment]
If that code snippet is actually what you're doing, I think the issue is that SFTX_PT is not being reset in between the loops -- even though rank 1 doesn't print any data in the first loop, it still evaluates that code block, so in the second loop, rank 1 is trying to read nonsense data.

A `static` variable still has a different copy for every MPI rank. It is only shared between different instances of the class on the same MPI rank.

**Comment by drummerdoc** [comment]
Also, there are nuanced definitions of "static".  It looks like you might have used it as a "file static" rather than a class static.  In that case, there is one copy per MPI rank, and it is only in scope in code below the declarations IN THAT FILE.  I love C++!
