### ISSUE TITLE
Passing ghost cell values into valid cells while using MPI in the AMReX framework?

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#529]
Hello all,

I am now writing the IBM codes in the AMReX framework. At one step, I need to re-distribute the force on the Lagrangian points into the Eulerian cells. Some of these Eulerian cells are ghost cells for a specific processor. After this re-distribution, I need to pass the forces at these Eulerian ghost cells to replace another processor's valid cells.  **Are there some internal subroutines supporting this operation? I mean, I want to use the ghost cells values in one processor to replace accordingly valid cells in another processor.**

In our inhouse FORTRAN codes, we just change the send and receive variables in the MPI_SENDRECV. See below: 
```
        CALL MPI_SENDRECV(TEMP_B(-1:0        , : , :) , 2*(NYNP+4)*(NZNP+4) , &
                          MPI_DOUBLE_PRECISION , IP_SEND , 22               , &
                          TEMP_B_ASS(NXNP-1:NXNP , : , :) , 2*(NYNP+4)*(NZNP+4) , &
                          MPI_DOUBLE_PRECISION , IP_RECV , 22               , &
                          MPI_COMM_WORLD , STATUS , IERR)
```

Yet I am not sure how we can do this operation quickly in the AMReX framework.

Best.

Jordan

**Comment by asalmgren** [comment]
The call you are looking for is "SumBoundary"

This sums the boundary from ghost cells and valid cells into valid cells.

We use this in particle deposition routines often -- same as what you're
doing.

Note that it is a sum not a replace so make sure to initalize the
destination location with zero

**Comment by JBlaschke** [comment]
You can see an example of this here: https://github.com/AMReX-FHD/FHDeX/blob/7d10177053e76b11be0a5480577ba18b8c027f3b/exec/immersed_boundary/channel_dumbbell/advance.cpp#L347

Over the next 10 lines, I create a Multifab with enough ghost cells. Then I do a immersed boundary spreading. Followed by a SumBoundary. Notice how I initialized my Multifab to zero first (setVal)
