### ISSUE TITLE
Visualization of Curvilinear Coordinates

### ISSUE THREAD

**Issue by kangkabseok** [AMReX-Codes/amrex#530]
I am trying to plot a solution on circle with polar coordinates.
Is there any exaplmes in AMReX?

**Comment by zingale** [comment]
you might give yt a try.  It can read AMReX data and can deal with polar coordinates, although I am not aware of anyone who has visualized polar AMReX data, so there might be a little hacking needed.

https://yt-project.org/

**Comment by dwillcox** [comment]
I've done this before with a yt script as follows:

```
"""
This script uses yt to plot a field in an AMReX plotfile in
spherical polar geometry.

Run as, e.g.:

$>python3 plot_spherical.py [plotfile name]

To plot a different field, e.g. [field name]

$>python3 plot_spherical.py [plotfile name] -f [field name]

Tested with Python 3.5.2 and yt 3.4.1
"""

import yt
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('plotfile', type=str, help='Name of AMReX plotfile.')
parser.add_argument('-f', '--field', type=str, default='density', help='Name of field to plot.')
args = parser.parse_args()

ds = yt.load(args.plotfile)

yt.SlicePlot(ds, 'r', args.field).save()
yt.SlicePlot(ds, 'theta', args.field).save()
yt.SlicePlot(ds, 'phi', args.field).save()
```

If you want to use VisIt to do this, open the plotfile and first add a Mesh object and apply a Transform operation to transform from cylindrical (e.g. for 2D) input coordinates to cartesian output coordinates. Then you can add a pseudocolor plot for a field, etc. as usual.
