### ISSUE TITLE
How can I interpolate fine grid ghosts from a coarser grid?

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#531]
I want to set fine grid ghosts from a coarser grid, without changing the interior of the fine grid. The functions I've found don't seem to be doing what I want:
* `FillBoundary` only works within a single level
* `FillPatchSingleLevel` fills the whole grid
* `FillPatchTwoLevels` does the same
* `InterpFromCoarseLevel` also fills the whole grid
* `InterpCrseFineBndryEMfield` is specific to the Maxwell equations

#391 asks a similar question, but doesn't answer my question.

I am using the `AmrCore` infrastructure.

**Comment by WeiqunZhang** [comment]
I suggest you can use `FillPatchTwoLevels` with a copy of the fine data as input for fine level.  This will fill the interior with your original data via local copy, ghost cells overlapping with fine valid cells with the original valid data, and other ghost cells with data interpolated from the coarse level.  The extra cost of local copy should not be an issue.

**Comment by eschnett** [comment]
Thanks.
