### ISSUE TITLE
PGI and NVCC

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#533]
For some reason when I set `COMP=pgi` and `USE_CUDA=TRUE` in my `GNUmakefile`, `NVCC_HOST_COMP` does not get set to `pgi`. It uses `nvcc --ccbin=g++`. Looking at the `GNUMake` files in AMReX, it looks like the intention is to set `NVCC_HOST_COMP=pgi` in the `nvcc.mak` file, but I think there might be some logic in `Make.defs` stopping it. I also see the comment in `nvcc.mak` about `nvcc` not accepting `pgc++` as a host compiler in certain situations, so maybe this is intentional. If I set `NVCC_HOST_COMP=pgi` on the command line, `--ccbin=pgc++` gets set as expected.

Also at line https://github.com/AMReX-Codes/amrex/blob/48f7b776539eec3dd2e67e4b382d1f23da40ce99/Tools/GNUMake/comps/nvcc.mak#L47 I think there needs to be logic to handle `--std=c++14` for the PGI compiler as well. If my GCC found on the system is > 5.x, `Xcompiler` will get `--std=c++14` and `nvcc` will get `--std=c++11`.

**Comment by WeiqunZhang** [comment]
To use pgi as nvcc host compiler, do

    make USE_CUDA=TRUE COMP=pgi NVCC_HOST_COMP=pgi

**Comment by maxpkatz** [comment]
Yes that is intentional since when we first implemented this the combination of latest PGI and latest nvcc were incompatible with each other, and what Weiqun has said is what we'd recommend.

Regarding C++14, please file a PR if that is needed.

**Comment by WeiqunZhang** [comment]
Yes we should use a similar logic to handle c++14 for pgi.  I just fixed it.

**Comment by jrood-nrel** [comment]
Thanks! No problem, I will continue to use `NVCC_HOST_COMP=pgi`.
