### ISSUE TITLE
Are there gappy simulation examples in the AMReX framework?

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#537]
Hello all,

Here is a question about gappy simulation. Now I think (maybe not right) solvers in the AMReX is based on the MultiFab instead of FArrayBoxes, which means we can only solve equations as a whole on a specific level. In the gappy simulation, we only want to solve the equation on subdomains, e.g. specific FArrayBoxes. Are there applications of AMReX framework which have implemented this gappy simulation solver? Or future plan?

Thanks and Best.

Jordan

**Comment by drummerdoc** [comment]
I'm not aware of such a thing, but there's no reason why you can't make a MultiFab on a single box and use the software as it exists, is there?  The tricky part is specifying exactly how you want the boundary conditions applied (where, physically).

**Comment by ruohai0925** [comment]
Thanks, Marc. I have not tried to make MultiFab on a single box before. 

The gappy simulation is related to some "fault-resilient" algorithms. The key issue is “fault resilience” against repeated and expected software or hardware failures during computations. Suppose some data is missing because of processors failing during computations, how can we use some interpolation or projection techniques to continue the simulation until the processors are fixed.

There are some papers about gappy simulation. 
https://www.sciencedirect.com/science/article/pii/S0021999117304989
https://www.sciencedirect.com/science/article/pii/S0021999117303960

Some colleagues in our group are studying these parts. I am now thinking about whether we can combine AMR with these "fault resilient" algorithms. I will add more information here later.

Jordan
