### ISSUE TITLE
Same memory layout for cell- and vertex-centred multifabs?

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#545]
Cell- and vertex-centred multifabs have sizes that differ by one when derived from the same box array. This is a bit inconvenient since each index type needs its own array indexing logic. The approach taken in Cactus is to pad cell-centred arrays so that they have the same shape and indexing mechanics as vertex-centred arrays. The padding is unused, and there is no harm if the code writes to these elements. I find that such code is easier to read since it has fewer loops.

Would you consider enabling something similar for AMReX? For example, being able to specify a certain amount of padding in box arrays would do the trick.

**Comment by asalmgren** [comment]
We have looked into this before and concluded it's not a good idea in the long run.   Applications are much more likely to make indexing mistakes and those mistakes are much less likely to get caught.   So no, there are no plans to add this functionality.
