### ISSUE TITLE
Interpolater: Difference between CellQuadratic and CellConservativeQuartic

### ISSUE THREAD

**Issue by GumpXiaoli** [AMReX-Codes/amrex#546]
Can someone kindly tell me the difference between CellQuadratic and CellConservativeQuartic? It seems that there is no fortran implementation of CellQuadratic in 3D condition.

**Comment by asalmgren** [comment]
Quadratic means a second-order fit, quartic means a fourth-order fit.  "Conservative" in this sense  means that the average of the fine values in a cell is equal to the value in the coarse cell.    You are correct that conservative quadratic is not implemented in 3D.  If you are interested in using it, we suggest you use the 2D as a guide to create the 3D then share with a pull request.
