### ISSUE TITLE
How do I calculate a reduction?

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#549]
I want to calculate a reduction, e.g. the maximum of an error that is defined point-wise. When I iterate over all cells of all grids, then this will include coarse grids that are covered by fine grids. I want to ignore these coarse points, since the error there will be very large but won't affect the evolution.

I am using the AmrCore infrastructure.

**Comment by WeiqunZhang** [comment]
This is what you can do.

    int coarse_level = ....;
    MultiFab coarse(....);
    AmrCore* amrcore = ...;
    iMultiFab  mask = makeFineMask(coarse, amrcore->boxArray(coarse_level+1),
                                           amrcore->refRatio(coarse_level);
    // You can save mask for later use
    // mask has the same BoxArray and DistributionMapping as coarse.
    // Cells covered by the fine level are set to 1, whereas the others are 0.
    //  We now need to switch their values.
    // This is not the most efficient way to do mask = 1-mask.
    mask.negate();  mask.plus(1,0);
 
    int icomp = ...;
    coarse.norminf(mask, icomp);

Because the mask generated by `makeFineMask` is the opposite of what we need for `norminf`, we have to do some extra work to the mask.  I will add two optional arguments to `makeFineMask` allowing users to provide their own values for coarse and fine flags.

**Comment by WeiqunZhang** [comment]
With the latest development branch, you can do

    iMultiFab  mask = makeFineMask(coarse, amrcore->boxArray(coarse_level+1),
                                       amrcore->refRatio(coarse_level),
                                       1, 0);
    coarse.norminf(mask, icomp);

Also note `norminf` (in `AMReX_MultiFab.H`) can take optional argument to disable MPI reduce.  Sometimes this allows you to merge several MPI reduces into one.

**Comment by eschnett** [comment]
Thank you!

I am using a reduction routine that calculates several reductions simultaneously, returning a struct. For this I'm looping over the multifab explicitly, but only once for all reductions. (I was thinking earlier that I should offer to contribute this.)
