### ISSUE TITLE
General reduction API?

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#551]
In the Cactus driver I have created a general reduction API that calculates several reductions at once (max, min, avg, etc.) This should be faster than calculating several reduction in series, but not much slower than calculating only a single reduction. At the heart is this struct:
```C++
template <typename T> struct reduction {
  T min, max, sum, sum2;
  T vol, maxabs, sumabs, sum2abs;
  reduction();
  reduction(const T &V, const T &x);
  reduction(const reduction &x, const reduction &y);
  reduction operator+(const reduction &y) const { return reduction(*this, y); }
  reduction &operator+=(const reduction &y) { return *this = *this + y; }

  T avg() const { return sum / vol; }
  T sdv() const { return sqrt(fmax1(T(0.0), vol * sum2 - pow(sum, 2))); }
  T norm0() const { return vol; }
  T norm1() const { return sumabs / vol; }
  T norm2() const { return sqrt(sum2abs / vol); }
  T norm_inf() const { return maxabs; }
};
```
with corresponding definitions of OpenMP and MPI reduction operations.

Are you interested in adding this to AMRex? If yes, I can create a pull request.

**Comment by WeiqunZhang** [comment]
Could you give a link to an example of how reduction is done in Cactus?

There is an example at `amrex/Tutorials/GPU/ParallelReduce/` showing how to do multiple reductions in AMReX.  That example focuses on GPU and has no OpenMP, but `ReduceOps` does support OpenMP when compiled with OpenMP and without CUDA.  What could certainly be improved is the MPI reduction part.  We could use custom data types and MPI_Ops.  If Cactus has a nice way of handling this, we are certainly interested.

**Comment by eschnett** [comment]
I can't find this tutorial. Can you post a link?

The Cactus implementation is [here](https://bitbucket.org/eschnett/cactusamrex/src/master/AMReX/src/reduction.cxx).

**Comment by WeiqunZhang** [comment]
Probably still in `development` branch.

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/amrex/blob/development/Tutorials/GPU/ParallelReduce/main.cpp

**Comment by eschnett** [comment]
Thanks. This example calculates several reduction in series, i.e. one after the other. It would be more efficient to calculate them simultaneously. This is what I'm proposing. The result of such a reduction is then not a single number, but a struct holding minimum, maximum, sum, etc.

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/amrex/blob/development/Tutorials/GPU/ParallelReduce/main.cpp#L74

There are multiple approaches there.  The code block above shows how to calculate them simultaneously.
