### ISSUE TITLE
AMReX with EB failing to compile with Intel 2018

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#557]
We are using `d823b8dcaefea0c0d3e8c56d230a8d3f7d0c5fbb` commit for AMReX and we are compiling PeleC EB cases successfully with Intel 2019, and GCC, but it looks like we get this error with Intel 2018:
```
AMReX/Src/EB/AMReX_EB2_Level.H(209): error: the default constructor of "amrex::EBCellFlagFab" cannot be referenced -- it is a deleted function
          EBCellFlagFab cellflagtmp;
                        ^
          detected during:
            instantiation of "void __gnu_cxx::new_allocator<_Tp>::construct(_Up *, _Args &&...) [with _Tp=amrex::EB2::GShopLevel<amrex::EB2::GeometryShop<amrex::EB2::AllRegularIF>>, _Up=amrex::EB2::GShopLevel<amrex::EB2::GeometryShop<amrex::EB2::AllRegularIF>>, _Args=<amrex::EB2::IndexSpaceImp<amrex::EB2::GeometryShop<amrex::EB2::AllRegularIF>> *, const amrex::EB2::GeometryShop<amrex::EB2::AllRegularIF> &, const amrex::Geometry &, int &, int &>]" at line 475 of
                      "/usr/include/c++/7/bits/alloc_traits.h"
```

**Comment by WeiqunZhang** [comment]
Could you try again with the latest development branch?  It seems that Intel 18 refuses to generate default ctor for EBCellFlag because there was explicit `noexcept`.  But we have added a `std::map` that has no `noexcept` default ctor.

**Comment by jrood-nrel** [comment]
Looks like it works. From our tests last night, I noticed it affected GCC 4 as well. Thanks!
