### ISSUE TITLE
AssignDensity fails when ncomp>1

### ISSUE THREAD

**Issue by cbehren** [AMReX-Codes/amrex#573]
AssignDensity in https://github.com/AMReX-Codes/amrex/blob/master/Src/AmrCore/AMReX_AmrParticles.H fails when running with more than one level and `ncomp`is not 1. The reason is that the `tmp` Multifab declared in line 98 has only one component. I guess the 1 should be replaced by `ncomp`. Also, the call to `AssignDensitySingleLevel` in 104 should have `ncomp` instead of 1 as the number of components.

**Comment by asalmgren** [comment]
I've just replaced 1 by ncomp in 4 places in AssignDensity -- can you try out the version now in development and see if that fixes it?
