### ISSUE TITLE
how to implement hoextrap for cells?

### ISSUE THREAD

**Issue by DUGKS** [AMReX-Codes/amrex#579]
I found that the default method for hoextrap boundary is designed for face values.

I want to change that function to `amrex_hoextraptocc (q, qlo, qhi, domlo, domhi, dx, xlo)` so that ghost cell values can be extrapolated using high order scheme. 

But a simple substitution of 
```
amrex_hoextraptocc(BL_TO_FORTRAN_N_ANYD(dest,dcomp), &numcomp,
                    BL_TO_FORTRAN_BOX(domain),
                    dx, xlo);
```
for
```
amrex_fab_filcc(BL_TO_FORTRAN_N_ANYD(dest,dcomp), &numcomp,
                       BL_TO_FORTRAN_BOX(domain),
                       dx, xlo, bcr[bcomp].vect());
```
disabled other boundary types such as foextrap, reflect_even, etc..

what's the best method to implement a hoextrap BC?

Thanks a lot!

**Comment by WeiqunZhang** [comment]
I think you can add a new bc type say HOEXTRAPCC to `AMReX_BC_TYPES.H` and related Fortran files `AMReX_bc_types_mod.F90` and `AMReX_bc_types.fi`.  Then add a new option to `amrex_filccn` in `AMReX_filcc_mod.F90`.  If you like to make this feature available for others, you are welcome to submit a pull-request.

**Comment by DUGKS** [comment]
I finally realized that a linear extrapolation is more preferable. So a new bc type called LIEXTRAP is added to AMReX_BC_TYPES.H as well as AMReX_bc_types_mod.F90.

In AMReX_BC_TYPES.H, the changes are
```
enum mathematicalBndryTypes : int {
    ...
    ...
    ...
    liextrap     =  5
};
#ifndef AMREX_XSDK
    ...
    ...
    ...
#define LIEXTRAP 5
    ...
    ...
    ...
#endif
```
In AMReX_bc_types_mod.F90, the newly added term is 
```
integer, parameter, public :: amrex_bc_liextrap     =  5
```

The newly added block in subroutine `amrex_filccn` located in AMReX_filcc_mod.F90 is somehow like
```
else if (bc(?,?,?) .eq. amrex_bc_liextrap) then

      do k = lo(3), hi(3)
          do j = lo(2), hi(2)
             do i = imin, imax
                q(i,j,k,n) = (2*q(ihi,j,k,n) - q(ihi-1,j,k,n))
             end do
          end do
       end do
```
A simple test based on 5x5 grids with two ghost cells has been conducted.
It's testified that the value in ghost cells(including the cross-corner cells) adjacent to the inner cell is exactly what the linear extrapolation of its neighbour cells gives. 
The values in the outermost ghost cell is the same as its neighbour ghost cell.

I'd be glad to share this feature if it is needed.

**Comment by drummerdoc** [comment]
Not that it matters at all, but the usual name for this sorta thing is FOEXTRAP (first-order extrapolation), vs. HOEXTRAP for high-order.

**Comment by DUGKS** [comment]
> Not that it matters at all, but the usual name for this sorta thing is FOEXTRAP (first-order extrapolation), vs. HOEXTRAP for high-order.

If so, FOEXTRAPLI would be a more suitable name.
