### ISSUE TITLE
AMReX Scaling

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#580]
Hello. We have begun the process of deciding whether or not to use AMReX in another project of mine. I am curious if there are any resources showcasing AMReX and its core performance qualities, such as scaling, on more of a standalone basis? I seem to only be able to find this information from applications using AMReX. While I know weak scaling to be very good for my PeleC application and for other applications using AMReX, we are looking to be able to justify it on its on merit. Therefore we weak scaled the amrcore advection tutorial but are seeing what seem to be poor results when compared to something like `p4est`.

For something like the advection tutorial, is it the case that there is just too little work per cell that the communication is very inflated? Should we expect more from scaling the tutorials, or is this showing that our methodology is flawed? The amcore advection tutorial was copied into larger domains as shown below, with the number of cells verified to be constant with the increase of computing elements.

![Screen Shot 2019-09-26 at 11 02 51 AM](https://user-images.githubusercontent.com/23264326/65910622-55706f00-e388-11e9-9593-069a113181ca.png)
![Screen Shot 2019-09-26 at 11 02 05 AM](https://user-images.githubusercontent.com/23264326/65910627-57d2c900-e388-11e9-8291-afb37476af0c.png)
[amrex_vs_p4est_weak.pdf](https://github.com/AMReX-Codes/amrex/files/3673115/amrex_vs_p4est_weak.pdf)

**Comment by WeiqunZhang** [comment]
Could you give us more details on how you did the weak scaling test of the advection problem with AMReX?

**Comment by michaeljbrazell** [comment]
the initial condition was repeated by modifying Prob.f90

 git diff Tutorials/Amr/Advection_AmrCore/Exec/SingleVortex/Prob.f90
diff --git a/Tutorials/Amr/Advection_AmrCore/Exec/SingleVortex/Prob.f90 b/Tutorials/Amr/Advection_AmrCore/Exec/SingleVortex/Prob.f90
index 556c0d8..4341fca 100644
--- a/Tutorials/Amr/Advection_AmrCore/Exec/SingleVortex/Prob.f90
+++ b/Tutorials/Amr/Advection_AmrCore/Exec/SingleVortex/Prob.f90
@@ -14,9 +14,11 @@ subroutine initdata(level, time, lo, hi, &
   real(amrex_real), intent(in) :: dx(3), prob_lo(3)
 
   integer          :: i,j,k
-  real(amrex_real) :: x,y,z,r2
+  real(amrex_real) :: x,y,z,r2,x0,y0,z0
+  integer :: l,m,n,s
+  
+  s=8
   
-  !$omp parallel do private(i,j,k,x,y,z,r2) collapse(2)
   do k=lo(3),hi(3)
      do j=lo(2),hi(2)
         z = prob_lo(3) + (dble(k)+0.5d0) * dx(3)
@@ -28,12 +30,21 @@ subroutine initdata(level, time, lo, hi, &
               r2 = ((x-0.5d0)**2 + (y-0.75d0)**2) / 0.01d0
               phi(i,j,k) = 1.d0 + exp(-r2)
            else
-              r2 = ((x-0.5d0)**2 + (y-0.75d0)**2 + (z-0.5d0)**2) / 0.01d0
-              phi(i,j,k) = 1.d0 + exp(-r2)
+              phi(i,j,k) = 1.d0
+              do l=1,s
+              do m=1,s
+              do n=1,s
+                x0 = 0.50d0 + dble(l-1)
+                y0 = 0.75d0 + dble(m-1)
+                z0 = 0.50d0 + dble(n-1)
+                r2 = ((x-x0)**2 + (y-y0)**2 + (z-z0)**2) / 0.005d0
+                phi(i,j,k) = phi(i,j,k) + exp(-r2)
+              end do
+              end do
+              end do
            end if
         end do
      end do
   end do
-  !$omp end parallel do

**Comment by michaeljbrazell** [comment]
input file:

max_step  = 100000000
stop_time = 2.0

# PROBLEM SIZE & GEOMETRY
geometry.is_periodic =  1  1  1
geometry.coord_sys   =  0       # 0 => cart
geometry.prob_lo     =  0.0  0.0  0.0 
geometry.prob_hi     =  1.0  1.0  1.0
amr.n_cell           =  64 64 64

# VERBOSITY
amr.v              = 1       # verbosity in Amr

# REFINEMENT
amr.max_level       = 4       # maximum level number allowed
amr.ref_ratio       = 2 2 2 2 2 2 # refinement ratio
amr.blocking_factor = 8       # block factor in grid generation
amr.max_grid_size   = 16

amr.regrid_int      = 2       # how often to regrid

# TIME STEP CONTROL
adv.cfl            = 0.7     # cfl number for hyperbolic system
                             # In this test problem, the velocity is
			     # time-dependent.  We could use 0.9 in
			     # the 3D test, but need to use 0.7 in 2D
			     # to satisfy CFL condition.

adv.do_reflux = 1

# Tagging
adv.phierr = 1.01 1.1 1.2 1.3 1.4 1.5 1.6

# PLOTFILES
amr.plot_file  = plt    # root name of plot file
amr.plot_int   = -10     # number of timesteps between plot files

# CHECKPOINT
amr.chk_file = chk      # root name of checkpoint file
amr.chk_int  = -10       # number of timesteps between checkpoint files
#amr.restart  = chk00060 # restart from this checkpoint file

##amr.loadbalance_with_workestimates=1

DistributionMapping.v = 1
DistributionMapping.strategy = KNAPSACK
#DistributionMapping.strategy = ROUNDROBIN

**Comment by WeiqunZhang** [comment]
Is the test 2d or 3d?

**Comment by michaeljbrazell** [comment]
then to double the problem set
geometry.prob_hi = 2.0 1.0 1.0 
and 
amr.n_cell = 128 64 64

**Comment by michaeljbrazell** [comment]
3D

**Comment by WeiqunZhang** [comment]
What's next in the scaling? 128 128 64 or 256 64 64?

How many processes do you use for the 64^3 problem?

Could you try `DistributionMapping.strategy = SFC`?

For the sake of demonstration, the advection tutorial uses `amr.blocking_factor = 8` and `amr.max_grid_size   = 16`.  These are too small for it to scale well.

**Comment by michaeljbrazell** [comment]
inputs111:geometry.prob_hi     =  1.0  1.0  1.0
inputs211:geometry.prob_hi     =  2.0  1.0  1.0
inputs221:geometry.prob_hi     =  2.0  2.0  1.0
inputs222:geometry.prob_hi     =  2.0  2.0  2.0
inputs422:geometry.prob_hi     =  4.0  2.0  2.0
inputs442:geometry.prob_hi     =  4.0  4.0  2.0
[mbrazell@el3 amrex_weak_scaling_study]$ grep amr.n_cell inputs*
inputs111:amr.n_cell           =  64 64 64
inputs211:amr.n_cell           =  128  64   64
inputs221:amr.n_cell           =  128  128  64
inputs222:amr.n_cell           =  128  128  128
inputs422:amr.n_cell           =  256  128  128
inputs442:amr.n_cell           =  256  256  128

64^3 use 2 nodes (72 processors) on Eagle

We ran a few cases with SFC and it was a little bit slower than KNAPSACK. So we stuck with KNAPSACK. But this was not thoroughly tested. 

yes, those are small grid sizes, but in comparison p4est uses 1 for blocking factor and 1 for max grid size. What do you suggest I try?

**Comment by michaeljbrazell** [comment]
for the 64^3 inputs111 problem:
  Level 0   128 grids  262144 cells  100 % of domain
            smallest grid: 16 x 16 x 8  biggest grid: 16 x 16 x 8
  Level 1   108 grids  110592 cells  5.2734375 % of domain
            smallest grid: 16 x 8 x 8  biggest grid: 16 x 8 x 8
  Level 2   128 grids  262144 cells  1.5625 % of domain
            smallest grid: 16 x 16 x 8  biggest grid: 16 x 16 x 8
  Level 3   216 grids  884736 cells  0.6591796875 % of domain
            smallest grid: 16 x 16 x 16  biggest grid: 16 x 16 x 16
  Level 4   945 grids  3596288 cells  0.3349304199 % of domain
            smallest grid: 8 x 8 x 8  biggest grid: 16 x 16 x 16

**Comment by WeiqunZhang** [comment]
Is p4est octree based?  What does max_grid_size=1 mean for p4est?  8^3 cells.  If so, the equivalent in AMReX is max_grid_size=8 and blocking_factor=16 (because there are 2x2x2 children for each octree parent node).

PS. there is a race condition in initdata.  x0,y0 and z0 need to be thread private.  It think l,m,n are automatically thread private because they are look indices, if I remember OpenMP standard correctly.

**Comment by michaeljbrazell** [comment]
p4est is octree based. I just meant the patch size is 1x1x1 which is one octant in p4est. So p4est has to regrid and repartition many more cells compared to patches in AMReX.

I deleted the openmp in prob.f90 so I didn't have to think about it.

**Comment by WeiqunZhang** [comment]
I think there are too many small grids especially on level 4.  Maybe you can use something like `amr.blocking_factor=16` and `amr.max_grid_size=64`.

**Comment by michaeljbrazell** [comment]
That made a significant improvement to the runtime! thank you. Re-gridding is still not scaling so well though. I also updated the p4est runs since I was running too small of a CFL. It's a different discretization so comparing total runtimes won't make much since... only the slopes really matter. 

[amrex_vs_p4est_weak_percent.pdf](https://github.com/AMReX-Codes/amrex/files/3673762/amrex_vs_p4est_weak_percent.pdf)
[amrex_vs_p4est_weak.pdf](https://github.com/AMReX-Codes/amrex/files/3673763/amrex_vs_p4est_weak.pdf)

**Comment by cburstedde** [comment]
Thanks for the comparison @michaeljbrazell.

The best of both worlds will be installing an m**d grid in each p4est octant, along the lines of what Donna Calhoun and myself are doing with forestclaw. This can be implemented entirely on the application side without changes to p4est.  m can be configurable at runtime. The numerical data should live in application memory and p4est can help with repartitioning it, exchanging ghost data, etc.

**Comment by cburstedde** [comment]
The m**d approach offers the following opportunities:

1. Starting with m=1 will already give scalability, albeit not much peak percentage.
1. m>1 can be chosen for optimal cache usage, and the upgrade path is not terrible.
1. m can be chosen such that one grid is a proper GPU work unit. Running 1 MPI rank per GPU device can properly use GPU clusters, as Lucas and Tim Warburton have shown in 2010 for up to 478 GPUs, effectively using 8**3 DOF per octant.

**Comment by asalmgren** [comment]
Another possible "best of both worlds" might be to enable oct-tree gridding in AMReX.  

@michaeljbrazell -- do you know if the "regridding" time was just for creating the boxes or whether it included copying the data.     Also -- how often was the regridding (every time step?) and did it always start at the base level or did it sometimes start at intermediate levels?

Thanks for the data.

**Comment by michaeljbrazell** [comment]
In the tutorial the function AmrCoreAdv::timeStep has a line: "if(regrid_int > 0)", a timer was added around that if statement. I'm not 100% sure the answer to your question but I think every level is able to coarsen/refine. So a lot of the time regridding is skipped on a level since another level already handled it. For these runs regrid_int = 2.

**Comment by michaeljbrazell** [comment]
Here is a 2304 proc run with the full profiler on. 

![amrex_64node_profile](https://user-images.githubusercontent.com/4116765/65988733-37187b00-e43d-11e9-9451-8c64c2a53a06.png)

**Comment by WeiqunZhang** [comment]
I made some changes in `weiqun/scaling` branch.  @michaeljbrazell Could you run the test with the new branch and show us the profiling results?

**Comment by michaeljbrazell** [comment]
Thanks @WeiqunZhang  ! I'll try it out this weekend. Our cluster is down for maintenance and I'm stuck in the queue on a different cluster.

**Comment by michaeljbrazell** [comment]
See pdfs for weak scaling, these runs are on cori with no OMP and blocking_factor = 8. I also included a 1024 proc profile, FPinfo() has improved significantly! It now looks like the lack of weak scaling in runtime is mostly due to regrid.

![Screen Shot 2019-10-05 at 8 45 20 AM](https://user-images.githubusercontent.com/4116765/66257324-7b14c400-e74c-11e9-8bca-b34b825ec63e.png)

[amrex_cori_weak_percent.pdf](https://github.com/AMReX-Codes/amrex/files/3693426/amrex_cori_weak_percent.pdf)
[amrex_cori_weak.pdf](https://github.com/AMReX-Codes/amrex/files/3693427/amrex_cori_weak.pdf)

**Comment by michaeljbrazell** [comment]
Here are the latest eagle runs with both the master branch and weiqun/scaling branch. 

[amrex_vs_p4est_weak_percent.pdf](https://github.com/AMReX-Codes/amrex/files/3703420/amrex_vs_p4est_weak_percent.pdf)
[amrex_vs_p4est_weak.pdf](https://github.com/AMReX-Codes/amrex/files/3703421/amrex_vs_p4est_weak.pdf)

![Screen Shot 2019-10-08 at 9 10 07 AM](https://user-images.githubusercontent.com/4116765/66413164-b8c35800-e9ab-11e9-82fb-a0c6306ab1d4.png)

**Comment by maikel** [comment]
Hi,

> Am 30.09.2019 um 22:20 schrieb Jon Rood <notifications@github.com>:
> 
> Hello. We have begun the process of deciding whether or not to use AMReX in another project of mine. I am curious if there are any resources showcasing AMReX and its core performance qualities, such as scaling, on more of a standalone basis? I seem to only be able to find this information from applications using AMReX. While I know weak scaling to be very good for my PeleC application and for other applications using AMReX, we are looking to be able to justify it on its on merit. Therefore we weak scaled the amrcore advection tutorial but are seeing what seem to be poor results when compared to something like p4est.

As a naive outsider, who did go through similar evaluations a year ago, I have two remarks:

1. Remark: The scope of p4est is relatively small, which I love. IMO, you could build software like AMReX on top of p4est. The feature set in AMReX is thus much richer and tailored for block based computations. Using AMReX for this kind of applications leads to higher productivity. To give an incomplete feature list...
		- various interpolations between refinement levels
		- multi-dimensional array abstractions and data handling 
		- automatic ghost cell transfers on patches (FillBoundary functions) and by using AMRLevel also asynchronouously with computation
		- an implementation to compute embedded boundary geometry information
		- a poisson solver

I have built a fairly simple explicit finite volume solver for reactive euler equations + EB only using AmrCore and not the AmrLevel facilities where the amount of work done per block is much greater than in the advection example. Are you interested in numbers for those computations? 

2. Remark: There is this paper http://www.sci.utah.edu/publications/Lui2011c/Luitjens_CCPE2011.pdf which describes a „scalable" Berger Rigoutsos algorithm. IIRC the meta data (BoxArray / DistributionMapping so to say) is semi-local. Thus, each rank sees a coarsened version of remote boxes. The algorithms for that paper are implemented in SAMRAI as different BoxGenerators / LoadBalancers, which is a library on a similar abstraction level as AMReX. I would be interested in numbers for their advection example with similar initial data and options set as in your AMReX case. 

That said, I would love to see a p4est backend (or similar) in AMReX but maybe it is easier to adapt something which is similar to the currently used algorithm in AMReX ? (Question for the AMReX developer)

**Comment by rmrsk** [comment]
In your new plots, the difference between run-time and regrid doesn't seem too bad (although not great). 

I'm a Chombo geek myself but here are my 5 cents: Does AMReX implement the"serial-like" BR algorithm where tags are collected and broadcasted to all ranks that replicate the algorithm? This algorithm might not be the best choice when regridding at large scale where the algorithm will begin to eat time and memory. For example, collecting and broadcasting 10M tagged points with 12 bytes per tag consumes 120MB (per rank that executes the algorithm). 

I certainly can't tell if this is the only issue that shows up in your tests, but as @maikel points out with the SAMRAI folks' paper, the classical algorithm has its limitations and there are other algorithms that one can (and maybe even should) use. But I first suggest that one checks if any of the conventional BR limitations apply to the scaling tests that you have presented. 

Octree grids avoid the above issues, and as @asalmgren said it might be an option for cases where the base grid allows that particular decomposition. But that is not always the case.

**Comment by GumpXiaoli** [comment]
Hi, @maikel 

Can you show your numbers for those computations?

**Comment by jrood-nrel** [comment]
I am going to close this since I don't want this issue to perpetually exist. This issue was mainly used to spark a discussion regarding our project. We are in the process of using incflo for our project and AMReX is aware of our work so we will continue to work with them on this.
