### ISSUE TITLE
Random: Single Precision Overloads

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/amrex#582]
The utility functions
- `amrex::Random`
- `amrex::RandomNormal`

need either a templateization for the real type or some variant/overload for single precision. Currently, they throw narrowing warnings in user code (WarpX) when used like this in single-precision builds:
```C++
amrex::XDim3 myvar{amrex::Random(), amrex::Random(), amrex::Random()};
```

**Comment by atmyers** [comment]
Could you tell me whether this PR fixes the issue for you? https://github.com/AMReX-Codes/amrex/pull/583

**Comment by ax3l** [comment]
That fixes it, thanks a lot!
