### ISSUE TITLE
regridding with many levels is slow

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#6]
When running Castro, with up to 8 levels of refinement, once you go above level 7, the regrid process starts getting really expansive, and does not seem proportional to the number of grids or zone

**Comment by zingale** [comment]
these are regirds that start at the finest level, so it is not the initial regrid.

For a test problem that @maxpkatz has, the number of grids on the new level is very small (in terms of volume)

**Comment by WeiqunZhang** [comment]
The suspect appears to be the code for constructing proper nesting domains in `AmrMesh::MakeNewGrids` in `Src/AmrCore/AMReX_AmrMesh.cpp`.  The block of code starts with

    Array<BoxList> p_n(max_level); // Proper nesting domain.

and ends with

            p_n[i].simplify();
    }

**Comment by WeiqunZhang** [comment]
We should investigate whether the underlying data structure of `BoxList` class should be changed from `std::list` to `std::vector`.

**Comment by WeiqunZhang** [comment]
Most of the time seems to be in `BoxList::complementIn`.

**Comment by WeiqunZhang** [comment]
BoxList::complementIn takes a Box and a BoxList and returns a new BoxList that is Box - BoxList.  The implementation has a flaw when Box is huge.   It creates boxes of size 64^2 cells in 2D.  That is why Max's test is so low.  The test has max_level=10 and ref_ratio=4.  So the domain boxes at very fine levels are huge.  Even though the number of fine Boxes is small, the proper nesting algorithm needs to compute complementIn (i.e., Domain Box - Fine Boxes).  The result of that is a huge number of boxes.

**Comment by drummerdoc** [comment]
Awesome, I was thinking my next big case would have 1025 levels, factor of 4 in 3D, so it's gonna be great when you get that sorted out!

P.S.: I'm not sure I'd call what you see an algorithm "flaw", but it's always good to make things faster/better :)

**Comment by WeiqunZhang** [comment]
Anyway, for Max's test, the new boxlist branch is probably >1000,000 times faster if > 10 levels are used.  So I think this issue can be closed, and I am going to merge boxlist into development later today.

Note some regression tests might fail because the order of boxes in a box array has changed resulting in fcompare to crash.  For all failed tests of AMReX, Castro and IAMR, the errors are roundoff.

**Comment by zingale** [comment]
fixed with the recent merge from the `boxlist` branch
