### ISSUE TITLE
No default type in AMReX_BaseFab.H

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#602]
https://github.com/AMReX-Codes/amrex/blob/3cf553a4111390195ed0cf779adb8f79eda4a01b/Src/Base/AMReX_BaseFab.H#L1160

I get errors for the linComb function when I try to compile. They go away if I change this line to be
```
template <RunOn run_on = RunOn::Cpu>
```
like the functions above it.

**Comment by WeiqunZhang** [comment]
Yes, that should be fixed.

**Comment by WeiqunZhang** [comment]
This is now fixed in commit efc6cb73a87c8.  Thanks!
