### ISSUE TITLE
Issue with inputs to isConnected

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#603]
https://github.com/AMReX-Codes/amrex/blob/780b8e79fec0d66be89e8a16238177324fc7264a/Src/EB/AMReX_EB_utils.cpp#L152

Code no longer compiles. Seems like the function calls for `isConnected` should have dimensional inputs. Like
```
isConnected({AMREX_D_DECL(ii,jj,kk)})
```
or 
```
isConnected(ii,jj,kk)
```
This impacts lines 152, 186, 198.

**Comment by asalmgren** [comment]
Oops!  Will fix this now.

**Comment by asalmgren** [comment]
Fixed
