### ISSUE TITLE
Non-uniform grid size?

### ISSUE THREAD

**Issue by mattbement** [AMReX-Codes/amrex#615]
Sorry if this has been previously discussed - does AMReX support non-uniform grid spacing, as in the attached picture?
![image](https://user-images.githubusercontent.com/24758215/68497016-98442300-0221-11ea-9b4e-f6e63cc5d3c5.png)

**Comment by WeiqunZhang** [comment]
Yes and no.  Many of the functions in AMReX assume logically rectangular grids and are independent of the physical size of cells.  They are safe to use.  But others like linear solvers and some functions in Geometry etc. are based uniform spacing.  So it depends on what you want to do.
