### ISSUE TITLE
MultiFab's Saxpy does not accept an IntVec for nghost

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#618]
The file `AMReX_MultiFab.H`, lines 533ff., declares `Saxpy` that calculate `dst += a*src`. This function expects an integer to define the number of ghost zones, and does not accept a vector of integers. This requires that the number of ghost zones is the same in all directions. All other functions nearby also accept an `const IntVect&  nghost` argument.

**Comment by eschnett** [comment]
Ditto for `LinComb`.

**Comment by WeiqunZhang** [comment]
sure. I have added those.  Will push to development branch in a few minutes.

**Comment by eschnett** [comment]
!

That's quick...

**Comment by WeiqunZhang** [comment]
Done.
