### ISSUE TITLE
AMReX GPU on nvidia-docker

### ISSUE THREAD

**Issue by bsrunnels** [AMReX-Codes/amrex#622]
I'm testing AMReX GPU in a Docker container (nvidia-docker), and getting a segfault when running the `Tutorials/Basic/HelloWorld_C` example. The abbreviated backtrace is here:

     3: amrex::DeallocateRandomSeedDevArray() 
     4: amrex::Initialize(...
     5: Util::Initialize(int, char**) at /alamo/src/Util/Util.cpp:91
     6: ./bin/test-3d-cuda-g++() [0x417c49]
     7: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f71fade3830]
     8: ./bin/test-3d-cuda-g++() [0x41d8b9]

The segmentation fault occurs in the `cudaFree` calls in `amrex::DeallocateRandomSeedDevArray()` (`AMReX_Random.cpp:320`)  It can be reproduced by running the container `bsrunnels/amrex-gpu-hello` on Docker Hub (`docker run bsrunnels/amrex-gpu/hello` using Nvidia docker). 

The docker is generated using the following Dockerfile

      FROM nvidia/cuda:9.0-devel
      RUN apt update
      RUN apt install -y git make gcc g++ gfortran libeigen3-dev python python3 mpich
      RUN git clone https://github.com/AMReX-Codes/amrex.git
      RUN cd /amrex/Tutorials/Basic/HelloWorld_C && make COMP=gnu USE_CUDA=TRUE -j8
      CMD /amrex/Tutorials/Basic/HelloWorld_C/main3d.gnu.DEBUG.CUDA.ex

Is this a result of using docker? Or an unsupported version of `nvcc`?

**Comment by zingale** [comment]
we recently had a similar issue with MAESTROeX and the problem was that the wrong CUDA architecture was being used.  This is controlled by the build system variable CUDA_ARCH.

**Comment by bsrunnels** [comment]
@zingale Thanks for the quick response - that was the issue.
For reference, I was trying to run on Turing architecture. I needed to run with `CUDA_ARCH=75` *and*  nvcc 10.1 (I had been using 9.1).
