### ISSUE TITLE
runtime configured inflow boundary conditions

### ISSUE THREAD

**Issue by darylbond** [AMReX-Codes/amrex#629]
I am wanting to implement inflow boundary conditions for my multi-fluid solver, based on the EB-CNS example, with runtime based definition of the condition. That is, define a boundary condition for each state vector, that is specific to that state, based on information passed in from the simulation configuration file. At this point I haven't been able to see how this can be done considering that we are passing in a function pointer that has no access to any contextualizing information, such as state id, that would enable my function to select the appropriate configuration.

If there is an example that I am unaware of then please let me know, otherwise, how could I go about implementing this without modifying core AMReX code?

Many thanks.

**Comment by emotheau** [comment]
Hi Daryl,
If I understand correctly, you want to specify values in ghost-cells from an input state vector. 
When it comes to compressible flows, these values should be prescribed with great care.
I suggest that you look at our paper:
"Navier-Stokes Characteristic Boundary Conditions Using Ghost Cells", AIAA J., Vol. 55, No. 10 : pp. 3399-3408, 2017

This type of boundary condition is implemented in our compressible flow solver PeleC:
https://github.com/AMReX-Combustion/PeleC

The PeleC code is more complicated than the EB-CNS example, but it can gives you an overview of the procedure.

**Comment by darylbond** [comment]
@emotheau thanks for the links! 

In PeleC, from what I can see, you essentially follow a two step procedure 1) use `bcnormal` to fill in preliminary values in the ghost cells, and then 2) call `impose_NSCBC` to get the final values. While I could implement a second pass strategy like this I would prefer to keep it all in the boundary function. Also, following this approach still gives no real flexibility when it comes to the action of `bcnormal` or its equivalent, it is the same function for all states (I have multiple states defined in my `DescriptorList`) and I don't want to write a specific function for each state as that eliminates the flexibility of my implementation. Note that I am also not writing a new `bc_fill_nd.F90` and associated files for each problem (see comments below about Lua).

Potential solutions I am considering are:

- Add another argument to `BndryFuncDefault` and its equivalents that passes in the state index. I can then use this in the fortran subroutine to reference an array of configuration parameters that I can specify for each state in the configuration module.
- Rewriting `StateDescriptor::BndryFunc` such that it takes an object rather than a function pointer (essentially replace `BndryFuncDefault` and its equivalents). This would allow as much extra information as desired to be packaged in when calling `DescriptorList::setComponent`. 
- Implement my own routines similar to `impose_NSCBC` and perform a second pass to load in the data I really want.

The background for this is that I have moved away from hard-coding every problem and now use an embedded Lua interpreter to perform my problem description such that a new problem is simply a new inputs file. I am now just trying to implement the same level of flexibility in the boundary conditions implementation as I have for the rest of the code. I am expecting that what I am asking for does not exist in the current implementation of AMReX,  but I may as well ask and hope that I am wrong.

**Comment by maikel** [comment]
> The background for this is that I have moved away from hard-coding every problem and now use an embedded Lua interpreter to perform my problem description such that a new problem is simply a new inputs file. I am now just trying to implement the same level of flexibility in the boundary conditions implementation as I have for the rest of the code. I am expecting that what I am asking for does not exist in the current implementation of AMReX, but I may as well ask and hope that I am wrong.

I have done similar things via an embedded python interpreter in the past. But only for very simple, non-performance sensitive computations, as in 2D for example. Given, that you already expose a non-owning access to the data buffer of `amrex::FArrayBox` to Lua you could implement the abstract `amrex::PhysBCFunctBase` base class and call your Lua feedback function from within `amrex::PhysBCFunctBase::FillBoundary`. In pseudo-ish C++ code

```cpp
void LuaBoundaryCondition::FillBoundary(amrex::MultiFab& mf, int dcomp, int ncomp, double timepoint, int bccomp) {
  const amrex::IntVect ngrow = mf.nGrowVect();
  amrex::Box grown_box = geom.growNonPeriodicDomain(ngrow);
  amrex::BoxList boundaries =
      amrex::complementIn(grown_box, amrex::BoxList{geom.Domain()});
  if (boundaries.isEmpty()) {
    return;
  }
  for (amrex::MFIter mfi(mf); mfi.isValid(); ++mfi) {
    amrex::FArrayBox& fab = mf[mfi];
    for (const amrex::Box& boundary : boundaries) {
      amrex::Box box_to_fill = mfi.growntilebox() & boundary;
      if (!box_to_fill.isEmpty()) {
         CALL_YOUR_LUA_FEEDBACK_FUNCTION(fab, box_to_fill, dcomp, ncomp, timepoint, bccomp);
      }
    }
  });
```

You can pass objects of classes which inherited from `amrex::PhysBCFunctBase` to the `amrex::FillPatchTwoLevels` or `amrex::FillPatchSingleLevel`.

**Comment by darylbond** [comment]
That is very helpful @maikel many thanks. I am trying to avoid using Lua for anything beyond initial configuration to avoid a performance penalty, but this definitely gives me some ideas.

**Comment by WeiqunZhang** [comment]
You can probably do something like this using std::function.

```
namespace {                                                                     
    typedef std::function<void(amrex::Real*, int const*, int const*,            
                               int const*, int const*,                          
                               amrex::Real const*, amrex::Real const*,          
                               amrex::Real const*, int const*)> BCFunction;     
    BCFunction my_denfill, my_hypfill;
}                                                                               
                                                                                
// The function pointers passed to BndryFunc have C binding                     
extern "C"                                                                      
{                                                                               
    void my_denfill_c (amrex::Real* a, int const* alo, int const* ahi,          
                       int const* domlo, int const* domhi,                      
                       amrex::Real const* dx, amrex::Real const* grid_lo,       
                       amrex::Real const* time, int const* bc)                  
    {                                                                           
        my_denfill(a,alo,ahi,domlo,domhi,dx,grid_lo,time,bc);                   
    } 
   // similarly for hypfill                     
}
```
When you set up the state descriptor, you do

```
    using namespace std::placeholders;                                          
    int prob_type = 0;  // This can be obtained from ParmParse                       
    my_denfill = std::bind(my_general_bc_fill,                                  
                           prob_type,State_Type,0,                          
                           _1,_2,_3,_4,_5,_6,_7,_8,_9); 
    my_hypfill = ...;                     
    desc_lst.setComponent(State_Type,                                           
                          Density,                                              
                          name,                                                 
                          bcs,                                                  
                          BndryFunc(my_denfill_c,cns_hypfill_c));
```

Your generic bc function is something like

``void my_general_bc_fill(int prob_type, int state_type, int groupfill, // these \
are extra parameters.                                                           
                        // parameters below are the normal bc function paramete\
rs.                                                                             
                        amrex::Real* a, int const* alo, int const* ahi,         
                        int const* domlo, int const* domhi,                     
                        amrex::Real const* dx, amrex::Real const* glo,          
                        amrex::Real const* time, int const* bc)                 
{                                                                               
    if (state_type == 0 and groupfill == 0) {                                   
        cns_denfill(a,alo,ahi,domlo,domhi,dx,glo,time,bc);                      
    } else if (state_type == 0 and groupfill == 1) {                            
        cns_hypfill(a,alo,ahi,domlo,domhi,dx,glo,time,bc);                      
    } else if (state_type == 1) {                                               
        cns_nullfill(a,alo,ahi,domlo,domhi,dx,glo,time,bc);                     
    }                                                                           
} 
```
Here cns_*fill etc. are the normal bc fill functions.

**Comment by drummerdoc** [comment]
I agree with Weiqun.  The simplest version of this is the ChemBndryFunc class used in PeleLM, which subclasses BndryFunc (and in fact is the reason we changed the bc filler functions to this functional form).  Here a new class instance can be created on the fly with its own constructor to store any info required and it just needs to supply the fill function signature that AMReX's fill patch is expecting.  In the ChemBndryFunc example, we just needed it to remember the component of the state in the State_Type descriptor, but you may want it to know lots more info about your problem as well.

**Comment by WeiqunZhang** [comment]
My version is trying to do the same thing with std::bind as Marc's version.  But I actually like Marc's version better.  It was the reason we made `BndryFunc::operator()` virtual and I have forgot about it when I saw the issue this morning.  It's a function on steroid (functionoid).   https://isocpp.org/wiki/faq/pointers-to-members#functionoids

**Comment by darylbond** [comment]
I have implemented a similar solution to ChemBndryFunc which seems to be working quite well. Huge thanks for all the suggestions. 

The only tweak that would be nice is to make all member functions of `BndryFunc` virtual (in particular `hasFabVersion`) so that I can have full control. Essentially I have overridden the FAB version of `operator ()` such that I don't need a function pointer and just need to force the selection of this operator even though `m_funcfab == nullptr`.

**Comment by WeiqunZhang** [comment]
Sure.  We can do that.  I have made BndryFunc::RunOnGpu() and hasFabVersion() virtual in the development branch.
