### ISSUE TITLE
Using std parameter in GNU make

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#634]
I noticed `-std=c++14` was not being used even though I'm using GCC 7. Should some kind of "greater than" logic be used here?
https://github.com/AMReX-Codes/amrex/blob/3a302579f324d82feb230bf2d94e71b98c84cb51/Tools/GNUMake/comps/gnu.mak#L117-L122

**Comment by jrood-nrel** [comment]
I can verify that if I use GCC 5, it includes `-std=c++14` for me.

**Comment by WeiqunZhang** [comment]
By default, gcc >= 5 uses

```
           gnu++14                                                                                          
           gnu++1y                                                                                          
               GNU dialect of -std=c++14.  This is the default for C++ code.  The name gnu++1y is           
               deprecated.
```

**Comment by WeiqunZhang** [comment]
Want to be clear.  Without `-std`, gcc >= 6 itself will use gnu++14.  So the make system is essentially doing

```
if gcc <= 3
   will fail at compile time because of the lack of support for C++11
else if gcc == 4
  use c++11
else if gcc == 5
  use c++14
else
  use gcc's default that is >= c++14
endif
```

**Comment by jrood-nrel** [comment]
I see. Thanks, I didn't realize this. I think I was seeing a problem in some code I was working with because it involved the GNU extensions being enabled due to using `gnu++14` by default. It's not a problem now that I understand it.
