### ISSUE TITLE
EB geometry creation - amrex::Abort

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/amrex#635]
Hi,

For certain geometries, the code aborts at the line

amrex::Abort("Failed to build required coarse EB level "+std::to_string(ilev));

But if the geometry is slightly altered/shifted, it works fine. Can you please explain why this happens exactly, and how it can be avoided? Not able to figure out from the code. Thanks.

**Comment by WeiqunZhang** [comment]
Please take a look at Issue #608.

**Comment by nataraj2** [comment]
Yes. That clarifies things. Thanks, Weiqun.
