### ISSUE TITLE
MFIter Loops with OpenMP and GPU

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#645]
Hello. Looking at the GPU CNS tutorial and Incflo for examples, I would expect most, if not all MFIter loops to look similar in regards to decorations for OpenMP/tiling and GPU, but neither example project appears to be totally consistent. When researching the correct way to use MFIter loops for OpenMP/tiling, and GPU/no tiling, what is the correct way to decorate the MFIter loop? Or is there a methodology I am not grasping for why certain loops in Incflo are explicitly not tiled, for example, or why I would choose to not use:
```
#ifdef _OPENMP
#pragma omp parallel if (Gpu::notInLaunchRegion())
#endif
        for (MFIter mfi(rho,TilingIfNotGPU()); mfi.isValid(); ++mfi)
```
for every MFIter loop?

The reason I am asking this is that there seems to be a problem we are seeing if we set `for (MFIter mfi(S_new,TilingIfNotGPU()); mfi.isValid(); ++mfi)`. When `TilingIfNotGPU` is `true` because we are compiling for the CPU, or if we explicitly use `mfi(S_new,true)`. We see the loop get called 16 times when we only expect it called once for the CPU case without OpenMP. Here is some example code for our `initdata`:
```
  for (MFIter mfi(S_new,TilingIfNotGPU()); mfi.isValid(); ++mfi)
  {
      const Box& box = mfi.validbox();
      auto sfab = S_new.array(mfi);
      amrex::ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept {
          pc_initdata(i, j, k, sfab, geomdata);
      });
  }
```
Is this an issue with how we are compiling or something else we are missing? Or is the 16 calls to `pc_initdata`happening with different bounds each call, even without threading? We notice a large penalty in runtime when tiling is set to `true` in this `initdata` example. We are using llvm with `USE_OMP=false`, `USE_CUDA=false`, and `USE_MPI=false`.

**Comment by maxpkatz** [comment]
```
      const Box& box = mfi.validbox();
```
You'll want that to be `mfi.tilebox()` for loops that tile. That's safe to use for the GPU loops as well, since the tilebox is equal to the validbox when you're not tiling.

**Comment by jrood-nrel** [comment]
Ah! Thanks @maxpkatz I need to double check that in our loops in question. That's probably it, but I will confirm.

**Comment by jrood-nrel** [comment]
Thanks @maxpkatz . That was our problem in all instances, although we were using `tilebox` in certain instances, we overlooked this.
