### ISSUE TITLE
cpp version of `get_neighbor_cells`?

### ISSUE THREAD

**Issue by marchdf** [AMReX-Codes/amrex#662]
Hi, we are working on porting Fortran kernels to c++ for PeleC. We have some Fortran code that looks like:

```
    call get_neighbor_cells_int(flag(i,j,k), nbr)
    flagArrayL = nbr(-1,0,0).eq.1 .and. .not. is_covered_cell(flag(i,j,k))
    flagArrayR = nbr(+1,0,0).eq.1 .and. .not. is_covered_cell(flag(i,j,k))
```

Is there a c++ equivalent for `get_neighbor_cells_int(flag(i,j,k), nbr)`? `AMReX_EBCellFlag.H` seems to have capability that looks close to what we are looking for but not quite. Or am I missing something? Thanks!

**Comment by WeiqunZhang** [comment]
You can do

```
bool flagArrayL = flag(i,j,k).isConnected(-1,0,0) and !flag(i,j,k).isCovered();
bool flagArrayR = flag(i,j,k.isConnected(+1,0,0) and !flag(i,j,k).isCovered();
```

**Comment by marchdf** [comment]
Thanks!
