### ISSUE TITLE
RealVect changes break my compile

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#663]
https://github.com/AMReX-Codes/amrex/blob/4cbc0b076a70a299fd4d8b0c51c6c3d6aa34f2ce/Src/Base/AMReX_RealVect.H#L554

I get an error when compiling for lines 554 and 562 in AMReX_RealVect.H. The error is
```
AMReX_RealVect.H:554:29: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
  static constexpr RealVect TheZeroVector () noexcept {
```
Any ideas how I can fix this? @rporcu

**Comment by WeiqunZhang** [comment]
I suspect the issue might be function `operator= (const RealVect& rhs)`.  Could you remove that function from .H and .cpp?  The compiler will generator it anyway.

**Comment by ldowen** [comment]
That didn't seem to fix it.

**Comment by rporcu** [comment]
I will fix it.
Thanks for letting me know and sorry for the issue.

Best,
Roberto

**Comment by rporcu** [comment]
Can you try removing the constexpr qualifier from the constructor at line 60 in file AMReX_RealVect.H ?

**Comment by zingale** [comment]
not sure if this is the same issue, but I get the compilation failure:
```
/home/zingale/development/AMReX//Src/Base/AMReX_RealVect.cpp:205:37: error: call of overloaded ‘RealVect(int)’ is ambiguous
  205 |     RealVect tmp(AMREX_D_DECL(0,0,0));
      |                                     ^
```
now.

**Comment by ldowen** [comment]
It looks like possible solutions are either removing `constexpr` from lines 554 and 562 in AMReX_RealVect.H or adding `constexpr` to line 76 in AMReX_RealVect.H

**Comment by WeiqunZhang** [comment]
@ldowen What compiler are you using?  I am trying to understand the issue.

**Comment by WeiqunZhang** [comment]
It's clang.

**Comment by WeiqunZhang** [comment]
I think I figured it out.  It's the copy constructor not being constexpr.

**Comment by WeiqunZhang** [comment]
Could you try the latest development?

**Comment by WeiqunZhang** [comment]
Instead of removing constexpr, I removed the copy-ctor to allow compiler generated copy-ctor.

**Comment by zingale** [comment]
development works for me

**Comment by ldowen** [comment]
I apologize for not getting back to you sooner. You are correct, it is clang, and the latest development branch worked for me! I will close this issue. Thank you for the help!
