### ISSUE TITLE
Private members in ParmParse

### ISSUE THREAD

**Issue by bsrunnels** [AMReX-Codes/amrex#666]
Is it possible to make the private ParmParse members `protected` instead of `private`?  (Specifically `pushPrefix` and `popPrefix`). I am writing some customized `read` routines for classes and would like to be able to add sub-prefixes by creating a derived class that accesses `pushPrefix` and `popPrefix`.

**Comment by WeiqunZhang** [comment]
Sure, we could do that.

But what does sub-prefix mean? `i0.i1.i2 = 1`?  You can already read that in 3 ways.

```
amrex::ParmParse pp;
pp.query("i0.i1.i2", i);
```

```
amrex::ParmParse pp("i0");
pp.query("i1.i2", i);
```

```
amrex::ParmParse pp("i0.i1");
pp.query("i2", i);
```

**Comment by bsrunnels** [comment]
Say I have a class `Circle` with field `radius`. I would like to be able to do:

    Circle circle1, circle2;
    Derived::ParmParse pp("shapes");
    pp.queryclass("circle1",circle1);
    pp.queryclass("circle2",circle2);

corresponding to the input file

    shapes.circle1.radius = 1.0
    shapes.circle2.radius = 2.0

where the handling of `radius` and other `Circle`-specific parameters is handled automatically. I'd like to be able to append `radius` to the prefix by the `queryclass` method, and would need access to the `push` and `pop` routines for that.

**Comment by WeiqunZhang** [comment]
The change has been made in development.

**Comment by bsrunnels** [comment]
Great, thanks.
