### ISSUE TITLE
amrex::Abort depending on order of input parameters (in WarpX)

### ISSUE THREAD

**Issue by mrowan137** [AMReX-Codes/amrex#668]
I am getting an AMReX error depending on the order of saved fields in my WarpX input file (full input is copied below).  With this ordering, 
```warpx.fields_to_plot = proc_number part_per_cell ```
the WarpX code runs without issue.  With this ordering,
```warpx.fields_to_plot = part_per_cell proc_number ```
the run gets to step 3 before this error appears:
```STEP 3 starts ...
amrex::Abort::7::CUDA error 700 in file ../amrex/Src/Base/AMReX_GpuDevice.H line 171: an illegal memory access was encountered !!!```
The full WarpX input file is copied here:
```
\# Maximum number of time steps: command-line argument                                                       
\# number of grid points: command-line argument                                                              
max_step = 10                                                                                            
warpx.load_balance_with_sfc = 0                                                                             
warpx.load_balance_int = 1
amr.plot_int = 1   # How often to write plotfiles.                                                         
warpx.fields_to_plot = part_per_cell proc_number
\# Maximum allowable size of each subdomain in the problem domain;                                           
\#    this is used to decompose the domain for parallel calculations.                                        
amr.max_grid_size = 64                                                                                      
amr.blocking_factor = 64                                                                                    
amr.n_cell = 256 256 384                                                                                    
\# Maximum level in hierarchy (for now must be 0, i.e., one level in total)                                  
amr.max_level = 0                                                                                           
\# Geometry                                                                                                  
geometry.coord_sys   = 0                  # 0: Cartesian                                                    
geometry.is_periodic = 0 0 1      # Is periodic?                                                            
geometry.prob_lo     = -20.e-6   -20.e-6   -30.e-6    # physical domain                                     
geometry.prob_hi     =  20.e-6    20.e-6    30.e-6                                                          
algo.current_deposition = esirkepov                                                                            
interpolation.nox = 3                                                                                          
interpolation.noy = 3                                                                                          
interpolation.noz = 3                                                                                          
warpx.cfl = 1.0                                                                                                
warpx.verbose = 1                                                                                              
warpx.do_pml = 0                                                                                               
particles.nspecies = 2                                                                                         
particles.species_names = electrons ions                                                                       
electrons.charge = -q_e                                                                                        
electrons.mass = m_e                                                                                           
electrons.injection_style = "NUniformPerCell"                                                                  
electrons.num_particles_per_cell_each_dim = 2 2 4                                                              
electrons.profile = constant                                                                                   
electrons.density = 1.e20  # number of electrons per m^3                                                       
electrons.momentum_distribution_type = "gaussian"                               
electrons.zmax = 7.e-6                                                                                          
electrons.zmin = 2.e-6                                                                                          
electrons.ux_th  = 0.001                                                                                        
electrons.uy_th  = 0.001                                                                                        
electrons.uz_th  = 0.01                                                                                         
electrons.ux_m  = 0.                                                                                            
electrons.uy_m  = 0.                                                                                            
electrons.uz_m  = 0.
ions.charge = q_e                                                                                              
ions.mass = m_p                                                                                                
ions.injection_style = "NUniformPerCell"                                                                       
ions.num_particles_per_cell_each_dim = 2 2 4                                                                   
ions.profile = constant                                                                                        
ions.density = 1.e20  # number of electrons per m^3                                                            
ions.momentum_distribution_type = "gaussian"                                                                   
ions.zmax =  7.e-6                                                                                             
ions.zmin =  2.e-6                                                              
ions.ux_th  = 0.001                                                                                             
ions.uy_th  = 0.001                                                                                             
ions.uz_th  = 0.01                                                                                              
ions.ux_m  = 0.                                                                                                 
ions.uy_m  = 0.                                                                                                 
ions.uz_m  = 0.    
```

**Comment by atmyers** [comment]
Thanks for reporting this. I think it's likely a WarpX issue, so I'm going to migrate this over there.
