### ISSUE TITLE
Segfault in latest Dev

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/amrex#669]
@WeiqunZhang you probably saw it already in our chat, but commit c01fd4cc6c12d2e8bdd2b289b8d8d4c5206559f6 introduces a segfault in WarpX for all CI jobs and local builds.

**Comment by ax3l** [comment]
With debug symbols, the following assert is thrown:
```
0::Assertion `dm.ProcessorMap().size() == bxs.size()' failed, file "../amrex/Src/Base/AMReX_FabArrayBase.cpp", line 188 !!!
```

**Comment by WeiqunZhang** [comment]
It is fixed now.  Thanks!

**Comment by ax3l** [comment]
Awesome, thanks a lot! :sparkles:
