### ISSUE TITLE
Compilation error with USE_CUDA=TRUE

### ISSUE THREAD

**Issue by cgilet** [AMReX-Codes/amrex#681]
When compiling incflo with USE_CUDA=TRUE, DEBUG=TRUE, I get these errors:

AMReX_EBMultiFabUtil.cpp -o tmp_build_dir/o/3d.gnu.DEBUG.CUDA.EB.EXE/AMReX_EBMultiFabUtil.o
../../amrex/Src/EB/AMReX_EBMultiFabUtil_3D_C.H(401): warning: calling a __host__ function from a __host__ __device__ function is not allowed

../../amrex/Src/EB/AMReX_EBMultiFabUtil_3D_C.H(581): warning: calling a __host__ function from a __host__ __device__ function is not allowed

/usr/include/c++/7/tuple(198): error: calling a __host__ function("std::vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::vector") from a __device__ function("std::vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::vector [subobject]") is not allowed

/usr/include/c++/7/tuple(198): error: identifier "std::vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::vector" is undefined in device code

/usr/include/c++/7/tuple(198): error: calling a __host__ function("std::vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::~vector") from a __device__ function("std::vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::~vector [subobject]") is not allowed

/usr/include/c++/7/tuple(198): error: identifier "std::vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::~vector" is undefined in device code

../../amrex/Src/EB/AMReX_EBMultiFabUtil_3D_C.H(401): warning: calling a __host__ function("amrex::Vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::dataPtr const") from a __host__ __device__ function("amrex::eb_interp_cc2facecent") is not allowed

../../amrex/Src/EB/AMReX_EBMultiFabUtil_3D_C.H(581): warning: calling a __host__ function("amrex::Vector< ::amrex::BCRec, ::std::allocator< ::amrex::BCRec> > ::dataPtr const") from a __host__ __device__ function("amrex::eb_interp_cc2face") is not allowed

4 errors detected in the compilation of "/tmp/tmpxft_000067e5_00000000-6_AMReX_EBMultiFabUtil.cpp1.ii".

**Comment by jmsexton03** [comment]
When I compile on corigpu for the current development version of amrex & incflo in incflo/test I don't get the errors, although I do get the warnings:
```
module load gcc cuda openmpi
module list
#Currently Loaded Modulefiles:
#  1) esslurm            2) modules/3.2.11.4   3) gcc/8.3.0          4) openmpi/4.0.2      5) jdk/1.8.0_202     
 6) cuda/10.2.89
make USE_CUDA=TRUE DEBUG=TRUE USE_MPI=FALSE 
```

**Comment by WeiqunZhang** [comment]
It might have something to do with the version of CUDA and GCC.  But in any case, it is a bug.  Marc and I were aware of this.  But haven't got time to fix it.  The good news is if you are not using that particular *EB* function on GPU (which is actually case for now for everyone), you can compile with `DEBUG=FALSE`.

**Comment by WeiqunZhang** [comment]
I was joking with Marc the other day saying I needed to remember to put on my todo list that I need to put this on my todo list.  Anyway I will stop my structured procrastination and fix it now.

**Comment by WeiqunZhang** [comment]
Just pushed a fix.

**Comment by cgilet** [comment]
Thanks!
