### ISSUE TITLE
Enhanced FlashFluxRegister methods

### ISSUE THREAD

**Issue by kweide** [AMReX-Codes/amrex#688]
Thank you @WeiqunZhang for adding the `amrex_flash_fluxregister` Fortran type and its `store`, `communicate`, and `load` methods.

Based on several use cases for flux register functionality in FLASH code, I would like to request three  enhancements to the functionality (roughly in order of priority):
1. Additional arithmetic (in `load`)
2. Area factors (in `store` and `load`)
3. `isFluxDensity` flags (in `store` and `load`)

I think these will be straightforward to implement (especially 1 and 2), and I am willing to try that and provide PRs. But you may have a different preferred way of doing something like this, and have much better understanding of performance or portability aspects, so I am going to write down the requirements (in the process also clarifying them for myself) and hope for comments or even code.

Details will follow in a series of comments.

**Comment by kweide** [comment]
### Remarks (maybe return to this later)
* __Motivation:__ All the things requested could be done with the existing `load` and `store` methods, by pre- and postprocessing the fluxes appropriately. The main reason for wanting new features inside those methods: the `FlashFluxRegister` code keeps track of where fine-coarse boundaries occur, and `amrex_flash_fluxregister` cleverly uses this information to restrict its actions (especially in `load`) to exactly the right cell face locations. We have to keep track of this metainformation separately in FLASH code (or we have to repeatedly invoke auxiliary functions to enquire about it), if we want some actions only to be performed on fluxes on the fine side of a f-c boundary (as we do).
* Nothing should have to change in the `communicate` method.
* __Implementation__ could be done by just adding to the existing `store` and `load` methods, by introducing optional arguments, by providing variant methods under different names (together with Fortran `GENERIC`), or a combination thereof. A similar choice has to be made at the level of C++ methods. That's one reason I'm asking for input.

**Comment by kweide** [comment]
### 0. Existing Functionality
(Inner code shown is for the 2D case.)

`call flux_reg%store(flux=src, flo, fhi, igrd, dir[, sf])` with partial interface
```Fortran
integer, intent(in) :: flo(*), fhi(*), igrd, dir  ! not repeated below
real, intent(in) :: flux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
``` 
leads to

```C++
     dest(i,j,0,n) = (src(2*i,2*j  ,0,n) +
                      src(2*i,2*j+1,0,n)) * (0.5*sf);
```


`call flux_reg%load(flux=dest, flo, fhi, igrd, dir[, sf])` with partial interface
```Fortran
real, intent(inout) :: flux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
```
leads to (only at fine sides of f/c boundaries!)

```C++
dest(i,j,k,n) = src(i,j,k,n) * sf
```

**Comment by kweide** [comment]
### 1. Additional Arithmetic in `load`
(Method `store` as above.)

`call flux_reg%load(flux=dest, flo, fhi, cflux, igrd, dir, sf_f, sf_c)` with partial interface
```Fortran
real, intent(inout) :: flux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
real, intent(in   ) :: cflux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
```
leads to (only at fine sides of f/c boundaries!)

```C++
dest(i,j,k,n) = src(i,j,k,n) * sf_f + cflux(i,j,k,n) * sf_c
```
(In the simplest use case we would call with `sf_f=+1.0, sf_c=-1.0`, but that will not always be the case.)

__Note__ `flux` and `cflux` dummy arrays have the same shape and bounds. The corresponding actual arguments will have to refer to memory locations different from each other, because of Fortran aliasing rules.

**Comment by kweide** [comment]
### 2. Area Factors
(shown here on top of Additional Arithmetic enhancement)

`call flux_reg%store(flux=src, area, flo, fhi, igrd, dir[, sf])` with partial interface
```Fortran
real, intent(in) :: flux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
real, intent(in) :: area(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3))
``` 
leads to (Note: no factor of `0.5`!)

```C++
     dest(i,j,0,n) = (src(2*i,2*j  ,0,n)*area(2*i,2*j  ,0) +
                      src(2*i,2*j+1,0,n)*area(2*i,2*j+1,0)) * sf;
```
(Optional `sf` may not actually be needed.)

`call flux_reg%load(flux=dest, area, flo, fhi, cflux, igrd, dir, sf_f, sf_c)` with partial interface
```Fortran
real, intent(inout) :: flux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
real, intent(in   ) :: area(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3))
real, intent(in   ) :: cflux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
```
leads to (only at fine sides of f/c boundaries!)

```C++
dest(i,j,k,n) = src(i,j,k,n)/area(i,j,k) * sf_f + cflux(i,j,k,n) * sf_c;
```
(In the simplest use case we would call with `sf_f=+1.0, sf_c=-1.0`, but that will not always be the case.)

(Again, `flux` and `cflux` dummy arrays have the same shape and bounds, but corresponding actual arguments will have to refer to memory locations different from each other.)

**Comment by WeiqunZhang** [comment]
Could you let know if the current `FlashFluxRegister` does what you need?

**Comment by kweide** [comment]
### 3. isFluxDensity flags
(shown here on top of Additional Arithmetic and Area Factors enhancements)

`call flux_reg%store(flux=src, area, flo, fhi, isFluxDensity, igrd, dir[, sf])` with partial interface
```Fortran
real, intent(in) :: flux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
real, intent(in) :: area(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3))
logical,intent(in) :: isFluxDensity(flo(3):fhi(3))
``` 
leads to

```C++
  if isFluxDensity(n) {
     dest(i,j,0,n) = (src(2*i,2*j  ,0,n)*area(2*i,2*j  ,0) +
                      src(2*i,2*j+1,0,n)*area(2*i,2*j+1,0)) * sf;
  } else {
     dest(i,j,0,n) = (src(2*i,2*j  ,0,n) +
                      src(2*i,2*j+1,0,n)) * sf;
  }
```
(Optional `sf` may not actually be needed.)

`call flux_reg%load(flux=dest, area, flo, fhi, isFluxDensity, cflux, igrd, dir, sf_f, sf_c)` with partial interface
```Fortran
real, intent(inout) :: flux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
real, intent(in   ) :: area(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3))
real, intent(in   ) :: cflux(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3),flo(4):fhi(4))
logical,intent(in) :: isFluxDensity(flo(3):fhi(3))
```
leads to (only at fine sides of f/c boundaries!)

```C++
  if isFluxDensity(n) {
      dest(i,j,k,n) = src(i,j,k,n)/area(i,j,k) * sf_f + cflux(i,j,k,n) * sf_c;
  } else {
      dest(i,j,k,n) = src(i,j,k,n)             * sf_f + cflux(i,j,k,n) * sf_c;
  }
```
(In the simplest use case we would call with `sf_f=+1.0, sf_c=-1.0`, but that will not always be the case.)

(Again, `flux` and `cflux` dummy arrays have the same shape and bounds, but corresponding actual arguments will have to refer to memory locations different from each other.)

If the conditional stuff is considered bad, then the logical `isFluxDensity` could be replaced by something like a 1D real array `fluxFactor` of the same shape, used as a switch (with values expected to be either `1.0` or `0.0`) and used to multiply some terms in the inner loops by either `fluxFactor(n)` or `(1-fluxFactor(n))`.

**Comment by WeiqunZhang** [comment]
I assume `isFluxDensity(flo(3):fhi(3))` should read `isFluxDensity(flo(4):fhi(4))`.

**Comment by kweide** [comment]
Yes, `isFluxDensity(flo(3):fhi(3))` should read 
`isFluxDensity(flo(4):fhi(4))`, I will correct it.

**Comment by WeiqunZhang** [comment]
How big is `fhi(4)-flo(4)+1` typically?  Is there an upper limit?

**Comment by WeiqunZhang** [comment]
Can we pass `isFluxDensity` to the constructor of `FlashFluxRegister`?  Does it change?

**Comment by kweide** [comment]
Regarding `fhi(4)-flo(4)+1` :
This will be the number of fluxes used by Hydro, including all those for variables that just get advected.  Btw. this should always be a compile-time constant in FLASH.

Typical sizes are "a handful" to "the number of nuclear species included + a handful." But I believe there are also plans to run FLASH in situations were NFLUXES would be hundreds-ish or more, which would include radiation groups.

**Comment by kweide** [comment]
For our Hydro purposes that I can think of, `isFluxDensity` should not change. It is possible that in some scheme the `load` call might want to use a different `isFluxDensity` from the `store`call; but I think we can disregard that possibility. So passing it to the `_build` routine should be fine.

**Comment by WeiqunZhang** [comment]
Here is what I think now.  We don't need to pass `isFluxDensity`.  The first time FlashFluxRegister sees it, a copy will be stored.  For later calls, we will check if the passed argument agrees with the stored values.  This is mostly a premature optimization to avoid copying data to gpu.

**Comment by kweide** [comment]
No objection. I don't really understand the GPU aspects well enough to comment more.

Testing of all this on our part may have to wait until next week, but I really appreciate your work.

**Comment by WeiqunZhang** [comment]
`isFluxDensity` has been implemented in `FlashFluxRegister` branch.

**Comment by kweide** [comment]
Thank you!  I have started running some tests in FLASH code using the previous version, `AMREX_GIT_VERSION=20.02-266-g2d4ad21e3691` (2d4ad21e3691). Maybe we can keep this issue open for tracking any successes or failures.

**Comment by kweide** [comment]
Found as problem in FLASH code with FlashFluxRegister from commit 2d4ad21e3691; I believe (but have not verified) that this is still present in the latest code version.

Test problem is 2D Sod with 6 levels AMR. Code initialized runs successfully for ~170 time steps. The grid changes 10 times during that time, blocks are both created and destroyed at various times, no problem. Then, after the grid changes once more, the run fails:

Symptoms: runtime failures, including SEGAULT, SIGFPE, etc., in not-exactly-reproducing ways, pointing to memory corruption. 

I think I understand what is happening, but I do not know why this wasn't a problem before with the regular FluxRegister class.

We use our own (FLASH5's) callbacks that are stored with `amrex_init_virtual_functions`. To trace the calls, each produces a line of output, as follows. (This is run on 1 MPK task.) (level numbers are according to FLASH convention, 1(coarsest) .. 6(FINEST).)
```
...
8th grid change event:
[gr_clearLevelCallback]              Cleared level 5
Remade level 5 - 160 blocks
[gr_clearLevelCallback]              Cleared level 6
Remade level 6 - 256 blocks
...
9th grid change event:
[gr_clearLevelCallback]              Cleared level 5
Remade level 5 - 160 blocks
[gr_clearLevelCallback]              Cleared level 6
Remade level 6 - 192 blocks
...
10th grid change event:
[gr_clearLevelCallback]              Cleared level 6
Remade level 6 - 256 blocks
...
11th grid change event:
[gr_clearLevelCallback]              Cleared level 4
Remade level 4 - 64 blocks
[gr_clearLevelCallback]              Cleared level 5
Remade level 5 - 128 blocks
...
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
```
Note that the last grid change, after which the exception occurs, does not go all the way to level 6, different from all the preceding grid change events. I have verified visually that this makes sense: all the finest blocks at this point in the simulation do (and should) remain unchanged.

My theory of the case: the FlashFluxRegister object coupling levels 5-6 needs to be rebuilt when the grid blocks at either level 5 or level 6 change. But the destroy/build only happens when the callbacks are called for level 6 - which is not always the case when grid blocks at level 5 change.

The code under `Tutorials/Amr/Advection_octree_F2` should have the same problem (but I haven't tested it), since the `call amrex_flash_fluxregister_build` statements in the callbacks follow the same logic.

I am not sure how this should be fixed.

**Comment by WeiqunZhang** [comment]
Could you try the latest `FlashFluxRegister` branch and let me if it's fixed?

**Comment by kweide** [comment]
Started testing now (but not yet additional features of area factors and isFluxDensity). Looks good so far. In particular, the runtime failures I reported above are gone.

Thank you!

**Comment by rajeeja** [comment]
It seems to work. Thanks!

**Comment by WeiqunZhang** [comment]
Great.  I will merge it into development branch.

**Comment by asalmgren** [comment]
Has this issue been resolved?   If so, @kweide could you close it?

**Comment by kweide** [comment]
The methods added are working fine for us, as far as we have exercised them.
