### ISSUE TITLE
CMake does not install the full Fortran interface

### ISSUE THREAD

**Issue by certik** [AMReX-Codes/amrex#69]
Here is how to reproduce using the latest master (3724a070adf93b46c4170eccb6d295e466abaed8) of AMReX:
```
module load cmake/3.6.2 gcc/5.3.0 openmpi/1.10.5
cd $HOME/repos/amrex
cmake -DCMAKE_INSTALL_PREFIX=inst .
make -j16
make install
```
This did not install the `Src/F_Interfaces/Base/AMReX_base_mod.F90` module into `$HOME/repos/amrex/inst/include`. In fact, by looking into the `Src/F_Interfaces/Base/` directory, it seems that it is missing the CMake build system completely.

This was originally reported in #63.

**Comment by mic84** [comment]
@certik I pushed the fix to branch mr-cmake. Please try it out and let me know if the problem persists. Thanks.
