### ISSUE TITLE
For December version of AMReX "Base" code, need to flush the TileArrayCache,FB, and CP otherwise problems ...

### ISSUE THREAD

**Issue by msussman42** [AMReX-Codes/amrex#692]
I put sanity checks into my code everywhere there is a "MFIter" loop.  The sanity check verifies that 
mf.boxArray().d_numPts() equals the sum over all the distinct MPI nodes, and all the OMP threads, of mfi.tilebox().d_numPts().

I found for a simple test, not using MPI, but using 4 OMP threads, that the sanity check failed after 6727431430 calls to MFIter (note, I did not put the sanity check in any MFIter loops in the "Base" directory so the critical number at which the sanity check fails is going to be greater than 6727431430).  When I put these flush commands at the beginning of each timestep, the problem disappears:
    FabArrayBase::flushTileArrayCache();
     FabArrayBase::flushFBCache();
     FabArrayBase::flushCPCache();

I am using the amrex libraries from December 2019.  I regrid every time step, but the grids are identical each time step.  Also, I notice that the code runs about 5 percent faster when I flush the cache.   Am I doing something wrong? Or is it expected that one should periodically give flush commands? Note: I call MFIter often, because I use a customized "gmres-multigrid" preconditioned BiCGStab solver - many calls to MFIter on the coarsest MG levels.  Here are some code fragments of one of the places I put a sanity check (I can give you github address of full test if interested):

    thread_class::init_d_numPts(localMF[fd_mf]->boxArray().d_numPts()); 
#ifdef _OPENMP
#pragma omp parallel
#endif
{
    for (MFIter mfi(*localMF[fd_mf],use_tiling); mfi.isValid(); ++mfi) {
     BL_ASSERT(grids[mfi.index()] == mfi.validbox());
     const int gridno = mfi.index();
     const Box& tilegrid = mfi.tilebox();

.......
    thread_class::tile_d_numPts[tid_current]+=tilegrid.d_numPts();
.......
    } // mfi
} // omp
    ns_reconcile_d_num(114);

The "ns_reconcile_d_num" command adds up the tilegrid.d_numPts() values from all the MPI nodes and OMP threads.

Sincerely,
Mark Sussman 
sussman@math.fsu.edu

**Comment by WeiqunZhang** [comment]
In principle, one should not need to call flush.  Maybe some resources are not properly released.  Instead of calling flush every step, could you try the following and let use know what you see?

```
if (ParallelDescriptor::IOProcessor()) {
	m_FA_stats.print();
	m_TAC_stats.print();
	m_FBC_stats.print();
	m_CPC_stats.print();
	m_FPinfo_stats.print();
	m_CFinfo_stats.print();
}
```

The cache sizes should stay stable after some point.  If they keep growing, we need to figure out why.

**Comment by msussman42** [comment]
Dear Dr. Weiqun Zhang,
I did the test.  Please find below what was observed.  Note: DEBUG=FALSE,
USE_MPI=FALSE, USE_OMP=TRUE,
USE_ASSERTION=TRUE, PROFILE=FALSE, MEM_PROFILE=FALSE, DIM=2
Mark
--------------------------------------------------------------------------------------------------
after the first time step:
### FabArray ###
    tot # of builds       : 63053
    max # of FabArrays    : 403
    max # of BoxArrays    : 4
    max # of BoxArray uses: 240
### TileArrayCache ###
    tot # of builds  : 16419
    tot # of erasures: 16407
    tot # of uses    : 21186959
    max cache size   : 14
    max # of uses    : 178
### FBCache ###
    tot # of builds  : 21
    tot # of erasures: 0
    tot # of uses    : 1646831
    max cache size   : 21
    max # of uses    : 0
### CopyCache ###
    tot # of builds  : 23958
    tot # of erasures: 23932
    tot # of uses    : 32850
    max cache size   : 28
    max # of uses    : 10
### FillPatchCache ###
    tot # of builds  : 10
    tot # of erasures: 0
    tot # of uses    : 2638
    max cache size   : 10
    max # of uses    : 0
### CrseFineCache ###
    tot # of builds  : 0
    tot # of erasures: 0
    tot # of uses    : 0
    max cache size   : 0
    max # of uses    : 0


After the last successful step (step 117); the last step prior to the step
in which my sanity check was violated:
### FabArray ###
    tot # of builds       : 26193694
    max # of FabArrays    : 403
    max # of BoxArrays    : 4
    max # of BoxArray uses: 240
### TileArrayCache ###
    tot # of builds  : 6861350
    tot # of erasures: 6861338
    tot # of uses    : 8928898804
    max cache size   : 14
    max # of uses    : 178
### FBCache ###
    tot # of builds  : 21
    tot # of erasures: 0
    tot # of uses    : 694062084
    max cache size   : 21
    max # of uses    : 0
### CopyCache ###
    tot # of builds  : 10036993
    tot # of erasures: 10036967
    tot # of uses    : 13661677
    max cache size   : 28
    max # of uses    : 10
### FillPatchCache ###
    tot # of builds  : 10
    tot # of erasures: 0
    tot # of uses    : 1035554
    max cache size   : 10
    max # of uses    : 0
### CrseFineCache ###
    tot # of builds  : 0
    tot # of erasures: 0
    tot # of uses    : 0
    max cache size   : 0
    max # of uses    : 0

**Comment by WeiqunZhang** [comment]
I don't see any obvious problems.  If you let me know how to run your test, I am happy to take a look.

**Comment by msussman42** [comment]
Dear Weiqun,
Thank you for agreeing to look into this for me.

On a linux machine for example (with g++, gfortran, etc), one should be
able to run the test as follows:
1. git clone git@github.com:msussman42/amrex_implicit_interfaces.git
2. cd amrex_implicit_interfaces/NS_fluids_lib
3. make
4. cd run2d
5. mkdir BCG_periodic_patch
6. cd BCG_periodic_patch
7. cp ../inputs.BCG_periodic_patch .
8. export OMP_NUM_THREADS=4
9. ../../amr2d.gnu.OMP.ex inputs.BCG_periodic_patch >& run.out &
10. after about 8 hours (after STEP = 118), the program should stop due to
the sanity check.

Note: The code is compiled using the amrex libraries in the
following directory:
amrex_implicit_interface/amrex-master/Src/Base_12_2019

I made some changes in Base_12_2019, but they should be unrelated.  I added
the keyword "SUSSMAN" wherever I made a change.  Some new files in this
directory have the keyword "SUSSMAN" in the filename.   The other source
directories are
amrex_implicit_interfaces/mglib
amrex_implicit_interfaces/NS_fluids_lib
amrex_implicit_interfaces/mglib
amrex_implicit_interfaces/amrlib
for which most of the code might be unrecognizable by you.  The cache print
statements that you recommended for me to add are in the amrlib/Amr.cpp
file. (in Amr::coarseTimeStep (Real stop_time))

Mark

**Comment by msussman42** [comment]
Dear Weiqun,
Just to let you know, we have to continually modify the code in the
amrex_implicit_interfaces repository, I believe that all the conditions for
the "test with breakdown" are still identical, but not 100 percent sure.
Please use the version from Feb 11 closest to 9:58pm (est) when checking
what causes the discrepancy.

Have you had a chance to look into this further? Is there some other
debugging statements I can add?  I was next thinking about putting the
sanity check in the MFIter loops that are within the "base" directory.
Also testing what happens if different caches are selectively flushed after
each time step.
Mark

**Comment by WeiqunZhang** [comment]
I am able to compile and run.  Here is what I have found so far.  This is most likely unrelated to the issue you reported.  I tried to compile it with both gcc 5.4.0 and clang 9.0.1.  For gcc, it doesn't like `#include <math.h>` in `Zeyu_Matix.cpp` and I have to change it to `#include <cmath>`.  For clang, I have to add `using std::abs`, otherwise there are a lot of warnings like

```
NavierStokes3.cpp:5314:7: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
            (abs(original_mom)<abs(proposed_mom))) {
             ^
```

I think it's better to use `cmath` instead of `math.h` in all C++ codes and use `std::abs` with explicit `std::`.

**Comment by msussman42** [comment]
Thank you Weiqun,
I was not aware of those "abs" problems - they must be compiler version
specific.  I will fix them, then rerun the test with/without the
cache-flush to make 100 percent sure the problem is unrelated.
Mark

**Comment by WeiqunZhang** [comment]
I can reproduce the error with `abs` fixed.  So far I don't have any clues why the assertion fails.  But I am still looking for it.

**Comment by msussman42** [comment]
Thank you Weiqun.
Mark

**Comment by WeiqunZhang** [comment]
Dear Mark,

I think this is now fixed in these two commits., 51565fcf416bcfc348 and 0e9ba3c2f3855492.  The problem was integer overflow.  Didn't anticipate cached tile arrays could be used so many times.

Thanks for reporting the bug!

Weiqun

**Comment by msussman42** [comment]
Thank you Weiqun! I feel honored and humbled to have succeeded in using
cached tile arrays more than any other human (up until this point). :-)
Mark
