### ISSUE TITLE
EB functionality on the GPU

### ISSUE THREAD

**Issue by marchdf** [AMReX-Codes/amrex#694]
Hi, @jrood-nrel and I are running into a couple EB issues on the GPU and hoping to get some help. We are working on this branch: https://github.com/jrood-nrel/PeleG/tree/gpu_fixes

1. It seems like `amrex_eb_get_reredistribution_threshold ()` can't be called from device
2. This seems to work fine when compiling for CPU, but not for GPU: 
```
      amrex::Real dt = amrex::ReduceMin(
        stateMF,
#ifdef AMREX_USE_EB
        flags,
#endif
        0,
        [=] AMREX_GPU_HOST_DEVICE(
          amrex::Box const& bx, amrex::FArrayBox const& fab
#ifdef AMREX_USE_EB
          ,
          amrex::EBCellFlagFab const& flagfab
#endif
          ) noexcept -> amrex::Real {
          return pc_estdt_hydro(
            bx, fab,
#ifdef AMREX_USE_EB
            flagfab,
#endif
            AMREX_D_DECL(dx1, dx2, dx3));
        });
```
the compiler error is:
```
../../../Submodules/AMReX/Src/Base/AMReX_FabArrayUtility.H(606): error: no instance of overloaded function "amrex::fudetail::call_f" matches the argument list
            argument types are: (const lambda [](const amrex::Box &, const amrex::FArrayBox &, const amrex::EBCellFlagFab &)->amrex::Real, const amrex::Box, const amrex::Array4<const amrex::Real>, const amrex::Array4<const amrex::EBCellFlag>)
          detected during:
            instantiation of "FAB1::value_type amrex::fudetail::ReduceMin_device(const amrex::FabArray<FAB1> &, const amrex::FabArray<FAB2> &, const amrex::IntVect &, F &&) [with FAB1=amrex::FArrayBox, FAB2=amrex::EBCellFlagFab, F=lambda [](const amrex::Box &, const amrex::FArrayBox &, const amrex::EBCellFlagFab &)->amrex::Real, bar=void]" 
(642): here
            instantiation of "FAB1::value_type amrex::ReduceMin(const amrex::FabArray<FAB1> &, const amrex::FabArray<FAB2> &, const amrex::IntVect &, F &&) [with FAB1=amrex::FArrayBox, FAB2=amrex::EBCellFlagFab, F=lambda [](const amrex::Box &, const amrex::FArrayBox &, const amrex::EBCellFlagFab &)->amrex::Real, bar=void]" 
(554): here
            instantiation of "FAB1::value_type amrex::ReduceMin(const amrex::FabArray<FAB1> &, const amrex::FabArray<FAB2> &, int, F &&) [with FAB1=amrex::FArrayBox, FAB2=amrex::EBCellFlagFab, F=lambda [](const amrex::Box &, const amrex::FArrayBox &, const amrex::EBCellFlagFab &)->amrex::Real, bar=void]" 
../../../Source/PeleC.cpp(932): here
```

Thanks!

**Comment by WeiqunZhang** [comment]
1. You are correct that it cannot be used on device.  What you can do is call it on the host and capture its value in device lambda.

2. The various versions of reduction functions rely on `enable_if`.  But unfortunately it has some limitation when dealing with CUDA device lambda.  So we decided to removed some variants for GPU.  You should be able to do the following instead,

```
      amrex::Real dt = amrex::ReduceMin(
        stateMF,
#ifdef AMREX_USE_EB
        flags,
#endif
        0,
        [=] AMREX_GPU_HOST_DEVICE(
          amrex::Box const& bx, amrex::Array4<amrex::Real const> const& fab
#ifdef AMREX_USE_EB
          ,
          amrex::Array4<amrex::EBCellFlag const> const& flagfab
#endif
          ) noexcept -> amrex::Real {
          return pc_estdt_hydro(
            bx, fab,
#ifdef AMREX_USE_EB
            flagfab,
#endif
            AMREX_D_DECL(dx1, dx2, dx3));
        });
```

Note that you need to change the parameters of `pc_estdt_hydro` from `FArrayBox` to `Array4`.

**Comment by marchdf** [comment]
Thanks @WeiqunZhang for those suggestions! Two other followups:

1. On closer look into the above `2`, really what was going on is that the flags were passed in just to get the type and then just return a default (large) dt if the flag type was `covered`. So the above code could have just read:
```
      amrex::Real dt = amrex::ReduceMin(
        stateMF,
#ifdef AMREX_USE_EB
        flags,
#endif
        0,
        [=] AMREX_GPU_HOST_DEVICE(
          amrex::Box const& bx, amrex::FArrayBox const& fab
#ifdef AMREX_USE_EB
          ,
          amrex::EBCellFlagFab const& flagfab
#endif
          ) noexcept -> amrex::Real {
          amrex::FabType typ = flagfab.getType(bx);
          return pc_estdt_hydro(
            bx, fab,
#ifdef AMREX_USE_EB
            typ,
#endif
            AMREX_D_DECL(dx1, dx2, dx3));
        });
```
and in `pc_estdt_hydro` it would have
```
[...]
  amrex::Real dt = 1.e37;

#ifdef AMREX_USE_EB
  if (flag_typ == amrex::FabType::covered) {
    return dt;
  }
#endif
[...]
```
It's my understanding given your comment that this bit
```
          amrex::Box const& bx, amrex::FArrayBox const& fab
#ifdef AMREX_USE_EB
          ,
          amrex::EBCellFlagFab const& flagfab
```
won't work for the GPU, but how can I then do get the type (currently doing `amrex::FabType typ = flagfab.getType(bx);`) in the lambda if all I have are `Array4` as you suggest? If there's a better way of accomplishing this, please let me know. 

2. We seem to be hitting some simulation crashes unless we do `CUDA_LAUNCH_BLOCKING=1`. Do you have any general advice of figuring where we are going wrong with our asynchronous kernels?

**Comment by WeiqunZhang** [comment]
1. `EBCellFlagFab::getType (const Box& bx)` is a host only function that cannot be called inside device lambda.  But you can do the following in `pc_estdt_hydro`.

```
amrex::Real dt = std::numeric_limits<amrex::Real>::max();
amrex::Loop(bx, [=,&dt] (int i, int j, int k) {
    if (not flagfab(i,j,k).isCovered()) {
        dt = amrex::min(dt,...);
    }
});
return dt;
```

2. Maybe there are some memory allocated before the kernel launch and get freed before the device code finishes using it.  You might want to look for places reported by like `git grep "FArrayBox "`, `git grep "BaseFab<amrex::Real> "`.  If you point me to the source code where the crash happens, I am happy to take a look.

**Comment by marchdf** [comment]
Thanks again @WeiqunZhang , I think we should be good to go now with your suggestions.

2. Let me see if I can narrow this down a bit more for you before taking up more of your time. But the basic idea is that if we just run the diffusion part of the code (https://github.com/jrood-nrel/PeleG/blob/gpu_fixes/Source/Diffusion.cpp, with, for example the TG case and `pelec.do_hydro=0`) with and without `CUDA_LAUNCH_BLOCKING=1` we don't get an actual simulation crash but there results are different enough that we think something's up. We've combed through all the `FArrayBox`s in the MFIter loop and they are all `Elixir`ed  but this doesn't feel like a memory error because cuda-memcheck isn't complaining and the simulation isn't actually crashing for this case. In any event, there's a bit more due diligence we want to do. I will keep you posted.

**Comment by maxpkatz** [comment]
cuda-memcheck wouldn't tell you about this sort of race condition, in the same way that valgrind wouldn't tell you about CPU thread race conditions. (cuda-memcheck does have a racecheck tool, but that is for accesses to shared memory only.) It's entirely possible to have a race condition that results from, e.g., incorrect use of elixirs that the tool doesn't tell you about, because we use a memory pool and when the memory is released it isn't actually freed on the GPU, so cuda-memcheck wouldn't have any reason to object.

**Comment by marchdf** [comment]
Thanks for clarifying that. Yes, our suspicion is a race condition. I guess, can you clarify what you mean by " It's entirely possible to have a race condition that results from, e.g., incorrect use of elixirs". From the documentation, we were under the impression that any `FArrayBox` that we create inside an MFIter loop, we should elixir to ensure that it doesn't go out of scope. But in doing that, we might have been overzealous and missed a subtlety.

**Comment by maxpkatz** [comment]
Yes, that is a correct statement. What I meant is that it's not especially hard to make mistakes using elixirs, and unfortunately we don't have a tool to help you find them. For example, you might have forgotten an elixir, or accidentally let it go out of scope too early. The code you linked is a little too long for me to inspect by eye, but if CUDA_LAUNCH_BLOCKING gives you different results, then that is a pretty good sign that you have a problem like this.

The code you linked is a little too complicated for me to inspect by eye. One thing I notice is that sometimes you create an elixir before the memory is allocated (with `resize`, using `flatn` as an example), and I don't think that would work, can you confirm @WeiqunZhang?

**Comment by WeiqunZhang** [comment]
@maxpkatz is correct.

**Comment by marchdf** [comment]
> One thing I notice in your code is that sometimes you create an elixir before the memory is allocated (with resize, using flatn as an example)

Interesting. We don't actually use `flatn` I think in that bit of code but there might be other spots we missed! We will dig. Thanks!

**Comment by maxpkatz** [comment]
While you look at that, be careful not to make the mistake of

```
FArrayBox tmp;

if (var) {
    tmp.resize();
    Elixir elix = tmp.elixir();
    func1(tmp);
}

func2(tmp);
```

because the memory is no longer required to be valid after the elixir goes out of scope.

**Comment by drummerdoc** [comment]
Maybe my simpleton perspective helps?   We used to do this
```
# omp crap
{
  FArrayBox tmp;
  for (MFIter mfi...) {
    tmp.resize(...);
  }
}
```
Now we do this
```
# omp crap
  for (MFIter ...) {
    FArrayBox tmp;
    Elixer etmp = tmp.elixer();
    KERNEL_LAUNCH_CRAP()
  }
```
In this usage, the Elixer steals control of the data pointer from tmp so that when tmp goes out of scope the data pointer is not deleted.  The MFIter destructor calls the Elixer destructor and deletes the memory pointed to by the data pointer.  If you mix the first and second usages, e.g., you'd get into trouble.

**Comment by marchdf** [comment]
Ok yeah good point. I am finding a bunch of places where we Elixir before the resize.  In your previous example, would it be ok to:
```
FArrayBox tmp;
Elixir elix;
if (var) {
    tmp.resize();
    elix = tmp.elixir();
    func1(tmp);
}

[other stuff]

if (var){
func2(tmp);
}
```

And just to make sure, are these equivalent?
```
amrex::FArrayBox tmp(bx, size);
Elixir tmpeli = tmp.elixir();
amrex::Array4<amrex::Real> tmp_arr = tmp.array();
```

```
amrex::FArrayBox tmp(bx, size);
amrex::Array4<amrex::Real> tmp_arr = tmp.array();
Elixir tmpeli = tmp.elixir();
```

**Comment by WeiqunZhang** [comment]
You could actually do
```
{
  FArrayBox tmp;
  for (MFIter mfi...) {
    tmp.resize(...);
    Elixer etmp = tmp.elixir();
  }
}
```
When resize is called on non-owning FArrayBox, it will allocate new memory.

**Comment by drummerdoc** [comment]
Ahh, yes. Sorry

**Comment by marchdf** [comment]
So we can get rid of the race condition by placing `amrex::Gpu::synchronize();` right before `MOLSrcTerm[mfi].copy(Dfab, vbox, 0, vbox, 0, NVAR);` (https://github.com/jrood-nrel/PeleG/blob/master/Source/Diffusion.cpp#L565). If we move the synchronize right after L566, then we get the race condition again. Maybe this can help you figure out what we are doing wrong?

**Comment by WeiqunZhang** [comment]
`MOLSrcTerm[mfi].copy(Dfab, vbox, 0, vbox, 0, NVAR);` is not run on gpu.  That's why.

**Comment by WeiqunZhang** [comment]
I suggest you write your kernel to do it on gpu.  Ideally, we would like to control where to run for `BaseFab::copy`, and we tried to implement it.  But due to some limitations, we failed.

**Comment by WeiqunZhang** [comment]
More specifically, `BaseFab::copy` is a host device function.  We are not allowed to launch CUDA kernel in a host device function. https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#cuda-arch-macro  We would have to make a host only function.  Then we could take a parameter to control where to run and run on gpu by default.  But not sure if that's a good idea.  Maybe it is.  It might break some codes because `copy` might get used in device code.  But it will eliminate this kind of bugs.  Comments are welcome.

**Comment by marchdf** [comment]
Thanks for explaining that @WeiqunZhang. I guess I have a follow up then: is `BaseFab::linComb` OK to run on the GPU? `setVal` is safe according to the documentation. Is there an easy way for me to see which are/are not safe?

**Comment by WeiqunZhang** [comment]
Both `BaseFab::linComb` and `BaseFab::setVal` are `__host__ __device__` function.  If they are called on the host, they will not run on gpu.

Basically all BaseFab member functions are host device functions that do not have kernel launch inside.  Most MultiFab member functions launch gpu kernels if it makes sense.

**Comment by maxpkatz** [comment]
In the past when we looked at this the goal was to maintain the __device__ functionality but let's revisit that. I am having trouble coming up with a use case for the __device__ functionality. If I'm already in a kernel, typically an AMReX parallel_for, and I want to do an axpy or a setVal, I'm just going to do that directly for clarity, rather than call a BaseFab function, which introduces some overhead anyway. The value of the BaseFab functions being able to operate on the GPU, to me, is that I can avoid going through the effort of writing my own parallel_for just to do it. So the question is, what are the realistic use cases where I'm already in a kernel and I choose to use BaseFab::linComb or BaseFab::setVal? Are any of the codes actually using that?

**Comment by marchdf** [comment]
Ok I think that makes sense to me know. I don't know about your wider use-case questions @maxpkatz but I see the benefit for our application. In our MFIter loop, we have things like

```
for (amrex::MFIter mfi(MOLSrcTerm, amrex::TilingIfNotGPU()); mfi.isValid();
         ++mfi)

[...]
MOLSrcTerm[mfi].setVal(0, vbox, 0, NVAR);
[...]
amrex::FArrayBox flux_ec;
[...]
flux_ec.linComb(
              diffusion_flux[dir], diffusion_flux[dir].box(), Density,
              hydro_flux[dir], hydro_flux[dir].box(), Density, 1.0, 1.0,
              flux_ec[dir].box(), Density, NVAR);
[...]
}
```
which I now understand will actually run on the host and not the device, as I previously thought/expected. I can easily write my own kernels for these but I think you have a good point @maxpkatz .

As an aside, would it makes sense to provide some of this BaseFab functionality for `Array4`, e.g. `copy`, `setVal`, `linComb`, etc? For our use-case, we have defined a `setV`/`setC` kernel to work on all/components of an `Array4`.  I will now be doing the same for `copy` and `linComb` since we use that in several places. But maybe this should live in AMReX? Maybe it already exists and I missed it when looking at the source code. Or maybe it doesn't but you have good reasons not to provide them.

**Comment by WeiqunZhang** [comment]
My inclination is to make BaseFab functions host __only__ and launch kernels by default.  The advantage is this avoids a lot of nasty bugs that are veru hard to track down.  The downside is minor.  It has no effects on CPU codes.  If BaseFab functions are used in device code, it wont' compile.  At most an housr is needed for an application code to fix if it's broken by the change.  Raising your objections.  If I don't hear any in the next week, I might do it.

As for `Array4`, I think we like to keep it small.

**Comment by marchdf** [comment]
> My inclination is to make BaseFab functions host only and launch kernels by default.

@WeiqunZhang I like this idea. That `copy` we had in the code definitely cost us some grief since we didn't expect that behavior. So this takes care of that problem. Let me know once you have done it and I will revert my hacks to make things work on our end.

Thanks for all your help, I am going to close this issue since most issues raised here have been addressed.
