### ISSUE TITLE
Non deterministic reflux on GPU?

### ISSUE THREAD

**Issue by marchdf** [AMReX-Codes/amrex#699]
@jrood-nrel and I have been wrestling with a problem on the GPU using AMR. Using the following branch https://github.com/jrood-nrel/PeleG/tree/problem and the TG problem compiled on the GPU (using this input file (it has 2 levels): https://github.com/jrood-nrel/PeleG/blob/problem/Exec/RegTests/TG/inputs_3d). 

Basically running the problem twice on the GPU and using fcompare on the plot file reveals diffs. If we run these with the flag `pelec.do_reflux=0` then we don't observe the diffs. Similarly, if we run with `max_level = 0`, we don't get diffs either. And running this problem on the CPU also doesn't diff. This leads us to think the `refluxing` operation is somehow making the runs non-deterministic.

**Comment by WeiqunZhang** [comment]
It's not surprising that the reflux is non-deterministic, and there is probably nothing we can do.  If you look at `amrex/Src/EB/AMReX_EBFluxRegister_3D_C.H`, you can see a lot of `HostDevice::Atomic::Add(...)`.

**Comment by marchdf** [comment]
Ok thanks for clarifying!
