### ISSUE TITLE
physical location from an array index (Fortran)

### ISSUE THREAD

**Issue by M-Badri** [AMReX-Codes/amrex#703]
The question, which might be superficial since I am quite a newbie in AMRex, is about the "amrex_geometry_get_ploc" function in  [AMReX_geometry_mod.F90] (https://github.com/AMReX-Codes/amrex/blob/master/Src/F_Interfaces/Base/AMReX_geometry_mod.F90)". 

As I understand, for a single level  2D `geometry([0.0, 0.0]:[1.0, 1.0])` over a single `box([1,1]:[ncell, necell])`  when this function is called with a (1, 1, 1, 1) argument, it should return the physical location (coordinate) of the `grid(1, 1)`, while it returns the physical location of lower-left corner of the physical domain . In other words, the equation

_ploc(i) = amrex_problo(i) + (iloc(i) - this%domain%lo(i)) * this%dx(i)_

for `i=1` returns the value of ` amrex_problo(i) `(since _iloc(i) = this%domain%lo(i))_ ), whereas I expected to get the coordinates of the of the first cell-center. There is a related problem for the `grid(ncell, ncell)` as well. 

Does the function need a modification? or simply my understanding is incorrect?

**Comment by WeiqunZhang** [comment]
It may not do what one might expect.  But it's not a bug.  It gives you the physical coordinates of at given nodal index.  It is used to get the lower left corner of a Box.  See for example, https://github.com/AMReX-Codes/amrex/blob/master/Tutorials/Amr/Advection_F/Source/fillpatch_mod.F90#L90

Also note the index of the domain starts with zero not one.

**Comment by M-Badri** [comment]
Thank you so much. I was so biased towards the cell-center calculation that I did not notice its node-base attitude. It would be particularly helpful if one knows that some calculations may be done node-base.
