### ISSUE TITLE
Multiple embedded boundaries

### ISSUE THREAD

**Issue by wattrg** [AMReX-Codes/amrex#704]
I am wanting to have two different embedded boundaries which have different boundary conditions applied to them. I'm working on a code based on the EB/CNS example. I'm imagining some sort of a flag stored with the other EB data which can be used to tell whether the boundary condition for each cell should be boundary condition A or B. 

If anyone has any ideas/advice on how to do this I'd greatly appreciate it as I'm quite new to AMReX.

Thanks!

**Comment by maikel** [comment]
Do you have *one* domain in which two different types of boundaries are embed to? If this is true you could generate your EB information as the union of the boundaries. As a second step I would introduce a mask telling you which sort of boundary condition should be applied to which EB. Would this suffice your need?

AMReX allows you to manage multiple index spaces, which might be helpful if you have separate domains with different level sets. This will allow you to have two MultiFabs associated to two different geometries. But I think that is not what you are looking for.

**Comment by wattrg** [comment]
Yes, I have one domain where I want different boundaries, so I also don't think that multiple index spaces is what I'm looking for. I think the mask idea is going to be what I'm after! Thanks for the help!
