### ISSUE TITLE
[Fortran] amrex_multifab_build argument intent

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#708]
Is there a reason the `mf` argument to `amrex_multifab_build` is `intent(inout)` and not `intent(out)`? Unless I'm missing something, it seems to me it ought to be the latter.  The difference being that `mf` will be finalized on entry.  As it is now, I must manually call `amrex_multifab_destroy` before calling build to avoid a memory leak.

**Comment by WeiqunZhang** [comment]
It was intentional.  See 960e1b0e30117172612dee5282e60e1050351d41.  I don't know if the problem still exist in the latest gfortran.  I also don't know if it was sufficient to only modify the intent of `mfiter`.  But the mood at that time was we could not trust Fortran compilers.
