### ISSUE TITLE
Add io website to GitHub description

### ISSUE THREAD

**Issue by adam-m-jcbs** [AMReX-Codes/amrex#71]
I think it'd be convenient to add a link to the github.io website for AMReX (https://amrex-codes.github.io/) to the GitHub description (https://github.com/AMReX-Codes/amrex) .  An example of this is the Maestro GitHub repo, which includes the io website in the description (https://github.com/AMReX-Astro/MAESTRO).  I realize the io website's mostly a stub for the moment, but as it grows it would be convenient to be able to quickly jump to it from the repository.

**Comment by asalmgren** [comment]
Good suggestion and done :-)
