### ISSUE TITLE
More non-deterministic flux registers? 

### ISSUE THREAD

**Issue by marchdf** [AMReX-Codes/amrex#717]
Hey again, 

I am seeing large, non-deterministic difference between a CPU and GPU run of one of our PeleC cases on the coarse cells near the C-F boundary, e.g. picture of the fcompare diff of z_velocity:
![Screen Shot 2020-02-27 at 11 21 56 AM](https://user-images.githubusercontent.com/15038415/75473991-6206ec80-5953-11ea-88a1-34a29c31747f.png)

The problem goes away if I comment out the following lines of code in https://github.com/jrood-nrel/PeleG/blob/eb_gpu/Source/Diffusion.cpp:
```
        if (level < parent->finestLevel()) {
          getFluxReg(level + 1).CrseAdd(
            mfi, {AMREX_D_DECL(&flux_ec[0], &flux_ec[1], &flux_ec[2])}, dxDp,
            dt, run);
        }
        
        if (level > 0) {
          getFluxReg(level).FineAdd(
            mfi, {AMREX_D_DECL(&flux_ec[0], &flux_ec[1], &flux_ec[2])}, dxDp,
            dt, run);
        }
```
It seems to also work if, instead of commenting the lines above, I comment out:
```
          pc_compute_hyp_mol_flux(
            cbox, qar, qauxar, flx, a, dx
#ifdef AMREX_USE_EB
            ,
            vfrac.array(mfi), flags.array(mfi), d_sv_eb_bndry_geom, Ncut,
            d_eb_flux_thdlocal, nFlux
#endif
          );
```

In trying to track this down by looking at the Tutorials, I noticed a couple of things/differences. 
- we are using `YAFluxRegister`
- we are doing the `CrseAdd` inside the `MFIter` loop. For GPU CNS and `AmrCoreAdv.cpp` it seems that the fluxes are held in a `MultiFab`, computed in an `MFIter` loop, and then after the `MFIter` loop, the `CrseInit` and `FineAdd` are called on that flux `MultiFab`.
- I am storing fluxes in `flx` which is a `GpuArray` of `Array4` and I am passing that to different functions (`pc_computy_hyp_mol_flux` will accumulate into it)
- It feels like some type of race condition but running with `CUDA_LAUNCH_BLOCKING=1` does not fix the problem.
- It also feels like it is happening in `pc_compute_hyp_mol_flux` somehow but it's not obvious that anything strange is going on there. Or why it would happen at the CF boundary only.

Any tips for figuring this out? Thanks in advance!

**Comment by WeiqunZhang** [comment]
I think I found the problem.  There are some add operations must be atomic.  We omp atomic for CPU.  But for GPU, we use atomicAdd for the EB functions, but forgot to update the regular version.  I will push a fix in a minute.  You are still expected to see non-deterministic behavior.  But the difference should be much smaller.

**Comment by WeiqunZhang** [comment]
Could you try the latest development branch of AMReX?

**Comment by marchdf** [comment]
Yes, I will give it a shot soon.

**Comment by marchdf** [comment]
Hi @WeiqunZhang , thank you for looking into this. Unfortunately, I am still getting larger than expected diffs:
![Screen Shot 2020-02-28 at 2 10 35 PM](https://user-images.githubusercontent.com/15038415/75587635-2001a780-5a34-11ea-888b-cd3b9d6e72c2.png)

I triple checked everything to make sure I was running the right commit of AMReX (commit: `b63b147984b2d7b822`). So maybe on top of the race condition you fixed, there is another one, maybe/probably in our code?

**Comment by WeiqunZhang** [comment]
It seems that it's on one side but not the other.  Do you see similar pattern on CPU?

**Comment by marchdf** [comment]
So it definitely feels like that. But this is actually a **diff** from fcompare of z_velocity between the CPU and GPU version. The actually z_velocity field on the GPU looks like this
![Screen Shot 2020-02-28 at 3 01 06 PM](https://user-images.githubusercontent.com/15038415/75590710-32331400-5a3b-11ea-8e9e-e17ee3657395.png)

**Comment by marchdf** [comment]
The refluxing issue we were seeing turned out to be a false flag. The proposed fix did indeed fix the first non-deterministic problem we were seeing but there was a remaining issue in the code (specifically, an uninitialized mass fraction field in an EOS calculation) that led to further non-determinism, thereby confounding the issues. Thank you again for your time!
