### ISSUE TITLE
Cray Compilers

### ISSUE THREAD

**Issue by timrlaw** [AMReX-Codes/amrex#719]
Hello there,

We have an AMReX-based code that we would like to be able to build with the Cray compiler, however it looks like AMReX has some issues with this at present. The CMake build system explicitly rejects Cray:

https://github.com/AMReX-Codes/amrex/commit/ee4ddb0f4e7e9f0eca5400c60141b087fca93326#diff-e8b1616974e76f0cbc95816d37c69ab8R47

Disabling this check allows the library to build without incident (with CCE 9.1.2), however it breaks in some fairly fundamental ways when run (ParmParse crashes with various I/O errors).

I was wondering if anyone was aware of any specific reasons why this wouldn't work with AMReX, or if there are any plans to try and support Cray in the near future? Would you support pull requests fixing Cray-related bugs?

Thanks!

**Comment by WeiqunZhang** [comment]
@mic84 can answer why Cray is not allowed in the CMake build system.  However, I can successfully compile with CCE 9.1.0 on Cori using the GNU make system.  And I am able to run with I/O errors.  I am more interested the I/O errors, and if it's our source code problem, how we can fix it.  Could you tell us more details?

**Comment by timrlaw** [comment]
Hi @WeiqunZhang, thanks for taking the time to look at this.

I've dug into it a bit more and it turns out the I/O errors were due to a rogue linker flag in our project (`-static-libstdc++`), my bad for not catching that before. Our code also does run when using the GNUmake build system with Cray.

However the CMake-built version crashes only slightly later than before, with:
```
Assertion `i>=0 && i < AMREX_SPACEDIM' failed, file "/home/users/.../install/amrex-2d-20.02-cce-9.1.2/dbg/include/AMReX_IntVect.H", line 171 !!!
```

I suspect this is part of the reason Cray+CMake is disabled @mic84 ?

**Comment by WeiqunZhang** [comment]
@mic84 told me that in the past there were some issues that cray compiler failed to compile our code, so it was disabled.  He is working on enable it again.

**Comment by timrlaw** [comment]
Okay, thanks both!

**Comment by mic84** [comment]
@timrlaw I re-enabled Cray compiler in CMake. Please try the amrex development branch and let me know if you have problems with it. Thanks.

**Comment by timrlaw** [comment]
@mic84 Seems to be fine. I'll open a new issue if I find anything broken. Cheers.
