### ISSUE TITLE
`amrex::Random()` may have different intervals on CPUs and GPUs

### ISSUE THREAD

**Issue by lucafedeli88** [AMReX-Codes/amrex#727]
Hi,

I think that, `amrex::Random()` as implemented now may produce random numbers in [0,1) on CPUs and in (0,1] on GPUs. Of course extracting exactly the endpoint of an interval is extremely unlikely, but if it happens a code designed with one of these alternatives in mind could crash (e.g. I use `-log(amrex::Random() )` in `WarpX`)

`amrex::Random()` uses either `curand_uniform` or `std::uniform_real_distribution` depending on the architecture. According to CUDA documentation, `curand_uniform` (https://docs.nvidia.com/cuda/curand/device-api-overview.html)
> returns a sequence of pseudorandom floats uniformly distributed between 0.0 and 1.0. It may return from 0.0 to 1.0, where 1.0 is included and 0.0 is excluded

while `std::uniform_real_distribution`  (https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution)
> Produces random floating-point values i, uniformly distributed on the interval [a, b)

If I am interpreting correctly these references, the behaviour of `amres::Random()` may cause some problems in certain conditions. In case, I've prepared a PR which should solve the issue: https://github.com/AMReX-Codes/amrex/pull/726

**Comment by atmyers** [comment]
Thanks for opening and fixing this Issue! Fixed in PR #726.
