### ISSUE TITLE
Would it be possible to use something like AMREX_ASSERT_WITH_MESSAGE to print a runtime string

### ISSUE THREAD

**Issue by lucafedeli88** [AMReX-Codes/amrex#737]
Hi,

to my understanding, the macro  `AMREX_ASSERT_WITH_MESSAGE(EX,MSG) (EX)?((void)0):amrex::Assert( # EX , __FILE__, __LINE__ , # MSG)`
always "stringifies" argument `MSG`, so that  it cannot be used to print a message composed at runtime. However, this might be beneficial in some situations.
 In the code I am working on (`WarpX`) the user can define many species in the inputfile and then assign several properties to these species. Is there a way to use something similar to `AMREX_ASSERT_WITH_MESSAGE` to print a message like  "property XXX of species YYY cannot have value ZZZ"? or should I just use an `amrex::Print()`?

**Comment by atmyers** [comment]
Hi Luca,

I would just use something like the logic here to do this: https://github.com/AMReX-Codes/amrex/blob/master/Src/Amr/AMReX_Amr.cpp#L1734

**Comment by lucafedeli88** [comment]
Thanks a lot for the advice!
