### ISSUE TITLE
fcompare exit code with MPI enabled

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#752]
Would it be possible to have `fcompare` give a failure exit code when diffs occur with MPI enabled? Looking at the code, it appears the exit code is disabled with MPI enabled.

https://github.com/AMReX-Codes/amrex/blob/b35aa25c7ad23709eaeec4441a1d788148ca9707/Tools/Plotfile/fcompare.cpp#L360-L370

**Comment by WeiqunZhang** [comment]
I made the change in development branch.  I don't remember why it was done that way.
