### ISSUE TITLE
Should this function be called IntVect?

### ISSUE THREAD

**Issue by MaxThevenet** [AMReX-Codes/amrex#757]
https://github.com/AMReX-Codes/amrex/blob/7d788fbc54639401a5b4ee535af179af5d0ab27f/Src/Base/AMReX_IndexType.H#L103

The use of this function results in confusing calls like
```c++
const IntVect stag_fp = mf_fp.boxArray().ixType().ixType();
```
Would `IntVect` (or `toIntVect`) be an acceptable name
```c++
const IntVect stag_fp = mf_fp.boxArray().ixType().IntVect();
```
? This is not of major importance, but several developers asked about this.

**Comment by MaxThevenet** [comment]
Ok, done in https://github.com/AMReX-Codes/amrex/pull/758.
I also kept the other version, let me know if you want me to replace the old name.

**Comment by WeiqunZhang** [comment]
We will keep the old name.
