### ISSUE TITLE
Reading particle Ascii files

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#797]
I switched my particle implementation from using ArrayOfStruct to using StructOfArrays. I am now having an issue with the `InitFromAsciiFile` function in [https://github.com/AMReX-Codes/amrex/blob/e0658315005f4521b73a530d53fc6c47fce93cba/Src/Particle/AMReX_ParticleInit.H#L6](url). Is this function set up to only work with ArrayOfStructs? Are there any tutorials or tests that utilizes the any of the binary or ascii initialization functions?

**Comment by atmyers** [comment]
It does not with StructOfArrays right now. I'll make a PR to fix this.

**Comment by ldowen** [comment]
Along similar lines, is the `InitFromAsciiFile` function designed to work on GPUs? Because I have run into issues that seem like the data isn't copied over to the GPUs.

**Comment by atmyers** [comment]
Could you see if this pull request solves the second issue? 

https://github.com/AMReX-Codes/amrex/pull/831

**Comment by ldowen** [comment]
There still appears to be a problem with ascii file particles on GPUs, even with that pull request. I am not sure if the issue is on my side now though.

**Comment by atmyers** [comment]
I wrote a test for this function and added it to the pull request. It seems to work as expected, with and without CUDA. If you're still having problems, maybe you could try to reproduce them on the test I checked in?

The SoA issue with that function should also be fixed now on that PR.

**Comment by ldowen** [comment]
I figured out what I was doing wrong on my side. It looks like it works with your changes from the PR.
