### ISSUE TITLE
Performing MPI_Allreduce with MultiFabs

### ISSUE THREAD

**Issue by srikrrish** [AMReX-Codes/amrex#814]
I want to perform MPI_Allreduce (specifically MPI_SUM) on local multifabs (with same size defined on each processor separately) and get the collective result in a multifab. Is it possible to perform MPI_Allreduce  with MultiFab datatype?. For example I am looking for something similar to this 

MultiFab rho_comp
int comm_vol
amrex::ParallelAllReduce::Sum(&rho_comp, comm_vol, amrex::ParallelContext::CommunicatorAll()); 

However, to my limited knowledge and searching around the source codes it seems currently it is not possible. Also it looks like amrex::ParallelDescriptor::Mpi_typemap<T>::type() is not defined for MultiFabs as of now, otherwise it could be used directly in conjunction with the native MPI_Allreduce command. 

So currently to me the two options seems to be 
i) Convert from amrex MultiFab to a double vector, use MPI_Allreduce on it and then put the result back into a MultiFab for further purposes.
ii) Write a MPI_datatype for amrex MultiFabs very similar to what has been done for amrex::Box in amrex::ParallelDescriptor::Mpi_typemap<T>::type()

Please let me know if there are simpler options than this or already there is some function available.

**Comment by WeiqunZhang** [comment]
`MultiFab` is container for distributed data on a `BoxArray`, a set of different Boxes.  It does not really make sense to do allreduce as what you have described.  If this is really what you want to do and the local size of the MultiFab is the same across MPI processes and each corresponding Box has the same number of cells across MPI processes, you could loop over the FArrayBoxes in your MultiFab and get a pointer to the data with `FArrayBox::dataPtr` function.

**Comment by srikrrish** [comment]
Thanks a lot for your response and I appreciate it very much. Yes, I agree that normally one wouldn't want to perform allreduce on multifabs like the way I mentioned as it would defeat the purpose of distributed data. But in my case the multifabs I want to perform allreduce are small in size and I can afford to have the entire thing in each processor. At least for now it is the easiest way I could think of for the algorithm I am working on without having complicated data transfers.

The multifabs satisfy all the requirements you mentioned (same size across all processors and same number of cells in each box). Do you mean I loop over all the Processors? but still I need to add data of (let's say the multifab is fab) fab on processor 0 to  fab on processor 1 and get the resulting data on both of them. How can I get that data on other processors?  Thanks

**Comment by WeiqunZhang** [comment]
By looping over FArrayBoxes in MultiFab, I mean
```
for (MFIter mfi(mf); mfi.isValid(); ++mfi) {
    Real* p = mf[mfi].dataPtr();
    // allreduce on data pointed by p
}
```

I think in your case, you should consider `Vector<FArrayBox>` instead.

**Comment by srikrrish** [comment]
Thanks a lot it is working now. I appreciate it very much!
