### ISSUE TITLE
Make AMReX build with NAG

### ISSUE THREAD

**Issue by certik** [AMReX-Codes/amrex#82]
I have made AMReX and our code that uses it work with NAG 6.1. I have submitted all necessary fixes:

* [x] #79 (fixed by 9a2888d84f96ad88eacc8961c66e7ad684287630)
* [x] #80 (merged)
* [ ] #81 or #83

With this PRs, AMReX and our code build and runs with NAG. I opened this issue to keep track of this. After they are all merged (or an equivalent fix is implemented), then we can close this issue.

**Comment by nncarlson** [comment]
The NAG 6.1 compiler bugs that instigated the workarounds of #81 and #82 have been fixed in build 6140 of the compiler (available at http://monet.nag.co.uk/compiler/r61download/ for those with a license to the compiler).  I think this can be closed now.

**Comment by certik** [comment]
Ok, perfect!
