### ISSUE TITLE
problem compiling amrex

### ISSUE THREAD

**Issue by nw236** [AMReX-Codes/amrex#832]
I starting to learn how to use amrex. So for I managed compiling on a virtual machine, during compilation on my linux box however I ran into a problem that I cannot make sense of. Configure runs without any message. During I get an error message. 

Does anyone have an idea?

make -f GNUmakefile
Loading /home/Coding/adaptiveMeshing/amrex/amrex/Tools/GNUMake/comps/gnu.mak...
Loading /home/Coding/adaptiveMeshing/amrex/amrex/Tools/GNUMake/sites/Make.unknown...
Compiling AMReX.cpp ...
g++  -Werror=return-type -g -O3 -std=c++11  -pthread   -DAMREX_GIT_VERSION=\"20.04-251-g47882ba850b9\" -DBL_GCC_VERSION=4.8 -DBL_GCC_MAJOR_VERSION=4 -DBL_GCC_MINOR_VERSION=8 -DAMREX_LAUNCH="" -DAMREX_DEVICE="" -DAMREX_CUDA_FORT_GLOBAL="" -DAMREX_CUDA_FORT_DEVICE="" -DAMREX_CUDA_FORT_HOST="" -DAMREX_CUDA_FORT_HOST_DEVICE="" -DBL_SPACEDIM=3 -DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DAMREX_PARTICLES -DAMREX_PARTICLES -DBL_USE_F_INTERFACES -I. -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/Base -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/AmrCore -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/Amr -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/Boundary -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/Particle -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/F_Interfaces/Particle -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/F_Interfaces/Base -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/F_Interfaces/Octree -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/F_Interfaces/AmrCore -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/LinearSolvers/MLMG -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/LinearSolvers/Projections -I/home/Coding/adaptiveMeshing/amrex/amrex/Src/F_Interfaces/LinearSolvers -c /home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX.cpp -o tmp_build_dir/o/3d.gnu.EXE/AMReX.o
In file included from /home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_Array.H:16:0,
                 from /home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_Vector.H:10,
                 from /home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_ParallelContext.H:7,
                 from /home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_ParallelDescriptor.H:5,
                 from /home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX.cpp:13:
/home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_REAL.H:81:5: error: missing space between ‘""’ and suffix identifier
     operator""_rt( long double x )
     ^
/home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_REAL.H:87:5: error: missing space between ‘""’ and suffix identifier
     operator""_rt( unsigned long long int x )
     ^
/home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_REAL.H:93:5: error: missing space between ‘""’ and suffix identifier
     operator""_prt( long double x )
     ^
/home/Coding/adaptiveMeshing/amrex/amrex/Src/Base/AMReX_REAL.H:99:5: error: missing space between ‘""’ and suffix identifier
     operator""_prt( unsigned long long int x )
     ^
make: *** [tmp_build_dir/o/3d.gnu.EXE/AMReX.o] Error 1

**Comment by zingale** [comment]
It looks like you are using GCC 4.8 which probably does not support the standard of C++ used in AMReX.  Perhaps you can try upgrading to a later compiler?

**Comment by WeiqunZhang** [comment]
This is a gcc 4.8 issue.  But it seems that you can fix it by inserting a space between `"` and `_` in `AMReX_REAL.H`.  Obligated compiler explorer link: https://godbolt.org/z/PoFfPg

**Comment by nw236** [comment]
Wow, I am impressed by the quick response. Thank you.
Updating the compiler to gcc 8 did work.
Thanks again.
