### ISSUE TITLE
specify different max sizes for boxarray in different directions in FORTRAN version

### ISSUE THREAD

**Issue by huanghua1668** [AMReX-Codes/amrex#84]
Hi there,

I want to specify different max sizes in different directions when I call the maxSize subroutine in FORTRAN, like ba%maxSize(size_x, size_y, size_z). So far this kind of function is available in C++ version, so can you add this utility to the FORTRAN version? Thank you very much.

Hua

**Comment by WeiqunZhang** [comment]
I just pushed a commit that provides this capability.  Please give it a try and let us know.

**Comment by huanghua1668** [comment]
Hi Weiqun,

I made a test run and this new capability works well.

Thanks.

Hua
