### ISSUE TITLE
Question: best way to get parent child box relationships

### ISSUE THREAD

**Issue by mclarsen** [AMReX-Codes/amrex#846]
I am trying to figure out how to get parent child relationships. For example, if a box on level 0 contains the whole problem and there are two level 1 boxs, then for each box I would to figure out the ids of the boxs that are above or below. I can do this with some communication to calculate these relationships, but I would like to avoid communication if possible. Is there a better way?

**Comment by WeiqunZhang** [comment]
Please take a look at `intersections` functions in `AMReX_BoxArray.H`.  For example, suppose I want to find out which coarse boxes intersect with a fine box, I can do
```
std::vector<std::pair<int,Box> > isects = coarse_boxarray.intersections(amrex::coarsen(fine_box, refinement_ratio));
```

Also note that there are no strict parent child relationships in AMReX's grids.

**Comment by atmyers** [comment]
+1 on using BoxArray intersections. This operation involves no parallel communication, because information about the full box array is duplicated on every process.

**Comment by mclarsen** [comment]
Thanks for the pointers. I really appreciate it. How would I get access to the full box array in this function:

https://github.com/AMReX-Codes/amrex/blob/fc08afe8327f96d507cda7f9f9a6423787381b2b/Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp#L248

I am tempted  to use something like this:
https://github.com/AMReX-Codes/amrex/blob/fc08afe8327f96d507cda7f9f9a6423787381b2b/Src/Amr/AMReX_Amr.cpp#L3164

My only concern is I don't know if `amr_levels` is always available in downstream codes(e.g., Nyx and Pele). Is this the case?

**Comment by atmyers** [comment]
You could get them from the `MultiFabs` using the `boxArray` method: https://github.com/AMReX-Codes/amrex/blob/fc08afe8327f96d507cda7f9f9a6423787381b2b/Src/Base/AMReX_FabArrayBase.H#L95

You may need to be careful about centering, however. I think I'd convert everything to cell-centered before working the `ba`s.

**Comment by mclarsen** [comment]
This is super helpful and exactly what  I was looking for. Its taking me a while to wrap my head around what is going on in the code base.
