### ISSUE TITLE
Error with SofA virtual particles

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#848]
When I try to access the StructOfArray data in a virtual particle, I get a segfault. I have no issues if I use ArrayOfStruct data types for the particles. Does this functionality work and I am using it wrong? Or is there an issue with it?

**Comment by atmyers** [comment]
It looks like virtuals / ghost are hard-coded to be AoS at the moment. We can remove this restriction, but it may be several days.

**Comment by ldowen** [comment]
Is there any news on this front? I am curious what kind of speed up I would get if I am able to use SoA with AMR.

**Comment by atmyers** [comment]
Not yet, but I will work on this and the other PeleC issues tomorrow.
