### ISSUE TITLE
Two small questions about the post-processing of amrex

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/amrex#85]
Hello all,

I am Ruohai. Here two small questions about the post-processing of amrex. In the tutorial, it recommends Visit and Paraview software. Yet, here are two problems when I use them.

1. I downloaded the latest Vists 2.12.3 in win7 system and try to open the Header file in plt02000 like the following picture. Yet, it shows the next two picture.

I have not found some suggestions from FAQ part. Since the calculation is finished, i think the file information is correct. I tested them in different window system, but it still failed. 

2. Another question is about Paraview, it says "Boxlib 3D Files" for Header file, but I can not find this type in the Paraview 5.3.0 64-bit. See the last two picture. So I can not open the file.

I think these are naive questions coming from myself, but actually I have not found some better ideas. I will be really thankful if someone can give me some suggestions. Thanks for your consideration.
 
Best!

![inputfile](https://user-images.githubusercontent.com/30739800/28992021-90d00f6c-7957-11e7-99bc-ba7f21e1a786.jpg)
![visiterror1](https://user-images.githubusercontent.com/30739800/28992020-90cfa716-7957-11e7-840c-5cec384d3f2a.png)
![visiterror2](https://user-images.githubusercontent.com/30739800/28992022-90d09ec8-7957-11e7-8d1a-4919d0ad7f00.png)
![paraviewerror1](https://user-images.githubusercontent.com/30739800/28992023-9b1e0a00-7957-11e7-86d9-520ceeac51d4.jpg)
![paraviewerror2](https://user-images.githubusercontent.com/30739800/28992024-9b1e1324-7957-11e7-9bfb-fe7e6cbfefb9.jpg)

**Comment by WeiqunZhang** [comment]
May I suggest Virtual Box https://www.virtualbox.org/wiki/Downloads and GNU/Linux?

**Comment by ruihai0925** [comment]
Thanks Weiqun,

Now I have solved this issue and use visit in the Linux system. You can close this question if it is convenient.

Best.

Ruohai
