### ISSUE TITLE
Error with size of member data in AmrParticleLocator with GPUs

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#852]
https://github.com/AMReX-Codes/amrex/blob/8194c10004aae594e2d120d79c5e30aa7b2dce3e/Src/Particle/AMReX_ParticleContainerI.H#L1076

When the `setGeometry` function is called for level > 0, I get an error that a vector is not properly sized. I outputted the values of and it seems like `num_levels = 2` but `m_locators.size() = m_grid_assignors.size() = 1` in  [https://github.com/AMReX-Codes/amrex/blob/8194c10004aae594e2d120d79c5e30aa7b2dce3e/Src/Particle/AMReX_ParticleLocator.H#L280](url). I don't have any problems when I run the same problem on CPUs. Am I missing something?

**Comment by atmyers** [comment]
If you change this line:

https://github.com/AMReX-Codes/amrex/blob/8194c10004aae594e2d120d79c5e30aa7b2dce3e/Src/Particle/AMReX_ParticleLocator.H#L263

to:

`if ( (m_locators.size() == 0) or (m_locators.size() != a_ba.size()) or !m_defined) return false;`

what happens?

**Comment by ldowen** [comment]
If I do that, I get an error here
[https://github.com/AMReX-Codes/amrex/blob/8194c10004aae594e2d120d79c5e30aa7b2dce3e/Src/Particle/AMReX_ParticleCommunication.H#L68](url)
It seems like it has resized `a_ba` and `m_locators` to 3, but I only have 2 levels.

**Comment by atmyers** [comment]
Is there a way I could run your code so I can reproduce this?

**Comment by ldowen** [comment]
There is a test here [https://github.com/AMReX-Combustion/PeleC-MP/tree/cpp_spray/Exec/SprayTests/AMR_test](url) that you would have to compile and run on GPUs. I am running the test on my local GPU machine.

There are a few repos and specific branches that are necessary. It is all a little spread out at the moment. PeleC needs to be on the `Landon/cpp_spray` branch and PelePhysics should be on the `development` branch. I am sure there are much easier ways to do this but I haven't figured them out yet.

Let me know a better way to get you access to the test and I will give it a shot.

**Comment by atmyers** [comment]
I was able to reproduce the issue. I think this fixes the problem: 

https://github.com/AMReX-Codes/amrex/pull/854

**Comment by ldowen** [comment]
That seems to have fixed the issue. Thanks!
