### ISSUE TITLE
FabArrayBase::FPinfo depends on FArrayBox, breaking templating

### ISSUE THREAD

**Issue by bsrunnels** [AMReX-Codes/amrex#874]
The struct `FabArrayBase::FPInfo.fact_crse_patch` uses the `FArrayBox` template, which means that it cannot be used with other types of `FabArray` derived objects (and breaks the ability to use the `FillPatch` routines with other types of `FabArray`s). This seems inconsistent with the abstract nature of `FabArrayBase`. Is there a reason it is not located in `FabArray` instead of `FabArrayBase`? This would enable it to be used with non-`FArrayBox` objects.

**Comment by WeiqunZhang** [comment]
Could you try #879?

**Comment by WeiqunZhang** [comment]
Sorry, I guess it won't work.  Will update it soon.

**Comment by WeiqunZhang** [comment]
I just pushed an update.

**Comment by bsrunnels** [comment]
What about just using the `AMREX_USE_EB` as a switch, and if not using `EB` then using a basefab constructor without the factory?

    #ifdef AMREX_USE_EB
    auto factory = makeEBFabFactory(cgeom, ba_crse_patch, dm, {0,0,0}, EBSupport::basic);
    MF mf_crse_patch(ba_crse_patch, dm, ncomp, 0, MFInfo(), *factory);
    #else
    MF mf_crse_patch(ba_crse_patch, dm, ncomp, 0);
    #endif

This would mean that templated fabs can only be used without embedded boundaries. But I suspect that using EB with templated fabs would create a bunch of problems anyway...?

**Comment by WeiqunZhang** [comment]
Making EB factory is an expensive call.

**Comment by bsrunnels** [comment]
Sorry - you're right - I copy/pasted from the wrong section of code. I updated my comment above.
The new correction would be just to change the constructor based on the `EB` flag. (This code would replace line 203 of `AMReX_FillPatchUtil_I.H`

**Comment by bsrunnels** [comment]
https://github.com/AMReX-Codes/amrex/pull/881

**Comment by WeiqunZhang** [comment]
We never know what people might want.  Are you worried about the maintenance cost?  Since we are making changes there and the cost of writing the code has been paid, why not keep it general?

**Comment by bsrunnels** [comment]
Ok - I thought that it might be a more lightweight fix that might prevent additional compile time cost. But https://github.com/AMReX-Codes/amrex/pull/879 works too - I'm good to go with that.
