### ISSUE TITLE
TARGET not created in this directory error

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#876]
Ever since https://github.com/AMReX-Codes/amrex/commit/a718d8f90da3299a686a7aab6f84ec9b88518b7a#diff-d959821542ed1f89ad8e06ba3939e3f6 , I see an error during configure when trying to use `generate_buildinfo`. The error is `TARGET 'target_name' was not created in this directory.`

**Comment by jrood-nrel** [comment]
If I comment out the `add_custom_command(PRE_BUILD)` lines, it works like it did for me previously.

**Comment by mic84** [comment]
@jrood-nrel thanks for reporting this. Can you send me the full configure log? Thanks.

**Comment by jrood-nrel** [comment]
We were able to create a local library in the directory where we call `generate_buildinfo` so that solves it for us without modification to AMReX. So I am going to close this issue.
