### ISSUE TITLE
PGI and XL compilers do not parse namelists from character arrays

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Codes/amrex#897]
The method of reading in a namelist from an allocatable character array as used in AMReX_parmparse_mod.F90 works with gcc and Intel, but it does not work with PGI and XL. Here is a test code which can be used to demonstrate the problem (`x` won't be updated by the read statement for PGI/XL, and the `iostat` return code won't be 0):

```
  program main

    implicit none

    double precision :: x

    character(len=:), allocatable :: probin

    namelist /nml/ x

    integer :: status

    x = 0.0d0

    allocate(character(len=64)::probin)

    probin = "&nml"//NEW_LINE('A')//" x = 1.0d0"//NEW_LINE('A')//"/"

    print *, probin

    read(probin, nml=nml, iostat=status)

    print *, status

    print *, x

  end program main
```

**Comment by maxpkatz** [comment]
The issue here is the newline characters in the probin variable. The parsing works correctly if they are removed.

**Comment by WeiqunZhang** [comment]
But we do need some kind of separator?  Just white space? `&nml x = 1.0d0 y = 2.d0 /`?

**Comment by maxpkatz** [comment]
White space is sufficient. However the problem is then how to parse lines with comments if they were in the namelist.

**Comment by WeiqunZhang** [comment]
If we assume everything after `!` is comment, that's easy to do.  Do gnu and intel work with white spaces?

**Comment by maxpkatz** [comment]
Yes, gcc and Intel are both OK with whitespace separation.

**Comment by WeiqunZhang** [comment]
OK.  I can make some changes and ask you to test with Maestro.
