### ISSUE TITLE
Questions about post processing in different CPUs 

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/amrex#90]
Hello there,

In the tutorial, it introduces how to divide different boxes into different processors to form Mulitfab, like:

phi_new[lev].reset(new MultiFab(ba, dm, ncomp, nghost))

I just wonder which function I can use to output the variable values for different processors? Also, are there some functions to help us output  the grid structure with or without ghost cells?

Thanks so much!

**Comment by asalmgren** [comment]
I'm not clear on what you mean by "output the variable values for different processors".  I'm guessing that you would want to write out the data in the MultiFab.   You can do this during the execution of the code using VisMF -- please see the AMReX User's Guide, p39 for an example of calling VisMF::Write.

To output the grid structure -- if you have a BoxArray ba you can simply type 

std::cout << "My boxarray: " << ba << std::endl;

to see the list of all the boxes in the boxarray.     

Does this answer your question?
