### ISSUE TITLE
AMReX CMake error with MPI::MPI_CXX IMPORTED_GLOBAL

### ISSUE THREAD

**Issue by sayerhs** [AMReX-Codes/amrex#944]
When using AMReX as a sub-package within an application's `CMakeLists.txt` (e.g., for amr-wind), CMake generates an error if the application does `find_package(MPI REQUIRED)` before adding AMReX. The exact error is

```
CMake Error at submods/amrex/Src/Base/CMakeLists.txt:15 (set_target_properties):
  Attempt to promote imported target "MPI::MPI_CXX" to global scope (by
  setting IMPORTED_GLOBAL) which is not built in this directory.
```

**Comment by asalmgren** [comment]
@sayerhs has this issue been resolved?

**Comment by sayerhs** [comment]
@asalmgren Unfortunately no. As of 1d75ba05f084cd3c1 I still get the error.

**Comment by ax3l** [comment]
Thank you for the report!
We will reorder the dependency search from using `add_subdirectory()` to [`include()`](https://github.com/ECP-WarpX/WarpX/blob/a84fbf632a93310a6f9cfaded704b295df98599c/CMakeLists.txt#L72-L87) logic to mitigate this. @mic84 is on it :)
