### ISSUE TITLE
Does AMReX support multi-block grid?

### ISSUE THREAD

**Issue by turbulent1975** [AMReX-Codes/amrex#978]
I'm now surveying block-structured adaptive mesh refinement packages, and interested in using AMReX. One of my concerns of AMR framework is the ability to handle multi-block grid (like that in the following image attached, which is copied from the website of chombo). I read the online document of AMReX, but I can't find the topic of multi-block grid. And I notice that all examples in the gallery seem to be single-block domain. So I'd like to know whether AMReX support multi-block grid or not?

![An example of multi-block grid](https://user-images.githubusercontent.com/66482813/83896064-2a93b180-a786-11ea-8a0f-c32e3de7d0e4.gif)

**Comment by atmyers** [comment]
We do not currently support multi-block grids. It's something we've discussed adding support for in the past, and we think it's quite doable, but so far it hasn't been critical for our application partners.

**Comment by turbulent1975** [comment]
@atmyers Thanks for your reply. Does your team plan to add support for the mulit-block grids in the near future?

**Comment by drummerdoc** [comment]
There are no immediate plans to support these types of grid configurations.

**Comment by turbulent1975** [comment]
I see.

**Comment by zongy17** [comment]
Hi, @turbulent1975 , I noticed that you mentioned the above figure of multi-block grid was copied from the website of chombo. So do you mean Chombo could handle such kind of problems? If yes, could you provide some reference for me? I am really interested in it!
