### ISSUE TITLE
AMReX breaks `abs`

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#979]
Since AMReX 20.06, it is not possibly any more to call `abs` in the `amrex` namespace. The recommended work-around is to call `std::abs`. This doesn't always work: if someone defines a new type (e.g. `mylib::quaternion`), and provides a function `abs` in the `mylib` namespace, then `std::abs` will not find it.

**Comment by WeiqunZhang** [comment]
In that case, it seems that you can use `mylib::abs`.

**Comment by WeiqunZhang** [comment]
And there is also `using mylib::abs`.

**Comment by eschnett** [comment]
```C++
template <typename T> T myfun(T x) {
  using std::abs;
  return abs(x);
}
```
You can't point to a specific location for `abs` since you don't know what `T` is.

**Comment by WeiqunZhang** [comment]
But you can have both `using std::abs;` and `using mylib::abs;`.

**Comment by eschnett** [comment]
Yes, you can. My point was that AMReX requires using `std::abs` now, and doesn't allow the other forms.

**Comment by WeiqunZhang** [comment]
Sure, one may have to modify the code a bit if it's inside amrex namespace or amrex namespace is imported.  But I think there are no cases that cannot be fixed.

**Comment by asalmgren** [comment]
@eschnett -- should this issue remain open or has it been successfully resolved?

**Comment by eschnett** [comment]
This issue concerns more or less just AMReX code itself. Others will not be affected, unless they `using namespace amrex`. (A respective warning in the documentation might be in order, if it isn't already there.) You can close the issue.
