### ISSUE TITLE
AMREX_NVCC_MAJOR_VERSION issue

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#987]
Seems like AMREX_NVCC_MAJOR_VERSION is not longer defined but is still being used in some places.

https://github.com/AMReX-Codes/amrex/blob/86a361c8856bdda455e3fe7d2c01b4d7ce35261a/Src/Base/AMReX_GpuDevice.cpp#L281

**Comment by maximumcats** [comment]
Looks like this happened in #981.

**Comment by WeiqunZhang** [comment]
We should switch to use nvcc's macro.

**Comment by maximumcats** [comment]
> 
> 
> We should switch to use nvcc's macro.

Agreed. This is the right thing to do anyway because the parsing of the output would have failed in CUDA 11.0 (the output format of `nvcc --version` changed).
